### ISSUE TITLE
generated variable names with ı instead i

### ISSUE THREAD

**Issue by Runomu** [mapstruct/mapstruct#883] opened 2016-09-04 22:06 UTC
I'm using mapstruct in spring-boot with component model 'spring'.  My problem is generated variable names have ı instead i. i'm using IDEA and encoding for editor is already set to UTF-8. i have also set encoding to UTF-8 in maven properties. But i can't still generate concrete classes with 'i' instead of 'ı'. After Build success it becomes 'ı'. And if i try to deploy, make module in IDEA fails and all 'ı' in code become question marks. Code looks like following: 

`
  @Generated(
       value = "org.mapstruct.ap.MappingProcessor",
      date = "2016-09-05T00:38:27+0300",
      comments = "version: 1.0.0.Final, compiler: javac, environment: Java 1.8.0_74 (Oracle Corporation)"
    )
   @Component
    public class VeininvoiceMapperImpl extends VeininvoiceMapper {

```
@Autowired
private LocalDateMapper localDateMapper;
@Autowired
private BoxTypeMapper boxTypeMapper;
@Autowired
private InvoiceStatusCodeMapper ?nvoiceStatusCodeMapper;
@Autowired
private SenderLabelMapper senderLabelMapper;
@Autowired
private PostboxLabelMapper postboxLabelMapper;
@Autowired
private VeinpartnerMapper veinpartnerMapper;

@Override
public Invoice veininvoiceToDto(Veininvoice veininvoice) {
    if ( veininvoice == null ) {
        return null;
    }

    Invoice ?nvoice = new Invoice();

    ?nvoice.setInvoiceStatusCode( ?nvoiceStatusCodeMapper.statusToDto( veininvoice.getInvoicestatuscode() ) );
    ?nvoice.setBoxType( boxTypeMapper.boxtypeToDto( veininvoice.getBoxtype() ) );
    ?nvoice.setPartner( veinpartnerMapper.veinpartnerToDto( veininvoice.getVeinpartner() ) );
    ?nvoice.setInvoiceNr( veininvoice.getInvoiceNr() );
    ?nvoice.setIsarchive( veininvoice.getIsarchive() );
    ?nvoice.setUblversionid( veininvoice.getUblversionid() );
    ?nvoice.setCustomizationid( veininvoice.getCustomizationid() );
    ?nvoice.setCopyindicator( veininvoice.getCopyindicator() );
    ?nvoice.setIssuedate( localDateMapper.issueDateToCalendar( veininvoice.getIssuedate() ) );
    ?nvoice.setIssuetime( veininvoice.getIssuetime() );
    ?nvoice.setServicetypecode( veininvoice.getServicetypecode() );
    ?nvoice.setNote( veininvoice.getNote() );
    ?nvoice.setCurrencycode( veininvoice.getCurrencycode() );
    ?nvoice.setLinecountnumeric( veininvoice.getLinecountnumeric() );
    ?nvoice.setIsactive( veininvoice.getIsactive() );
    ?nvoice.setSenderLabel( senderLabelMapper.senderLabeltoDto( veininvoice.getSenderLabel() ) );
    ?nvoice.setPostboxLabel( postboxLabelMapper.postboxLabelToDto( veininvoice.getPostboxLabel() ) );
    ?nvoice.setId( veininvoice.getId() );
    ?nvoice.setUuid( veininvoice.getUuid() );

    return ?nvoice;
}
```

}`

**Comment by agudian** [comment] 2016-09-05 06:03
Hmm, intersting. What's the default file encoding and the default Locale on your system?

**Comment by Runomu** [comment] 2016-09-05 06:46
i'm still struggling for this problem. yes its really suspicious. Because windows 10 in Turkish is installed on my laptop. And Turkish has that character :) i really dont know how to find out default encoding. But on save as in Notepad first encoding option was ANSI.

i tried now following for maven-compiler-plugin. But there is still ı instead i :(

`                  <compilerArgs>
                        <arg>-J-Duser.language=en_us</arg>
                    </compilerArgs>`

**Comment by Runomu** [comment] 2016-09-05 07:38
finally i solved problem with following maven configuration parameters. set fork to true and file.encoding to UTF-8

```
 <plugin>
      <groupId>org.apache.maven.plugins</groupId>
           <artifactId>maven-compiler-plugin</artifactId>
           <version>3.5.1</version>
           <configuration>
             <fork>true</fork>
               <compilerArgs>
                        <arg>-J-Duser.language=en_us</arg>
                        <arg>-J-Dfile.encoding=UTF-8</arg>
               </compilerArgs>
               <source>1.8</source>
                <target>1.8</target> 
                <encoding>${project.build.sourceEncoding}</encoding>
                 <annotationProcessorPaths>
                    <path>
                          <groupId>org.mapstruct</groupId>
                           <artifactId>mapstruct-processor</artifactId>
                           <version>${mapstruct.version}</version>
                       </path>
                 </annotationProcessorPaths>
               </configuration>
           </plugin>
```

**Comment by Runomu** [comment] 2016-09-05 13:23
unfornunality problem is not solved. setting fork to true and adding  -J-Duser.language=en_us and -J-Dfile.encoding=UTF-8 just helped to generate letter as i insted of ı. But if i try to deploy or make module. it fails again and somehow letter i is changed to ?. 

in order to test it, i have created a sample project just with mapper dependencies and an object and dto beginned with (ITestObject). And i gave it to my colleague. he has exactly same version for Java and Intellij and also installed windows 10 Turkish on his laptop.  We changed  -J-Dfile.encoding=UTF-8  to  -J-Dfile.encoding=windows-1254.  he made module without any problems after Build Success. File has not been corrupted. just in case recompile he had also corrupted Mapper file as me. I think, problem is somehow related to OS with IntelliJ.

**Comment by agudian** [comment] 2016-09-05 18:25
IntelliJ probably doesn't pick up those settings from the pom.xml to pass on to Javac, so you might have to set it manually in the project settings.
Anyway, it would still be nice to have this fixed. If you feel like it, you could try to fix it - given that your PC already has the proper environment required for reproducing it. Would that work for you? It would probably be a bit more tricky for us... :wink:

**Comment by gunnarmorling** [comment] 2016-09-21 18:57
Hey @Runomu just wanted to check in on this on. Any chance that you send a bug fix for this one? Your help would be greatly appreciated.

**Comment by sjaakd** [comment] 2016-12-21 22:05
@gunnarmorling , @agudian .. what needs to be done for this one? Limit the characters to a smaller set (CP1252 or US ASCII) and replace violating characters? Support more character encodings or make it somehow configurable? Can we?

**Comment by shalugin** [comment] 2017-06-26 15:09
Maybe it's not a bug. What if someone want's to use non English letters?

**Comment by filiphr** [comment] 2017-06-26 17:16
What @sjaakd  meant is to limit the characters that MapStruct can use in the generation of the variables. In the example the problem is in a variable that we are generating. 

What is really strange is that there is no problem with `Invoice`, but with `invoice`. The variable name is derived from `Invoice` with just it's first letter decapitalized. 

We certainly don't plan to limit the characters that users want to use in their types 😄. If you are experiencing the same problem we would be happy for some help as we don't have a setup where we use different character sets for our environment

**Comment by filiphr** [comment] 2017-06-27 20:55
You are right maybe we need to use the recommendation that is written in the `Javadoc` of `toLowerCase()`.

Can you maybe create a small maven project that can reproduce the problem? We could include it in our integration tests.

**Comment by shalugin** [comment] 2017-06-29 07:50
@filiphr 

Repository: https://github.com/shalugin/toLowerCase

There are four test. "capitalizeEnglish" and "decapitalizeEnglish" are green. "capitalizeTurkish" and "decapitalizeTurkish" are red, until you add locale variable to capitalize and decapitalize functions.

**Comment by filiphr** [comment] 2017-06-29 18:34
@shalugin awesome for the reproducer. Thanks a lot for the help with this one

**Comment by gunnarmorling** [comment] 2017-07-07 16:07
Done.

**Closed by gunnarmorling** 2017-07-07 16:07 UTC
Labels: bug
