### ISSUE TITLE
Reuse @Mapping definitions at a class or global level

### ISSUE THREAD

**Issue by sonyakc** [mapstruct/mapstruct#1538] opened 2018-07-06 18:51 UTC
Hi,
Was wondering if there's a way to reuse mapping definitions for a specific method across various method definitions. I see the annotations are defined using the "method" target type but to promote reuse and having a single source of mapping definitions for common definitions, it would be great if we could have a way to define these at the class or a more global level. 

```
  @Mappings({
    @Mapping(target = "target.a", source = "a"),
    @Mapping(target = "target.b", source = "b"),
    @Mapping(target = "target.c", source = "c"),
    @Mapping(target = "target.d", source = "d")
  })
```

**Comment by sjaakd** [comment] 2018-07-07 09:41
@sonyakc : Thanks for the issue, but I believe this is a duplicate of #807 . Up to now, we did not implemented this with a reason: we always like to tie the mappings to real objects. So, to support that we implemented the `@InheritConfiguration` and the `@InheritInverseConfiguration`. In order for that to work you need:
1. base classes for both source and target
2. a mapping configuration (or mapper) mapping these base classes
3. you know can inherit configurations.
There are examples in our documentation. I'm going to close this issue as a duplicate. If you don't agree: let us know :smile:

**Closed by sjaakd** 2018-07-07 09:41 UTC
