### ISSUE TITLE
Custom mapper from generic type T to List<T> stops working with 1.4.0.Beta1

### ISSUE THREAD

**Issue by rlei** [mapstruct/mapstruct#2111] opened 2020-06-07 21:59 UTC
Hi,

We have this mapper setup (simplified) which works fine with 1.3.0.Final:
```java
// classes
class Example {
    String name;
}
class UseExample {
    Example ex;
}
class DTO {
    List<String> strs;
}

// mappers
default String mapExample(Example ex) { return ex.getName(); );

@Named("wrapInList")
default <T> List<T> wrapInList(T t) {
    return singletonList(t);
}

@Mapping(target = "strs", source = "ex", qualifiedByName = "wrapInList")
DTO map(UseExample from);
```

and 1.3.0.Final generates the mapping code correctly from `Example` to `List<String>`:
```java
...
List<String> list = wrapInList( mapExample( from.getEx() ) );
...
```

But 1.4.0.Beta1 fails with:
> error: No qualifying method found for qualifiers:  and / or qualifying names: wrapInList

Is this a regression, or no longer supported in 1.4? Thanks! BTW kudos for the 1.4 beta release, it's awesome!

**Comment by filiphr** [comment] 2020-06-13 08:07
This is on purpose. It was actually wrong before, since it was ignoring the qualifiers when doing 2 step mapping.

You are saying that you want to use `wrapInList` qualifier for mapping between `ex` to `strs`. and there is no such qualifier, `mapExample` is not qualified. This is documented in the behaviour changes in the release notes. See #1714 and PR #1739 for more info as well.

@sjaakd did some work on this and perhaps he can chime on. Maybe we need to still pick `mapExample` if we didn't find a matching qualified method.

**Comment by rlei** [comment] 2020-06-13 15:43
@filiphr thanks a lot for your answer. Indeed, all I need to do is just removing the "wrapInList" qualifier, and MapStruct can do the 2 step mapping with the generic `wrapInList` mapper again.

I feel the 1.4 behavior does make more sense than the previous implicit mapper finding. However I feel it's also interesting to see if there's a way to specify qualifier for two step mapping methods.

Shall I keep this issue open? Or would it be helpful for MapStruct to be a bit more specific in the error message, such as 
> No qualifying method found for qualifiers: and / or qualifying names: wrapInList. Note that the qualified mapper must be a direct mapper in order to be found.
?

**Comment by filiphr** [comment] 2020-06-14 07:58
@rlei I think that the clarifying message for the qualifiers is part of #1767. 

Anyways I would like to keep this open so that we can discuss within the team about my comment.

Regarding the qualifiers, I think that it will work correctly if you qualify the `mapExample` method as well (although not 100% sure)

**Comment by sjaakd** [comment] 2020-06-14 08:02
I'll have a look what is going on here. Note: the qualifiers are there to guide MapStruct to a proper mapping method when there are multiple options. That it is not the case here.

**Comment by sjaakd** [comment] 2020-06-14 11:46
I guess: the original issue was: #1714 and the PR #1739. 

The "tricky" thing here  is there are actually 2 mappings constituting to the complete mapping.  source -> `mapExample` -> ` wrapInList` -> target. For one of them you pointed out a qualifier for the other one you did not.

The documentation states:
`A class / method annotated with a qualifier will not qualify anymore for mappings that do not have the qualifiedBy element.` Note: that's exactly what you want: resolve conflicts.

Now, modifying your example can be done in 2 ways.
1. You did @filiphr already discussed: remove the qualifier and the `qualifiedBy`.
2. Stick the qualifier to both methods, since both methods `mapExample` and `wrapInList` play a role in this mapping ..

Both work (fortunately :smile: ): 

```java
@Mapper
public interface Issue2111Mapper {


    @Mapping(target = "strs", source = "ex", qualifiedByName = "wrapInList")
    DTO map(UseExample from);

    @Named("wrapInList")
    default String mapExample(Example ex) {
        return ex.name;
    }

    @Named("wrapInList")
    default <T> List<T> wrapInList(T t) {
        return singletonList( t );
    }

    class Example {
        public String name;
    }

    class UseExample {
        public Example ex;
    }

    class DTO {
        public List<String> strs;
    }

}
``` 

 The latter one is a nice extra test case, which I'll add to the regression suite. 

I guess we can close the issue, WDYT @filiphr ?

**Closed** 2020-06-14 12:00 UTC

**Comment by sjaakd** [comment] 2020-06-14 14:24
> I guess we can close the issue, WDYT @filiphr ?

I guess he agrees :smile:
