### ISSUE TITLE
When expression is used to specify a method for a String, the normal mapping is changed to use the specified method

### ISSUE THREAD

**Issue by YAGAMIL** [mapstruct/mapstruct#3002] opened 2022-09-01 03:05 UTC
Because some parameter mappings require specific logic, I added such a method

```
	static String firstAsterisk(String value) {
		return Optional.ofNullable(value).filter(v -> v.contains("*"))
				.map(v -> v.substring(0, v.indexOf("*"))).orElse(value);
	}
```
In my mapping statement method, I use @mapping like this
```
	@Mapping(target = "value", ignore = true)
	@Mapping(target = "name",expression = "java(RecordTransfer.firstAsterisk(recordDTO.getName()))")
	@Mapping(target = "nickName", expression = "java(RecordTransfer.firstAsterisk(recordDTO.getNickname()))")
	Record convert(RecordDTO recordDTO);
```

The code of "RecordtransferImpl" it generates is like this

```
    @Override
    public Record convert(RecordDTO recordDTO) {
        if ( recordDTO == null ) {
            return null;
        }

        Record.RecordBuilder record = Record.builder();

        record.id( recordDTO.getId() );
        record.gmtCreate( recordDTO.getGmtCreate() );
        record.gmtModified( recordDTO.getGmtModified() );
        record.required( recordDTO.getRequired() );
        record.path( RecordTransfer.firstAsterisk( recordDTO.getPath() ) );
        record.otherName( RecordTransfer.firstAsterisk( recordDTO.getOtherName() ) );
        record.info( RecordTransfer.firstAsterisk( recordDTO.getInfo() ) );
        record.name( RecordTransfer.firstAsterisk(recordDTO.getName()) );
        record.nickname( RecordTransfer.firstAsterisk(recordDTO.getNickname()) );

        return Record.build();
    }
```

And I created all in this RecordTransfer mapping method, as long as the switch field is of type String, all has been replaced by RecordTransfer.firstAsterisk( )

**Comment by chenzijia12300** [comment] 2022-09-01 04:39
I think this is caused by the fact that your `firstAsterisk` method is defined inside the mapper, which makes the framework think that you want to customize the way you map all strings to strings.
You should probably move this method to another class and reference it fully qualified in the `expression` property

**Comment by YAGAMIL** [comment] 2022-09-01 06:25
> 

Yeah, but I don't think MapStruct should do that, or if I need that optimization, mark a switch annotation like this@TypeHandler(type=String.class)，Otherwise, this default substitution should not be done

**Comment by filiphr** [comment] 2022-09-01 06:45
>Yeah, but I don't think MapStruct should do that

A lot of our users are going to disagree with you about this @YAGAMIL. If you decide to write a custom mapping method and make it available for the mapper either by using `Mapper#uses` or as a method in the mapper itself then MapStruct will not use the default conversions. This is all explained in our documentation https://mapstruct.org/documentation/stable/reference/html/#adding-custom-methods.

Thanks for the explanation @chenzijia12300.

If you want to only use your methods for your usecase you should mark them with `@Named`. In your example you don't even need to use `expression`.

e.g.

```java
@Named("firstAsterisk")
static String firstAsterisk(String value) {
		return Optional.ofNullable(value).filter(v -> v.contains("*"))
				.map(v -> v.substring(0, v.indexOf("*"))).orElse(value);
	}
```

And then you would use:

```java
	@Mapping(target = "value", ignore = true)
	@Mapping(target = "name", qualifiedByName = "firstAsterisk")
	@Mapping(target = "nickName", qualifiedByName = "firstAsterisk")
	Record convert(RecordDTO recordDTO);
```

----

I am going to close this one as it works as intended

**Closed by filiphr** 2022-09-01 06:45 UTC
