### ISSUE TITLE
[Compilation Error] class  'java.util.ArrayList'  not found. MappersImpl cannot be compiled.

### ISSUE THREAD

**Issue by euclideanrn** [mapstruct/mapstruct#1590] opened 2018-08-22 09:17 UTC
Hi
I think I have encountered an exception here:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project lst-targetad-service: Compilation failure
[ERROR] ***/target/generated-sources/annotations/***/***/***/***/beans/mapping/MappersImpl.java:[102,55] 找不到符号
[ERROR]   符号:   类 ArrayList
[ERROR]   位置: 类 ***.***.***.***.beans.mapping.MappersImpl
```

And here is my definition interface 'Mappers.java':
```java
@Mapper(componentModel = "spring",
        nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
        nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT,
        uses = MappingFactories.class
)
public interface Mappers {

    @Mappings({
            @Mapping(target = "gmtCreate"  , expression = "java( new java.util.Date() )"),
            @Mapping(target = "gmtModified", expression = "java( new java.util.Date() )")
    })
    ResourceTemplateDO mapToResourceTemplateDO(TemplateCommandParam source);

    @Mappings({
            @Mapping(target = "gmtCreate"  , expression = "java( new java.util.Date() )"),
            @Mapping(target = "gmtModified", expression = "java( new java.util.Date() )"),
            @Mapping(target = "templateId" , source     = "id"                          )
    })
    ResourceTemplateVersionDO mapToResourceTemplateVersionDO(TemplateCommandParam source);

    ResourceTemplateDO mapToResourceTemplateDO(TemplateQueryParam source);

    TemplateModel mapToTemplateModel(ResourceTemplateDO source);
    TemplateVersionModel mapToTemplateVersionModel(ResourceTemplateVersionDO source);

    default java.lang.String map(java.util.List<java.lang.String> value) {
        return JSON.toJSONString(value);
    }

    default java.util.List<java.lang.String> map(java.lang.String value) {
        return JSON.parseObject(value, new TypeReference<List<String>>(){}.getType());
    }
}
```

the generated class 'MappersImpl.class':
```java
package com.alibaba.lst.targetad.beans.mapping;

import *.dal.dataobj.ResourceTemplateDO;
import *.dal.dataobj.ResourceTemplateVersionDO;
import *.service.model.domain.TemplateModel;
import *.service.param.TemplateCommandParam;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.annotation.Generated;
import java.util.List;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2018-08-22T17:31:15+0800",
    comments = "version: 1.2.0.Final, compiler: javac, environment: Java 1.8.0_161 (Oracle Corporation)"
)
@Component
public class MappersImpl implements Mappers {

    @Override
    public ResourceTemplateDO mapToResourceTemplateDO(TemplateCommandParam source) {

        ResourceTemplateDO resourceTemplateDO = new ResourceTemplateDO();

        if ( source != null ) {
            if ( source.getId() != null ) {
                resourceTemplateDO.setId( source.getId() );
            }
            if ( source.getDescription() != null ) {
                resourceTemplateDO.setDescription( source.getDescription() );
            }
            if ( source.getName() != null ) {
                resourceTemplateDO.setName( source.getName() );
            }
            if ( source.getCreator() != null ) {
                resourceTemplateDO.setCreator( source.getCreator() );
            }
            if ( source.getAuthorizedUsers() != null ) {
                resourceTemplateDO.setAuthorizedUsers( map( source.getAuthorizedUsers() ) );
            }
        }
        resourceTemplateDO.setGmtCreate( new java.util.Date() );
        resourceTemplateDO.setGmtModified( new java.util.Date() );

        return resourceTemplateDO;
    }

    @Override
    public ResourceTemplateVersionDO mapToResourceTemplateVersionDO(TemplateCommandParam source) {

        ResourceTemplateVersionDO resourceTemplateVersionDO = new ResourceTemplateVersionDO();

        if ( source != null ) {
            if ( source.getId() != null ) {
                resourceTemplateVersionDO.setTemplateId( source.getId() );
            }
            if ( source.getId() != null ) {
                resourceTemplateVersionDO.setId( source.getId() );
            }
            if ( source.getContent() != null ) {
                resourceTemplateVersionDO.setContent( source.getContent() );
            }
        }
        resourceTemplateVersionDO.setGmtModified( new java.util.Date() );
        resourceTemplateVersionDO.setGmtCreate( new java.util.Date() );

        return resourceTemplateVersionDO;
    }

    @Override
    public ResourceTemplateDO mapToResourceTemplateDO(TemplateQueryParam source) {

        ResourceTemplateDO resourceTemplateDO = new ResourceTemplateDO();

        if ( source != null ) {
            if ( source.getId() != null ) {
                resourceTemplateDO.setId( source.getId() );
            }
            if ( source.getName() != null ) {
                resourceTemplateDO.setName( source.getName() );
            }
            if ( source.getCreator() != null ) {
                resourceTemplateDO.setCreator( source.getCreator() );
            }
        }

        return resourceTemplateDO;
    }

    @Override
    public TemplateModel mapToTemplateModel(ResourceTemplateDO source) {

        TemplateModel templateModel = new TemplateModel();

        if ( source != null ) {
            if ( source.getId() != null ) {
                templateModel.setId( source.getId() );
            }
            if ( source.getName() != null ) {
                templateModel.setName( source.getName() );
            }
            if ( source.getGmtCreate() != null ) {
                templateModel.setGmtCreate( source.getGmtCreate() );
            }
            if ( source.getGmtModified() != null ) {
                templateModel.setGmtModified( source.getGmtModified() );
            }
            if ( source.getDescription() != null ) {
                templateModel.setDescription( source.getDescription() );
            }
            if ( source.getCreator() != null ) {
                templateModel.setCreator( source.getCreator() );
            }
            List<String> list = map( source.getAuthorizedUsers() );
            if ( list != null ) {
                templateModel.setAuthorizedUsers( list );
            }
            else {
                templateModel.setAuthorizedUsers( new ArrayList<String>() );
            }
        }

        return templateModel;
    }

    @Override
    public TemplateVersionModel mapToTemplateVersionModel(ResourceTemplateVersionDO source) {

        TemplateVersionModel templateVersionModel = new TemplateVersionModel();

        if ( source != null ) {
            if ( source.getId() != null ) {
                templateVersionModel.setId( source.getId() );
            }
            if ( source.getContent() != null ) {
                templateVersionModel.setContent( source.getContent() );
            }
            if ( source.getPrevId() != null ) {
                templateVersionModel.setPrevId( source.getPrevId() );
            }
        }

        return templateVersionModel;
    }
}

```

And after checkout the source code [SetterWrapperForCollectionsAndMapsWithNullCheck.ftl](https://github.com/mapstruct/mapstruct/search?q=SetterWrapperForCollectionsAndMapsWithNullCheck.ftl&unscoped_q=SetterWrapperForCollectionsAndMapsWithNullCheck.ftl)   
It seems like this part of code does not handle the ‘import’ part correctly.
SetterWrapperForCollectionsAndMapsWithNullCheck.ftl:
```xml
<@lib.sourceLocalVarAssignment/>
<@lib.handleExceptions>
  <@callTargetWriteAccessor/>
  <#if !ext.defaultValueAssignment??>else {<#-- the opposite (defaultValueAssignment) case is handeld inside lib.handleLocalVarNullCheck -->
    ${ext.targetBeanName}.${ext.targetWriteAccessorName}<@lib.handleWrite><#if mapNullToDefault><@lib.initTargetObject/><#else>null</#if></@lib.handleWrite>;
  }
  </#if>
</@lib.handleExceptions>
```
'找不到符号’ here means cannot find the class ‘java.util.ArrayList’
because the MappersImpl does not import class ‘java.util.ArrayList’
Is this an existing issue, or do I miss something?

**Comment by chigix** [comment] 2018-08-22 11:25
I've checked the usage of `defaultExpression` with `java.util.Array` instantiate expression, and there is no problem in my compilation.

Initially, what version of mapstruct do you involved in your maven project? I was testing upon version 1.3.0-beta1 installed from maven community.

Actually, there is another problem in your compilation I'm currently a little concerned as well that why the if else block for `defaultExpression` could be 

> else if {
>                templateModel.setAuthorizedUsers( new ArrayList<String>() );
>         }

This `if` block, I think, seems a much more terrible problem, I didn't see such result in my testing compilation on `defaultExpression` too, which makes me currently confused about the generated class code you posted in this issue.

**Comment by euclideanrn** [comment] 2018-08-22 12:02
@chigix sorry, I have made a mistake in copy&paste which has already been fixed by re-edit the issue post.

**Comment by euclideanrn** [comment] 2018-08-22 12:03
@chigix sorry, I have made a mistake in copy&paste which has already been fixed by re-edit the issue post.

**Comment by sjaakd** [comment] 2018-08-25 07:43
@euclideanrn : the `new ArrayList()` is coming from the fact you use `NullValueMappingStrategy.RETURN_DEFAULT`. This makes MapStruct generate code which returns a default object. In the case of `List` this is an `ArrayList`. 
1. It might be a bug that MapStruct does not include the import. you could resolve that with `import` as a temp fix.
2. But Is this what you want? If you omit the strategy it will just return null.

**Comment by kikuko72** [comment] 2018-08-27 11:53
I have a similar issue.
following sources causes a compilation error when I run `mvn compile` (using  mapstruct1.3.0.Beta1).

the points is:
1.  the user mapper doesn't imports `List`.
2. `NullValueCheckStrategy.ALWAYS`
3. `NullValueMappingStrategy.RETURN_DEFAULT`
4. with lombok.

Book.java
``` java
public class Book {
}

```

BookShelf.java
``` java
import lombok.Data;

import java.util.List;

@Data
public class BookShelf {
    List<Book> books;
}
```

BookMapper.java
``` java
import org.mapstruct.Mapper;

import java.util.List;

@Mapper
public interface BookMapper {
    Book map(Book book);
    List<Book> map(List<Book> books);
}
```

BookShelfMapper.java
``` java
import org.mapstruct.Mapper;
import org.mapstruct.NullValueCheckStrategy;
import org.mapstruct.NullValueMappingStrategy;


@Mapper(uses = BookMapper.class,
        nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
        nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT)
public interface BookShelfMapper {
    BookShelf map(BookShelf bookShelf);
}
```

**Comment by sjaakd** [comment] 2018-08-27 19:30
@kikuko72 : If you remove Lombok (and add getter / setter), does it stil give problems? I've opened a PR (https://github.com/mapstruct/mapstruct/pull/1598) but not able to reproduce the problem in unit test.

**Comment by kikuko72** [comment] 2018-08-27 22:38
@sjaakd : I removed Lombok and added getter / setter, it still give problems.
 4 (with lombok.) is wrong,  the matter is getter / setter .

to reproduce the problem , PR (#1598) needs 2 mappers.
 - A Mapper with collection mapping method (like my BookMapper).
 - A Mapper with @Mapper.uses (like my BookShelfMapper).

could you try add a mapper with `List` mapping method and make Issue1590Mapper use `@Mapper.uses` ?

**Comment by sjaakd** [comment] 2018-08-28 06:43
Ok! Lombok being part of this problem stroke me as odd.  I'll Adapt my reproducer to match your setup and see what happens.

**Comment by sjaakd** [comment] 2018-08-28 18:28
Thanks for the reproducer! I used it and provided a fix.

**Comment by sjaakd** [comment] 2018-08-29 19:13
@kikuko72 thanks  for the final hints.. That  pushed me in the right direction. Problem fixed on master.

**Closed by sjaakd** 2018-08-29 19:13 UTC
Labels: bug

**Comment by kikuko72** [comment] 2018-08-30 11:00
@sjaakd thanks for the fix.

**Comment by euclideanrn** [comment] 2020-03-15 15:25
@sjaakd Thanks for the fix. And thanks for the help @kikuko72 .
