### ISSUE TITLE
Missing import when mapping nested enums

### ISSUE THREAD

**Issue by emat84** [mapstruct/mapstruct#3004] opened 2022-09-02 09:36 UTC
Even after the recent fixes that went in 1.5.2, I can still reproduce a missing import when mapping an inner Enum to a String.

1.4.2.Final works

1.5.1.Final and 1.5.2.Final don't work

the generated code looks like:

`targetInstance.targetField( Enum.valueOf( Clazz.InnerEnum.class, sourceInstance.getSourceField() ) );`

and will result in `package Clazz does not exist`

**Comment by filiphr** [comment] 2022-09-02 12:34
I believe that this has already been fixed on main. This looks like a duplicate of #2945. Therefore, I am going to close this one.

**Closed by filiphr** 2022-09-02 12:34 UTC
