### ISSUE TITLE
Qualifier is ignored in case of name based mapping

### ISSUE THREAD

**Issue by imeszaros** [mapstruct/mapstruct#2125] opened 2020-06-21 22:25 UTC
As stated here: https://github.com/mapstruct/mapstruct/issues/2124#issuecomment-647184770 , MapStruct ignores the qualifier specification for a mapping if it is name based (i.e. source property is not specified explicitly).

Imho this behavior could be enhanced either:
- when a qualifier is specified, it can be assumed that the user would like to defer from the automatic (name based) mapping, so MapStruct should honor it, or
- at least the annotation processor should emit a warning that the qualifier is ignored, so the user immediately understands what is going on.

**Comment by sjaakd** [comment] 2020-07-03 06:31
@imeszaros can you provide a reproducer?

**Comment by sjaakd** [comment] 2020-07-07 17:13
which version of MapStruct?

**Comment by filiphr** [comment] 2020-07-07 17:22
@sjaakd did you check the linked issue? I think that there is a reproducer there

**Comment by sjaakd** [comment] 2020-07-07 17:27
> @sjaakd did you check the linked issue? I think that there is a reproducer there

Sorry.. I'm a bit sleepy as well. Missed that entirely..

**Comment by imeszaros** [comment] 2020-07-07 17:37
Sorry for the delay.. it was 1.4 Beta. Do you need an example repo?

**Comment by filiphr** [comment] 2020-09-19 08:05
I am fairly certain that this is the same as #2164 which has been fixed in 1.4.0.CR1.

Please let us know if that is the case @imeszaros, so we can reopen this one.

**Comment by imeszaros** [comment] 2020-09-19 09:49
@filiphr I'm not sure it works fully as expected. I created a repository: https://github.com/imeszaros/mapstruct-playground

Please see the test mapper: https://github.com/imeszaros/mapstruct-playground/blob/master/src/main/kotlin/playground/Mapper.kt

And it generates:

<details>
<summary>Show</summary>

```java
package playground;

import javax.annotation.processing.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2020-09-19T11:42:03+0200",
    comments = "version: 1.4.0.CR1, compiler: IncrementalProcessingEnvironment from kotlin-annotation-processing-gradle-1.4.10.jar, environment: Java 11.0.7 (AdoptOpenJDK)"
)
public class MapperImpl extends Mapper {

    @Override
    public CommitComment clone0(Repository repository, CommitComment commitComment, CloneContext cloneContext) {
        if ( repository == null && commitComment == null ) {
            return null;
        }

        Integer issueId = null;
        String comment = null;
        if ( commitComment != null ) {
            issueId = commitComment.getIssueId();
            comment = commitComment.getComment();
        }

        CommitComment commitComment1 = new CommitComment( issueId, comment );

        return commitComment1;
    }

    @Override
    public CommitComment clone1(CommitComment commitComment, Repository repository, CloneContext cloneContext) {
        if ( commitComment == null && repository == null ) {
            return null;
        }

        Integer issueId = null;
        String comment = null;
        if ( commitComment != null ) {
            issueId = commitComment.getIssueId();
            comment = commitComment.getComment();
        }

        CommitComment commitComment1 = new CommitComment( issueId, comment );

        return commitComment1;
    }

    @Override
    public CommitComment clone2(CommitComment commitComment, Repository repository, CloneContext cloneContext) {
        if ( commitComment == null && repository == null ) {
            return null;
        }

        Integer issueId = null;
        String comment = null;
        if ( commitComment != null ) {
            issueId = commitComment.getIssueId();
            comment = commitComment.getComment();
        }

        CommitComment commitComment1 = new CommitComment( issueId, comment );

        return commitComment1;
    }

    @Override
    public CommitComment clone3(CommitComment commitComment, CloneContext cloneContext) {
        if ( commitComment == null ) {
            return null;
        }

        Integer issueId = null;
        String comment = null;

        if ( commitComment.getIssueId() != null ) {
            issueId = mapIssueNumber( commitComment.getIssueId().intValue(), cloneContext );
        }
        comment = commitComment.getComment();

        CommitComment commitComment1 = new CommitComment( issueId, comment );

        return commitComment1;
    }

    @Override
    public CommitComment clone4(CommitComment commitComment, Repository repository, CloneContext cloneContext) {
        if ( commitComment == null && repository == null ) {
            return null;
        }

        Integer issueId = null;
        String comment = null;
        if ( commitComment != null ) {
            if ( commitComment.getIssueId() != null ) {
                issueId = mapIssueNumber( commitComment.getIssueId().intValue(), cloneContext );
            }
            comment = commitComment.getComment();
        }

        CommitComment commitComment1 = new CommitComment( issueId, comment );

        return commitComment1;
    }
}
```
<details>

**Comment by filiphr** [comment] 2020-09-19 15:41
You are completely right @imeszaros, thanks a lot for the repository. The problem is when multiple source parameters are used. We will look into this.

**Closed** 2020-09-21 05:55 UTC
Labels: bug
