### ISSUE TITLE
Dependency injection enhancement

### ISSUE THREAD

**Issue by igor-dmitriev** [mapstruct/mapstruct#1078] opened 2017-02-17 09:40 UTC
There is no opportunity to use dependency injection without DI container, I think this is a mistake.
I have following mappers:

```
@Mapper(uses = AccountMapper.class, componentModel = "jsr330")
public UserMapper{
   ...
}

```
it will be generated in:

```
@Singleton
@Named
public class UserMapperImpl implements UserMapper{
    @Inject
    private AccountMapper accountMapper;
    ....
}
```

I am going to use my UserMapper somewhere where there is no DI container, like Spring or Guice, whatever. And since you use field-injection it's impossible. I can't create `new UserMapperImpl()` and use it, cause I will get NPE.

How can we cope with it??

1. Add setter for each dependency, use setter-injection instead of field-injection (I think this is not a good idea)
2. Use Constructor injection (this is awesome, this is recommended by Spring community)

In this case I am able to create `new UserMapperImpl(new AccountMapperImpl());` and use it like vanilla Java.

Actually it's a common issue, yo shouldn't be dependent on DI framework, framework should help you.

Otherwise I have to do a hook using Reflection:
```
Field accountMapper = ReflectionUtils.findField(UserMapperImpl.class, "accountMapper");
ReflectionUtils.makeAccessible(accountMapper);
ReflectionUtils.setField(accountMapper, userMapper, new AccountMapperImpl());
 
```
It looks ugly.

> The wrong way is to use field injection, never ever do this, not even when 
> you are all by yourself all alone at home and no one is looking, never do this.
> Every time you do this a unit test dies, don't do it

  **Josh Long ©**

Anyway thank you for your great tool, I am happy to use it :)

**Comment by Maaartinus** [comment] 2017-02-17 16:20
> I am going to use my UserMapper somewhere where there is no DI container, like Spring or Guice,

I wouldn't call Guice a container or a framework, as it has no lifecycle and it's easy to use. All you need is to
- configure it, e.g., via `@ImplementedBy(UserMapperImpl.class) class UserMapper {...}` (if you can and want to modify the mapper class) or `bind(UserMapper.class).to(UserMapperImpl.class)`
- create an injector (usually as a singleton)
- and ask for `injector.getInstance(UserMapper.class)` (ideally you use only one such call, everything else gets autowired)

> And since you use field-injection it's impossible.

Guice performs field injection, too, though constructor injection is clearly the preferred way. I use field injections where I have to (mostly in tests), and constructor injection everywhere else.

> The wrong way is to use field injection

I disagree. Sometimes, all alternatives are even worse.

---

I use lombok (which now works well together with mapstruct) and quite a few of my classes look like

`@RequiredArgsConstructor(onConstructor=@__(@Inject)) class MyClass {....}`

The syntax is strange, but I make all fields final and they get initialized by Guice.

**Comment by igor-dmitriev** [comment] 2017-02-17 16:31
@Maaartinus you didn't get the issue, I need to test my classes which use UserMapper without Spring container, how can I do that???

**Comment by Maaartinus** [comment] 2017-02-17 16:48
@igor-dmitriev I'm pretty new here (apologies if I'm talking non-sense). I use Guice even for tests (it doesn't measurably slow them down). Others claim that it's not clean.

Maybe, I understand now: You want the generated code to support testing (e.g., to include a constructor, so that you can do construction injection also manually), right?

**Comment by davidfra** [comment] 2017-02-17 16:49
I have a similar problem. We are using blueprint in an OSGi context to inject an EntityManager.
As seen in the examples, it is possible to use mappers that resolve referenced entities from the database.

The problem is: aries blueprint needs a setter method to be able to inject other instances, or at least a constructor.

It would be really nice, if you could add an option to generate a setter method for every used Mapper.

Maybe like:

`@Mapper(componentModel="none", generateSettersForComponents=true, uses=MyOtherMapper.class)`

**Comment by davidfra** [comment] 2017-02-17 17:01
It seems a similar issue was already opened some time ago: #571

**Comment by igor-dmitriev** [comment] 2017-02-17 17:10
@davidfra I don't like that setters, they just should change the implementation from field-injection to constructor-injection, that will be the right solution.

**Comment by agudian** [comment] 2017-02-17 19:57
Well, that really depends on the use case... Some DI frameworks allow cycles in the runtime graph (no, cycles are not *always* plain bad and there are cases when that allows to avoid an over-complicated class structure) - and in those cases you'd be lost (or at least challenged) if you only had constructor-injection. As for testability, I'd usually use the chosen DI frameworks test infrastructure, e.g. the stuff that Spring brings in is really great and allows to easily declare what classes are to be properly created and populated and where mocks should be added instead... 

However, some DI frameworks explicitly and by design do not allow cycles and highly suggest using constructor-injection, like Dagger as reported in #571, so we have the usage of constructor-injection on our backlog already - it's just that no one stepped up and implemented it, yet... Would one of you maybe be interested in doing that? 
I could imagine that we might add an option to the `@Mapper` annotation similar to the suggestion above, e.g. `useConstructorInjection=true` or something like that, but that should be discussed first.

Anyway, my suggestion is to close this one as a duplicate to #571 and continue the discussion on how to add constructor-injection in that issue (and find a solution that also works for the other component models). Is that okay?

**Comment by igor-dmitriev** [comment] 2017-02-17 20:38
@agudian I got it, I would like to help you wit it, actually I am happy to do that.

**Comment by agudian** [comment] 2017-02-17 21:27
Awesome! Let us know if you need any assistance... A good place to start could be the `AnnotationBasedComponentModelProcessor` and its three sub-classes to see how we currently modify the model that represents the mapper class to generate for the non-default component models.
That could be a place to add the special constructor (I'm not sure if we could make constructor-based injection work on `default`-component model mappers, as they are currently instanciated through the `MapperFactory` by rather simple means).

Closing this as duplicate to #571.

**Closed by agudian** 2017-02-17 21:27 UTC
