### ISSUE TITLE
Method already defined when mapping a recursive data structure into a list of the same structure

### ISSUE THREAD

**Issue by codeStev** [mapstruct/mapstruct#3532] opened 2024-02-16 18:28 UTC
### Expected behavior

I've got the following data structures I would like to map:

```java
class Source {

    private Node node;

    // getters/setters

}

class Target {

    private List<NodeDto> nodeDtoList;

    // getters/setters

}
```
The recursive structures "Node" and "NodeDto" look like this :

```java
class Node {

    //properties

    List<Node> childNodes;

    // getters/setters

}

class NodeDto {

    //properties

    List<NodeDto> childNodes;

    // getters/setters

}
```

The map method looks as follows: 
```java
@Mapping( target = "nodeList", source = "node.childNodes" )
abstract Target map( Source source);
```

The reason for mapping it like this is to omit the root element of the tree since it is not wanted in this case.

MapStruct generates the methods with the following signature correctly :

```java
NodeDto nodeToNodeDto( Node node )

List<NodeDto> nodeListToNodeDtoList( List<Node> )
```

I would expect MapStruct to use the already generated method to map the list and not to generate the same method twice.

### Actual behavior

MapStruct generates the method   `List<NodeDto> nodeListToNodeDtoList( List<Node> )` twice, provoking a compile error in the generated implementation.
If I don't specify the source the root element will get mapped, which is not wanted behaviour.

The Exception Message looks like this : 

`error: method nodeListToNodeDtoList(List<Node>) is already defined in class TargetMapperImpl`

### Steps to reproduce the problem

My configuration looks as follows: 

```java
@MapperConfig(
        unmappedTargetPolicy = ReportingPolicy.ERROR,
        unmappedSourcePolicy = ReportingPolicy.IGNORE,
        componentModel = MappingConstants.ComponentModel.SPRING,
        injectionStrategy = InjectionStrategy.CONSTRUCTOR,
        nullValueIterableMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT)
public interface CentralMapperConfig {

}
```

The problem should be reproducable with the snippets described above. I omitted the getters/setters and the Mapping class to keep it more readable.

### MapStruct Version

MapStruct 1.5.3

**Comment by ktkjbs** [comment] 2024-02-22 08:44
I tried to reproduce it with the code below, but it doesn't work. I don't see anything different from your code

this is my code

```Java
// it works!
  @Mapper(componentModel = "spring")
  interface TestMapper {

    @Mapping(source = "rootNode.childNodes", target = "childNodeDtos")
    Target map(Source source);

    record Source(Node rootNode) {

    }

    record Target(List<NodeDto> childNodeDtos) {

    }

    record Node(String name, List<Node> childNodes) {

    }

    record NodeDto(String name) {

    }
  }
```

and mapstruct impl code is here

```Java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2024-02-22T17:32:49+0900",
    comments = "version: 1.5.3.Final, compiler: javac, environment: Java 17.0.5 (Amazon.com Inc.)"
)
@Component
public class TestMapperImpl implements TestMapper {

    @Override
    public Target map(Source source) {
        if ( source == null ) {
            return null;
        }

        List<NodeDto> childNodeDtos = null;

        List<Node> childNodes = sourceRootNodeChildNodes( source );
        childNodeDtos = nodeListToNodeDtoList( childNodes );

        Target target = new Target( childNodeDtos );

        return target;
    }

    private List<Node> sourceRootNodeChildNodes(Source source) {
        if ( source == null ) {
            return null;
        }
        Node rootNode = source.rootNode();
        if ( rootNode == null ) {
            return null;
        }
        List<Node> childNodes = rootNode.childNodes();
        if ( childNodes == null ) {
            return null;
        }
        return childNodes;
    }

    protected NodeDto nodeToNodeDto(Node node) {
        if ( node == null ) {
            return null;
        }

        String name = null;

        name = node.name();

        NodeDto nodeDto = new NodeDto( name );

        return nodeDto;
    }

    protected List<NodeDto> nodeListToNodeDtoList(List<Node> list) {
        if ( list == null ) {
            return null;
        }

        List<NodeDto> list1 = new ArrayList<NodeDto>( list.size() );
        for ( Node node : list ) {
            list1.add( nodeToNodeDto( node ) );
        }

        return list1;
    }
}
```

**Comment by seaworld0125** [comment] 2024-02-22 08:45
I tried to reproduce it with the code below, but it doesn't work. I don't see anything different from your code

this is my code

```Java
// it works!
  @Mapper(componentModel = "spring")
  interface TestMapper {

    @Mapping(source = "rootNode.childNodes", target = "childNodeDtos")
    Target map(Source source);

    record Source(Node rootNode) {

    }

    record Target(List<NodeDto> childNodeDtos) {

    }

    record Node(String name, List<Node> childNodes) {

    }

    record NodeDto(String name) {

    }
  }
```

and mapstruct impl code is here

```Java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2024-02-22T17:32:49+0900",
    comments = "version: 1.5.3.Final, compiler: javac, environment: Java 17.0.5 (Amazon.com Inc.)"
)
@Component
public class TestMapperImpl implements TestMapper {

    @Override
    public Target map(Source source) {
        if ( source == null ) {
            return null;
        }

        List<NodeDto> childNodeDtos = null;

        List<Node> childNodes = sourceRootNodeChildNodes( source );
        childNodeDtos = nodeListToNodeDtoList( childNodes );

        Target target = new Target( childNodeDtos );

        return target;
    }

    private List<Node> sourceRootNodeChildNodes(Source source) {
        if ( source == null ) {
            return null;
        }
        Node rootNode = source.rootNode();
        if ( rootNode == null ) {
            return null;
        }
        List<Node> childNodes = rootNode.childNodes();
        if ( childNodes == null ) {
            return null;
        }
        return childNodes;
    }

    protected NodeDto nodeToNodeDto(Node node) {
        if ( node == null ) {
            return null;
        }

        String name = null;

        name = node.name();

        NodeDto nodeDto = new NodeDto( name );

        return nodeDto;
    }

    protected List<NodeDto> nodeListToNodeDtoList(List<Node> list) {
        if ( list == null ) {
            return null;
        }

        List<NodeDto> list1 = new ArrayList<NodeDto>( list.size() );
        for ( Node node : list ) {
            list1.add( nodeToNodeDto( node ) );
        }

        return list1;
    }
}
```

**Comment by seaworld0125** [comment] 2024-02-22 08:58
I'll suggest this code. This code seems to do what you want.

```Java
  @Mapper(componentModel = "spring")
  interface TestMapper {

    @Mapping(source = "rootNode.childNodes", target = "childNodeDtos")
    Target map(Source source);

    @Mapping(source = "childNodes", target = "childNodeDtos")
    NodeDto map(Node node);

    record Source(Node rootNode) {

    }

    record Target(List<NodeDto> childNodeDtos) {

    }

    record Node(String name, List<Node> childNodes) {

    }

    record NodeDto(String name, List<NodeDto> childNodeDtos) {

    }
  }
```

```Java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2024-02-22T17:52:46+0900",
    comments = "version: 1.5.3.Final, compiler: javac, environment: Java 17.0.5 (Amazon.com Inc.)"
)
@Component
public class TestMapperImpl implements TestMapper {

    @Override
    public Target map(Source source) {
        if ( source == null ) {
            return null;
        }

        List<NodeDto> childNodeDtos = null;

        List<Node> childNodes = sourceRootNodeChildNodes( source );
        childNodeDtos = nodeListToNodeDtoList( childNodes );

        Target target = new Target( childNodeDtos );

        return target;
    }

    @Override
    public NodeDto map(Node node) {
        if ( node == null ) {
            return null;
        }

        List<NodeDto> childNodeDtos = null;
        String name = null;

        childNodeDtos = nodeListToNodeDtoList( node.childNodes() );
        name = node.name();

        NodeDto nodeDto = new NodeDto( name, childNodeDtos );

        return nodeDto;
    }

    private List<Node> sourceRootNodeChildNodes(Source source) {
        if ( source == null ) {
            return null;
        }
        Node rootNode = source.rootNode();
        if ( rootNode == null ) {
            return null;
        }
        List<Node> childNodes = rootNode.childNodes();
        if ( childNodes == null ) {
            return null;
        }
        return childNodes;
    }

    protected List<NodeDto> nodeListToNodeDtoList(List<Node> list) {
        if ( list == null ) {
            return null;
        }

        List<NodeDto> list1 = new ArrayList<NodeDto>( list.size() );
        for ( Node node : list ) {
            list1.add( map( node ) );
        }

        return list1;
    }
}
```

**Comment by filiphr** [comment] 2024-07-20 14:12
Thanks for the detailed example @codeStev. It seems like this has the same root cause as #3591. Going to close this one in favor of that one

**Closed by filiphr** 2024-07-20 14:12 UTC
Labels: bug
