### ISSUE TITLE
Error message is incorrect. Mapper's location is not shown.

### ISSUE THREAD

**Issue by MaximKislekov** [mapstruct/mapstruct#1527] opened 2018-06-18 10:34 UTC
Mapstruct: 1.2.0.Final
Java 1.8.0_171
Gradle

Error message is incorrect. Mapper 's location is not shown.
Message: 

> error: Unmapped target property: "id".

Expected message

> error: Unmapped target property: "id".
/mypackage/VenueMapper.java:12: error: Unmapped target property: "id".

Code:
```
@Mapper(config = BaseMapperConfig.class)
public abstract class VenueMapper implements BaseCrudMapper<Venue, VenueDto> {
}
```
```
@MapperConfig(
        unmappedTargetPolicy = ReportingPolicy.ERROR,
        mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_FROM_CONFIG)
public interface BaseMapperConfig {
}
```
BaseCrudMapper is in other gradle project.

**Comment by sjaakd** [comment] 2018-06-18 15:34
Duplicate of #1504 . Issue is resolved in PR #1503

**Closed** 2018-06-18 15:35 UTC
Labels: duplicate
