### ISSUE TITLE
Defining mappings in config files/database tables

### ISSUE THREAD

**Issue by sandeeprajub4u** [mapstruct/mapstruct#531] opened 2015-04-06 08:58 UTC
Can we define the mappings in config file/database tables? We would like the mapping (Impl) classes to be generated at runtime (which would be at the startup of our application) rather than at compile time. How to achieve it with mapstruct?

**Comment by agudian** [comment] 2015-04-06 18:07
@sandeeprajub4u - defining mappings in config files or database tables is not possible. The generation of mapper implementations from mapper interfaces at runtime is not something we actually propose (although it is technically possible to invoke the Java annotation processor, compile the result and add the classes to the classloader - we do that in our unit-tests).

What we see as one of the main advantages of MapStruct compared to mappers that work at runtime only (such as Dozer or Orika), is the type safety and compile-time check that what you want to map is acually mappable. We want compile errors if a user tries to map a CarDto to a CustomerEntity - and not some exceptions or unintended behaviour at runtime when that code is actually executed. This is also why we want to express every mapping-configuration aspect in the form of annotations on the mappers or the mapping methods, so that you need to re-compile if you want any changes to have an effect.

I'm closing this, labled as "question". If you feel there is a feature missing here, or that I misunderstood your proposal, please feel free to reopen and we can discuss this further.

**Closed by agudian** 2015-04-06 18:07 UTC
Labels: question
