### ISSUE TITLE
mapping a key/value to other java bean

### ISSUE THREAD

**Issue by endison1986** [mapstruct/mapstruct#2750] opened 2022-02-10 02:03 UTC
when I try to mapping a key/value to other java bean, I got this error message.

```java
    @Mapper
    public interface TestMapper {
        TestMapper INSTANCE = Mappers.getMapper( TestMapper.class );
        @Mapping(target = "value", source = "params.value")
        User convert(User2 user);
    }

    @Getter
    @Setter
    public static class User2 {
        private Map<String, Object> params;
    }
    @Getter
    @Setter
    public static class User {
        private String value;
    }
```

```console
java: No property named "params.value" exists in source parameter(s). Did you mean "params.empty"?
```

**Comment by Zegveld** [comment] 2022-02-10 11:44
you want to retrieve a specific value from the map I assume. MapStruct does not support this in the above manner.

See [mapping map to bean](https://mapstruct.org/documentation/dev/reference/html/#mapping-map-to-bean) for information about mapping a Map to a Bean. 

Or create a method which will tell MapStruct how to do the mapping for example:
```
  @Mapper
    public interface TestMapper {
        TestMapper INSTANCE = Mappers.getMapper( TestMapper.class );
        @Mapping(target = "value", source = "params", qualifiedByName="getValueKeyFromMap")
        User convert(User2 user);
        
        @Named("getValueKeyFromMap")
        default String valueKeyFromMap(Map<String, Object> map) {
            Object value = map.get("value");
            return /* do Object to String transformation for value */;
        }
    }
```

**Comment by filiphr** [comment] 2022-02-11 08:58
@Zegveld are you sure that this is not supported? WIth the new [mapping map to bean](https://mapstruct.org/documentation/dev/reference/html/#mapping-map-to-bean) this should be doable.

The problem is still there though that you need a method for mapping from `Object` to `String` because MapStruct doesn't know how to map that.

**Comment by Zegveld** [comment] 2022-02-11 09:38
> @Zegveld are you sure that this is not supported? WIth the new [mapping map to bean](https://mapstruct.org/documentation/dev/reference/html/#mapping-map-to-bean) this should be doable.

I am now unsure whether it is supported as a **nested mapping**, because I did not work on it myself (going to test it after work or during lunch). Also it seems that I forgot to ask which mapstruct version was being used and probably incorrectly assumed `1.5.0.Beta2`. Since the mapping map-to-bean will be introduced with 1.5.0 (currently in Beta2).

**Comment by filiphr** [comment] 2022-02-11 10:17
I had a test case open, but I am on my phone now. Can link it later

**Comment by Zegveld** [comment] 2022-02-11 11:41
@filiphr , you are correct it works exactly as specified in the example. All that is needed is to use the 1.5.0 build. Currently `1.5.0.Beta2`

**Comment by filiphr** [comment] 2022-02-12 08:27
Thanks for trying it out @Zegveld. I also found the example [`MapToBeanFromMapAndNestedMapWithDefinedMapping`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/test/java/org/mapstruct/ap/test/frommap/MapToBeanFromMapAndNestedMapWithDefinedMapping.java).

Closing this as it works as it should in the upcoming 1.5.0

**Closed by filiphr** 2022-02-12 08:27 UTC
