### ISSUE TITLE
Non effective code generated for nested property conversion

### ISSUE THREAD

**Issue by pavelbely** [mapstruct/mapstruct#843] opened 2016-07-27 07:04 UTC
Hi!

MapStruct generates code to call method twice instead of saving it result to a variable and then working with it.

Consider the interface
```java
@Mapper
public interface TagMapper {

	@Mapping(target = "date", source = "gitlabTag.commit.authoredDate")
	TagInfo gitlabTagToTagInfo(GitlabTag gitlabTag);
}
```

And the following is generated. Please mind double usage of gitlabTagCommitAuthoredDate() method.
```java
public class TagMapperImpl implements TagMapper {

    @Override
    public TagInfo gitlabTagToTagInfo(GitlabTag gitlabTag) {
        if ( gitlabTag == null ) {
            return null;
        }

        TagInfo tagInfo = new TagInfo();

        if ( gitlabTagCommitAuthoredDate( gitlabTag ) != null ) {
            tagInfo.setDate( new DateTime( gitlabTagCommitAuthoredDate( gitlabTag ) ) );
        }
        ...

        return tagInfo;
    }

    private Date gitlabTagCommitAuthoredDate(GitlabTag gitlabTag) {

        if ( gitlabTag == null ) {
            return null;
        }
        GitlabBranchCommit commit = gitlabTag.getCommit();
        if ( commit == null ) {
            return null;
        }
        Date authoredDate = commit.getAuthoredDate();
        if ( authoredDate == null ) {
            return null;
        }
        return authoredDate;
    }
}
```

I am using MapStruct 1.0.0.Final with Java 8.

**Comment by agudian** [comment] 2016-07-28 18:29
Still present in 1.1.0.Beta2. We should fix that.
@pavelbely, thanks for letting us know! Would you be interested in providing a fix?

**Comment by pavelbely** [comment] 2016-07-29 06:28
You are welcome, Andreas.
Sure, I will try to fix it.

**Comment by sjaakd** [comment] 2016-07-29 07:17
There should be such issue for the reverse nesting case. I noticed it just before merging but ran out of time. Perhaps we are talking about the same one.

Verstuurd vanaf mijn iPhone

**Comment by sjaakd** [comment] 2016-07-29 08:44
Could this be caused by an old version as well? I vaguely remember that such issue is fixed in the forward mapping (even before 1.0.0)...

Verstuurd vanaf mijn iPhone

**Comment by sjaakd** [comment] 2016-08-27 20:03
Hi, 

I tried to reproduce this on 1.1.0.Beta2.. This is the result:

```java
public class TagMapperImpl implements TagMapper {

    @Override
    public TagInfo gitlabTagToTagInfo(GitlabTag gitlabTag) {
        if ( gitlabTag == null ) {
            return null;
        }

        TagInfo tagInfo = new TagInfo();

        tagInfo.setDate( gitlabTagCommitAuthoredDate( gitlabTag ) );

        return tagInfo;
    }

    private Date gitlabTagCommitAuthoredDate(GitlabTag gitlabTag) {

        if ( gitlabTag == null ) {
            return null;
        }
        Commit commit = gitlabTag.getCommit();
        if ( commit == null ) {
            return null;
        }
        Date authoredDate = commit.getAuthoredDate();
        if ( authoredDate == null ) {
            return null;
        }
        return authoredDate;
    }
}
```

However, if I change the `@Mapper` to `@Mapper( nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS )` it will trigger the ineffective code as in your example. Have you migrated to 1.1.0.Beta2?

We should fix this. But its more a corner case than I initially thought.

**Comment by sjaakd** [comment] 2016-08-30 20:55
@pavelbely : can you check this to the lasted 1.1.0.SNAPSHOT? I could not completely reproduce your original problem. My guess is it was already fixed. I fixed another corner case. I'm going to close it for the mean time.

@agudian: thanks for reviewing.

**Closed by sjaakd** 2016-08-30 20:55 UTC
Labels: enhancement

**Comment by stoerr** [comment] 2016-09-08 11:53
This ticket seems to introduce some bugs. We tried to upgrade from 1.1.0.Beta2 to 1.1.0.CR1, and got some NullPointerExceptions. If you try to map the following, you get code that will throw an NPE when nested.getPropInt is null. Shall I report a separate bug, or is it sufficient to include this here?

@Mapper
public interface BuggyMapper {

    class Src {
        public SrcNested getNested() {
            return new SrcNested();
        }
    }

    class SrcNested {
        public Integer getPropInt() {
            return 1;
        }
    }

    class Dest {
        public void setPropLong(Long l) {
        }
    }
    @Mapping(source = "nested.propInt", target = "propLong")
    Dest convert(Src src);
}

generates the following buggy code:

public class BuggyMapperImpl implements BuggyMapper {

    @Override
    public Dest convert(Src src) {
        if ( src == null ) {
            return null;
        }

        Dest dest = new Dest();

        dest.setPropLong( srcNestedPropInt( src ).longValue() );

        return dest;
    }

    private Integer srcNestedPropInt(Src src) {

        if ( src == null ) {
            return null;
        }
        SrcNested nested = src.getNested();
        if ( nested == null ) {
            return null;
        }
        Integer propInt = nested.getPropInt();
        if ( propInt == null ) {
            return null;
        }
        return propInt;
    }
}

**Comment by sjaakd** [comment] 2016-09-08 13:42
Thanks for the report . Will look into this.

**Comment by gunnarmorling** [comment] 2016-09-08 14:06
> Shall I report a separate bug, or is it sufficient to include this here?

Could you please open a new one for this? Thanks!

**Comment by stoerr** [comment] 2016-09-09 13:02
I did report a new bug for this problem #891 .

**Comment by sjaakd** [comment] 2016-09-09 15:28
Thanks ! I'll look into it early next week.
