### ISSUE TITLE
Missing import using built-in types for Date conversion

### ISSUE THREAD

**Issue by tbrizard** [mapstruct/mapstruct#987] opened 2016-12-07 20:11 UTC
I am seeing the same error described in https://github.com/mapstruct/mapstruct/issues/248.  However, in my case the target property is of type `java.lang.String` and the source type is `java.sql.Timestamp`.  The code compiles without error using 1.0.0.Final and I only started to get compile errors when I upgraded to 1.1.0.Final.

The interface having the issue is thousands of lines long (I didn't write it ;-) ), so I've created a simple test to try and re-produce the issue (see below).  But in my simple test the source is generated correctly (i.e. the `java.util.Date` import is there).  Also, in the mapper interface having the issue I added `@Mapper(imports = { Date.class })` which still did not add the import in the generated code.

Perhaps someone else can quickly spot the issue.

```
public class Order {

	private String id;
	private Timestamp timestamp;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Timestamp getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(Timestamp timestamp) {
		this.timestamp = timestamp;
	}

}
```

```
public class OrderDTO {

	private String id;
	private String timestamp;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

}
```
```
@Mapper
public interface CustomerMapper {

	OrderDTO orderToDTO(Order order);
}
```

The above code essentially sets up the same scenario as the mapper that is having the compilation issue. As a matter of fact, the private methods for dealing with the GregorianCalendar and Date conversion are identical and the line that converts the Timestamp to a String when setting it on the target is also nearly identical. Yet, the generated code for the mapper above does include the import for `java.util.Date` whereas the other generated mapper code does not.  I am guessing there is something with the complexity of the other mapper interface that causes MapStruct to skip the importing of the Date class for some reason.

**Comment by filiphr** [comment] 2016-12-07 20:47
@tbrizard Can you perhaps show us the `imports` on your mapper? Do you perhaps have a class which is also named `Date`? What is the exact compilation error that you are seeing?

You said that with 1.0.0.Final it compiled. However, there was no support for `java.sql.Timestamp` at that time. Did you had a custom method that was doing to mapping?

**Comment by gunnarmorling** [comment] 2016-12-07 21:04
A conflict with another class of the same simple name `Date` would be my guess as well.

**Comment by filiphr** [comment] 2016-12-07 22:15
@gunnarmorling most probably the problem is that there is another class with that simple name. However, I think that we might need to consider changing the templates for the `BuiltInMethod`(s). For example in the `DateToXmlGregorianCalendar.ftl` we have `private XMLGregorianCalendar ${name}( Date date )` where `Date` (the parameter) and `XMLGregorianCalendar` (the return type) are not written using the type model.

WDYT?

**Comment by tbrizard** [comment] 2016-12-07 22:15
I confirmed I don't have another Date class being used in my mapper or in the particular beans involved that are calling dateToXmlGregorianCalendar method within the generated mapper code.  Here are some more details.

The actual compilation error:
```
[ERROR] diagnostic: C:\XXXXXXXXX\generated-sources\java\com\XXXXXXX\DaoMapStructImpl.java:6407: error: cannot find symbol
    private XMLGregorianCalendar dateToXmlGregorianCalendar( Date date ) {
                                                             ^
  symbol:   class Date
  location: class com.XXXXXXXXXXX.DaoMapStructImpl
[ERROR] error on execute: error during compilation
```

Using 1.0.0.Final
```
. . . .

import java.util.Arrays;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;

. . . .

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2016-12-07T16:39:37-0500",
    comments = "version: 1.0.0.Final, compiler: javac, environment: Java 1.8.0_101 (Oracle Corporation)"
)
@ApplicationScoped
public class DaoMapStructImpl implements DaoMapStruct {

. . . .

     myBean.setTimestamp( xmlGregorianCalendarToString( dateToXmlGregorianCalendar( anotherBean.getTimestamp() ) , null ) );

. . . .

}
```

Using 1.1.0.Final
```
. . . .

import java.util.Arrays;
import java.util.GregorianCalendar;
import java.util.HashMap;

. . . . 

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2016-12-07T16:46:42-0500",
    comments = "version: 1.1.0.Final, compiler: javac, environment: Java 1.8.0_101 (Oracle Corporation)"
)
@ApplicationScoped
public class DaoMapStructImpl implements DaoMapStruct {

. . . .

        myBean.setTimestamp( xmlGregorianCalendarToString( dateToXmlGregorianCalendar( anotherBean.getTimestamp() ), null ) );

. . . .

}
```

With no changes to my mapper or bean classes you can see that 1.0.0.Final generates the code that includes the `java.util.Date` import whereas 1.1.0.Final does not.

**Comment by filiphr** [comment] 2016-12-08 19:42
@tbrizard This is really strange problem that you have. Is it somehow possible for you to give us a reproducible example so we can investigate the error?

**Comment by gunnarmorling** [comment] 2016-12-12 19:57
Weird indeed. A condensed example would be much appreciated. Or, if you feel adventureous, you also could debug into MapStruct itself and check where in the model tree the `Date` type gets lost from the list of types to be imported (watch for the `getImportTypes()` method).

**Comment by tbrizard** [comment] 2016-12-12 20:54
@gunnarmorling - I'll start digging into the MapStruct code and take a look at the `getImportTypes` as you suggested.  I'll post back what I find in the next few days.

**Comment by gunnarmorling** [comment] 2017-02-17 22:08
Hey @tbrizard did you ever have a chance to look into this one?

**Comment by filiphr** [comment] 2018-02-19 23:23
It seems this is no longer a problem. Closing the issue

**Closed by filiphr** 2018-02-19 23:23 UTC
