### ISSUE TITLE
Add @TargetProperty

### ISSUE THREAD

**Issue by sasavilic** [mapstruct/mapstruct#2811] opened 2022-04-07 14:51 UTC
I am trying to use (or better to say abuse) mapstruct do generate diff of my object without using reflection. It got all ingredients that I need expect name of the fields that is being mapped. Is there a way to get such information and if not, would you be willing to consider adding @TargetProperty similar to @TargetType?

Below is example of what I am trying to achieve: 

```java
@Mapper
public abstract class DiffGenerator {
    public static class Foo {
        private Integer bar;

        private String cat;

        private String dog;

        public Integer getBar() {
            return bar;
        }

        public Foo setBar(Integer bar) {
            this.bar = bar;
            return this;
        }

        public String getCat() {
            return cat;
        }

        public Foo setCat(String cat) {
            this.cat = cat;
            return this;
        }

        public String getDog() {
            return dog;
        }

        public Foo setDog(String dog) {
            this.dog = dog;
            return this;
        }
    }


    public enum PropertyState {
        ADDED,
        MODIFIED,
        REMOVED
    }

    public static class Property<T> {
        private final Class<T> clz;
        private PropertyState state = null;
        private T oldValue = null;
        private T newValue = null;

        public Property(Class<T> clz) {
            this.clz = clz;
        }

        public Class<T> getClz() {
            return clz;
        }

        public PropertyState getState() {
            return state;
        }

        public Property<T> setState(PropertyState state) {
            this.state = state;
            return this;
        }

        public T getOldValue() {
            return oldValue;
        }

        public Property<T> setOldValue(T oldValue) {
            this.oldValue = oldValue;
            return this;
        }

        public T getNewValue() {
            return newValue;
        }

        public Property<T> setNewValue(T newValue) {
            this.newValue = newValue;
            return this;
        }
    }

    protected static class Visitor {
        private final Map<String, Property<?>> deltas = new LinkedHashMap<>();

        public Map<String, Property<?>> getDeltas() {
            return deltas;
        }

        private boolean secondPass = false;

        private void markSecondPass() {
            secondPass = true;
        }

        public <T> void recordValue(String propertyName, T value, Class<T> clz) {
            Property<T> property = (Property<T>)deltas.computeIfAbsent(propertyName, x -> new Property<>(clz));
            if (!secondPass) {
                if (value != null) {
                    property.setOldValue(value);
                    property.setState(PropertyState.REMOVED);
                }
            } else {
                if (value != null) {
                    property.setNewValue(value);
                    property.setState(PropertyState.ADDED);
                    if (property.getOldValue() != null) {
                        property.setState(PropertyState.MODIFIED);
                    }
                }
            }
        }

    }

    public Map<String, Property<?>> getFooDelta(Foo oldObj, Foo newObj) {
        Visitor visitor = new Visitor();
        map(oldObj, visitor);
        visitor.markSecondPass();
        map(newObj, visitor);
        return visitor.getDeltas();
    }

    protected <T> T recordChange(T src, @Context Visitor visitor, @TargetType Class<T> clz) {
        visitor.recordValue("<HERE IS WHAT IS MISSING>", src, clz);
        return src;
    }

    protected abstract Foo map(Foo foo, @Context Visitor visitor);
}
```

**Comment by Zegveld** [comment] 2022-04-07 16:38
There is already an issue for this request, closing it as it is a duplicate of #2688

**Closed by Zegveld** 2022-04-07 16:38 UTC
