### ISSUE TITLE
Error for fields which are not in record class for mapping

### ISSUE THREAD

**Issue by ajinkyapatki44** [mapstruct/mapstruct#3035] opened 2022-09-28 11:45 UTC
### Expected behavior

**My Java Record Classes:** 
**First one:**
```java
public record PersonRecord(List<String> addressList) {  }
```

**Second one:**
```java
public record EmployeeRecord(List<String> addressList) {  }
```

**Mapper Interface** :-

```java
@Mapper(unmappedSourcePolicy = ReportingPolicy.ERROR, unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface PersonMapper {

  PersonMapper INSTANCE = Mappers.getMapper(PersonMapper .class);
  PersonRecord toPersonRecord(EmployeeRecord employeeRecord);
}
```

Expected is it should not fail when I build project.

### Actual behavior

When I build project, it's failing with below errors
```
 error: Unmapped target property: "ressList".
  PersonRecord toPersonRecord(EmployeeRecord employeeRecord);
```
If you look at records, defined property is addressList which is same in both record classes.

I have tried to add some more normal (String, Integer etc) fields, its working for those.
but its failing for collection fields(List, Set).

### Steps to reproduce the problem

Just added dependency to classpath and created below interface

```java
@Mapper(unmappedSourcePolicy = ReportingPolicy.ERROR, unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface PersonMapper {

  PersonMapper INSTANCE = Mappers.getMapper(PersonMapper .class);
  PersonRecord toPersonRecord(EmployeeRecord employeeRecord);
}

```

### MapStruct Version

1.5.2

**Comment by filiphr** [comment] 2022-09-28 18:41
@ajinkyapatki44 the problem is not for collection fields (List, Set), but the problem is in the name of the fields that are starting with `add`. The error should actually not be there and we shouldn't treat that as a property I do agree. We are going to look into fixing it.

Anyways, what happens if you do not use a `ReportingPolicy.ERROR`? I believe that we are going to properly map the address list from one to another record.

**Comment by ajinkyapatki44** [comment] 2022-09-30 10:48
@filiphr  No, problem is not with **add**, see below code, I have updated parameter name to departmentList.

public record PersonRecord(List<String> departmentList) {}

public record EmployeeRecord(List<String> departmentList) {}

Mapper is same as above.

Now it started giving me below error:
error: Unmapped target property: **"artmentList"**.
  PersonRecord toPersonRecord(EmployeeRecord employeeRecord);
               ^

I can see it is skipping 3 characters from variable name. (addressList ----> ressList,  departmentList ----> artmentList )

**Comment by filiphr** [comment] 2022-10-02 10:09
Which Java version are you using @ajinkyapatki44? We have this exact test case in our integration tests and it works properly

**Comment by ajinkyapatki44** [comment] 2022-10-03 06:44
@filiphr  
openjdk version "17.0.4.1" 2022-08-12 LTS
OpenJDK Runtime Environment Corretto-17.0.4.9.1 (build 17.0.4.1+9-LTS)

**Comment by filiphr** [comment] 2022-10-03 19:23
Really strange @ajinkyapatki44 I just tried with 

```
openjdk 17.0.4 2022-07-19 LTS
OpenJDK Runtime Environment Corretto-17.0.4.8.1 (build 17.0.4+8-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.4.8.1 (build 17.0.4+8-LTS, mixed mode, sharing)
```

and it works as expected. Can you please create a reproducible example in a git repo that we can clone and run MapStruct?

**Comment by filiphr** [comment] 2022-11-03 21:45
Closing this because I couldn't reproduce the problem.

**Closed by filiphr** 2022-11-03 21:45 UTC
Labels: bug
