### ISSUE TITLE
Mapstruct tries to access private constructor instead of using (Lombok) Builder for deepclone

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#2410] opened 2021-04-09 16:52 UTC
Mapstruct tries to access private constructor instead of using (Lombok) Builder for deepclone

```java
    @Mapper( mappingControl = DeepClone.class )
    public interface CloningMapper {
        Entity clone(Entity in);
    }
```

```java
@Getter
@Builder
public class Entity implements Serializable {
  
    private String name;
}
```

**Comment by thunderhook** [comment] 2023-09-20 20:43
@sjaakd Just checking some old issues. I could not reproduce this, do you have a possible reproducal? If not, feel free to close the issue. (tried with 1.4.2 and 1.5.5 with and without `lombok-mapstruct-binding`)

```java
import java.io.Serializable;

import lombok.Builder;
import lombok.Getter;
import org.mapstruct.Mapper;
import org.mapstruct.control.DeepClone;

@Mapper(mappingControl = DeepClone.class)
interface CloningMapper {
    Entity clone(Entity in);
}

@Getter
@Builder
class Entity implements Serializable {
    private String name;
} 
```

generated...

```java
class CloningMapperImpl implements CloningMapper {

    @Override
    public Entity clone(Entity in) {
        if ( in == null ) {
            return null;
        }

        EntityBuilder entity = Entity.builder();

        entity.name( in.getName() );

        return entity.build();
    }
}
```

**Comment by filiphr** [comment] 2023-09-30 08:53
Thanks for checking @thunderhook. Closing this, @sjaakd will reopen if he can still reproduce it.

**Closed by filiphr** 2023-09-30 08:53 UTC
