### ISSUE TITLE
Mapping using decorator throws "Can't generate mapping method from non-iterable type to iterable type"

### ISSUE THREAD

**Issue by thekalinga** [mapstruct/mapstruct#875] opened 2016-08-31 08:03 UTC
Given the following classes

```java
class Root {
  public Collection<Child> children;
  public String additionalProp;
  // getter & setters
}

class Child {
  public String prop;
  // getter & setters
}

class ChildResponse {
  private String prop;
  private String additionalProp;
  // getter & setters
}
```

```java
@DecoratedWith(RootDecorator.class)
public interface RootMapper {
   List<ChildResponse> toChildResponses(Root root);
   ChildResponse toChildResponseDefault(Child child);
}
```

```java
public abstract class RootDecorator implements RootMapper {
  @Autowired
  @Qualifier("delegate")
  private RootMapper delegate;
  
  public List<ChildResponse> toChildResponses(Root root) {
    return root.getChildren().stream().map(v -> {
      ChildResponse response = delegate.toChildResponseDefault(v);
      response.setAdditionalProp(v.getAdditionalProp());
      return response;
    }).collect(toList());
  }
}
```

If I try to compile, I get the following exception

```java
Can't generate mapping method from non-iterable type to iterable type
```

Please note that I have explicitly overriden ```toChildResponses()``` method

**Comment by sjaakd** [comment] 2016-08-31 08:31
@thekalinga: this is not how decorators work. 
1. MapStruct first tries to generate the `RootMapper`, `RootMapperImpl`.
2. MapStruct then tries to generate the `RootDecorator`. MapStruct will generate a simple implementation of all non overridden methods, delegating their call to the `RootMapper`.

Step 1. fails in your scenario.

There are a number of ways to fix this:
1.  define an abstract class 'RootMapper` (instead of an interface) in which you implement the `List<ChildResponse> toChildResponses(Root root)` mapper?
2. add a used (hand written) mapper to the `RootMapper` that has the `List<ChildResponse> toChildResponses(Root root)`  (more reusable across other mappers too).

Is this the only reason you implemented the decorator? If so, you possibly don't need it.

**Comment by thekalinga** [comment] 2016-08-31 08:59
@sjaakd Thanks for your prompt response.

1. I am achieving reusability by injecting this mapper in other mapper decorators/services.
2. ```java @Mapper(uses = {ReusuableChildMapper.class})``` is useful only if this mapeper is applicable to other mappers aswell, but in my case, this mapping is required only once, just for this scenario.
3. If I make it an abstract class, what will happen to other abstract methods in this abstract, would mapstruct auto generate mapping for those methods aswell?

I believe the build should not generate the delegate method/atleast should blindly delegate to the decorator, if with the same method signature.

My mapping classes have various default mapping methods (with `Default` prefix) & other mapping methods. Its a convention not to use `Default` sufix methods.

If any other non `Default` method require additional processing, I enhance this in the delegate.

Please let me know if I'm doing anything wrong.

**Comment by sjaakd** [comment] 2016-08-31 09:09
> I am achieving reusability by injecting this mapper in other mapper decorators/services.
> @Mapper(uses = {ReusuableChildMapper.class}) is useful only if this mapper is applicable to other mappers aswell, but in my case, this mapping is required only once, just for this scenario.

That's just perfectly fine.

> If I make it an abstract class, what will happen to other abstract methods in this abstract class, would mapstruct auto generate mapping for those methods aswell?

Yes. Abstract methods in abstract classes and interfaces (in essence also abstract methods) will trigger MapStruct to do its job.. See chapter 3.2 of our documentation.

> I believe the build should not generate the delegate method/atleast should blindly delegate to the decorator, if there is a method among the decorators with the same signature.

But that's exactly the intention. It leaves the possibility to let the generated MapStruct method in the decorated mapper do the bulk of the work. In your decorator, you can just tweak the things you need to get tweaked and then call the decorated mapper.

**Comment by thekalinga** [comment] 2016-08-31 10:54
Thanks

**Comment by sjaakd** [comment] 2016-08-31 10:59
@thekalinga .. I hope the issue is resolved. I'll continue to close this issue. If you have additional questions, please also checkout our [user-group](https://groups.google.com/forum/?fromgroups#!forum/mapstruct-users).

**Closed by sjaakd** 2016-08-31 10:59 UTC
