### ISSUE TITLE
handle Optional transparently

### ISSUE THREAD

**Issue by xenoterracide** [mapstruct/mapstruct#3457] opened 2023-11-29 14:42 UTC
### Use case

when you have one object that has a "Nullable" interface, and the other uses `Optional`, this mapping should be able to be done without issue; as long as the type is recognized. I got an error trying to map `String` and `Optional<String>`.

### MapStruct Version

1.5.5

**Comment by filiphr** [comment] 2023-12-11 21:29
Closing this as a duplicate of #674.

**Closed by filiphr** 2023-12-11 21:29 UTC
