### ISSUE TITLE
@MapperConfig(componentModel = "jsr330") does not generate empty @Inject annotated constructor

### ISSUE THREAD

**Issue by Double-O-Seven** [mapstruct/mapstruct#2182] opened 2020-08-19 09:55 UTC
Hello, I'm generating Mappers with `componentModel = "jsr330"`. However, there is a small problem:

Unless the generated mapper uses another mapper, no empty `@Inject` annotated constructor is generated. This is suboptimal where requiring an `@Inject` annotated constructor, in case of Dagger for example, or when a Guice module is configured with `requireAtInjectOnConstructors`.

**Comment by sjaakd** [comment] 2020-08-21 08:57
I guess this should be made configurable somehow. We already have `InjectionStrategy` perhaps this can be extended with an enum value.. E.g. 

```java
public enum InjectionStrategy {

    /** Annotations are written on the field **/
    FIELD,

    /** Annotations are written on the constructor **/
    CONSTRUCTOR,

    /** Annotations are written on the constructor, an empty constructor with @Inject will be generated when no used mappers **/
    CONSTRUCTOR_INCLUDING_EMPTY

}

```

@filiphr .. WDYT?

**Comment by filiphr** [comment] 2020-08-26 19:46
@sjaakd this depends on the chosen `componentModel`. I think that this is a duplicate of #1617 (if it is about Dagger). I have commented (a while ago) here: https://github.com/mapstruct/mapstruct/issues/1617#issuecomment-500362762. 

As for Guice, won't the solution done for https://github.com/mapstruct/mapstruct/issues/1657 work here? Basically use:

```
bind( SomeMapper.class ).to( Mappers.getMapperClass( SomeMapper.class ) );
```

**Comment by sjaakd** [comment] 2020-08-28 20:03
I'm not too familiar with `Guice` and `Dagger`. I guess they are both JSR330 compliant (just as `Spring` and `CDI`), right? Then it would perhaps be sensible to add a configuration option like I described.. Perhaps we cover even more JSR330 implementations. Like Apache `commons inject`

**Comment by filiphr** [comment] 2020-08-29 06:24
>I'm not too familiar with `Guice` and `Dagger`. I guess they are both JSR330 compliant (just as `Spring` and `CDI`), right? 

If they require something special to make it work, like empty constructor annotated with `@Inject`, they are not 100% compliant in my opinion.

I would prefer to have dedicated component model for this. This could even be done with a custom `ModelElementProcessor` extending from `AnnotationBasedComponentModelProcessor` or even `Jsr330ComponentProcessor` and overriding `additionalPublicEmptyConstructor` and returning `true`.

**Comment by sjaakd** [comment] 2020-08-29 07:21
> I would prefer to have dedicated component model for this. This could even be done with a custom `ModelElementProcessor` extending from `AnnotationBasedComponentModelProcessor` or even `Jsr330ComponentProcessor` and overriding `additionalPublicEmptyConstructor` and returning `true`.

So.. that's not too tricky.. If that's the only thing, lets add `Dagger` as component model..

**Comment by sjaakd** [comment] 2020-08-29 09:45
@Double-O-Seven .. Would you be able to look at this, write a PR and add a component type for dagger, just as @filiphr suggests? 

we don't have any experience with Dagger, but from what I understand, I guess you need to:
1. tackle the empty constructor along the lines that @filiphr suggests
2. add unit tests (there are already unit test for spring and cdi), making use of dagger to see if it really works.
3. ?  (I don't know if that's it, or that dagger requires more changes in the processor-to-devolop.

**Comment by filiphr** [comment] 2020-08-29 09:49
I'll close this one in favour of #1617. Feel free to use that one if you want to work on this @Double-O-Seven. Feel free to reach out if you need some help

**Closed by filiphr** 2020-08-29 09:49 UTC
Labels: feature, up-for-grabs

**Comment by Double-O-Seven** [comment] 2020-08-30 17:54
@filiphr @sjaakd Sure, I'll have a look at it.
