### ISSUE TITLE
qualifiedByName 被覆盖了，问题是出在用法不准确吗

### ISSUE THREAD

**Issue by yukai3804** [mapstruct/mapstruct#2288] opened 2020-11-30 07:58 UTC
![image](https://user-images.githubusercontent.com/7309823/100582777-bc8b0a00-3324-11eb-9a1b-33631ae966da.png)

![image](https://user-images.githubusercontent.com/7309823/100582764-b72dbf80-3324-11eb-9ebe-eca37caaec4c.png)

![image](https://user-images.githubusercontent.com/7309823/100582804-c44aae80-3324-11eb-9fb7-bc2fb107c202.png)

**Comment by yukai3804** [comment] 2020-11-30 07:58
@Mapping(source = "offerRange", target = "offerRange", qualifiedByName = "fenToYuan")
    @Mapping(source = "competitionStart", target = "competitionStart", qualifiedByName = "fenToYuan")
    @Mapping(source = "competitionTime", target = "competitionTime", qualifiedByName = "secondToMin")
    @Mapping(source = "extendTime", target = "extendTime", qualifiedByName = "secondToMin")
    CompetitionOrderSpRuleVo orderInfoToRuleVo(CompetitionOrderInfo orderInfo);




/**
     * 将领域中金额分转元
     *
     * @param fen 分
     * @return 元
     */
    @Named("fenToYuan")
    default String fenToYuan(Long fen) {
        if (Objects.isNull(fen)) {
            return "0";
        }
        return BigDecimalUtil.fenToYuan(fen);
    }

    /**
     * 秒 转分
     *
     * @param second 秒
     * @return 分
     */
    @Named("secondToMin")
    default Integer secondToMin(Long second) {
        return Math.toIntExact(second / 60);
    }



 @Override
    public CompetitionOrderSpRuleVo orderInfoToRuleVo(CompetitionOrderInfo orderInfo) {
        if ( orderInfo == null ) {
            return null;
        }

        CompetitionOrderSpRuleVo competitionOrderSpRuleVo = new CompetitionOrderSpRuleVo();

        competitionOrderSpRuleVo.setCompetitionStart( fenToYuan( orderInfo.getCompetitionStart() ) );
        competitionOrderSpRuleVo.setOfferRange( fenToYuan( orderInfo.getOfferRange() ) );
        competitionOrderSpRuleVo.setCompetitionTime( fenToYuan( orderInfo.getCompetitionTime() ) );
        competitionOrderSpRuleVo.setExtendTime( fenToYuan( orderInfo.getExtendTime() ) );
        competitionOrderSpRuleVo.setWhetherOpen( orderInfo.getWhetherOpen() );
        competitionOrderSpRuleVo.setCompetitionMethod( orderInfo.getCompetitionMethod() );

        return competitionOrderSpRuleVo;
    }

**Comment by filiphr** [comment] 2020-11-30 16:55
Can you please share `CompetitionOrderSpRuleVo` and tell us which version you are using?

**Comment by xiejin90314** [comment] 2020-12-22 08:00
老哥你说的啥意思? mapstrcut有很多种用法,你这种写法也可以,但是不是很推荐,建议写一个转化规则类[比如BaseTranRule.class]
```
@Mapper(
        uses = {
                BaseTranRule.class
        },
        componentModel = "spring",
        nullValueCheckStrategy = ALWAYS,
        nullValueMappingStrategy = RETURN_NULL,
        nullValuePropertyMappingStrategy = IGNORE
)
public interface ActivityBidAppAssembler {


    @Mapping(target = "id", ignore = true)
    @Mapping(target = "uid", ignore = true)
```
里面一些分转化成元,时间戳转化成'yyyy-mm-dd'等格式规则放在BaseTranRule.class里面
```
/**
 * 基础数据类型转化
 * Created by somebody on 2020/04/22
 */
@Component
public class BaseTranRule {

    public Long convertTimeStamp(Instant time) {
        if (time == null) {
            return null;
        }
        return time.getEpochSecond();
    }

    public Instant convertInstant(Date dateTime) {
        if (dateTime == null) {
            return null;
        }
        return dateTime.toInstant();
    }

}

```
这样,当涉及到转化类型的目标转化类型匹配的时候就会自动转化,而且通用的转化规则放在一个类里面也方便维护

**Comment by filiphr** [comment] 2021-02-06 15:48
Closing this due to no feedback. Without looking into `CompetitionOrderSpRuleVo` we can't write a reproducal test case for this.

@yukai3804 please provide that class and we can reopen this.

**Closed by filiphr** 2021-02-06 15:48 UTC
