### ISSUE TITLE
Component Model "Class"

### ISSUE THREAD

**Issue by xenoterracide** [mapstruct/mapstruct#3476] opened 2023-12-18 18:18 UTC
### Use case

based on https://mapstruct.org/documentation/stable/reference/html/#passing-target-type, what if I don't need to inject anything? more context is at #3472

```java
@Mapper(
        mappingControl = DeepClone.class,
        uses = GroupProxyFactory.class,
        componentModel = ComponentModel.SPRING)
interface GroupCloner {
    Group clone(Group source);
}
```

```java
public class GroupProxyFactory {

// I could be static
    <T extends Group> T resolve(Group entity, @TargetType Class<T> clazz) {
        var trackedClass =
                TrackerProxyFactory.getTrackedClass(
                        clazz, GroupModifications.class, GroupChangeTrackingInvoker.class);
// obnoxious long, doesn't really matter implementation
        return res;
    }
}
```

I wrote a class with a static function (not thinking to annotate the class), and noticed it wasn't being used (actually it's still not).

I'm not longer sure if I'm reporting a bug, or requesting a feature... maybe both. It feels like this should work, but the generated code isn't using the `GroupProxyFactory`.

What I was going to suggest though is that it doesn't really need to know how to inject `GroupProxyFactory`, I wouldn't consider it a `Bean` it's just a class that it could `new` itself; or find a static method on.

As it is, even as documented it doesn't seem to work...

### Generated Code

```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2023-12-18T13:09:06-0500",
    comments = "version: 1.5.5.Final, compiler: IncrementalProcessingEnvironment from gradle-language-java-8.5.jar, environment: Java 11.0.21 (Eclipse Adoptium)"
)
@Component
class GroupClonerImpl implements GroupCloner {

    @Override
    public Group clone(Group source) {
        if ( source == null ) {
            return null;
        }

        Group group = new Group();
```

should be

```java
Group group = groupProxyFactory.resolve(source, Group.class);
```

Honestly I'd be even happier with

```java
Group group = groupProxyFactory.resolve(source);
```

### MapStruct Version

1.5.5

**Comment by xenoterracide** [comment] 2023-12-18 18:38
Oh, I figured it out, very non obvious though based on the original link. I needed `@ObjectFactory`. I still don't understand why previous things didn't work, so I think there's a bug.

**Comment by filiphr** [comment] 2023-12-18 19:05
>I needed `@ObjectFactory`. I still don't understand why previous things didn't work, so I think there's a bug.

Not sure why the example is without `@ObjectFactory`. Perhaps we should look into it, but it works with `@ObjectFactory`, so it isn't of a high priority.

MapStruct can't differentiate whether a method is a factory or not if it has source parameters.

>Honestly I'd be even happier with
>```java
>Group group = groupProxyFactory.resolve(source);
>```

That works if you use `@ObjectFactory`.

e.g.


```java
public class GroupProxyFactory {

    @ObjectFactory
    public static <T extends Group> T resolve(T group) {
        // implement your own logic
    }

}
```

**Comment by xenoterracide** [comment] 2023-12-18 20:58
should the example work without `@ObjectFactory`? the original one https://mapstruct.org/documentation/stable/reference/html/#passing-target-type

**Comment by filiphr** [comment] 2023-12-27 09:01
I had a better look at the passing target type example. That works as designed. It isn't meant to be used as an object factory, but as a regular mapping method. See my comment in https://github.com/mapstruct/mapstruct/issues/3472#issuecomment-1870093395

**Comment by xenoterracide** [comment] 2023-12-27 14:19
I was never able to get that to work without `@ObjectFactory`. Sadly I forget why but the example just didn't work.

**Comment by filiphr** [comment] 2023-12-27 14:43
>Sadly I forget why but the example just didn't work, it didn't generate the code, just kept calling the normal constructor.

The example is not for object factories, that's why it didn't work for you. When you use `@ObjectFactory` then everything works as expected. Without the `@objectFactory` annotation MapStruct things that it is just another mapping method and would use it if possible.

**Comment by xenoterracide** [comment] 2023-12-27 14:58
It didn't work as expected for me though. It never used the other class at all. It just generated the code as it would have without it.

**Comment by xenoterracide** [comment] 2023-12-27 15:17
This
```java
@Mapper(
        mappingControl = DeepClone.class,
        uses = GroupProxyResolver.class,
        componentModel = ComponentModel.SPRING)
interface GroupCloner {
    Group clone(Group source);
}
public class GroupProxyResolver {

// I could be static
    <T extends Group> T resolve(Group entity, @TargetType Class<T> clazz) {
    }
}
```

and this

```java
@Mapper(
        mappingControl = DeepClone.class,
        componentModel = ComponentModel.SPRING)
interface GroupCloner {
    Group clone(Group source);
}
```

generated the exact same code for me. The target resolver wasn't used at all, which as far as I could see from the documentation was not correct.

**Comment by filiphr** [comment] 2023-12-27 15:26
The fact that it generated the same code is correct. Basically for MapStruct both of the methods in the `GroupCloner` and `GroupProxyResolver` are mapping methods. Perhaps it will be clearer with this example.

```java
public class GroupHolder {

    private final Group group;

    // constructor and getter
}
```

If you now do

```java
@Mapper(
        mappingControl = DeepClone.class,
        uses = { GroupProxyResolver.class, GroupCloner.class },
        componentModel = ComponentModel.SPRING)
interface GroupHolderCloner {
    GroupHolder clone(GroupHolder source);
}
```

you are going to have a compile error with "Ambiguous mapping methods found for mapping Group to Group ..." and you will have the methods from `GroupProxyResolver` and `GroupCloner` there.

What you are looking for is to make the method in `GroupProxyResolver` as a factory, at least that's what I have understood from your comments so far.

**Comment by xenoterracide** [comment] 2023-12-27 15:41
yes, I mean, I think that's what I was looking to do. I just don't understand was `uses` with `@TargetClass` is supposed to do, and how it's supposed to work now. If that's what I wanted I have no idea how it should work, because I don't see any different code generated. If I was doing the hibernate thing it doesn't seem like it would work either.

**Comment by filiphr** [comment] 2023-12-27 15:49
I am going to close this and focus all the discussions in #3486. In our docs we have 2 examples with `@TargetType`

* [Passing the mapping target type to custom mappers](https://mapstruct.org/documentation/stable/reference/html/#passing-target-type) which shows how you can pass the target type to mapping methods. This for example is for mapping something like `Reference(String id)` into an entire entity. e.g. the DTO only has a reference, but after the mapping you get back a car with a different owner and JPA handles the updates for you
* [Object factories](https://mapstruct.org/documentation/stable/reference/html/#object-factories) which shows how you can use it when you do not have a source, e.g. you want to create an instance of the entity using a JPA factory

**Closed by filiphr** 2023-12-27 15:49 UTC

**Comment by xenoterracide** [comment] 2023-12-27 15:55
https://mapstruct.org/documentation/stable/reference/html/#passing-target-type

^ this doesn't do ANYTHING, that's what this is about... as far as I can tell it doesn't work, it's at the very top of this ticket. I recite-ed my example.

These generate the same code?! uses does nothing here

```java
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING, uses = ReferenceMapper.class )
public interface CarMapper {

    Car carDtoToCar(CarDto carDto);
}
```


```java
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING)
public interface CarMapper {

    Car carDtoToCar(CarDto carDto);
}
```

**Comment by filiphr** [comment] 2023-12-27 16:05
Please share the entire code that you have for those 2 example, because it does generate different code.

This is the basis (getters and setters omitted for brevity):

```java
public class BaseEntity {

    private String id;
}

public class Car extends BaseEntity {

    private String name;
    private Owner owner;
}

public class Owner extends BaseEntity {

    private String name;

}

public class Reference {

    private String id;
}

public class CarDto {

    private String name;
    private Reference owner;
}
```

Then 

```java
@Mapper
public interface CarMapper {

    Car map(CarDto source);

}
```

is going to generate:

```java
public class CarMapperImpl implements CarMapper {

    @Override
    public Car map(CarDto source) {
        if ( source == null ) {
            return null;
        }

        Car car = new Car();

        car.setName( source.getName() );
        car.setOwner( referenceToOwner( source.getOwner() ) );

        return car;
    }

    protected Owner referenceToOwner(Reference reference) {
        if ( reference == null ) {
            return null;
        }

        Owner owner = new Owner();

        owner.setId( reference.getId() );

        return owner;
    }
}
```

whereas 

```java
@Mapper(uses = ReferenceMapper.class)
public interface CarMapper {

    Car map(CarDto source);

}
```

is going to generate:

```java
public class CarMapperImpl implements CarMapper {

    private final ReferenceMapper referenceMapper = new ReferenceMapper();

    @Override
    public Car map(CarDto source) {
        if ( source == null ) {
            return null;
        }

        Car car = new Car();

        car.setName( source.getName() );
        car.setOwner( referenceMapper.resolve( source.getOwner(), Owner.class ) );

        return car;
    }
}
```

**Comment by xenoterracide** [comment] 2023-12-27 16:49
That code is copy/paste from the example in the documentation... I couldn't get the example in the documentation to work. In fact that code is not the complete code! that's part of the challenge there. it talks about `Reference` which is not a class that I could find in anything. See, in your example here you're showing what it is.

This was my complete code, or at least as complete as the given example

```java
@Mapper(
        mappingControl = DeepClone.class,
        uses = GroupProxyFactory.class,
        componentModel = ComponentModel.SPRING)
interface GroupCloner {
    Group clone(Group source);
}
```

```java
public class GroupProxyFactory {

// I could be static
    <T extends Group> T resolve(Group entity, @TargetType Class<T> clazz) {
       // heck I don't even need clazz I chould just use entity...
       clazz.
        return res;
    }
}
```

this was never generated

```java
 private final GroupProxyFactory groupProxyFactory = new GroupProxyFactory();
...
      Group group groupProxyFactory.resolve( source, Group.class );
```

Maybe, it's because I missed some point of trying to replicate. That could mean 2 things, 1. the docs could be improved, 2. maybe mapstruct should have thrown an error.

I think 1 is definitely true because I went around trying to figure out what `Reference` is, it doesn't appear to be documented. I assumed it was a hibernate class I'd never used... but eventually figured out that isn't true.

```java
public class Proxied {
}
```

```java
@Mapper(
    mappingControl = DeepClone.class,
    uses = ProxyResolver.class,
    componentModel = MappingConstants.ComponentModel.SPRING)
interface ProxyCloner {
    Proxied clone(Proxied source);
}
```

```java
@Component
public class ProxyResolver {

    <T, R extends T> R resolve(Group group, @TargetType Class<T> clazz) throws InvocationTargetException, InstantiationException, IllegalAccessException {
        @SuppressWarnings("unchecked")
        var instance = (R) Arrays.stream(clazz.getDeclaredConstructors()).findFirst().orElseThrow().newInstance();
        return instance;
    }
}
```

what this generates

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2023-12-27T11:39:38-0500",
    comments = "version: 1.5.5.Final, compiler: IncrementalProcessingEnvironment from gradle-language-java-8.5.jar, environment: Java 11.0.21 (Eclipse Adoptium)"
)
@Component
class ProxyClonerImpl implements ProxyCloner {

    @Override
    public Proxied clone(Proxied source) {
        if ( source == null ) {
            return null;
        }

        Proxied proxied = new Proxied();

        return proxied;
    }
}
```

what I expected based on the documentation

```java
@Component
class ProxyClonerImpl implements ProxyCloner {

    private final ProxyResolver proxyResolver = new ProxyResolver(); // actually this shouldn't be because this is a component itself, this should be constructor injected, but that's a different issue.

    @Override
    public Proxied clone(Proxied source) {
        if ( source == null ) {
            return null;
        }

        Proxied proxied = proxyResolver.resolve( source, Proxied.class);

        return proxied;
    }
}
```

now, for giggles, let's say what I got is what you expect? it doesn't make any sense to do that though. even if it doesn't know where to call resolve it should still have created the Resolver. Let's say you don't want to do that because this obviously will never work... then throw a compile error and say property not detected or something... I spent a ton of time with trying to get that example to do anything. I'm *very* frustrated that I don't know why this doesn't generate anything at all.

**Comment by xenoterracide** [comment] 2023-12-27 17:01
for giggles, this makes it even more hilarious, if I redefine proxy to be as above, it still doesn't use the resolver.

```java
public class Proxied {
    private Proxied proxy;


    public Proxied getProxy() {
        return proxy;
    }

    public void setProxy(Proxied proxy) {
        this.proxy = proxy;
    }
}
```

now if I do this

```java
public class Proxied {

    private Inner inner;

    public Inner getInner() {
        return inner;
    }

    public void setInner(Inner inner) {
        this.inner = inner;
    }

    public static class Inner {

    }
}
```

```java
@Component
public class ProxyResolver {

    Proxied.Inner resolve(Proxied inner, @TargetType Class<Proxied.Inner> clazz) throws InvocationTargetException, InstantiationException, IllegalAccessException {
        @SuppressWarnings("unchecked")
        var instance = (Proxied.Inner) Arrays.stream(clazz.getDeclaredConstructors()).findFirst().orElseThrow().newInstance();
        return instance;
    }
}
```

I get a compile error, but I don't see the functional difference between this and the hibernate example at all.

```
error: No target bean properties found: can't map property "Proxied.Inner inner" to "Proxied.Inner inner". Consider to declare/implement a mapping method: "Proxied.Inner map(Proxied.Inner value)".
    Proxied clone(Proxied source);
            ^
```

**Comment by filiphr** [comment] 2023-12-27 17:10
>I couldn't get the example in the documentation to work. In fact that code is not the complete code! that's part of the challenge there. it talks about `Reference` which is not a class that I could find in anything. See, in your example here you're showing what it is.

The documentation indeed makes some assumptions. It assumes that you can determine some pseudo structure. Perhaps, we can improve on that in there for sure.

You are really mixing the concepts that MapStruct has. There are several types of methods in MapStruct. For what you need there are 2 types of methods:

* Mapping methods - this are the core methods that MapStruct has and what is being used to map from one source to another source. Mapping methods can have additional parameters such as `@TargetType`, `@Context`, `@MappingTarget`, etc.
* Object factories - this are methods that are going to create an instance of the target type and then mapstruct will do its logic. These methods are the ones that are going to be used instead of the constructor.

Your two methods

```java
 Group clone(Group source);
 <T, R extends T> R resolve(Group group, @TargetType Class<T> clazz) 
```

are both mapping methods for MapStruct. They both provide mapping from `Group` to `Group`. What I showed was using this. What you want instead is the `resolve` method to be `ObjectFactory`.

So if you want to achieve

```java
Proxied proxied = proxyResolver.resolve( source, Proxied.class);
```

then the only thing you need to do is to annotate the `resolve` method with `@ObjectFactory`.

-----

>I get a compile error, but I don't see the functional difference between this and the hibernate example at all.


In the hibernate example all the classes have properties in them. In your example `Proxied.Inner` does not have any properties "No target bean properties found...".

-----

>now, for giggles, let's say what I got is what you expect? it doesn't make any sense to do that though. even if it doesn't know where to call resolve it should still have created the Resolver. Let's say you don't want to do that because this obviously will never work... then throw a compile error and say property not detected or something... I spent a ton of time with trying to get that example to do anything. I'm very frustrated that I don't know why this doesn't generate anything at all.

I have been trying to help you for quite a while. However, your attitude in the issues is totally unacceptable. This is an open source project that the entire team is working on in their own free time. If you are not willing to try and understand what we are trying to explain to you and see the difference in what you are sharing with us and what we are sharing with you then I would say that there is no point in discussing anymore.

I can certainly understand that you are frustrated because you are having troubles understanding something, but being condescending is certainly not OK.

**Comment by xenoterracide** [comment] 2023-12-27 18:05
> The documentation indeed makes some assumptions. It assumes that you can determine some pseudo structure. Perhaps, we can improve on that in there for sure.

yes please, I think, and no offense, I was having as much trouble understanding your pseudocode, as you were with mine.

 I think especially it's hard to know what `Reference` is because it's such a generic name as it could easily belong to something from a framework. Pretty sure hibernate has something similar... but I'd have to dig, and not today.
 

> You are really mixing the concepts that MapStruct has

sure, but I couldn't figure out what I needed, and in this case, I can see it not generating code. How am I to know it's not what I need if I can't find an example of what I need verbatim. I had to experiment. Based on the example it *should* be able to do what I'm saying, even if it's not the right tool.

> In the hibernate example all the classes have properties in them. In your example Proxied.Inner does not have any properties "No target bean properties found...".

uh, in the example (in the documentation) none of that is shown at all. Also, why does it matter? shouldn't this be able to create an object without properties?

in Spring I once asked for (what is now known as) `SimpleTransactionScope` it's primary usage was to inject a new "date like" instance. I'm not even sure this project existed when this was done... I don't know if this is the best example, but maybe it's fine. The problem we're solving is someone creating a new date instance in every single service.

```java
@Scope("transaction") // registration of simple transaction scope not included
@Bean // uh, do the no proxy option
Instant now() {
   return Instant.now();
}
```

```java
@Service
class MyGroupService {
 private final ObjectFactory<Instant> nowFactory; // injected constructor excluded for brevity, this is a spring ObjectFactory

 void saveFrom( MyGroupDto dto ) {
    MyGroupEntity entity = dao.load(dto.getId());
    mapper.copy(dto, entity);
    entity.setDateModified(nowfactory.getObject()); // used to be a new Date() which causes problems because our can now be inconsistent across the transaction, this scope solves it
    dao.save(entity);
 }
}
```

```java
@Service
class MyPersonService {
 private final ObjectFactory<Instant> nowFactory; // injected constructor excluded for brevity

 void saveFrom( MyPersonDto dto ) {
    MyGroupEntity entity = dao.load(dto.getId());
    mapper.copy(dto, entity);
    entity.setDateModified(nowfactory.getObject());
    dao.save(entity);
 }
}
```

```java
@Service
class SomeCaller {

    @Transactional
    void saveAll( MyPersonDto person, MyGroupDto group ) {
       personService.saveFrom(person);
       groupService.saveFrom(group);
    }
}
```

so what if I wanted to use mapstruct to reduce this code in the copy by loading my object factory? I wouldn't expect it to understand springs `ObjectFactory` but it feels like I would use a resolver for this? or maybe I'm supposed to use it for the `dao.load` and I'd use an `@ObjectFactory` for the date? it *feels* like between these 2 it can be done. however, an `Instant`, `Calendar`, `Date`, etc, don't have properties you can/should copy. I'd still need an injected service to do this. We can say for our purpose that Dto, does not have a date modified (it probably did...).

Although, now I think explaining this I'm confused as to why I need both. I think I could get mapstruct to do something like

```java
// entity resolver basically calls dao.load(dto.getId()

MyGroupEntity copy( MyGroupDto dto ) {
   MyGroupEntity entity = entityResolver.resolve( dto, MyGroupEntity.class ); // why isn't this factory?
   entity.setDateModified( nowResolver.resolve( dto, MyGroupEntity.class ) ); // args aren't needed could be factory? but needs spring context
}
```

> This is an open source project that the entire team is working on in their own free time. 

I have contributed to many open source projects myself. I get it. I tried in my own projects to answer every question with documentation. Please don't assume others are not contributing. By the very nature of creating tickets we are actually trying to contribute. I'm trying to improve documentation and possibly errors here.

**Comment by xenoterracide** [comment] 2023-12-27 18:41
I'm thinking, should I, would you be ok with, spawn 2 tickets from this?

1. the doc bug with using this hibernate feature
2. add a compile time error/warning if the contents of `uses` isn't used.

**Comment by filiphr** [comment] 2023-12-28 09:56
>How am I to know it's not what I need if I can't find an example of what I need verbatim

MapStruct has so many possibilities that it is impossible to have verbatim examples for all the possible permutations of what you can do with it.

>uh, in the example (in the documentation) none of that is shown at all. Also, why does it matter? shouldn't this be able to create an object without properties?

MapStruct is a framework for mapping properties between different beans. A base assumption that all examples have some properties is more than justified for this. Also the fact that it has a compile error when an object has no properties is an explicit choice by us, what is the point of a mapping method for something that has no properties to map to?

>The problem we're solving is someone creating a new date instance in every single service.

This example is exactly what I have been trying to get from you. To understand what kind of problem you are trying to solve with MapStruct. And for the example you provided there is actually a different solution in related to [Mapping customization with before-mapping and after-mapping methods](https://mapstruct.org/documentation/stable/reference/html/#customizing-mappings-with-before-and-after).

There are 2 possible approaches that you could do to achieve this

<details>
<summary>Using update methods</summary>
So let's take your examples and make some assumptions

```java
public class BaseEntity {
    private Instant dateModified;

    // other properties omitted for brevity
}

public class MyGroupEntity extends BaseEntity {
    // properties omitted for brevity
}

public class MyPersonEntity extends BaseEntity {
    // properties omitted for brevity
}
```

We are going to simplify the services to look like:

```java
@Service
class MyGroupService {

 void saveFrom( MyGroupDto dto ) {
    MyGroupEntity entity = dao.load(dto.getId());
    mapper.copy(dto, entity);
    dao.save(entity);
 }
}

@Service
class MyPersonService {

 void saveFrom( MyPersonDto dto ) {
    MyPersonEntity entity = dao.load(dto.getId());
    mapper.copy(dto, entity);
    dao.save(entity);
 }
}
```

and then for the mapping we have

```java
@Service
public class MappingUtils {

    private final ObjectFactory<Instant> nowFactory; // injected constructor excluded for brevity, this is a spring ObjectFactory

    // This after mapping will be called at the end of each mapper when the target is an instance of BaseEntity
    @AfterMapping
    public void afterEntityMapping(@MappingTarget BaseEntity entity) {
        entity.setDateModified(nowfactory.getObject());
    }
}

@Mapper(componentModel = "spring", uses = MappingUtils.class)
public PersonMapper {

    void copy(MyPersonDto dto, @MappingTarget MyPersonEntity entity);
}

@Mapper(componentModel = "spring", uses = MappingUtils.class)
public GroupMapper {

    void copy(MyGroupDto dto, @MappingTarget MyGroupEntity entity);
}
```

**Note**: We are using update methods with `@MappingTarget`. There is a difference in how the generated code looks like for an update method versus a regular method.

The generated code for one of the mappers will look like:

```java
@Component
public class GroupMapperImpl implements GroupMapper {

    @Autowired
    private MappingUtils mappingUtils;

    @Override
    public void copy(MyGroupDto dto, MyPersonEntity entity) {
        // mapping code

        mappingUtils.afterEntityMapping(entity);
    }
}
```

Keep in mind that something like `@Mapper(componentModel = "spring", uses = MappingUtils.class)` can be replaced  with `@Mapper(config = MyMappingConfig.class)` where `MyMappingConfig` looks like:

```java
@MapperConfig(componentModel = "spring", uses = MappingUtils.class)
public interface MyMappingConfig {

}
```

</details>

<details>
<summary>Using regular mapping methods</summary>

We have the same assumption for the entity from the previous example and we make the following for the dtos:

```java
class BaseDto {
    private String id;
    // other properties omitted for brevity
}

class MyPersonDto extends BaseDto {

    // properties omitted for brevity
}

class MyGroupDto extends BaseDto {

    // properties omitted for brevity
}
```

The services can then look like:

```java
@Service
class MyGroupService {

 void saveFrom( MyGroupDto dto ) {
    MyGroupEntity entity = mapper.copy(dto);
    dao.save(entity);
 }
}

@Service
class MyPersonService {

 void saveFrom( MyPersonDto dto ) {
    MyPersonEntity entity = mapper.copy(dto);
    dao.save(entity);
 }
}
```

We will need to adapt the mapping utils a bit in order to be able to lead the entity through an object factory (a MapStruct object factory)

```java
@Service
public class MappingUtils {

    private final ObjectFactory<Instant> nowFactory; // injected constructor excluded for brevity, this is a spring ObjectFactory

    // This method will be invoked by MapStruct to create an instance in which we need to map the dto into
    @org.mapstruct.ObjectFactory
    public <E extends BaseEntity> E loadEntity(BaseDto dto, @TargetType Class<E> entityClass) {
        // somehow find the dao for the right entity class

        return entityDao.load(dto.getId());
    }


    // This after mapping will be called at the end of each mapper when the target is an instance of BaseEntity
    @AfterMapping
    public void afterEntityMapping(@MappingTarget BaseEntity entity) {
        entity.setDateModified(nowfactory.getObject());
    }
}
```

The mappers will then look like:

```java
@Mapper(componentModel = "spring", uses = MappingUtils.class)
public PersonMapper {

    MyPersonEntity copy(MyPersonDto dto);
}

@Mapper(componentModel = "spring", uses = MappingUtils.class)
public GroupMapper {

    MyGroupDto copy(MyGroupDto dto);
}
```

and the generated code looks like

```java
@Component
public class GroupMapperImpl implements GroupMapper {

    @Autowired
    private MappingUtils mappingUtils;

    @Override
    public MyPersonEntity copy(MyGroupDto dto, MyPersonEntity entity) {
        if ( dto == null ) {
            return null;
        }

        MyPersonEntity entity = mappingUtils.load(dto, MyPersonEntity.class);

        // mapping code

        mappingUtils.afterEntityMapping(entity);

        return entity;
    }
}
```
</details>

---

For the questions from your last comment


> 1. the doc bug with using this hibernate feature

Yes sure we can improve the docs here a bit. We can also decouple it from hibernate as it isn't necessarily linked to hibernate.

> 2. add a compile time error/warning if the contents of `uses` isn't used.

This would be a bit difficult since it would lead to backwards incompatibility. You could be having those `uses` through `@MapperConfig` and they don't have to be used always. Also, will it really help? If one method is used then there won't be a warning / error. However, it is still possible to have wrong assumptions and you think that a method should be used, but it isn't.

**Comment by xenoterracide** [comment] 2024-01-03 18:13
backwards compatibility is overrated on a major release. sadly I'm starting to see the hard way, via java and gradle that it results in endlessly bloated software that has obviously become hard to use and improve. I'm not saying one should *always* be breaking things, and certainly I believe in semantic versioning and support cycles. At this point though with the aforementioned examples I'd like to see them break eggs and kick more code out and worry less about certain libraries. Should that happen without consideration? no, but a good example for java would be a new reflection API, and a deprecation cycle and removal of the old one from the jdk. For gradle it might be removal of groovy support, or fixing some defaults. semver is good, and I think people should make good use of it.

I will make the documentation bug.
