### ISSUE TITLE
MapStruct does not seems to like Lombok when there is nested properties

### ISSUE THREAD

**Issue by Vespira** [mapstruct/mapstruct#712] opened 2015-12-21 09:01 UTC
Hello guys,
First post here, and I'm really sorry it's a bug report for you :]

Above all, MapStruct is really easy to use and well made, so thank you.

I'm using the version 1.0.0.CR1 in a Spring Boot project. I use it to map DTO's to Pojo's & Pojo's to DTO's. The problem here is when I use Lombok to generate (with the @Data annotation) the object related methods, the MapStruct @Mapping annotation on my Mapper class does not recognize the nested properties I'm trying to map.

An example : 
Let's say I have an entity Device and User. a User can have many Devices, but a Device can belong to only 1 User. If I want to make a DTO of the Device entity where the id is passed instead of a complete User I make it this way : 

public interface DeviceMapper {
...
@Mapping(source = "fkUser.id", target = "fkUserId")
DeviceDTO deviceToDeviceDTO(Device device);

@Mapping(source = "fkUserId", target = "fkUser")
Device deviceDTOToDevice(DeviceDTO deviceDTO);

...
}

But If I lombok my Device DTO and Entity class, it will never find fkUser.id. I tried several names, several ways to reference it, but it seems that the generated getters/setters are only known for first level properties of the classes to map.

Thanks a lot for your update on this,
In a will to help,
Alex

**Comment by sjaakd** [comment] 2015-12-22 07:36
Would that somehow tie in to the other problems we have with Lombok? E.g. Have you tried to separate Lombok generation into a separate Maven project and use that project and any of the Lombok generated dto's in the Mapstruct project as dependency?

**Comment by gunnarmorling** [comment] 2015-12-22 08:01
Hi, thanks for the nice words :)

It's interesting that you see Lombok-generated properties at all. There is already #510 around issues with using Lombok and MapStruct together in part compilation. The issue is that Lombok goes beyond what's defined in the annotation processing specification (JSR 269) by modifying the types under compilation, but there is no way for other processors such as MapStruct to detect this fact and react accordingly.

So far the only reliable way to make it work is having two different modules: One contains the data structures you enhance with Lombok, the other one contains the MapStruct mappers and references the former (that way seeing the final bytecode as modified by Lombok before).

**Comment by Vespira** [comment] 2015-12-23 09:05
@gunnarmorling @sjaakd 
Thanks for your reply, I didn't tried to make a separate project yet. I just don't use Lombok when I have to Map objects. My theory on this, is : 
Lombok generate the utils methods on the entity,
MapStruct is building the implementation of the Mapper classes based on the method generated. But Lombok haven't generated the getters/setters for the tied entity (to take the same example as above : I have a Device entity bound to my Employee) but Employee methpods are not there yet !

**Comment by gunnarmorling** [comment] 2015-12-23 09:09
Yes, that's roughly what's going on. If you like, check out the discussion in #510. The basic issue is that the JSR 269 environment doesn't expect processors to *modify* the types under compilation (as Lombok is doing it), so there is no way for other processors to detect this situation and delay their own processing until a class has been fully amended by the first processor. That's why having it in two modules helps: MapStruct will then see the complete class and be able to generate the mappers based on all the getters/setters.

**Comment by Vespira** [comment] 2015-12-23 09:40
Ok thanks for the recap (and reactivity) I completly got it, :+1: 

You can close this subject if you think it's a duplicate of the #510 . As I think it's an overkill to create a module just to allow Lombok working hand-by-hand with MapStruct I just gonna skip Lombok (and therefore, prevent myself to become lazier than necessary :p)

**Comment by gunnarmorling** [comment] 2015-12-23 11:38
Yes, I'd do the same ;)

I'm going to close this one as a duplicate then; Thanks for providing this feedback nevertheless, and if you have any other feature requests or bug reports, please let us know.

**Closed by gunnarmorling** 2015-12-23 11:38 UTC
