### ISSUE TITLE
Mapping of immutable objects with Builders

### ISSUE THREAD

**Issue by michalcholewinski** [mapstruct/mapstruct#782] opened 2016-03-14 21:26 UTC
Would be very nice to have functionality to map immutable objects (without setters) which contains only Builder with methods consistent with the naming convention "withSth().withAnother()" or something like this.
Already discussed with Andreas Gudian.

**Comment by gunnarmorling** [comment] 2016-03-15 07:10
@michalcholewinski, part of this already is there: You could configure MapStruct to rocognize your "with..." methods as setters. That way you could map between the source and a builder. But you'd have to invoke build() yourself, and it wouldn't work with nested objects. So so more advanced support for builder-like patterns would be great to have. Interested in helping out?

**Comment by maposchmi** [comment] 2016-04-06 10:40
This worked for us.
Our Mappers are abstract and extend BeanZuBeanMitBuilder

[BeanZuBeanMitBuilder.java.txt](https://github.com/mapstruct/mapstruct/files/206217/BeanZuBeanMitBuilder.java.txt)
[BuilderNamingStrategy.java.txt](https://github.com/mapstruct/mapstruct/files/206218/BuilderNamingStrategy.java.txt)

**Comment by ugrave** [comment] 2016-04-15 10:28
Hi,
the [Jakson](https://github.com/FasterXML/) api has a annotation called [JsonPOJOBuilder](jackson-databind/src/main/java/com/fasterxml/jackson/databind/annotation/JsonPOJOBuilder.java). This can be used to define a builder to deserilize Jason to model object.
Mapstruct could also define such a annotation to define a builder.

```
public @interface MapstructObjectBuilder {
    Class<?> builder(); // The class of the builder
    String build() default "build"; // The name of the build method
    String prefix() default "with"; // prefix for set methods
}
```

**Comment by mvonrenteln** [comment] 2016-08-04 15:59
How is this custom NamingStrategy registered with mapstruct? I could not find anything in the documentation..

**Comment by agudian** [comment] 2016-08-04 16:37
@mvonrenteln Currently that's only possible through a ServiceLoader file in META-INF of a jar that you add to the processor classpath. There is an example below integration-tests/src/test/resources.

**Comment by mvonrenteln** [comment] 2016-08-05 12:47
Okay, thanks, I will look into it. The example in integration test worked but the adaptions seem to be a bit tricky... Java-Model-API seems to be a bit complicated. I will adapt it next iteration.

**Comment by egotsev** [comment] 2016-12-29 09:09
Is anyone working on this issue? If not, I would be interested in implementing it. Can you point me to some documentation as a starting point?

**Comment by egotsev** [comment] 2016-12-29 12:16
Okay, I can start studying the code and working on this right after NYE. Any other hints and tricky points are welcome. :slightly_smiling_face:

**Comment by hakamairi** [comment] 2017-02-22 16:42
Any updates? I would love to use this feature.

**Comment by LucasAndersson** [comment] 2017-02-28 13:47
I would also love to use this feature, it would be great if you could support at least the default builder pattern generated by Lombok as well out of the box somehow.

**Comment by rasheedamir** [comment] 2017-03-04 20:26
@agudian any hopes for this to be in place soon? It will take away lot of donkey work we have to do!

**Comment by kerdosa** [comment] 2017-03-14 12:39
Hi, which freemaker template is used to generate constructor() code? And which freemaker template is used to generate setter method?

**Comment by filiphr** [comment] 2017-03-14 19:24
@kerdosa If you mean the constructor for the object that we are mapping it is generated in the [`BeanMappingMethod`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/resources/org/mapstruct/ap/internal/model/BeanMappingMethod.ftl#L37).

As for the setter methods the [`SetterWrapper`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/SetterWrapper.ftl) and [`SetterWrapperForCollectionsAndMaps`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/SetterWrapperForCollectionsAndMaps.ftl).

Maybe if you let us know why exactly you need them, we can help you out more specifically.

**Comment by kerdosa** [comment] 2017-03-19 13:52
@filiphr That's exactly what I wanted to know. I am thinking that we can add a strategy for how to create an object, which will be Constructor or Builder, and pass this configuration to templates. Current template generates the code with Constructor. We can generate builder-based code if mapper is configured with Builder strategy.

**Comment by smartytime** [comment] 2017-06-22 06:51
This is something I've been looking into.  I have a very rough prototype working and the regression tests passing, but I'm not loving the implementation  I was thinking that you could add an annotation onto a mapping method like this:

```
@Builder(builderClass = com.some.ImmutableType.Builder, buildMethod = "build", staticBuilderMethod = "builder")
public ImmutableType toImmutableType(MutableType source);
```
which would generate something like this:

```
@Override
    public ImmutableType toImmutable(MutableType source) {
        if ( source == null ) {
            return null;
        }

        ImmutableType.Builder immutableType = ImmutableType.builder();

        immutableType.name( source.getName() );
        immutableType.age( source.getAge() );

        return immutableParent.build();
    }
```

When an immutable is a mapping source, it all works great.  When it's a target, you run into a few problems:

1.  Mapstruct wants to look for write accessors on the ImmutableType class, but in this case, it really needs to look at ImmutableType.Builder.  Because the Type definitions in mapstruct are created independently of any particular method mapping, it makes it difficult to attach the concept of "Builder" to the target class, even though that's what makes the most sense to me.  Personally, I'd probably prefer to move a @Builder annotation to the mapping target class rather than the mapping method, but  I'm not sure if that breaks any mapstruct best practices though.

Either way, to properly support Builder implementations, each Type should probably have a "mappingTargetType" property, that could store the builder class.  Then, any write-based logic could be based on the mappingTargetType instead of the "this" type. 

2.  There's not a great way to detect that methods are "setters", not without rolling a custom AccessorNamingStrategy.  And, in the case of lombok, which I'm primarily solving for, you can't modify the setter methods in the builder anyway - they are always the same name as the property.

I'd prefer that builder setter names be treated specially, and that there was some built-in support for detecting builder setters based on common conventions.  For example, any single-arg public method in the builder that has a single parameter and returns the builder type could be considered a  "setter" method.

I'm happy to work on this, but could use some guidance from the pros on how this could best be achieved.

**Comment by mvonrenteln** [comment] 2017-06-22 14:36
@smartytime Great to see you're interested in this, too!

Would be great to see your actual solution!

These two Problems can be solved seperately. For your first point I have implemented a workaround that you can find on [stackoverflow](https://stackoverflow.com/questions/38770813/mapping-an-object-to-an-immutable-object-with-builder-using-immutables-annotati). The second one I have on my long time TODO list... ;)

**Comment by smartytime** [comment] 2017-06-23 04:45
I submitted a PR to spark a discussion.  I'm confident there's a better way to handle it, but it's technically working.

https://github.com/mapstruct/mapstruct/pull/1229

**Comment by filiphr** [comment] 2017-06-24 08:04
I am replying first here without looking at the code in the PR as not to have some bias from the code 😄.

First of all, how would this work with automatic sub method generation? i.e. recursively creating mapping methods between types?

Regarding the annotation, have you thought about reusing `@BeanMapping` and adding a new field there? We could have a field `builderClass`. I am not sure if you are going to need `buildMethod` and `staticBuilderMethod`. During the processing time one can easily find the build method. 

As for the `staticBuilderMethod`, this method is on the `ImmutableType` right? How will this work for builders that are not nested classes in their types?

Regarding your problems:

1. During the creation of the `SourceMethod` there is access to all the annotations of the method, so we can get the type that we need to use to map to, i.e. to get write accessors to. There are already some annotations that can be plugged into your types like `@ObjectFactory`, `@AfterMapping`, `@BeforeMapping`, `@Named`. However, currently there are no annotations that one needs to put in their types.

1. We could provide an alternative `AccessorNamingStrategy` that is going to work for builders. Users will only have to make sure that they are using that one, this will be a non-breaking change. Alternatively, we could change the signatures of the `AccessorNamingStrategy` and send some more info, like are we in the context of builder or not. However, I am not sure how I feel about that (not because of the breaking change).

In any case for the second problem we should distinguish when we are in a context of a builder type so we can do some special logic.

**Comment by filiphr** [comment] 2017-06-24 09:58
I have seen the PR for this issue. Before going into more into depth of the review, I think that we need some answers to some more general questions. I am writing here as I think that there are more people watching this issue and we can get some feedback.

My points:

**Comment by filiphr** [comment] 2017-06-24 10:07
* Most important how do we want the API to look like? What makes more sense? Having it on the types themselves, or somehow differently? 
* Do people always have control over the types and builders code?
* Do we want to have interfaces created by builders? Should we go for a smaller experimental option and then extend it?
* Starting with 1.2.0 MapStruct will create sub-mapping methods. Which means that there won't be a need to generate explicit mappings between 2 types. Will this work with builders? It seems that it'll work with the current implementation, but it will be nice to have some tests for it as well.
* Do we expect that each builder will be within the class that it creates or there can be builders outside of this class?
* Will it make sense for MapStruct to find the `build` method in the builder automatically? This can be done by looking for an empty method that returns a type equal to the target type.
* Will it make sense for MapStruct to find the `builderStaticMethod` in the type being created or the builder automatically? This can be done by looking for an empty static method in the type being created or using an empty constructor of the builder

**Comment by smartytime** [comment] 2017-06-26 08:03
@filiphr - I just read through your comments here.  I've updated my original comment on the PR with an updated approach that I think solves for many of the issues you raised above.  Specifically, it removes any assumptions that builders will be nested, and provides support for abstracts/generics for targets and builders.  I'm trying to get a passing build to push up the latest changes.

As for the API... I respect the notion that we should not have to annotate the domain.  There are always cases where that is difficult or impossible because the domain is included as a library.  I consider the Builder class to also be part of the domain.

So, even though I went the route of annotating the domain, I think we should also support annotating the mapping method.  And, if we're going to support annotating the mapping method, maybe we just start there and remove the ability to map the domain.  It seemed more intuitive to annotate the domain when I started, because that information was more closely tied to the _implementation_, not just with the mapping, and it seemed like there could be ambiguous/conflicting annotations on methods.  But I didn't chase that thought process all the way down.  And the more I think about it, I think the method annotation may alleviate some difficulties I ran into.

For example, one thing I wrestled with was needing to know which Type any given builder produces.  The use case may not be required or desired, but it was to try to support something like the following.  I'm going to pretend to use method mapping to show how it could be problematic:

```
AbstractTarget toAbstractTarget(ConcreteSource source);

/* 
    Assume ConcreteTargetBuilder is not an inner class of ConcreteTarget.  I needed to know that 
    ConcreteTarget.Builder "builds" ConcreteTarget, which can be used to satisfy AbstractTarget.
    But, by inspecting ConcreteTargetBuilder alone I cannot make that determination.  So I ended up 
    putting annotations on the builders that point back at the concrete implementation.

    If we annotated toAbstractTarget, it would solve the issue, right?
*/
default ConcreteTargetBuilder concreteTargetFactory() {
  return ConcreteTarget.builder();
}
```
I think your suggestions about autodetecting buildMethod and builderStaticMethod are great.  I'll do some work on that shortly.  Alternatively, you should be able to provide an @ObjectFactory for the builder as well - for cases where the builder doesn't have a special static getter on the target class. 

I don't understand the question "Do we want to have interfaces created by builders" - are you asking whether a builder can return an interface (rather than a concrete type)?  If so, then hopefully the latest changes will address that.  If you meant something else, would you mind elaborating?

I need to look into submapping methods.  I don't fully understand that yet.

Also, how should we handle ```@BeforeMapping``` and ```@AfterMapping```?  I assume we should be passing the builder instance into those methods instead of the target type.  Especially if the method is void.  

Great feedback - would welcome any other suggestions or comments.

**Comment by filiphr** [comment] 2017-07-01 21:14
@smartytime first of all sorry for the time it took me to get back to you. 

>For example, one thing I wrestled with was needing to know which Type any given builder produces

If we know that a certain type is builder then we could theoretically look for methods that have no parameters, return a non-void Type and this return Type is not the Builder itself. MapStruct could assume that this type is the type that the builder builds (see my comments about using an SPI as well).

For example:

```
class Builder {

    Builder name(String name) {
        //set
        return this;
    }

    /** 
    * This method will be a candidate for the method I explained earlier.
    */
    BuildType build() {
        //Here the initializing is created
    }
}
```
It is not that complex to find such methods during compilation time.

I would say that for `@ObjectFactory`  it should work out of the box like it works now. Once we know that for a certain `Type` we need to use some Builder than all the actions that MapStruct does know will be done with this Builder Type instead of the `Type`.

>are you asking whether a builder can return an interface (rather than a concrete type)? If so, then hopefully the latest changes will address that. If you meant something else, would you mind elaborating?

Yes that is what I meant. The builder will have some interface as a return type. I think that with your latest comments in the PR (that it works for abstract classes) this should be resolved.

>I need to look into submapping methods. I don't fully understand that yet.

Let me know if you have some problems with this one. It is quite new and will be part of the `1.2.0.Final` release. In a nutshell MapStruct will automatically try to generate intermediary methods between different types. The approach with annotating the domain works perfectly for this as we have all the information there. However, until now we have tried to avoid needing to annotate it, as it is not always under your control.

>Also, how should we handle @BeforeMapping and @AfterMapping? I assume we should be passing the builder instance into those methods instead of the target type. Especially if the method is void.

I would say yes, we would pass the builder instead of the target type (actually there won't be any target type until we do return). This is similar as the `@ObjectFactory`. I also think nothing will need to be changed here as we would be passing the Builder Type to all the discovery methods instead of the target type. 

An alternative way to discover the builders (instead of annotating the domain) would be to use a Service Provider Interface (SPI). Within this SPI MapStruct can pass the Type that it wants to create and will ask for a Builder Type, and we would use that further down. With this one would not pass the builders in the mapping methods.

It could be something like:

```
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;

public interface BuilderProvider {
    TypeMirror findBuilder(TypeMirror typeMirror, Elements elements, Types types);
}
```

With an SPI users can manually map types to builders, or even have an automatic way of discovering them. Theoretically it would be possible to reuse the Lombok, AutoValue annotations as well. We can even create SPIs for each of those projects in our examples repository and users will be able to use them, maybe even provide them as separate modules if people are interested.

I'll also address your edited message in the PR there.

Btw. We would not include this in the next 1.2.0 release, but schedule it for the 1.3.0. I hope that this would be OK for you. We are almost ready with 1.2.0 and we are planning to have a CR1 really soon. For us would be completely OK to do a 1.3.0 release only with this feature (in order to have it out faster). Thanks for the understanding

**Comment by smartytime** [comment] 2017-09-10 21:20
@filiphr - I'm picking this back up - would like to see if we can get it wrapped up...

The latest changes to the PR removed all class annotations and simply use `@BeanMapping(builderType = Bean.Builder.class)` - feels much more aligned.

As you mentioned, this doesn't solve intermediate mappings, so I'm going to take a stab at the SPI example from your last comment for builder discovery.  And I really like the idea of using introspection to discover build/builder/accessors.  

Please let me know if anything has changed from your end.  I know it's been a while.

**Comment by filiphr** [comment] 2017-09-12 18:32
@smartytime great that you want to pick it back up. On our side nothing has changed. I think that this is an awesome feature. It will certainly make things easier for users using Builders and MapStruct.

By the way, you won't be using introspection, but the java annotation processor packages. This is much more powerful than introspection, because you are seeing what the compiler sees. With Introspection you have less information because it is during runtime 😄 .

If you need anything, just let us know. We are more than happy to help you out with this feature.

Btw, you might wanna rebase everything on master (if you didn't do already), as there might be some other changes that you might use.

**Comment by smartytime** [comment] 2017-09-14 00:55
Thanks for the reply.  You'll notice I closed the other PR.  I'm going to start fresh because now that II've read over your comments a number of times I think I'm starting to understand what you've been telling me.  This is what I'm thinking:

I'm going to start over, taking the SPI approach.  I can see now how it will be much less intrusive.  I'm sure I'll have a bunch of questions.

**Comment by filiphr** [comment] 2017-09-14 19:00
No problem @smartytime thanks for tackling this. It is really an interesting approach. I think that we can have a nice non-intrusive clean solution. 

Looking forward to your next PR. If you have any questions feel free to ping me on our [gitter](https://gitter.im/mapstruct/mapstruct-users) chat. I am mostly available in the evenings or during the weekends.

**Comment by LucasAndersson** [comment] 2017-09-15 09:02
This issue is the only thing keeping me (and I'm sure many others) from using MapStruct. Great to hear it's being worked on @smartytime

**Comment by kiamesdavies** [comment] 2017-09-20 16:08
This is great. Waiting .......

**Comment by leimer** [comment] 2017-11-16 12:28
At my work we would love to use MapStruct. But we heavily use Lombok and its Builder annotation. So we have many immutable types with builders. This issue is now open for 1,5 years. I think it's time to get this working.

I read the conversation and currently trying to figure out the terminology and technologies used at MapStruct. @smartytime @filiphr do you currently put some effort in this issues? I so, can I help you to finish a working implementation? If not, I would love to take all the discussion in account and try to create a PR for this.

**Comment by filiphr** [comment] 2017-11-16 22:13
@leimer there is already #1296 PR opened for this. However, I am not sure what is the status for @smartytime in it.

If you are interested have a look at the discussion in there as well.

We would definitely want to have this for our next 1.3 release (which we hope it would be soon). If you are willing to help us out we would very much appreciate the help. We can of course help you out in the process as well.

Just as info, we want to have something that would not be overly dependant on the different implementations of the builders. Ideally MapStruct shouldn't need to know about Lombok, AutoValue and all the other flavors.

**Comment by atomcat1978** [comment] 2017-11-29 13:38
Actually, I think, that the current version of MapStruct can be used together quite well with immutables. It is a question of mapping architecture. I'm soon going to write a blog entry about the approach we use in our current project.

**Comment by michaeljeanh** [comment] 2017-12-08 21:38
+1
This feature is what's keeping me from using MapStruct. Any ETA?

**Comment by atomcat1978** [comment] 2017-12-11 17:08
It seems like it takes a while to get the post out on our company website, so here is the basic idea:

Suppose that we have a SoapUser object that should be mapped to a User domain object (the domain object is immutable). It is possible to set up the mapper as an abstract class in Mapstruct, so we can create the following mapping definition:

```

@Mapper
public abstract class UserMapper {

	abstract User.Builder soapUserToUserBuilder(SoapUser soapUser);

	public User soapUserToUser(SoapUser soapUser) {
		User.Builder builder = soapUserToUserBuilder(soapUser);
		return builder != null ?
				builder.setType(getUserType(soapUser))
				.build() :
				null;
	}

	private UserType getUserType(SoapUser soapUser) {
                // implementation.... Not important
	}
}
```

The essence is, that the ```soapUserToUserBuilder ``` is created by MapStruct, and is hidden from the world outside. It returns our configured builder. In the method ```soapUserToUser``` we just call the method, adjust on the builder if required, call ```build()```, and return the created immutable object.

This way the codebase won't be full of ```.build()``` garbage, and I think, it is a pretty transparent solution.

One might combine it with immutables to save on required number of code lines when it comes to creating immutable classes.

**Comment by atomcat1978** [comment] 2017-12-11 17:10
Ok, I just saw, that @maposchmi  basically did the same thing :)

**Comment by michaeljeanh** [comment] 2017-12-11 22:17
@atomcat1978 Good work around, but still won't work with Lombok's '@Builder' or any Builder class that has its default no-args constructor private (which is the way it should).

**Comment by atomcat1978** [comment] 2017-12-12 08:56
@michaeljeanh I agree. Actually, it is sad that going immutable in Java is a pretty hard thing. At the end of the journey I’ve ended up with Kotlin at my current customer:) Actually, it would be nice to have a MapStruct port to Kotlin:)

**Comment by filiphr** [comment] 2017-12-17 02:06
We will definitely have this for 1.3.0, I am now trying to use the open PR to enhance it and provide a support for the builder pattern and different builder creators such as Lombok, Protobuf, AutoValue, Immutables, FreeBuilder.

I've been making an analysis of all of those libraries so we can have support out of the box for all of them without the need for MapStruct to know about them. 

From my analysis there are 2 approaches that this libraries use:

* A public static method on the actual type (Lombok, AutoValue and FreeBuilder with `Person.builder()` and Protobuf with `Person.newBuilder()`). Lombok and Protobuf create those methods automatically, whereas for AutoValue and FreeBuilder one needs creates the method in the abstract class by itself
*  A public static method on the implementing class. This is the case only for Immutables. The method is found in the `ImmutablePerson`, the class created by Immutables.

Our current way of thinking is the following.

* As proposed by @gunnarmorling in https://github.com/mapstruct/mapstruct/pull/1296#issuecomment-351532625, there will be a new annotation that can be applied on a `MapperConfig`, `Mapper` or a mapping method

```java
@interface BuilderConfig {
    String builderCreationMethod() default "<CLASS_NAME>#builder";
    String buildMethod() default "build";
}
```

I think that we need to make the `@BuilderConfig` a meta annotation, so users can define their own custom annotations and use them.

MapStruct will have an SPI:

```java
public interface BuilderProvider {

    // config can be null, which means that the user has not defined @BuilderConfig at all
    BuilderInfo getBuilderInfo(TypeMirror type, BuilderConfig config, Elements elements, Types types);
}

public class BuilderInfo {

    private ExecutableElement builderCreationMethod;
    private ExecutableElement buildMethod;
}
```


In the default implementation there would be 2 possible options (pseudo code):

```java
public class DefaultBuilderProvider implements BuilderProvider {

    @Override
    public BuilderInfo getBuilderInfo(TypeMirror type, BuilderConfig config, Elements elements, Types types) {
        TypeElement element = getTypeElement(type, elements, types);
        if (config == null) {
            return getBuilderInfo(element, elements, types);
        } else {
            return getBuilderInfo(element, config, elements, types);
        }
    }
  
    protected BuilderInfo getBuilderInfo(TypeElement typeElement, Elements elements, Types types) {
        List<ExecutableElement> methods = ElementFilter.methodsIn( typeElement.getEnclosedElements() );

        for (ExecutableElement method: methods) {
            if (isPossibleBuildCreationMethod(method)) {
                TypeElement returnElement = getTypeElement(method.getReturnType());
                List<ExecutableElement> builderMethods = ElementFilter.methodsIn( typeElement.getEnclosedElements() );
                // if the builderMethods contain a public static method with no arguments that returns
                // the typeElement then we have a hit and we return new BuilderInfo(method, buildMethod)
            }
        }
        return null;
    }

    protected BuilderInfo getBuilderInfo(TypeElement typeElement, BuilderConfig config, Elements elements, Types types) {
        String builderCreationMethod = config.builderCreationMethod();
        builderCreationMethod = builderCreationMethod.replace("<CLASS_NAME>", typeElement.getQualifiedName());

        String[] parts = builderCreationMethod.split("#");
        TypeElement builderCreationElement = typeElement;
        if (parts.length < 1) {
            return null;
        }
        else if (parts.length == 2) {
           builderCreationElement = elements.getTypeElement(parts[0]);
        }

        ExecutableElement builderCreationMethod = findMethod(builderCreationElement, parts[1]);
        ExecutableElement buildMethod = findMethod(builderCreationElement, config.buildMethod());
        return new BuilderInfo(builderCreationMethod, buildMethod);
    }
}
```

I think that with this approach we are going to be able to create builders for all frameworks except Immutables out of the box. Additionally we would be able to have a support for handwritten builders as well (provided they follow the builder pattern and provide a public static method with no arguments).

Adding support for Immutables would require users to define their own config via `@BuilderConfig(builderCreationMethod = "Immutable<CLASS_NAME>#builder")`.


NB: I've been doing some testing and I think that there would be some issues with Lombok as the builder method is not there during the compilation phase. So I suppose that they would need to do something similar like what they did for the getters and setters

**Comment by agudian** [comment] 2017-12-17 16:27
Looks good, Filip!

Perhaps we should also define the syntax for representing a constructor for the builder in the annotation, e.g. ˋ<CLASS_NAME>.Builder#<init>ˋ (or what was the toString name of the constructors?).

**Comment by sjaakd** [comment] 2017-12-17 18:20
@filiphr Nice analysis.

2 remarks: why do we need a new annotation..? 
1. Can't we add it to the `@BeanMapping` and `@Mapper` itself (hierarchy mechanism) since I think it only applies to bean mappings, not to value mappings, lists and maps).
2. I think all libraries are more or less based on an annotation processor. So ordering is not only an issue for Lombok, right?

**Comment by filiphr** [comment] 2017-12-17 22:10
@agudian 
>Perhaps we should also define the syntax for representing a constructor for the builder in the annotation, e.g. ˋ<CLASS_NAME>.Builder#ˋ (or what was the toString name of the constructors?).

For constructors I think using ˋ<CLASS_NAME>.Builder#<init>ˋ for a constructor `ExecutableElement#getSimpleName` returns `<init>`. Which means that if there must be something after `#` always.

@sjaakd 

>1. Can't we add it to the `@BeanMapping` and `@Mapper` itself (hierarchy mechanism) since I think it only applies to bean mappings, not to value mappings, lists and maps).

We can add a property to `@BeanMapping` and `@Mapper`. However, I think having it's own type / method level meta annotation is more suitable for this. We need to take into consideration that this would be applied to the nested auto mappings as well, not just the single bean mapping.

>2. I think all libraries are more or less based on an annotation processor. So ordering is not only an issue for Lombok, right?

Not really, as we are playing nicely with other annotation processors, and in all cases (except Immutables) the builder creation method is in the user defined type. In order to make this work for Immutables, maybe we should allow throwing the `TypeHierarchyErroneousException` from the SPI, or add some other exception or something other possibility so we can postpone the processing to the next round. A user implemented SPI can check for the Immutables annotation and can deterministically know if the class is there or not. For the Lombok case see https://github.com/rzwitserloot/lombok/issues/1538.

**Comment by sjaakd** [comment] 2017-12-19 07:50
@filiphr i'm not sure if I want to go for separate annotations. The principle has been to put everything in single annotations that you can stick to a certain method. If we decide to change this, we should do it on other spots as well. For instance: split @Mapping into @Mapping, @Expression, @Constant. This becomes possible when we go for java 8.

**Comment by gunnarmorling** [comment] 2017-12-19 11:22
I kinda see where @sjaakd is coming from, but I also see the aspect that the separate annotation nicely groups the builder-related properties together. How about having a separate annotation but using it in a nested way:

    @BeanMapping(builder=@BuilderConfig(method="build"))

?

On the suggested `BuilderProvider`,  I'm not sure whether the usage of `@BuilderConfig` should actually be part of the signature, so far I had considered the usage of this annotation just as an implementation detail of the default implementation of the SPI, but other implementations could use a different mechanism. Although this point gets a bit mood when shifting the annotation into `@BeanMapping` as suggested above.

**Comment by sjaakd** [comment] 2017-12-19 19:32
@gunnarmorling , @filiphr . .I'm not against introducing a new `@BuilderConfig`. But perhaps in 2.0 we should reconsider our annotation approach in general. With the `@Repeatable` and skipping  java 6 & 7 we have new options availabe. So we could for instance 
1. skip the `@MapMapping` and `@IterableMapping` because the method itself already tells wich method is applicable. 
2. At the other hand we could introduce `@Expression`, `@Constant` and split the `@Mapping`
3. Provide a script to migrate (e.g. like assertj did as well).

I you see it like that, introducing an `@BuilderConfig` is a step-up to that new approach. However. We should be consistent.

**Comment by filiphr** [comment] 2017-12-30 11:14
@gunnarmorling regarding passing the `@BuilderConfig` in the SPI, I was more thinking of that part there to be something else and not the annotation itself (Didn't think of a good name :smile:). Something that would contain the information from the `@BuilderConfig`, if there is one. If we do that then users would be able to provide custom logic if there is no `@BuilderConfig` defined, and they can even enhance the `@BuilderConfig` as they see fit. Maybe the passed class in the SPI can be `BuilderConfigInfo`

The reason why I was going for a separate annotation is due to the fact that this would allow users to mix different builder strategies (for example something coming from a 3rd party library). That way, they can define a builder configuration just for a single method, and use the default for the rest. If it is meta annotation, they can even define something like `@SomeLibraryBuilderConfig` and use it around.

@sjaakd I am more for `@BuilderConfig` as it is a configuration how a builder looks like (either on method or mapper level). `@Builder` is more for creating a builder like Lombok does and the other frameworks. As for `@UseBuilder` it looks more like saying that we should use a builder. However, in my opinion we should decide if we should use a Builder when the SPI returns the information. Otherwise, automatic nested methods won't work with immutable types with builders

**Comment by milanov** [comment] 2018-03-29 15:32
Hi there, hoping this will get resolved soon, as it will make a lot of manual builders that we've had to manually write unneeded..

**Comment by filiphr** [comment] 2018-03-31 13:24
@milanov the support will land on our master really soon :)

**Closed** 2018-04-04 17:26 UTC
Labels: feature

**Comment by filiphr** [comment] 2018-04-04 17:31
I am happy to announce that the builder support is finally on master. We are going to do a 1.3.0 Beta release so you can all try it out. Thanks a lot for all the support and the patience with us.

**Comment by ramses-gomez** [comment] 2018-05-09 10:52
Hello when is the 1.3.0 beta being released?

**Comment by filiphr** [comment] 2018-07-09 18:58
@ramses-gomez I hope we would be able to release by the end of this week 😄. Thanks a lot for the patience with us.

@joedj sorry for the misunderstanding. Maybe we need to change that hint. Yes Mappers and Lombok classes need to be in separate compilation units. In this case those are the sources and test-sources compilations. However, for real world use cases you would probably need to have a module with the lombok classes and another module with the MapStruct mappers (that is until https://github.com/rzwitserloot/lombok/issues/1538 is not resolved)

**Comment by gaweL-** [comment] 2018-08-27 07:17
Hi, 

Thanks for this feature, helping a lot :) 

The `ImmutablesBuildProvider` currently assumes Immutables genereted classes are available under the "Immutable*" pattern (ImmutablesBuildProvider:84). Is it possible for you to support the `org.immutables.value.Style#typeImmutable` annotation/method ?

**Comment by filiphr** [comment] 2018-09-14 18:58
@gaweL- I don't see why something like this won't be possible. Can you please create a new issue for this?
