### ISSUE TITLE
Different Builders compilation result in IDEA and gradle 

### ISSUE THREAD

**Issue by Guchman** [mapstruct/mapstruct#1852] opened 2019-07-30 08:38 UTC
I have class
```
@Getter
@EqualsAndHashCode
@ToString
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Account {
    @NotEmpty
    private String id;
    private LocalDate dateOpened;
    private LocalDate dateClosed;
}

@Mapper(componentModel = "spring",
        nullValueCheckStrategy = ALWAYS)
@NoArgsConstructor
public abstract class AccountDataConverter {

    @Mapping(target = "dateOpened", dateFormat = "yyyy-MM-dd")
    @Mapping(target = "dateClosed", dateFormat = "yyyy-MM-dd")
    public abstract Account convert(AccountData accountData);
}

@Data
public class AccountData {
    @Id
    private String id;
    private String dateOpened;
    private String dateClosed;
}
```
When I run build with gradle 5.4.1-5.5.1 it's fails with:
Property "dateClosed" has no write accessor
Property "dateOpened" has no write accessor

But when I run buidl through IDEA converter compiles well:
```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2019-07-30T11:32:12+0300",
    comments = "version: 1.3.0.Final, compiler: javac, environment: Java 12.0.1 (AdoptOpenJDK)"
)
@Component
public class AccountDataConverterImpl extends AccountDataConverter {

    @Override
    public Account convert(AccountData accountData) {
        if ( accountData == null ) {
            return null;
        }
        AccountBuilder account = Account.builder();
        if ( accountData.getId() != null ) {
            account.id( accountData.getId() );
        }       
        if ( accountData.getDateOpened() != null ) {
            account.dateOpened( LocalDate.parse( accountData.getDateOpened(), DateTimeFormatter.ofPattern( "yyyy-MM-dd" ) ) );
        }
        if ( accountData.getDateClosed() != null ) {
            account.dateClosed( LocalDate.parse( accountData.getDateClosed(), DateTimeFormatter.ofPattern( "yyyy-MM-dd" ) ) );
        }

```

Mapstruct 1.3.0.Final
lombok 1.18.8
gradle 5.4.1-5.5.1

Update 1:
Also @Setters on the fields fixes build, but compilation result is same as in the gradle case without @Setters. Weird

**Comment by filiphr** [comment] 2019-07-31 13:24
@Guchman I think that this is the same as #1581 and is caused by https://github.com/rzwitserloot/lombok/issues/1538.

**Comment by filiphr** [comment] 2019-08-18 14:27
Closing it in favour of #1581. If it is different then we can reopen it.

**Closed by filiphr** 2019-08-18 14:27 UTC

**Comment by Krzysztof-Lempicki** [comment] 2019-09-08 21:57
Hi, 
To run mapstruct with lombok according to:
[working example from above](https://github.com/SimSonic/lombok-mapstruct-builders-example/blob/master/pom.xml)
most important change that I made was to downgrade java version to **1.8**. It not work with ### 1.10.
