### ISSUE TITLE
Allow usage of custom @Generated annotation 

### ISSUE THREAD

**Issue by jamfor352** [mapstruct/mapstruct#3083] opened 2022-11-17 17:01 UTC
### Use case

Currently, my team uses Jacoco reports to get code coverage. This works well, however we get coverage reports for Mapstruct-created mappers - while there may be a use case for this, we have explicit designs where some of the routes will never be invoked (for example, mapstruct doing null checks where our code can never trigger those).
This leads to us having to implement unit tests which just test the MapStruct mapper, which is a waste of time and testing a third party library is almost certainly an anti-pattern.

It would be good if we could define which `@Generated` interface to use - either a custom one we provide or default to `javax.annotation.processing.Generated` - the reason for this is that the default one provides a Retention level of SOURCE which doesn't work with Jacoco or any other bytecode checkers.

### Possible workarounds

None

**Comment by Zegveld** [comment] 2022-11-17 17:47
This request seems to be the same as #1528.

With the upcoming 1.6.0 release the `@AnnotateWith` annotation is introduced.
This allows you to add your own annotations at either class or method level to the generated code.
see #1574 for more information.

Closing this as a duplicate of #1528

**Closed by Zegveld** 2022-11-17 17:47 UTC

**Comment by jamfor352** [comment] 2022-11-17 18:04
@Zegveld Does this allow you to _replace_ the current default `@Generated` tag as well?

**Comment by Zegveld** [comment] 2022-11-17 18:27
It does not allow you to replace the default `@Generated` but it will allow you to add a secondary `@Generated` annotation.

For example:
```
@Mapper
@AnnotateWith( com.example.Generated.class )
interface MyMapper {
...
```
could turn into:
```
import javax.annotation.processing.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2022-11-17T15:57:41+0200",
    comments = "version: 1.6.0, compiler: javac, environment: Java 17.0.4 (Azul Systems, Inc.)"
)
@com.example.Generated
public class MyMapperImpl implements MyMapper {
...
```

**Comment by jamfor352** [comment] 2022-11-17 18:32
OK, cool - hopefully this is a solution which works with the  code Jacoco uses (I would presume so, the fully qualified package name being in front shouldn't cause any issues as per my understanding)
