### ISSUE TITLE
Qualified methods are used by all signature matching mappings

### ISSUE THREAD

**Issue by dermoritz** [mapstruct/mapstruct#1070] opened 2017-02-07 09:28 UTC
I just tried the `@Named` annotation to mark methods to be used by specific mappings (marked with `qualifiedByName`). The Problem is those methods are used by all mapping that match the signature.

As usual i placed the mappings and methods in the same abstract class:

```
    // @formatter:off
    @Mappings({
            ...
            @Mapping(source = "id" , target = "formId"),
            @Mapping(source = "terminterestrate" , target = "fixedInterestRateYears", qualifiedByName = FIXED_INTEREST_RATE)

    })
    // @formatter:on 
    abstract OutType mapRequestToDomain(InType request);


    @Named(FIXED_INTEREST_RATE)
    public Integer fixedInterestRate(String string){
        Integer i = null; 
        try{
            i=new Scanner(string).useDelimiter("\\D").nextInt();
        }catch (Exception e){
            LOGGER.warn("Could not parse \"" + string + "\" to an Integer.");
        }
        return i;
    }
```
The problem is that the method `fixedInterestRate` is used by all mapping that need string->integer conversion. I think this is a bug?!

I also tried to out source the named methods in a separate class - with no success.
And meanwhile i tried the old way using custom annotations -> same problem.
So for me the documentation "A class / method annotated with a qualifier will not qualify anymore for mappings that do not have the qualifiedBy element." is wrong?!

So how to create mapping methods exclusively used by marked mappings.

**Comment by sjaakd** [comment] 2017-02-07 19:07
Are you sure you are importing the `@Named` from mapstruct iso another package? (Believe me, been there, done that :) ).

Have you tried:
```java
@Qualifier
@Target( ElementType.METHOD )
@Retention( RetentionPolicy.CLASS )
public @interface FixedInterestRates {
}
```
?

**Comment by sjaakd** [comment] 2017-02-08 22:08
I tried to reproduce the problem. For that purpose I added `testIn` to the `InType` and `testOut` to the `outType`. Both the same types as the `@Named` method has as return / source parameter signature.

To be complete:

```java
public class InType {

    private String id;
    private String terminterestrate;
    private String testIn;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTerminterestrate() {
        return terminterestrate;
    }

    public void setTerminterestrate(String terminterestrate) {
        this.terminterestrate = terminterestrate;
    }

    public String getTestIn() {
        return testIn;
    }

    public void setTestIn(String testIn) {
        this.testIn = testIn;
    }

}
```

```java
public class OutType {

    private String formId;
    private Integer fixedInterestRateYears;
    private Integer testOut;

    public String getFormId() {
        return formId;
    }

    public void setFormId(String formId) {
        this.formId = formId;
    }

    public Integer getFixedInterestRateYears() {
        return fixedInterestRateYears;
    }

    public void setFixedInterestRateYears(Integer fixedInterestRateYears) {
        this.fixedInterestRateYears = fixedInterestRateYears;
    }

    public Integer getTestOut() {
        return testOut;
    }

    public void setTestOut(Integer testOut) {
        this.testOut = testOut;
    }

}
```

```java
@Mapper
public abstract class TypeMapper {

    public static final String FIXED_INTEREST_RATE = "FIXED_INTEREST_RATE";

    public static final TypeMapper INSTANCE = Mappers.getMapper( TypeMapper.class );

    @Mappings({
        @Mapping(source = "testIn", target = "testOut"),
        @Mapping(source = "id", target = "formId"),
        @Mapping(source = "terminterestrate", target = "fixedInterestRateYears", qualifiedByName = FIXED_INTEREST_RATE)

    })
    // @formatter:on
    abstract OutType mapRequestToDomain(InType request);

    @Named(FIXED_INTEREST_RATE)
    public Integer fixedInterestRate(String string) {
        Integer i = null;
        try {
            i = new Scanner( string ).useDelimiter( "\\D" ).nextInt();
        }
        catch( Exception e ) {
            e.printStackTrace();
        }
        return i;
    }
}

```

And now the generated result. As you can see the method annotated with `@Named` is not qualifying for `testIn` to `testOut`. MapStruct generates a type conversion for that (lacking a non qualified mapping method). If you would have given a method without the `@Named` it would have selected that one for `testIn` to `testOut`.

It behaves as you (and I expect). WDYT?

```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2017-02-08T23:00:32+0100",
    comments = "version: , compiler: javac, environment: Java 1.8.0_45 (Oracle Corporation)"
)
public class TypeMapperImpl extends TypeMapper {

    @Override
    OutType mapRequestToDomain(InType request) {
        if ( request == null ) {
            return null;
        }

        OutType outType = new OutType();

        outType.setFormId( request.getId() );
        if ( request.getTestIn() != null ) {
            outType.setTestOut( Integer.parseInt( request.getTestIn() ) );
        }
        outType.setFixedInterestRateYears( fixedInterestRate( request.getTerminterestrate() ) );

        return outType;
    }
}
```

**Comment by sjaakd** [comment] 2017-02-12 07:56
@dermoritz any news? I want to go ahead on this one (close it if there's no issue, solve it if there is). Can you give some feedback..? Without feedback, I'll proceed to close later this week, since I can't reproduce it.

**Comment by dermoritz** [comment] 2017-02-13 09:35
The main Problem was indeed that in imported the javax.inject.Named! 
But i don't know why my self created annotations also failed to work. 
i combined all ways from manual: i had some methods annotated with wrong named, a separate class with embedded annotations but in all cases the methods were used always if only the signature matched.

So probably an explicit hint that jsr annotation are not supported would be fine.

Thanks again for your effort and the fast suport.

**Comment by sjaakd** [comment] 2017-02-13 09:48
@dermoritz  There's an issue on improving error messages ( #767 ) . I think we should take that one up soon. You can add a comment there if you like.

A common problem with the `@Qualifier` self-made annotations are wrong retention ( if you stick an annotation to a method, it should have `ElmentType.METHOD` and the fact that you don't have it available in a compiler (`RetentionPolicy.SOURCE iso CLASS`). E.g.:

```java
@Qualifier
@Target( ElementType.METHOD )
@Retention( RetentionPolicy.CLASS )
public @interface FixedInterestRates {
}
```

Hope it helps.

**Comment by sjaakd** [comment] 2017-02-13 09:49
> So probably an explicit hint that jsr annotation are not supported would be fine.

I remember its somewhere in the Javadoc.. Anyway.. Made the mistake myself.



> Thanks again for your effort and the fast suport.

No problem. Hope it helped.

**Closed by sjaakd** 2017-02-13 09:49 UTC
