### ISSUE TITLE
Problem with mapping inherited JAXB beans

### ISSUE THREAD

**Issue by jlzi** [mapstruct/mapstruct#803] opened 2016-04-17 10:03 UTC
I have two JAXB beans and two ObjectFactory, one for each JAXB bean. One JAXB bean extends another one.
I want to map these JAXB beans to two separate Java beans, one of which extends another one.
I have created two mappers for this purpose, one for each JAXB bean. Mapper for child class "uses" mapper for parent class.

As a result during the generation of the implementations of the mappers, I receive the unexpected error: "error: Can't map property "java.util.Date credteffet" to "javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> credteffet".".
Looks like the mapper for the child class does not "understand" that it should delegate some part of mapping to the mapper for the parent class.

I'm attaching the project which illustrates the issue. To try to generate the implementations and reproduce the error just run "gradle genMap" command.
[mapstruct-inheritance-issue.zip](https://github.com/mapstruct/mapstruct/files/222591/mapstruct-inheritance-issue.zip)

**Comment by PierrickPuimeanChieze** [comment] 2016-04-18 09:15
I have exactly the same problem, but I have only one mapper, for the child classe. But even like this, MapStruct doesn't seem to find the parent class properties.

**Comment by agudian** [comment] 2016-04-18 18:35
> Looks like the mapper for the child class does not "understand" that it should delegate some part of mapping to the mapper for the parent class.

That's not how it is supposed to happen anyway. At least we didn't implement it that way. The mapping method of the child type would include all the setter-invocations, including those for the properties of the super type. The mapper of the super type wouldn't be invoked. Plus, "used" mappers or facotries of one mapper are not propagated to mappers that reference this mapper in their `uses` section. So the `ObjectFactory` of the `EventVO` type is not available to the mapper for the `DealEventVO`. Add it there as well and it should be fine. Take a look into the generated source to see what actually happens there.

**Comment by agudian** [comment] 2016-04-18 18:38
So this actually works:
```java
@Mapper(uses = { ObjectFactory.class, com.cassiopae.front.event.schema.ObjectFactory.class })
public interface DealEventMapper {

    DealEventVO map(DealEvent event);

    DealEvent map(DealEventVO event);
}
```

**Comment by agudian** [comment] 2016-04-18 18:42
> I have exactly the same problem, but I have only one mapper, for the child classe. But even like this, MapStruct doesn't seem to find the parent class properties.

@PierrickPuimeanChieze Guessing that you are using JAXB as well, adding the proper `ObjectFactories` should do the trick for you as well. If not, please open another issue with some more information.

I'm closing this issue as "not a bug". Thanks for the report, though! :+1: 

If you feel like there's something missing in the documentation about it, we gladly take pull-requests for those as well... :smiley:

**Closed by agudian** 2016-04-18 18:42 UTC
Labels: not a bug

**Comment by mnreddy7** [comment] 2018-03-30 09:43
I'm facing a different issue but related to mapping jaxb fields. Can you check the following [https://stackoverflow.com/questions/49570864/how-to-map-jaxb-elements-annotated-with-xmlseealso-using-mapstruct](url)
