### ISSUE TITLE
Inheritance Issue with MapStruct Mapper - Child Class Not Using Parent Class's "uses" Mapper or feature ? 

### ISSUE THREAD

**Issue by ZeroToHero-StepByStep** [mapstruct/mapstruct#3489] opened 2023-12-28 01:36 UTC
### Expected behavior

**Description**
In a MapStruct-based Java application, a child mapper interface (GetJobListMapper) extends a parent mapper interface (DTO_JobMapper), which specifies a custom mapper in its uses clause (DTO_JobCategoryMapper.class). However, during compilation, MapStruct fails to recognize the custom mapper defined in the parent interface, resulting in a qualifier error.

### Actual behavior

Compilation fails with the following error:

`error: Qualifier error. No method found annotated with @Named#value: [ toDtoJobCategory ]. Occurred at 'DTO_Job toDTO(DM_Job job)' in 'DTO_JobMapper'.`

**Expected Behavior**
The child mapper interface GetJobListMapper should inherit the uses clause from the parent DTO_JobMapper, allowing it to utilize the custom mapper (DTO_JobCategoryMapper) defined in the parent interface for the jobCategory field.

### Steps to reproduce the problem

**Github**
https://github.com/ZeroToHero-StepByStep/MapStructMapping

**Code**

```
@Mapper(componentModel = "spring", uses = {DTO_JobCategoryMapper.class})

public interface DTO_JobMapper {

    @Mapping(source = "createdTime", target = "createdTime", qualifiedByName = "formatCreatedTime")
    @Mapping(source = "jobCategory", target = "jobCategory", qualifiedByName = "toDtoJobCategory")
    DTO_Job toDTO(DM_Job job);

    @Named("formatCreatedTime")
    default String formatCreatedTime(LocalDateTime createdTime) {
        // Your formatting logic...
        return "Formatted Time"; // Simplified for example
    }
}

@Mapper(componentModel = "spring")
public interface DTO_JobCategoryMapper {

    @Named("toDtoJobCategory")
    default DTO_JobCategory toDTO(DM_JobCategory category) {
        // Your conversion logic...
        return DTO_JobCategory.EXAMPLE; // Simplified for example
    }
}


@Mapper(componentModel = "spring")
public interface GetJobListMapper extends DTO_JobMapper {
    // Other methods...
}

@Data
public class DTO_Job {
    private String createdTime;
    private DTO_JobCategory jobCategory;
}

public enum DTO_JobCategory {
    EXAMPLE("Example");
    private final String displayName;
    DTO_JobCategory(String displayName) {
        this.displayName = displayName;
    }
}

@Data
@AllArgsConstructor
public class DM_Job {
    private LocalDateTime createdTime;
    private DM_JobCategory jobCategory;

}

@Data
@AllArgsConstructor
public class DM_Job {
    private LocalDateTime createdTime;
    private DM_JobCategory jobCategory;

}


```

**gradle settings:** 

```
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.1'
    id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
}

tasks.named('test') {
    useJUnitPlatform()
}

```
Create a parent mapper interface DTO_JobMapper with @Mapper(componentModel = "spring", uses = {DTO_JobCategoryMapper.class}). This interface includes a mapping method toDTO that maps DM_Job to DTO_Job and uses a custom mapping method for the jobCategory field.
Define a child mapper interface GetJobListMapper that extends DTO_JobMapper.
Attempt to compile the project.

![image](https://github.com/mapstruct/mapstruct/assets/24948392/8d8f6bbb-6f06-4514-8597-4657a97d5567)

**Thoughts**

 I can understand the "uses" is like a composition for a class. But the thing is `DTO_JobMapper` does know the `toDtoJobCategory` in this scope /class(but could not find, which is confusing), just the child do not know where it is when extending it. 
 
 If we delete/comment out the `GetJobListMapper` , everything is built up fine. 
 Maybe an idea is when using "uses" keyword, having the visibility option to let it be used by child classes or not (if this is current intended behaviour)? 
 
 **Workaround**
 
 In order to get this working, they are two alternatives I found.
 
 1. Add `uses = {DTO_JobCategoryMapper.class}` into `GetJobListMapper` declaration. 
 
 ```
 @Mapper(componentModel = "spring", uses = {DTO_JobCategoryMapper.class})
public interface GetJobListMapper extends DTO_JobMapper {
    // Other methods...
}
```

which seems redundant (not expected) as it has been aded to the `DTO_JobMapper`. 

### MapStruct Version

1.5.5.Final

**Comment by ZeroToHero-StepByStep** [comment] 2024-01-24 11:18
Any update ?

**Comment by Zegveld** [comment] 2024-01-27 09:22
`@Mapper` annotation was never intended to be inherited by extending. Also it is impossible for us to detect which interfaces extend the current interface if you start leaving off the `@Mapper` at the child, since you already have it defined at the parent.

Each `@Mapper` annotation is a starting point for generating a mapper, and the configuration of that annotation is used for the generation. So in your case the workaround is the expected way to handle this. You could look into `@MapperConfig` for defining generic configurations to be used. [see shared configurations for more information.]( https://mapstruct.org/documentation/stable/reference/html/#shared-configurations) 

This feels like an enhancement if we want to support this behavior, however then you also need to think about how to act if someone uses `@Mapper(uses={SomeOtherClass.class})`.

What does the user expect:
* Both the `uses` of this and the parent class should be combined
  * resulting in an ambigious exception if the user wants it to replace the parents `uses`.
* The child `uses` should replace the parent class `uses`.
  * resulting in a Qualifier error as you have here if the user does not want this.

**Comment by filiphr** [comment] 2024-01-28 16:20
Thanks for the explanation @Zegveld. @ZeroToHero-StepByStep please tell us if something is not clear.

I am going to close this for now as it works as designed. In a nutshell `@Mapper` is not meant to be passed down to children, if you need something like that please use `@MapperConfig`

**Closed by filiphr** 2024-01-28 16:20 UTC
Labels: bug
