### ISSUE TITLE
EnumMapping to support String to Enum conversion

### ISSUE THREAD

**Issue by typekpb** [mapstruct/mapstruct#3430] opened 2023-10-31 04:41 UTC
### Use case

EnumMapping with it's `nameTransformationStrategy = CASE_TRANSFORMATION` to perform uppercase/lowercase conversions I find super-handy.
However, I'd love to have the similar options for String to Enum conversion out of the box.

My use case is: API filed of type String should be mapped to internal enum without beeing too case sensitive => enabling internal conversion. 

### MapStruct Version

1.5.5

**Comment by filiphr** [comment] 2023-11-26 17:40
@typekpb have you tried this already? We do support this. Have a look at

https://github.com/mapstruct/mapstruct/blob/2bb2aefed8957861bf297b8f953b40e8753a8c75/processor/src/test/java/org/mapstruct/ap/test/value/nametransformation/CheeseEnumToStringPrefixMapper.java#L26-L29

**Comment by RichMacDonald** [comment] 2024-11-11 04:33
The problem is not that `@EnumMapping(nameTransformationStrategy = MappingConstants.PREFIX_TRANSFORMATION, configuration = "FRENCH_")` works.

The problem is that `@EnumMapping(MappingConstants.CASE_TRANSFORMATION, configuration = "upper")' does not.

The test case would be `assertThat( mapper.map( "brie" ) ).isEqualTo( CheeseType.BRIE );`

I have the same feature request.

**Comment by filiphr** [comment] 2024-11-17 15:22
@RichMacDonald if you do `@EnumMapping(MappingConstants.CASE_TRANSFORMATION, configuration = "lower")` then `assertThat( mapper.map( "brie" ) ).isEqualTo( CheeseType.BRIE );` will work.

Basically the transformation is for what should be done on the enum. so in this case instead of matching `BRIE` as a string we would match `brie`. The code for this looks like:

```java
    @Override
    public CheeseType map(String value) {
        if ( value == null ) {
            return null;
        }

        TestMapper.CheeseType cheeseType;

        switch ( value ) {
            case "brie": cheeseType = CheeseType.BRIE;
            break;
            case "blue": cheeseType = CheeseType.BLUE;
            break;
            default: throw new IllegalArgumentException( "Unexpected enum constant: " + value );
        }

        return cheeseType;
    }
```

I think that there might be some misunderstanding in the the transformation works. I'll close this and we can continue the discussion in the other issue you openned

**Closed by filiphr** 2024-11-17 15:22 UTC
