### ISSUE TITLE
warning: The following options were not recognized by any processor: '[mapstruct.unmappedTargetPolicy, mapstruct.defaultComponentModel]'

### ISSUE THREAD

**Issue by shalugin** [mapstruct/mapstruct#1256] opened 2017-07-20 16:40 UTC
I have the following warning during project compilation:

`warning: The following options were not recognized by any processor: '[mapstruct.unmappedTargetPolicy, mapstruct.defaultComponentModel]'`

I've added following options to build.gradle:

```
compileJava {
    options.compilerArgs += "-Amapstruct.defaultComponentModel=spring"
    options.compilerArgs += "-Amapstruct.unmappedTargetPolicy=ERROR"
}

```

Is this a known bug?

I founded this on SO: https://stackoverflow.com/questions/27607509/annotationprocessor-option-not-recorgnized-by-any-processor

**Comment by filiphr** [comment] 2017-07-21 08:02
@shalugin I don't know why it isn't working correctly for you. We have a correct setup for the processor options, like it is linked in the SO question. And it works with maven. 

How does your gradle setup look like? Is it the same as in the [mapstruct-on-gradle](https://github.com/mapstruct/mapstruct-examples/blob/master/mapstruct-on-gradle) example?

I just tried your example and it works with the examples.

**Comment by shalugin** [comment] 2017-07-21 08:38
@filiphr I'm trying to figure out wich modules show this error.

I have multi module project. And compile args sets in projects, wich use mapstruct.

Example of build.gradle:

```

plugins {
    id 'net.ltgt.apt' version '0.9'
}

description 'Blah blah blah'

compileJava {
    options.compilerArgs += "-Amapstruct.defaultComponentModel=spring"
    options.compilerArgs += "-Amapstruct.unmappedTargetPolicy=ERROR"
}

dependencies {
    compile project(':mod1')
    compile project(':mod2')
    compile project(':mod3')

    compile "org.mapstruct:mapstruct-jdk8:${mapStructVersion}"

    compile("org.springframework.boot:spring-boot-starter-web:${springBootVersion}") {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
    }
    compile "org.springframework.boot:spring-boot-starter-jetty:${springBootVersion}"
    compile("org.springframework.boot:spring-boot-starter-data-jpa:${springBootVersion}") {
        exclude group: 'org.hibernate'
    }
    compile "org.postgresql:postgresql:${postgresqlVersion}"

    compile "org.apache.httpcomponents:httpclient:${httpClientVersion}"
    compile "org.apache.httpcomponents:httpmime:${httpClientVersion}"
    compile "commons-io:commons-io:${commonsIoVersion}"

    compile "org.hibernate:hibernate-core:${hibernateVersion}"

    apt "org.mapstruct:mapstruct-processor:${mapStructVersion}"
    apt "org.projectlombok:lombok:${lombokVersion}"
}

```

Probably this error from `mod1`, `mod2` or `mod3`

**Comment by filiphr** [comment] 2017-07-21 08:57
Unfortunately, I am not that experiences with gradle. Maybe you can try compiling each module separately and see when exactly the warning comes. Maybe in one of your modules you set the arguments, but the processor is not actually invoked

**Comment by shalugin** [comment] 2017-07-21 09:02
I figured. This warning from dependent module.

So, if configuraction depends on another module we will receive this warning, because compilerArgs propagates to dependent module.

**Comment by filiphr** [comment] 2017-07-21 09:04
Great that we found the problem. It looks like a gradle configuration setup to me. Therefore, I am closing this issue, feel free to reopen if you think we need to address something on our side.

**Closed by filiphr** 2017-07-21 09:04 UTC

**Comment by shalugin** [comment] 2017-07-21 09:49
That was my mistake. I've added this compileArgs options to build.gradle to all subprojects :)

**Comment by sjaakd** [comment] 2017-07-21 12:34
Is this something we should document?

Verstuurd vanaf mijn iPhone

**Comment by shalugin** [comment] 2017-07-21 15:40
The main problem is that with gradle it's not obviously which module was cause of this warning.
I use gradle 4.

By the way, warnings/errors with gradle may be more usefull. I don't know, maybe issue for this already exists.

Try to recognize wich class has this unmapped property:

Command:
`gradle build`

Output:
```
Starting a Gradle Daemon, 11 busy and 2 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :model:compileJava
error: Unmapped target property: "x".
1 error

```

**Comment by filiphr** [comment] 2017-07-22 16:09
The warnings / errors in MapStruct should be quite good. In this particular case we output the error on the method that it produces it. Does this particular mapper extend some other more generic one that comes from different jar?

With maven the error message contains the name of the mapper and the line of the method (this is all done by the [`Messager`](https://docs.oracle.com/javase/8/docs/api/javax/annotation/processing/Messager.html) from javac).

**Comment by shalugin** [comment] 2017-07-27 09:54
> Does this particular mapper extend some other more generic one that comes from different jar?

Yes. I have simple generic interface:

```
public interface Converter<D, E> {

    D convert(E entity);

    E convertToEntity(D dto);
}

```

And I have many childrens, like this:
```

@Mapper(uses = {OksmConverter.class, IsoCountryConverter.class})
public interface CountryConverter extends Converter<CountryDTO, Country> {
}

```

**Comment by filiphr** [comment] 2017-07-27 10:01
@shalugin I would suggest you to follow #598. That one has the exact same problems with the error messages. We need to come up with a nice clean way of annotating the position that has problems.

**Comment by 62mkv** [comment] 2020-03-03 08:00
why is `mapstruct.verbose` option not working ? even in the https://github.com/mapstruct/mapstruct-examples/blob/master/mapstruct-on-gradle/build.gradle, if I change the task configuration closure as follows:

```
tasks.withType(JavaCompile) {
    options.compilerArgs = [
            '-Amapstruct.verbose=true'
    ]
}
```

I get 

`warning: The following options were not recognized by any processor: '[mapstruct.verbose]'`

why is that ?

**Comment by 62mkv** [comment] 2020-03-03 12:24
raised https://github.com/mapstruct/mapstruct/issues/2036 to address this

**Comment by filiphr** [comment] 2020-03-04 11:46
It is not working because it is not released. It would be part of 1.4

**Comment by sebasira** [comment] 2021-02-06 13:26
@shalugin So who do you resolve the warning about the compile options not being recognized? I started having this issue after upgrading to Gradle 6.7 and SpringBoot 2.4

I need to put it on every sub-module? or only the main module?

Thank you

**Comment by shalugin** [comment] 2021-02-07 06:27
@sebasira I've fixed that warning by removing compile options from submodules that doesn't use mapstruct.

**Comment by shalugin** [comment] 2021-02-07 06:30
@sebasira 
I don't remember exactly. 
I've fixed that warning by removing compile options from submodules that doesn't use mapstruct.

**Comment by akuma8** [comment] 2023-07-10 16:34
@filiphr I have the same warning with maven and after upgrading from Spring Boot 3.0.6 to Spring Boot 3.1.1. 
```
[WARNING] The following options were not recognized by any processor: '[mapstruct.defaultComponentModel]'
```
The mappers are well generated with the `@Component`, so I don't know what's going on.

**Comment by skromberg** [comment] 2023-07-23 20:26
> @filiphr I have the same warning with maven and after upgrading from Spring Boot 3.0.6 to Spring Boot 3.1.1.
> 
> ```
> [WARNING] The following options were not recognized by any processor: '[mapstruct.defaultComponentModel]'
> ```
> 
> The mappers are well generated with the `@Component`, so I don't know what's going on.

Same with Spring Boot 3.1.2 and maven setup:

```xml
    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven-compiler-plugin.version}</version>
        <configuration>
          <source>${java.version}</source>
          <target>${java.version}</target>
          <forceJavacCompilerUse>true</forceJavacCompilerUse>
          <annotationProcessorPaths>
            <path>
              <groupId>org.mapstruct</groupId>
              <artifactId>mapstruct-processor</artifactId>
              <version>${mapstruct.version}</version>
            </path>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>${lombok.version}</version>
            </path>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok-mapstruct-binding</artifactId>
              <version>${lombok-mapstruct-binding.version}</version>
            </path>
            <path>
              <groupId>org.springframework.boot</groupId>
              <artifactId>spring-boot-configuration-processor</artifactId>
              <version>${spring-boot-maven-plugin.version}</version>
            </path>
          </annotationProcessorPaths>
          <compilerArgs>
            <arg>-Amapstruct.verbose=true</arg>
            <arg>-Amapstruct.defaultComponentModel=jakarta</arg>
            <arg>-Amapstruct.unmappedTargetPolicy=ERROR</arg>
            <arg>-Amapstruct.defaultInjectionStrategy=CONSTRUCTOR</arg>
          </compilerArgs>
        </configuration>
      </plugin>
```

```bash
[INFO] --- compiler:3.11.0:testCompile (default-testCompile) @ external-service ---
[INFO] Changes detected - recompiling the module! :dependency
[INFO] Compiling 36 source files with javac [debug target 17] to target/test-classes
[WARNING] The following options were not recognized by any processor: '[mapstruct.unmappedTargetPolicy, mapstruct.defaultInjectionStrategy, mapstruct.defaultComponentModel]'
[INFO] 
```

**Comment by filiphr** [comment] 2023-07-30 07:54
>[INFO] Compiling 36 source files with javac [debug target 17] to target/test-classes
>[WARNING] The following options were not recognized by any processor: '[mapstruct.unmappedTargetPolicy, mapstruct.defaultInjectionStrategy, mapstruct.defaultComponentModel]'

Reading this it tells me that the warning comes from the test compile phase. Perhaps you only need to configure the `test` compile phase in order to avoid the maven-compiler-plugin trying to use the `compilerArgs` and `annotationProcessorPaths` in the test compile phase

**Comment by Quillraven** [comment] 2023-08-31 11:16
I am also using it in Maven and getting the warnings. No idea how to remove them. I tried two different approaches:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.11.0</version>
    <executions>
        <execution>
            <id>default-compile</id>
            <phase>compile</phase>
            <goals>
                <goal>compile</goal>
            </goals>
            <configuration>
                <generatedSourcesDirectory>${basedir}/${genSrcDirectory}</generatedSourcesDirectory>
                <source>${java.version}</source>
                <target>${java.version}</target>
                <useIncrementalCompilation>false</useIncrementalCompilation>
                <annotationProcessorPaths>
                    <path>
                        <groupId>org.projectlombok</groupId>
                        <artifactId>lombok</artifactId>
                        <version>${lombok.version}</version>
                    </path>
                    <path>
                        <groupId>org.mapstruct</groupId>
                        <artifactId>mapstruct-processor</artifactId>
                        <version>${mapstruct.version}</version>
                    </path>
                </annotationProcessorPaths>
                <compilerArgs>
                    <arg>-implicit:class</arg>
                    <arg>-Amapstruct.unmappedSourcePolicy=ERROR</arg>
                    <arg>-Amapstruct.unmappedTargetPolicy=ERROR</arg>
                </compilerArgs>
            </configuration>
        </execution>
    </executions>
</plugin>
```

and

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.11.0</version>
    <configuration>
        <generatedSourcesDirectory>${basedir}/${genSrcDirectory}</generatedSourcesDirectory>
        <source>${java.version}</source>
        <target>${java.version}</target>
        <useIncrementalCompilation>false</useIncrementalCompilation>
        <annotationProcessorPaths>
            <path>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </path>
            <path>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${mapstruct.version}</version>
            </path>
        </annotationProcessorPaths>
        <compilerArgs>
            <arg>-implicit:class</arg>
            <arg>-Amapstruct.unmappedSourcePolicy=ERROR</arg>
            <arg>-Amapstruct.unmappedTargetPolicy=ERROR</arg>
        </compilerArgs>
    </configuration>
</plugin>
```

Any ideas how to resolve the warning?
`[WARNING] The following options were not recognized by any processor: '[mapstruct.unmappedTargetPolicy, mapstruct.unmappedSourcePolicy]'`

**Comment by filiphr** [comment] 2023-09-10 22:05
Your first example should work @Quillraven. You'll need to share more from the log for us to be able to help you more

**Comment by Quillraven** [comment] 2023-09-11 06:05
@filiphr there is no useful information in the log imo but let me add it:

```
C:\Users\klaus2\.jdks\azul-11.0.19\bin\java.exe -Dmaven.multiModuleProjectDirectory=C:\Users\klaus2\IdeaProjects\openapi-test -Djansi.passthrough=true "-Dmaven.home=C:\Users\klaus2\AppData\Local\JetBrains\IntelliJ IDEA 2022.2.2\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Users\klaus2\AppData\Local\JetBrains\IntelliJ IDEA 2022.2.2\plugins\maven\lib\maven3\bin\m2.conf" "-Dmaven.ext.class.path=C:\Users\klaus2\AppData\Local\JetBrains\IntelliJ IDEA 2022.2.2\plugins\maven\lib\maven-event-listener.jar" "-javaagent:C:\Users\klaus2\AppData\Local\JetBrains\IntelliJ IDEA 2022.2.2\lib\idea_rt.jar=52444:C:\Users\klaus2\AppData\Local\JetBrains\IntelliJ IDEA 2022.2.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Users\klaus2\AppData\Local\JetBrains\IntelliJ IDEA 2022.2.2\plugins\maven\lib\maven3\boot\plexus-classworlds-2.7.0.jar;C:\Users\klaus2\AppData\Local\JetBrains\IntelliJ IDEA 2022.2.2\plugins\maven\lib\maven3\boot\plexus-classworlds.license" org.codehaus.classworlds.Launcher -Didea.version=2023.2.1 compile
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< com.example:openapi-test >----------------------
[INFO] Building openapi-test 0.0.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- openapi-generator:7.0.0:generate (default) @ openapi-test ---
[INFO] Previous run output is removed from C:\Users\klaus2\IdeaProjects\openapi-test\gen-src
[INFO] Generating with dryRun=false
[INFO] Output directory (C:\Users\klaus2\IdeaProjects\openapi-test\gen-src) does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[INFO] OpenAPI Generator: spring (server)
[INFO] Generator 'spring' is considered stable.
[INFO] ----------------------------------
[INFO] Environment variable JAVA_POST_PROCESS_FILE not defined so the Java code may not be properly formatted. To define it, try 'export JAVA_POST_PROCESS_FILE="/usr/local/bin/clang-format -i"' (Linux/Mac)
[INFO] NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[INFO] Processing operation read
[INFO] Processing operation create
[INFO] Processing operation order
[INFO] writing file C:\Users\klaus2\IdeaProjects\openapi-test\gen-src\src\main\java\org\openapitools\model\CreateApiResponse.java
[INFO] writing file C:\Users\klaus2\IdeaProjects\openapi-test\gen-src\src\main\java\org\openapitools\model\CreateResponse.java
[INFO] writing file C:\Users\klaus2\IdeaProjects\openapi-test\gen-src\src\main\java\org\openapitools\model\OrderApiResponse.java
[INFO] writing file C:\Users\klaus2\IdeaProjects\openapi-test\gen-src\src\main\java\org\openapitools\model\OrderKeyApiResponse.java
[INFO] writing file C:\Users\klaus2\IdeaProjects\openapi-test\gen-src\src\main\java\org\openapitools\model\OrderKeyResponse.java
[INFO] writing file C:\Users\klaus2\IdeaProjects\openapi-test\gen-src\src\main\java\org\openapitools\model\ReadApiResponse.java
[INFO] writing file C:\Users\klaus2\IdeaProjects\openapi-test\gen-src\src\main\java\org\openapitools\model\ReadResponse.java
[INFO] writing file C:\Users\klaus2\IdeaProjects\openapi-test\gen-src\src\main\java\org\openapitools\api\OrderControllerApi.java
[INFO] writing file C:\Users\klaus2\IdeaProjects\openapi-test\gen-src\pom.xml
[INFO] writing file C:\Users\klaus2\IdeaProjects\openapi-test\gen-src\README.md
[INFO] writing file C:\Users\klaus2\IdeaProjects\openapi-test\gen-src\src\main\java\org\openapitools\api\ApiUtil.java
[INFO] writing file C:\Users\klaus2\IdeaProjects\openapi-test\gen-src\.openapi-generator-ignore
[INFO] writing file C:\Users\klaus2\IdeaProjects\openapi-test\gen-src\.openapi-generator\VERSION
[INFO] writing file C:\Users\klaus2\IdeaProjects\openapi-test\gen-src\.openapi-generator\FILES
################################################################################
# Thanks for using OpenAPI Generator.                                          #
# Please consider donation to help us maintain this project 🙏                 #
# https://opencollective.com/openapi_generator/donate                          #
################################################################################
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ openapi-test ---
[INFO] Copying 1 resource from src\main\resources to target\classes
[INFO] Copying 2 resources from src\main\resources to target\classes
[INFO] 
[INFO] --- compiler:3.11.0:compile (default-compile) @ openapi-test ---
[INFO] Compiling 9 source files with javac [debug target 11] to target\classes



[WARNING] The following options were not recognized by any processor: '[mapstruct.unmappedTargetPolicy, mapstruct.unmappedSourcePolicy]'



[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.867 s
[INFO] Finished at: 2023-09-11T08:02:49+02:00
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0
```

And here is the pom file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.14</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.example</groupId>
    <artifactId>openapi-test</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>openapi-test</name>
    <description>openapi-test</description>

    <properties>
        <java.version>11</java.version>
        <genSrcDirectory>gen-src</genSrcDirectory>
        <inputYamlFile>src/main/resources/api-docs.yaml</inputYamlFile>
        <mapstruct.version>1.5.5.Final</mapstruct.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.7.0</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- dependencies for autogenerated yaml classes (openapi) -->
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>0.2.6</version>
        </dependency>

        <!-- mapping between REST request/response TO and app input/output TO -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${mapstruct.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>
            </plugin>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <executions>
                    <execution>
                        <id>default-compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <generatedSourcesDirectory>${basedir}/${genSrcDirectory}</generatedSourcesDirectory>
                            <source>${java.version}</source>
                            <target>${java.version}</target>
                            <useIncrementalCompilation>false</useIncrementalCompilation>
                            <annotationProcessorPaths>
                                <path>
                                    <groupId>org.projectlombok</groupId>
                                    <artifactId>lombok</artifactId>
                                    <version>${lombok.version}</version>
                                </path>
                                <path>
                                    <groupId>org.mapstruct</groupId>
                                    <artifactId>mapstruct-processor</artifactId>
                                    <version>${mapstruct.version}</version>
                                </path>
                            </annotationProcessorPaths>
                            <compilerArgs>
                                <arg>-implicit:class</arg>
                                <arg>-Amapstruct.unmappedSourcePolicy=ERROR</arg>
                                <arg>-Amapstruct.unmappedTargetPolicy=ERROR</arg>
                            </compilerArgs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.0.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <groupId>${project.groupId}</groupId>
                            <artifactId>${project.artifactId}_project</artifactId>
                            <artifactVersion>${project.version}</artifactVersion>

                            <inputSpec>${basedir}/${inputYamlFile}</inputSpec>
                            <output>${basedir}/${genSrcDirectory}</output>
                            <!-- clean output directory -> set it to true to remove classes properly in case they get renamed -->
                            <cleanupOutput>true</cleanupOutput>
                            <generatorName>spring</generatorName>

                            <!--                            <templateDirectory>${basedir}/templates</templateDirectory>-->

                            <!--                            <apiPackage>de.volkswagen.order.port.provider.restapi.generated</apiPackage>-->
                            <!--                            <modelPackage>de.volkswagen.order.port.provider.restapi.generated.model</modelPackage>-->
                            <!--                            <importMappings>OrderKeyTO=de.volkswagen.order.model.to.OrderKeyTO</importMappings>-->

                            <configOptions>
                                <annotationLibrary>swagger2</annotationLibrary>
                                <dateLibrary>java8</dateLibrary>
                                <interfaceOnly>true</interfaceOnly>
                                <useTags>true</useTags>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <useBeanValidation>false</useBeanValidation>
                                <library>spring-boot</library>
                                <useResponseEntity>false</useResponseEntity>
                                <serializableModel>true</serializableModel>
                                <containerDefaultToNull>false</containerDefaultToNull>
                                <!-- hide timestamp to reduce noise in git history for generated classes -->
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>

                                <additionalModelTypeAnnotations>
                                    &#64;lombok.NoArgsConstructor
                                    &#64;lombok.experimental.Accessors(fluent = true)
                                </additionalModelTypeAnnotations>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>

```

**Comment by filiphr** [comment] 2023-09-11 09:55
@Quillraven and do you have some mappers in your source code? If you do not then the MapStruct processor will not run and it won't consume the compiler arguments.

**Comment by Quillraven** [comment] 2023-09-11 11:22
It includes a mapper as well called `ResponseMapper`. I will attach the example project. Maybe it helps.

[openapi-test.zip](https://github.com/mapstruct/mapstruct/files/12575377/openapi-test.zip)

**Comment by trupasinghe-atlas** [comment] 2023-09-15 06:38
@filiphr Is there a way to ignore this warning without turning off all warnings?  `<showWarnings>false</showWarnings>`
Because I have multiple modules this warning appears everywhere.

**Comment by filiphr** [comment] 2023-09-16 09:58
@Quillraven I tried your code and I do not get any warnings.

>@filiphr Is there a way to ignore this warning without turning off all warnings?

If you properly configure your project you should not have this warning. This warnings are there only if a module does not have mappers.

**Comment by Quillraven** [comment] 2023-09-18 07:15
@filiphr I tried it again. When doing clean -> compile then I don't get a warning in the first run through. When I then run compile again then I  get the warning.
Maybe because the mapper is already there and it does not have to do anything?

**Comment by trupasinghe-atlas** [comment] 2023-09-27 00:43
> ```
>  <compilerArgs>
>                                 <arg>-implicit:class</arg>
>                                 <arg>-Amapstruct.unmappedSourcePolicy=ERROR</arg>
>                                 <arg>-Amapstruct.unmappedTargetPolicy=ERROR</arg>
>                             </compilerArgs>
> ```

I have multi-module maven mono repo. But only a few modules use Mapstruct. So when I have compiler args at root mvn config all other modules throw this warning. 
So I moved my compiler args into the required modules that use Mapstruct. This means I added the below block into the modules that I use mapstruct. That remove all the thousand of warnings from build logs :D

```<pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                        <compilerArgs>
                            <arg>-Amapstruct.defaultComponentModel=jsr330</arg>
                            <arg>-Amapstruct.unmappedTargetPolicy=ERROR</arg>
                            <arg>-Amapstruct.defaultInjectionStrategy=constructor</arg>
                        </compilerArgs>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>```

**Comment by filiphr** [comment] 2023-09-30 09:22
@Quillraven I managed to reproduce it. The reason why you get the warning is due to the fact that the `openapi-generator-maven-plugin` always generates new classes and that triggers the maven compilation. However, the maven compiler does not invoke the processor since nothing has changed. If I remove the plugin then it works as expected, there are no warnings
