### ISSUE TITLE
avoid intermittent Objects creation when target is nested object and all leaf objects are null.

### ISSUE THREAD

**Issue by evipin** [mapstruct/mapstruct#1434] opened 2018-04-15 18:36 UTC
I am mapping  a source object to a nested target object. it creates parent object even when all child objects are null. 
@Mapping(source = "addressBook", target = "person.contact.home.address")
@Mapping(source = "addressBook", target = "person.contact.home.streetName"")
   
when **address & streetName** are null , I do want _home_ object to be created. Currently home object is created and it shows up in Json file.

**Comment by filiphr** [comment] 2018-04-20 17:44
I think you mean you do not want it to be created. In any case this is a duplicate of #1166

**Closed by filiphr** 2018-04-20 17:44 UTC
