### ISSUE TITLE
Can't generate mapping where target record takes at least one Map parameter

### ISSUE THREAD

**Issue by Left** [mapstruct/mapstruct#3094] opened 2022-11-29 15:07 UTC
### Expected behavior

I can create a mapper that has java record with at least one Map field as a target 

### Actual behavior

Build error

### Steps to reproduce the problem

Here is a minimum reproducible scenario:
 
TestRecord.java:
```java
public record TestRecord(Map<String, String> params) {
}
```

TestStruct.java:
```java
public class TestStruct {
  private final Map<String, String> params;

  public TestStruct(Map<String, String> params) {
    this.params = params;
  }

  public Map<String, String> getParams() {
    return params;
  }
}
```

TestMapper.java:
```java
@Mapper(
    unmappedTargetPolicy = ReportingPolicy.ERROR
)
public interface TestMapper {
  TestMapper INSTANCE = Mappers.getMapper(
      TestMapper.class);

  TestRecord map(TestStruct param);
}
```

As a result, I'm getting build error: Unmapped target property: "ams".

NOTE that ams is a 3-symbols-trimmed "params" name.

### MapStruct Version

MapStruct 1.5.3.Final

**Comment by filiphr** [comment] 2023-02-05 08:48
Closing this since I cannot reproduce it with 1.5.3.Final. Please provide some example project where this can be reproduced and we'll reopen it

**Closed by filiphr** 2023-02-05 08:48 UTC
Labels: bug
