### ISSUE TITLE
Mapstruct inside an AspectJ project in Eclipse causes NPE in mapper interface

### ISSUE THREAD

**Issue by boristhecat** [mapstruct/mapstruct#1190] opened 2017-04-28 06:32 UTC
We are currently using mapstruct in a project mainly developed using Eclipse. Yesterday we configured a maven module to be an 'AspectJ project' in Eclipse and right after that, our Mapper-Interfaces are showing the Error below. 

Removing all methods from the mapper interface as well as removing the aspectj capabilities from the eclipse project makes the error go away.

```
Internal error in the mapping processor: java.lang.NullPointerException at 
 org.aspectj.org.eclipse.jdt.internal.compiler.lookup.FieldBinding.sourceField(FieldBinding.java:425) at 
 org.aspectj.org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl
 $SourceLocationComparator.determineSourceStart(TypeElementImpl.java:108) at 
 org.aspectj.org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl
 $SourceLocationComparator.getSourceStart(TypeElementImpl.java:72) at 
 org.aspectj.org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl$SourceLocationComparator.compare(TypeElementImpl.java:
 65) at org.aspectj.org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl
 $SourceLocationComparator.compare(TypeElementImpl.java:1) at java.util.TimSort.countRunAndMakeAscending(Unknown Source) 
 at java.util.TimSort.sort(Unknown Source) at java.util.Arrays.sort(Unknown Source) at java.util.ArrayList.sort(Unknown Source) at 
 java.util.Collections.sort(Unknown Source) at 
 org.aspectj.org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl.getEnclosedElements(TypeElementImpl.java:166) at 
 org.mapstruct.ap.internal.util.workarounds.SpecificCompilerWorkarounds.replaceTypeElementIfNecessary(SpecificCompilerWorkarou
 nds.java:112) at org.mapstruct.ap.internal.util.Executables.getAllEnclosedExecutableElements(Executables.java:149) at 
 org.mapstruct.ap.internal.model.common.Type.getAllExecutables(Type.java:487) at 
 org.mapstruct.ap.internal.model.common.Type.getSetters(Type.java:556) at 
 org.mapstruct.ap.internal.model.common.Type.getPropertyWriteAccessors(Type.java:418) at 
 org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.souceMethod(BeanMappingMethod.java:102) at 
 org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:362) at 
 org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:146) at 
 org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:117) at 
 org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:76) at 
 org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:270) at 
 org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:250) at 
 org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:216) at 
 org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:155) at 
 org.aspectj.org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139) at 
 org.aspectj.org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121) at 
 org.aspectj.org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProce
 ssorManager.java:159) at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:931) at 
 org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:437) at 
 org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:417) at 
 org.aspectj.ajdt.internal.core.builder.AjBuildManager.performCompilation(AjBuildManager.java:1036) at 
 org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:309) at 
 org.aspectj.ajdt.internal.core.builder.AjBuildManager.incrementalBuild(AjBuildManager.java:189) at 
 org.aspectj.ajde.core.internal.AjdeCoreBuildManager.performBuild(AjdeCoreBuildManager.java:127) at 
 org.aspectj.ajde.core.AjCompiler.build(AjCompiler.java:91) at org.eclipse.ajdt.core.builder.AJBuilder.build(AJBuilder.java:257) at 
 org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735) at 
 org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) at 
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206) at 
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246) at org.eclipse.core.internal.events.BuildManager
 $1.run(BuildManager.java:301) at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) at 
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304) at 
 org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360) at 
 org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383) at 
 org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144) at 
 org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235) at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by filiphr** [comment] 2017-07-21 08:19
I think that this actually might be some bug in the eclipse compiler that aspectj uses. However, I don't know much about the eclipse compiler.

I think that #1257 actually duplicates this.

@agudian can you have a look?

@boristhecat which version of MapStruct and Aspectj are you using?

**Comment by krezzsy** [comment] 2017-07-24 13:09
maybe, u will use as the basis my version? (1.8.8) Cause time is running and we still don't have any solutions.

**Comment by agudian** [comment] 2017-07-24 17:29
I guess you tried the latest release version of MapStruct? And perhaps also the latest candidate release (1.2.0.CR1)? Do you get the same error there?

The best way we can help you is if you provide a small, minimal self-contained sample project (preferrably something with Maven, or if you don’t use it here in this case, a self-contained Eclipse project with dependencies and project metadata).
Because if we can’t easily reproduce the error, chances are good that the issue won’t get picked so soon 😉

**Comment by agudian** [comment] 2017-07-25 17:35
Oh, one more thing I just noticed while reading the stack trace more closely: this looks much more like an issue with the aspectJ implementation. It might be using an outdated version of the eclipse-jdt-core bundle (which contains the compiler classes). If that version is not outdated, then the issue might need to be fixed downstream in Eclipse itself.
I'm not so sure what we can do to mitigate the error in our code. Just catching the exception probably won't do the trick, as we atually need the result.

@krezzsy did you check if the latest versions of AspectJ and/or Eclipse would fix this for you?

**Comment by krezzsy** [comment] 2017-07-26 08:05
@agudian Well, I can't change the aspectj version because it's not my own project, i tried to use the latest version of mapstruct (1.2.0.CR1), but seems like problem in aspectj.

**Comment by boristhecat** [comment] 2017-08-01 08:18
Sorry for the delay  😶 

Since i dont have access to the project anymore i actually cant provide a corresponding example :/
However, i could still find the used versions:
```xml
<org.mapstruct.version>1.1.0.Final</org.mapstruct.version>
<aspectj.runtime.version>1.8.9</aspectj.runtime.version>
```

**Comment by avdyk** [comment] 2017-12-13 10:15
Hi,

I have the same problem: a project with aspectj and a class with mapstruct. NPE!

I don't need aspectj on the mapstruct class. The solution I found is to exclude the mapstruct class from aspectj:
```
<plugin>
  <groupId>org.codehaus.mojogroupId>
  <artifactId>aspectj-maven-plugin</artifactId>
  <!-- ... -->
  <configuration>
    <!-- ... -->
    <sources>
      <source>
        <excludes>
          <exclude>**/some/pkg/SomeClass*.java</exclude>
        </excludes>
      </source>
    </sources>
  </configuration>
</plugin>
```
It works for me, hope it helps,
Cheers

**Comment by filiphr** [comment] 2018-04-01 10:10
Thanks for the workaround @avdyk.

As we can't reproduce this and it most likely is an issue in the AspectJ compiler. I am going to close this issue. If someone thinks that we need to reopen it we can do it

**Closed by filiphr** 2018-04-01 10:10 UTC

**Comment by davidbilge** [comment] 2018-08-08 13:09
I am experencing the same problem and the fix is extremely unsatisfying. Using AspectJ 1.8.13, i.e. the latest release from the 1.8 branch and Mapstruct 1.2.0.Final.

**Comment by davidbilge** [comment] 2018-08-09 06:33
I tried using 1.9.1. It still does not work, but the error message is different:

`Internal compiler error: java.lang.Exception: java.lang.NullPointerException at org.aspectj.org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:169)`

**Comment by sjaakd** [comment] 2018-08-09 07:32
Could it be that you try to setup aspects in generated code which is not yet there? Perhaps you should exclude all generated code?

**Comment by davidbilge** [comment] 2018-08-09 07:42
@sjaakd I do not see how that would be possible in the configuration of the aspectj-maven-plugin - can you point me into the right direction?

**Comment by sjaakd** [comment] 2018-08-09 07:58
Well, I'm not an expert here, but I can imagine that you setup injection points (or whatever the correct terminology is) to -for instance- log all public method calls. If you do that I presume this happens also in generated code. This generated code is generated by a similar process as compile time injection points. Now suddenly you have a race condition..

**Comment by davidbilge** [comment] 2018-08-09 08:44
I see what you mean. What I think actually happens is:

1. The maven compiler plugin runs and with it all annotation processors (one of which is mapstruct's)
1. The maven aspectj plugin runs and enhances all generated class files or recompiles all source files (not sure which actually happens)

Either way, no race condition should occur. But maybe I'm wrong and the aspectj-compiler runs the APTs again?

**Comment by sjaakd** [comment] 2018-08-09 09:49
Isn't the aspectj plugin not simply a wrapper around the apt? Can you force the mapstruct plugin to run first (eg assign it to an earlier lifecycle?). 


Thinking out loud:  jdt uses partial compilation. Hence I don't think it adheres to maven lifecycles very well. But perhaps I'm wrong. 

Does your command line maven build work?

**Comment by davidbilge** [comment] 2018-08-09 09:51
Oh sorry, I should have been more precise about that: It's the command line build that fails with the above error. It showed the same error as in OPs case with aspectj 1.8.

This is actually not an error I see in eclipse, interestingly.

**Comment by sjaakd** [comment] 2018-08-09 15:15
Ah. It's the jdt that is used by the aspectj plugin that fooled me. Try playing with the lifecycle in maven

**Comment by sjaakd** [comment] 2018-08-09 15:56
So: I think that both aspects and apt have lifecycle generate-sources. As of maven 3 I think that plugins are ran in their defined order. Make sure apt runs first, by defining it first. Check with maven -d whether this actually happens

**Comment by filiphr** [comment] 2018-08-18 09:06
@davidbilge if you can provide is with an example project that we can run and try it out it would be really helpful. I personally don't have a lot of experience with aspectj, but if I can get a reproducal project I would be able to pinpoint what exactly the problem is :)
