### ISSUE TITLE
object factory generate invalid code inside explicitly declared list mapping function

### ISSUE THREAD

**Issue by hestwood** [mapstruct/mapstruct#405] opened 2014-12-31 05:30 UTC
If define below list mapping method in mapper:
abstract List<A> bListToAList(List<B> b)

Then use entityFactory:

<T> T createEntity(Class<T> entityClass){ .. }

Generated code inside bListToAList would be:

factory.createEntity( .class );

**Comment by hestwood** [comment] 2015-01-05 03:13
Below is the code to reproduce the problem , please kindly check.

```Java
public class People {
	private String name;
	private List<People> children;
	
	public List<People> getChildren() {
		return children;
	}

	public void setChildren(List<People> children) {
		this.children = children;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}

public class Person {
	private String id;
	private List<Person> children;
	
	public String getId() {
		return id;
	}
	
	public void setId(String id) {
		this.id = id;
	}

	public List<Person> getChildren() {
		return children;
	}

	public void setChildren(List<Person> children) {
		this.children = children;
	}
}

public class EntityFactory {
	public static <T> T createEntity(@TargetType Class<T> entityClass ){
		return null;
	}
}

@Mapper(uses={EntityFactory.class})
public abstract class PersonMapper {
	
	PersonMapper INSTANCE = Mappers.getMapper(PersonMapper.class);
	@Mappings({@Mapping(source="id",target="name")}
	)
	abstract People personToPeople(Person person);
	
	abstract List<People> personListToPeopleList(List<Person> children);
	
}

//generated code
public class PersonMapperImpl extends PersonMapper {

    private final EntityFactory entityFactory = new EntityFactory();
    @Override
    List<People> personListToPeopleList(List<Person> children) {
        if ( children == null ) {
            return null;
        }

        List<People> list = entityFactory.createEntity( .class );

        for ( Person person : children ) {
            list.add( personToPeople( person ) );
        }

        return list;
    }

    @Override
    People personToPeople(Person person) {
        if ( person == null ) {
            return null;
        }

        People people = entityFactory.createEntity( People.class );

        people.setName( person.getId() );
        people.setChildren( personListToPeopleList( person.getChildren() ) );


        return people;
    }

}
```

**Comment by hestwood** [comment] 2015-01-05 03:14
I understand that it is not necessary to declare "personListToPeopleList" but for my case this method has to be declared so it could be referenced in other manual mapper method int he mapper class.

**Comment by sjaakd** [comment] 2015-01-05 11:46
@hestwood Thanks.

The problem is that MapStruct creates invalid code here. So: `List<People> list = entityFactory.createEntity( .class );`. I've used your code as reproducer and I'll look for the cause.

I do however see that the method: `People personToPeople(Person person)` neatly uses `personListToPeopleList( person.getChildren() )`, and does not generate a new one.

**Comment by hestwood** [comment] 2015-01-06 03:20
Thanks for quick fix , although I didn't get your reply : "I do however see that the method: People personToPeople(Person person) neatly uses personListToPeopleList( person.getChildren() ), and does not generate a new one." 

I think the problem is not that it is generating extra methods but just miss the class name in the generated list mapping code.

**Comment by hestwood** [comment] 2015-01-06 03:37
BTW: when next version that contains the fix would be released?

**Comment by sjaakd** [comment] 2015-01-06 14:04
That will be RC1. No date is set, but you can always use the latest code base and build yourself.

**Comment by sjaakd** [comment] 2015-01-06 20:24
PR is merged. Solution provided.

**Closed by sjaakd** 2015-01-06 20:24 UTC
Labels: bug

**Comment by hestwood** [comment] 2015-01-07 02:30
Thanks for quick fix. But it seems the latest snapshot has a problem , it is got from https://mapstruct.ci.cloudbees.com/job/mapstruct-snapshot/lastSuccessfulBuild

The error is: An internal error occurred during: "Building workspace".
org.mapstruct.ap.processor.ModelElementProcessor: Error reading configuration file

**Comment by agudian** [comment] 2015-01-07 18:47
> The error is: An internal error occurred during: "Building workspace".
> org.mapstruct.ap.processor.ModelElementProcessor: Error reading configuration file

No idea - is there some more info you can provide on the error?

**Comment by gunnarmorling** [comment] 2015-01-07 20:20
A stacktrace or so would be good. Sounds like this occurs within and IDE? Does the issue also happen when using MapStruct with Maven or plain javac?

**Comment by hestwood** [comment] 2015-01-07 23:41
Never mind , after a clean build , this problem is gone
