### ISSUE TITLE
Nasted mappers with @MappingTarget don't import target class

### ISSUE THREAD

**Issue by lucasmerencia** [mapstruct/mapstruct#612] opened 2015-08-06 12:00 UTC
I using mapstruct 1.0.0.CR1 to map my dtos to entities.

But I found a problem with nasted mappers with `@MappingTarget`. 

I'm mapping DiscountDto to Discount:
```java
@Mapper(componentModel = "cdi")
public interface DiscountDTOMapper {

  Discount toDiscount(DiscountDTO discountDto, @MappingTarget Discount discount);

}
```

And I'm mapping SaleDto to Sale:
```java

@Mapper(componentModel = "cdi", uses = {  DiscountMapper.class })
public interface SaleMapper {
  Sale toSale(SaleDTO sale, @MappingTarget Sale sale);
}
```

On generated class `SaleMapperImpl` there is this code:
```java

if ( sale.getDiscount() == null ) {
  sale.setDiscount( new Discount() );
}
```

But this class doesn't compiles because `Discount` is not imported in `SaleMapperImpl`.

Has anyone had any similar problem?
There is a workaround for it?

**Comment by gunnarmorling** [comment] 2015-08-06 12:20
I am not quite clear about the cause if this, but for the time being you can add an import for the missing type via `@Mapper#imports()`.

**Comment by agudian** [comment] 2015-08-06 13:23
I'm pretty sure I fixed that already.

**Comment by agudian** [comment] 2015-08-06 13:25
Ah, see #604 - the pull request for it is still open, though.

**Comment by agudian** [comment] 2015-08-06 13:28
Closing it as a duplicate of #604. Thanks for the report, though!

**Closed by agudian** 2015-08-06 13:28 UTC
Labels: bug, duplicate
