### ISSUE TITLE
Drop support for Java 6 and Java 7

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct#1301] opened 2017-09-23 13:55 UTC
Up until MapStruct 1.2.x, we fully support using MapStruct with JDK 6, JDK 7 and JDK 8 (at compile time), and have it working on JDK 9 out of the box (with maybe an `-addmods` parameter required).

We talked about ditching JDK 6 and 7 for a long time and I think with the official release of JDK 9, it's a good time to do so now.

Here's what we can do:

- [x] Decide on a good time frame for the release and the release version to be used for that change.
- [x] Remove `mapstruct-jdk8` artifact and only use `mapstruct` going forward (using multi-release jar format in case we need different annotations/classes for future Java versions). We can also simplify our build structure again and remove the internal core-common Maven module. And while we're at it, we could rename the directory `core` to `mapstruct` to make it match the Maven artifact name.
- [x] Remove the ITs flavors that target Java 6 or Java 7, maybe also remove the `maven-processor-plugin` flavors (it's only delegating to the default compiler anyway).
- [ ] generate error when 6 or java 7 is used
- [x] adapt our test cases and make effective use of `@Repeatable` (perhaps also the documentation). Maybe we could do a regex replace.. (see https://github.com/mapstruct/mapstruct/issues/1628)
- [ ] look very careful which SpecificCompilerWorkarounds are still needed. Its mostly Eclipse tycho (but probably related to old java versions).
- [x] I think we go through lengths so java 8 types are not required during annotation processor run if java8 is not on path (e.g. in conversions and built-in mappings). We can remove that.
- [x] use diamond operator were applicable
- [ ] renaming directory `core` to `mapstruct`
😁

**Comment by filiphr** [comment] 2017-10-03 20:52
I would add that we change the way we do our integration tests. Instead of using toolchains let's use  the Travis [Matrix Expansion](https://docs.travis-ci.com/user/build-stages/matrix-expansion/). This would reduce the complexity of our integration tests as well. We can even do the entire build once with Java 8 and once with Java 9.

I am already using it for the IntelliJ plugin https://travis-ci.org/mapstruct/mapstruct-idea and it is pretty easy.

**Comment by sjaakd** [comment] 2017-10-17 18:45
> Decide on a good time frame for the release and the release version to be used for that change.

I believe we need a major release for doing so, just to indicate clearly the significance. What about doing a 2.0 release with all the (relevant) pending PR's and the dropped support for JDK6 and 7? We can leave major restructuring for 3.0 (like getting rid of templates on the lowest level as @gunnarmorling proposed). That would clear the path for a quick ditch without having to work a long time on 2.0.

**Comment by gunnarmorling** [comment] 2017-10-17 18:58
It's a very good question. Personally I don't think we'd *have* to do the major version bump just due the Java 8 requirement. E.g. Hibernate also did it in one of the 5.x minors and there were no big complaints by the community. As long as it's properly communicated.

If going to 2.0, we should also get rid of the deprecated features and more generally think about other things we thing should be incompatibly altered. Hence I rather had in mind to wait a bit still with 2.0. But the preference isn't huge, so I also can be convinced of doing it earlier than later :)

The template stuff would be very nice, but it's probably not something we'll get to any time soon, given the amount of team we currently are ready to put into it.

**Comment by agudian** [comment] 2017-10-17 19:00
I guess the biggest argument for a 2.0 release would be the change in the artifact name, or more precisely: removing the mapstruct-jdk8 artifact. That might be icky depending on where people managed that dependency...

**Comment by kevcodez** [comment] 2017-10-20 08:01
Not much of a help regarding the questions above, however, I'd be glad to help migrate some of the code base to Java 8 - feel free to mention me when you created a new branch or start using Java 8 on the master ;)

**Comment by gunnarmorling** [comment] 2017-10-20 08:13
Will do, thanks a lot; that's much appreciated! The plan is to do a 1.3
release rather soonish and then go to 2.0, migrating to Java 8 as part of
that.

**Comment by neoXfire** [comment] 2018-10-02 16:37
As @kevcodez, I'd be pleased to help for that migration. Java 11 is released now, Java 6 seems so old now for the source code :).
Do you want to initiate a branch or do you accept pull request with new branchs for this ?

**Comment by kevcodez** [comment] 2018-10-02 19:38
@neoXfire I was also just offering to help with migration - maybe @gunnarmorling or @filiphr can help you with this ;)

**Comment by neoXfire** [comment] 2018-10-03 21:49
I succeeded in making a full java 8 maven build work with core-jdk8 dropped.
See [here ](https://github.com/mapstruct/mapstruct/compare/master...neoXfire:java8]).
Some maven plugin versions should have been upgraded to make it work.
I noticed some warning during build. I don't know if these are serious or not.

I'm a bit concerned about hickory dependency. It doesn't seem to be maintain anymore and they are some warning from PrismGenerator Processor `@SupportedSourceVersion(SourceVersion.RELEASE_6) `from `PrismGenerator` class. I don't know how exactly it is used in mapstruct but have you looked at others options ?

**Comment by sjaakd** [comment] 2018-10-12 19:13
@neoXfire .. I'll have a look the work soon.. I'm also not sure how to continue on this one. Will discuss it with the others as well.

**Comment by gunnarmorling** [comment] 2018-10-12 19:19
Thanks a lot, @neoXfire! Can you file a pull request with your changes? That makes it easier to review. That being said, I vote for making the change to JDK 8 and later within MapStruct 1.3. I think that's acceptable if clearly communicated. We can publish a relocation artifact for the old "jdk8" one, which points to the new. So people will see a warning telling to reference the correct one instead. In 2.0, we'd get rid of the relocation artifact, too.

**Comment by filiphr** [comment] 2018-10-13 06:27
>That being said, I vote for making the change to JDK 8 and later within MapStruct 1.3. I think that's acceptable if clearly communicated. We can publish a relocation artifact for the old "jdk8" one, which points to the new. So people will see a warning telling to reference the correct one instead. In 2.0, we'd get rid of the relocation artifact, too.

I am also OK with making the change to JDK 8 within MapStruct 1.3. We are still in the Beta release and  I even doubt that anyone will feel the change. I think that most of our users are on Java 8 already. 

Regarding:
>I'm a bit concerned about hickory dependency. It doesn't seem to be maintain anymore and they are some warning from PrismGenerator Processor 

Actually the `PrismGenerator` doesn't work on Java 9+ (I have a branch locally where I have been playing around with compiling and building MapStruct different Java versions). So we will need to find some solution for that. I can't even find the location of the sources for the hickory dependency. Maybe @gunnarmorling knows more about the project.

**Comment by gunnarmorling** [comment] 2018-10-13 07:28
> Actually the PrismGenerator doesn't work on Java 9+ 

Can you share some details what the issues actually are?

> I can't even find the location of the sources for the hickory dependency

It used to be on the old java.net infrastructure, so it's gone probably :( I could find a clone though on GitHub by a colleague of mine: https://github.com/vietj/hickory. Not sure though whether he deployed it to Central, too.

So that's one route to explore; the other one would be to just take the generated prisms and treat them as manually created sources going forward. Of course this will require some manual efforts, whenever MapStruct adds new annotations or changes the existing ones.

**Comment by filiphr** [comment] 2018-10-13 07:46
>Can you share some details what the issues actually are?

I forgot, but I will try it again and let you know. I think that the fix for it was quite easy, so we can do a clone and publish it to central. We are using https://mvnrepository.com/artifact/com.jolira/hickory/1.0.0.

I couldn't find the clone of your colleague in Central. However, if he wants we can do the support for Java 9 in hickory together and publish it somehow.

>the other one would be to just take the generated prisms and treat them as manually created sources going forward

I actually did that so I can continue forward, but didn't like the approach as it was leading to manual efforts :)

**Comment by filiphr** [comment] 2018-10-14 20:50
@gunnarmorling just checked Hickory and Java 9 and all is fine. The problem is in the `maven-processor-plugin`. However, we can use the `annotationProcessorPaths` from the `maven-compiler-plugin` instead of that one, so we should be fine.

**Comment by filiphr** [comment] 2018-10-15 20:18
I have just merged #1623 MapStruct now has Java 8 as a baseline 🎉. Big thank you to @neoXfire doing the PR.

I'll leave this issue open so we can address some of the other points into it

**Comment by filiphr** [comment] 2018-10-17 18:03
@neoXfire looks good to me I am only not certain which change is the "Replace for loops by foreach". If it is with the `foreach` on the `Iterable` I would say not really for now.

Also for some of the points we might need to see how it's readability would look like 😄.

Feel free to do a PR with your changes. What I would only advise is to maybe split PRs if it turns out that it is too big.

**Comment by neoXfire** [comment] 2018-10-19 15:01
I forget to remove mapstruct-common dependencies in some pom.xml.
Here : https://github.com/mapstruct/mapstruct/blob/master/core/pom.xml#L25
And here : https://github.com/mapstruct/mapstruct/blob/master/parent/pom.xml#L235
 Build fails if no artefact is deployed yet into maven local or remote repositories. I'm going to correct that tonight in a PR.

**Comment by sjaakd** [comment] 2018-10-19 17:47
Ok thanks :smile:

**Comment by filiphr** [comment] 2018-11-11 11:05
The main things for this issue have been done. I have created #1645 with some extra stuff. If more things are needed we should create separate issues accordingly.

**Closed by filiphr** 2018-11-11 11:05 UTC
Labels: build, for:team-discussion
