### ISSUE TITLE
When uses @Mappingtarget, @Builder doesn't work

### ISSUE THREAD

**Issue by kqkdChen** [mapstruct/mapstruct#2327] opened 2021-01-12 02:34 UTC
for example: 
```java
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CommandParam {

    private Long txId;

    private Long timeout;

}
```

business objects
```java
@Builder
@Getter
@ToString
public class CommandBo {

    private Long txId;

    private Long timeout;

}
```

Using @Mappingtarget to update business objects
```java
 CommandBo updateBo(CommandParam param, @MappingTarget CommandBo bo);
```

The code generated automatically is as follows
```java
    @Override
    public CommandBo updateBo(CommandParam param, CommandBo bo) {
        if ( param == null ) {
            return null;
        }

        return bo;
    }
```
This is not the result I want，Why didn't @Builder work ?

Used MapStruct version: 1.4.1.FINAL
Used Lombok version: 1.18.12

**Comment by william-hyx** [comment] 2021-01-13 07:54
same problem !

**Comment by kqkdChen** [comment] 2021-01-13 07:56
> same problem !
Waiting for an explanation from the official

**Comment by filiphr** [comment] 2021-01-17 12:57
This is a duplicate of https://github.com/mapstruct/mapstruct/issues/2155.

You can't really update an immutable entry. You have to use the builder in `@MappingTarget` when you want to do updates.

**Closed by filiphr** 2021-01-17 12:57 UTC

**Comment by 92Sam** [comment] 2025-02-11 21:28
Hello, used the following annotation and works for me.

```java
public interface SingleTransferDetailMapper {
    @BeanMapping(builder = @Builder(disableBuilder = true))
    SingleTransferDetail toSingleTransferDetailByProvider(SingleTransfer singleTransfer)

     @AfterMapping
    default void afterMappingToSingleTransferDetail(@MappingTarget SingleTransferDetail target, SingleTransfer singleTransfer){
   }
}
```
