### ISSUE TITLE
String addLine1 not mapped!!

### ISSUE THREAD

**Issue by behradnasehi** [mapstruct/mapstruct#2533] opened 2021-08-03 10:08 UTC
why addLine1 and addLine2 not mapped?

```
@Data
@Builder(toBuilder = true)
@AllArgsConstructor
@NoArgsConstructor
public class ServiceAddress {
    private String addLine1;
    private String addLine2;
    private String city;
    private String state;
    private String country;
    private String zip;
    private String zipCodeExtension;
}

    @Data
    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @Builder(toBuilder = true)
    @NoArgsConstructor
    @AllArgsConstructor
    public class OrderDTO {
    private List<OrderElement> orderElement;

    @Data
    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @Builder(toBuilder = true)
    @NoArgsConstructor
    @AllArgsConstructor
    public static class OrderElement {

        @Override
        public boolean equals(Object o) {
            return o == this;
        }

        private ServiceAddress serviceAddress;

        @Data
        @JsonIgnoreProperties(ignoreUnknown = true)
        @JsonInclude(JsonInclude.Include.NON_NULL)
        @Builder(toBuilder = true)
        @NoArgsConstructor
        @AllArgsConstructor
        public static class ServiceAddress {
            private String addLine1;
            private String addLine2;
            private String city;
            private String state;
            private String country;
            private String zip;
        }
    }
}


@Mapper(componentModel = "spring")
public interface test {
    ServiceAddress toServiceAddress(OrderDTO.OrderElement.ServiceAddress serviceAddress);
}

@Override
    public com.univoip.cip.lib.dao.dto.externalconnector.onebill.ServiceAddress toServiceAddress(ServiceAddress serviceAddress) {
        if ( serviceAddress == null ) {
            return null;
        }

        ServiceAddressBuilder serviceAddress1 = com.univoip.cip.lib.dao.dto.externalconnector.onebill.ServiceAddress.builder();

        serviceAddress1.city( serviceAddress.getCity() );
        serviceAddress1.state( serviceAddress.getState() );
        serviceAddress1.country( serviceAddress.getCountry() );
        serviceAddress1.zip( serviceAddress.getZip() );

        return serviceAddress1.build();
    }
```

**Comment by Zegveld** [comment] 2021-08-09 21:45
I think the reason why they aren't mapped is because the 'addLine1' and 'addLine2' methods from the builder are seen as methods that add something to a collection named 'line1' and 'line2'. If the mapping is done using the getters/setters then the result will be that they are mapped, because these methods will be named 'setAddLine1' and 'setAddLine2'. 

The following methods will currently work for the mapping:
1. Change the names of the fields so they do not start with 'add' followed by an uppercase letter.
2. Tell the mapping to not use the builders, but instead let it use the setters. for example: `\@BeanMapping( builder = \@Builder( disableBuilder = true ))` or at the `\@Mapper( builder = \@Builder( disableBuilder = true ))`.

Would be nice if mapstruct could tell whether the method is an add method or a set method for these coincidental abbreviations.

**Comment by filiphr** [comment] 2021-08-14 09:42
@Zegveld your analysis is spot one. A fluent setter like `Builder addLine1(String line)` is treated as an adder method for MapStruct.

Apart from the 2 options proposed solutions by @Zegveld if you can somehow force the generated method to look like `Builder setAddLine1(String line)` then MapStruct will find that property correctly as well.

I am closing this for now. If someone has an idea for how this can be solved please let us know

**Closed by filiphr** 2021-08-14 09:42 UTC

**Comment by behradnasehi** [comment] 2021-08-14 12:08
@Zegveld @filiphr 
I disable builder and fixed it

**Comment by MazizEsa** [comment] 2023-10-31 14:37
Could always use https://mapstruct.org/documentation/stable/reference/html/#customizing-mappers-using-decorators and do manual mapping on the properties with add.* in the name.

**Comment by savinov** [comment] 2025-02-04 11:59
Another option to solve the problem is to add `setterPrefix = "set"` into the builder annotation.
