### ISSUE TITLE
Map a java.sql.Date to a java.time.LocalDate

### ISSUE THREAD

**Issue by pioto** [mapstruct/mapstruct#1591] opened 2018-08-22 21:30 UTC
When attempting to map a field which, on the source object has type `java.util.Date` but which, when loaded via JPA ends up with a `java.sql.Date` object instance, it seems that MapStruct tries to use the `.toInstant()` method to perform the mapping.

However, this will not work, as `java.sql.Date` always throws an `UnsupportedOperationException`.

The root cause is probably just the poor design of the java.sql.Date class and its friends from an inheritance perspective, but it would be nice if there were some "magic" in MapStruct to handle this conversion, as I expect it isn't that unusual when working with a JPA entity.

A workaround seems to be using an `expression` like:

```java
    @Mapping(
            target = "createdDate",
            expression = "java(((java.sql.Date)(source.getCreated())).toLocalDate())"
    )
```

**Comment by filiphr** [comment] 2018-08-22 21:55
The problem is that MapStruct is an annotation processor which means that it knows only the compilation types and not the runtime types. If you define your type as `java.sql.Date` instead of `java.util.Date` then it should work properly (it will do double conversion, but we accept a PR for `java.sql.Date` into `java.time.LocalDate` 😄).

Another approach would be instead of using an expression to use a [qualifier](http://mapstruct.org/documentation/dev/reference/html/#selection-based-on-qualifiers).

**Comment by pioto** [comment] 2018-08-22 22:01
Yeah, I came across this approach instead, using `@Mapper(uses=SqlDateMapper.class)`, and this bit of code:

```java
public class SqlDateMapper {

    public java.util.Date asDate(LocalDate date) {
        return java.util.Date.from(date.atStartOfDay(ZoneId.systemDefault()).toInstant());
    }

    public LocalDate asLocalDate(java.util.Date date) {
        if (date instanceof java.sql.Date) {
            return ((java.sql.Date) date).toLocalDate();
        } else {
            return LocalDate.from(date.toInstant());
        }
    }

}
```

That's probably the "right" fix for my use case. (Your default conversions also use UTC instead of the local zone, which probably won't quite match up with my business rules' expectations)

**Comment by filiphr** [comment] 2018-09-14 19:01
I've marked this as up-for-grabs in case someone wants to provide a contribution.

**Closed** 2018-10-15 19:41 UTC
Labels: enhancement, good first issue, up-for-grabs
