### ISSUE TITLE
Map a collection with parameter with mapstruct

### ISSUE THREAD

**Issue by TheStijn** [mapstruct/mapstruct#809] opened 2016-05-10 13:45 UTC
http://stackoverflow.com/questions/36399695/map-a-collection-with-parameter-with-mapstruct

To map a certain object with mapstruct I need some custom post processing which needs an additional parameter to do it's work:

@Mapper
public abstract class AlertConfigActionMapper {

```
@Mappings({ @Mapping(target = "label", ignore = true)})
public abstract AlertConfigActionTO map (AlertConfigAction action, Locale userLanguage);

@AfterMapping
public void setLabel (AlertConfigAction  action, @MappingTarget AlertConfigActionTO to, Locale userLanguage) {
    for (AlertConfigActionLabel label : action.getAlertConfigActionLabels()) {
        if (label.getLanguage().equals(userLanguage)) {
            to.setLabel(label.getLabel());
            break;
        } else if (label.getLanguage().equals(Locale.ENGLISH)) {
            to.setLabel(label.getLabel());
        }
    }

}
```

}
This works just fine. The problem starts when I add following method to this mapper:

public abstract ArrayList<AlertConfigActionTO> mapList (List<AlertConfigAction> actions, Locale userLanguage);
I need to pass this parameter (userLanguage) as well but mapstruct seems to 'break down' in this case: I generates following code for this part (which naturally gives a compilation error):

@Override
public List<AlertConfigActionTO> mapList(List<AlertConfigAction> actions, Locale userLanguage) {
    if ( actions == null && userLanguage == null ) {
        return null;
    }

```
List<AlertConfigActionTO> list = new List<AlertConfigActionTO>();

return list;
```

}
I'm sure it is related to the parameter since if I remove it (from all mapping methods) then the mapList method is generated correctly.

What is needed to be done to allow custom parameters in this case?

**Comment by sjaakd** [comment] 2017-02-12 08:18
@TheStijn the upcoming Beta should allow for adding parameters marked with an `@Context` annotation. If you've got time, can you check whether our current snapshot solves your issue?

**Comment by dimw** [comment] 2017-03-03 13:49
@sjaakd, just tried out the ```@Context``` feature from 1.2.0.Beta1 and it works as expected. :thumbsup:

It is probably also reasonable to have some kind of automatic context enrichment when using collection mapping method. In particular, the original collection should be automatically passed to the downstream element conversion method (if a `@Context`-annotated element converter is found):

```
// NOT WORKING EXAMPLE
@Mapper
public interface CarMapper {
    CarDto carToCarDto(Car car, @Context List<Car> cars);
    List<CarDto> carsToCarDtos(List<Car> cars);
}
```

Currently this drawback can be solved by using a helper method, which is not very elegant:
```
@Mapper
public abstract class CarMapper {
    abstract CarDto carToCarDto(Car car, @Context List<Car> cars);
    abstract List<CarDto> carsToCarDtos(List<Car> cars, @Context List<Car> contextCars);
    
    public List<CarDto> carsToCarDtos(List<Car> cars) {
        return carToCarDto(cars, cars);
    }
}
```

**Comment by sjaakd** [comment] 2017-03-03 20:20
IIUC you want MapStruct to automatically generate the helper method for you?

**Comment by dimw** [comment] 2017-03-03 21:17
@sjaakd, MapStruct should not necessarily generate a helper method. Instead, it should make use of the context-aware element conversion method and pass the context. Let me show an example.

**Given:** 
The following interface is defined.
```java
@Mapper
public interface CarMapper {
    CarDto carToCarDto(Car car, @Context List<Car> cars);
    List<CarDto> carsToCarDtos(List<Car> cars);
}
```

**Expected:** 
While processing the collection mapper method
```java
List<CarDto> carsToCarDtos(List<Car> cars);
```
the mapstruct-processor does not complains about the missing element conversion method (which currently happens)
```java
CarDto carToCarDto(Car car);
```
but instead it uses the context-aware element conversion method
```java
CarDto carToCarDto(Car car, @Context List<Car> cars);
```
and passes the input collection `cars` as the context.

The generated code of the collection mapper method should look as following:
```java
List<CarDto> carsToCarDtos(List<Car> cars) {
    if ( cars == null ) {
        return null;
    }

    List<CarDto> list = new ArrayList<CarDto>();
    for ( Car car : cars ) {
        list.add( carToCarDto( car, cars) );
    }

    return list;
}
```

**Comment by sjaakd** [comment] 2017-03-03 22:01
@dimw MapStruct just passes `@Context` as parameter if it finds a method with the same context type and an `@Context` annotated parameter...

So

```java
   CarDto carToCarDto(Car car, @Context List<Car> cars);

    List<CarDto> carsToCarDtos(List<Car> cars, @Context List<Car> contextCars);
```

leads to:

```java
    public CarDto carToCarDto(Car car, List<Car> cars) {
        if ( car == null ) {
            return null;
        }

        CarDto carDto = new CarDto();

        return carDto;
    }

    @Override
    public List<CarDto> carsToCarDtos(List<Car> cars, List<Car> contextCars) {
        if ( cars == null ) {
            return null;
        }

        List<CarDto> list = new ArrayList<CarDto>();
        for ( Car car : cars ) {
            list.add( carToCarDto( car, contextCars ) );
        }

        return list;
    }
```

Interpreting the context parameter is something that MapStruct should never do. By definition it would then not be context anymore to the mapper.  

The typical use case for context is an object that has for instance an id generator, or a locale. You just want to `bring` it through an object graph to a hand written method were you want to use it. Alternatively you could add `@BeforeMapping` in the context and place logic there whenever you call mapping method with a certain signature.

**Comment by dimw** [comment] 2017-03-03 23:19
@sjaakd, thanks for the quick response. I completely agree on your point that MapStruct should never interpret the context. However, it was not my intention to introduce such functionality.

My point is about a half-automatic-MapStruct-way of passing the collection of entities (given in the collection mapper method) down to the entity mapper as a context.

Why do I need this? Well, there are many cases, where you require the underlying collection while mapping a single entity, e.g.:
- to determine position of the entity in the list,
- to use the size of the list,
- to consider the successor and predecessor entities in the list,
- etc.

The possibility of using `@Context` seems to be great for that since now you can pass the the list to a before/after mapper, e.g.:
```java
@AfterMapping
void mapCarDtoIndex(Car car, @MappingTarget CarDto carDto, @Context List<Car> cars) { 
    int index = cars.indexOf(car);
    carDto.setIndex(index);
}
```
However, this only works if all the upstream abstract methods have the context too (as mentioned in your example):
```java
abstract CarDto carToCarDto(Car car, @Context List<Car> cars);
abstract List<CarDto> carsToCarDtos(List<Car> cars, @Context List<Car> cars);
```
Using this style you have to pass cars twice when calling the mapper function ```carsToCarDtos(cars, cars)``` from a consumer, which is some kind of ugly code. For that reason I have introduced the helper method (mentioned in my 1st comment).

Once again, since having the initial collection in the entity mapper is pretty common, the idea was to automatically derive the argument as the context from the `List<CarDto> carsToCarDtos(List<Car> cars)` method. Another option could be introduction of a dedicated annotation, e.g.:
```java
List<CarDto> carsToCarDtos(@PassAsContext List<Car> cars);
```
Sorry for being not clear enough in my previous posts.  I'm OK with the existing workaround if you feel that passing the collections to the entity mappers automatically is out-of-scope of MapStruct.

**Comment by sjaakd** [comment] 2017-03-04 06:41
@dimw, I get your point now. I opened up a new issue for that purpose. Thanks for your explanation.

@TheStijn : can we close this one an mark it as solved?

**Comment by TheStijn** [comment] 2017-04-13 16:39
Hi @sjaakd,

sorry for the late reaction.
I finally had some time to try this out.
It works but not for all cases it seems.
```

@Mapper
public abstract class WidgetMapper {

    @Mappings({
            @Mapping(target = "displayTitle", ignore = true)
    })
    abstract WidgetTO map(Widget widget, @Context String test);
```
This will work nicely but it no longer works when:

`abstract WidgetTO map(Widget widget, @Context Locale locale);`

Exception is not very helpful:

> WidgetMapper.java:[17,17] Internal error in the mapping processor: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for sun.util.resources.OpenListResourceBundle not found

I tried with other types as well (custom, Timezone, ...) and for now it only fails with the class Locale.

Apart from this issue (which I can have a workaround for) it is working very nice.

Looking forward to the next final version; any idea when we might expect that?

Sincerely,
Stijn

**Comment by agudian** [comment] 2017-04-13 17:16
@TheStijn that's very unexpected... could you please open a new issue with the full stack trace and if possible a minimal example mapper that reproduces the error?

**Comment by filiphr** [comment] 2017-06-28 20:36
@TheStijn Without looking at the entire Stacktrace we can't really know what the problem is. It might be interaction with Lombok or something from an `AccessorNamingStrategy`. I will close this issue, can you create a new one if the problem with the `@Context Locale` still occurs?

**Closed by filiphr** 2017-06-28 20:36 UTC
