### ISSUE TITLE
InheritConfiguration annotation not working 

### ISSUE THREAD

**Issue by 1483523635** [mapstruct/mapstruct#1720] opened 2019-02-15 04:07 UTC
- [ ] Is this an issue (and hence not a question)? 
YES !!!!

When I using `@InheritConfiguration` I found this not working   
 Here is recurring step
Prepare an entity `HomeEntity`
```java
public class HomeEntity {
   private String name;
   private Address address;
    // pure get set 
   //  ...
}
public class Address {
    private String detail;
   // pure get set 
   // ...
}
```
Prepare a dto `HomeDto`
```java
public class HomeDto {
   private String name;
   private String addressDetail;
   // pure get set 
}
```
Here is Maper Interface `HomeMapper`
```java
@Mapper
public interface HomeMapper {

    HomeMapper INSTANCE = Mappers.getMapper(HomeMapper.class);

    @Mapping(target = "addressDetail", source = "homeEntity.address.detail")
    HomeDto toDto(HomeEntity homeEntity);

    @InheritConfiguration(name = "toDto")
    HomeDto toDtoWithName(HomeEntity homeEntity, String name);

}
```
Here is the generated code 
```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2019-02-15T11:47:44+0800",
    comments = "version: 1.3.0.Final, compiler: javac, environment: Java 1.8.0_181 (Oracle Corporation)"
)
public class HomeMapperImpl implements HomeMapper {

    @Override
    public HomeDto toDto(HomeEntity homeEntity) {
        if ( homeEntity == null ) {
            return null;
        }

        HomeDto homeDto = new HomeDto();

        homeDto.setAddressDetail( homeEntityAddressDetail( homeEntity ) );
        homeDto.setName( homeEntity.getName() );

        return homeDto;
    }

    @Override
    public HomeDto toDtoWithName(HomeEntity homeEntity, String name) {
        if ( homeEntity == null && name == null ) {
            return null;
        }

        HomeDto homeDto = new HomeDto();

        if ( homeEntity != null ) {
            homeDto.setName( homeEntity.getName() );
        }

        return homeDto;
    }

    private String homeEntityAddressDetail(HomeEntity homeEntity) {
        if ( homeEntity == null ) {
            return null;
        }
        Address address = homeEntity.getAddress();
        if ( address == null ) {
            return null;
        }
        String detail = address.getDetail();
        if ( detail == null ) {
            return null;
        }
        return detail;
    }
}

```
Apparently the InheritConfiguration annotation not working !!!

Here is my Gradlew file 
```groovy
plugins {
    id 'java'
    id 'net.ltgt.apt' version '0.15'
}

apply plugin: 'net.ltgt.apt-idea'
apply plugin: 'net.ltgt.apt-eclipse'

group 'com.test'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile 'org.mapstruct:mapstruct:1.3.0.Final'

    annotationProcessor 'org.mapstruct:mapstruct-processor:1.3.0.Final'
    testAnnotationProcessor 'org.mapstruct:mapstruct-processor:1.3.0.Final' 
}
```
How to fix this

**Comment by sjaakd** [comment] 2019-02-15 06:31
I guess the signature of the method is different..

**Comment by sjaakd** [comment] 2019-02-19 19:26
So.. I can confirm my statement above.. All source parameters need to be the same. Checkout chapter 11.1 of our [reference](http://mapstruct.org/documentation/dev/reference/pdf/mapstruct-reference-guide.pdf) guide:

`One method A can inherit the configuration from another method B if all types of A (source types and result type) are assignable to the corresponding types of B.` 

Going to close this, since it works as described. As a tip: why don't you use a default method and call the other method, like this:

```java
@Mapper
public interface HomeMapper {
    HomeMapper INSTANCE = Mappers.getMapper(HomeMapper.class);
    
    default HomeDto toDtoWithName(HomeEntity homeEntity, String name) {
        HomeDto homeDto = toDto( homeEntity );
        homeDto.setName( name );
        return homeDto;
    }
    
    @Mapping(target = "addressDetail", source = "homeEntity.address.detail")
    HomeDto toDto(HomeEntity homeEntity);
}
```

**Closed by sjaakd** 2019-02-19 19:26 UTC

**Comment by mayras** [comment] 2019-06-09 07:08
"One method A can inherit the configuration from another method B if all types of A (source types and result type) are assignable to the corresponding types of B."
It's really bad point, I have same source types for both methods, but different targets with same base class, how can it be fixed? I believe - it's possible to write solution for this type of situations and it's very important, we have big team and everyone is really sad about that.

**Comment by filiphr** [comment] 2019-06-10 09:30
> I have same source types for both methods, but different targets with same base class, how can it be fixed?

@mayras how is this related to this issue? Looking at it you have different source types. One method has `HomeEntity` and the other one has `HomeEntity` and `String` as source types.


> I believe - it's possible to write solution for this type of situations and it's very important, we have big team and everyone is really sad about that.

As @sjaakd mentioned it works as designed. In case you have some different expectations or you think that it is easy to adapt you can provide a PR with the solution

**Comment by mayras** [comment] 2019-06-10 10:27
@filiphr, it's not question how it's mentioned about designed, it's question about cases which are very realistic and it happens very often, I can create another issue, no problem, but copy of annotations is very important point over class inheritence, but, sorry, you cut it by design ...

**Comment by filiphr** [comment] 2019-06-10 10:32
@mayras sorry but I am not following you. What do you mean with copy of annotations? This issue was about `@InheritConfiguration` not working

**Comment by mayras** [comment] 2019-06-10 10:59
InheritConfiguration should work for different arguments in scope of class inheritance, it's very important for a lot of projects, believe me.

**Comment by filiphr** [comment] 2019-06-10 12:46
OK now I get it, you are looking for the `@InheritConfiguration` to be applied even when the source types do not match, i.e. applied partially to the types that do match.

Currently, we are focused on other issues and I don't see someone from the MapStruct team working on it. If you are interested in providing a PR for this functionality we can review it and guide you.

>it's very important for a lot of projects, believe me.

It is not a matter of believing you or not. I understand that it might be really important to your project. However, we haven't heard about such request before you mentioned it.

**Comment by sjaakd** [comment] 2019-06-10 20:00
I guess its a duplicate of [this](https://github.com/mapstruct/mapstruct/issues/807) one.
