### ISSUE TITLE
Possibility to map immutable objects using AllArgsConstructors

### ISSUE THREAD

**Issue by eximius313** [mapstruct/mapstruct#1589] opened 2018-08-21 17:55 UTC
I see that version `1.3.0` of Mapstruct focuses on immutable objects, wich is great. 
Unfortunately, currently only builders are supported. 
But what about objects that have all-argument constructors (or created by Lombok's `@AllArgsConstructors`) ? Can you please support that?

**Comment by sjaakd** [comment] 2018-08-21 18:04
duplicate of #73

**Closed by sjaakd** 2018-08-21 18:04 UTC
Labels: duplicate

**Comment by filiphr** [comment] 2018-08-21 18:09
@eximius313 this is also one big requested feature of MapStruct. This release we tackled the builder support and hopefully we can tackle the constructor support in the release after 1.3 😄

**Comment by eximius313** [comment] 2018-08-21 18:10
@filiphr, thank you for the information ;)
