### ISSUE TITLE
MapStruct takes random repository method to map a long field

### ISSUE THREAD

**Issue by simasch** [mapstruct/mapstruct#3536] opened 2024-02-21 14:08 UTC
### Steps to reproduce the problem

I have this mapping:

```
@Mapper(componentModel = "spring", uses = {
  ClubContestRegistrationRepository.class,
  DisciplineRepository.class,
  ClubContestRegistrationMapper.class,
  DisciplineMapper.class
})
public interface ClubContestDisciplineRegistrationMapper {
  @IgnoreAutoMappedMembers()
  @Mapping(source = "clubContestRegistrationId", target = "clubContestRegistration", qualifiedBy = MapAsReference.class)
  @Mapping(source = "disciplineId", target = "discipline", qualifiedBy = MapAsReference.class)
  void updateEntity(ClubContestDisciplineRegistrationCreateUpdateDto dto, @MappingTarget ClubContestDisciplineRegistrationEntity entity);

  @Mapping(target = "clubContestRegistrationId", source = "clubContestRegistration.id")
  ClubContestDisciplineRegistrationDto toDto(ClubContestDisciplineRegistrationEntity entity);
}
```

If my repository has a count method that returns a Long (or any other method that returns a long) the generated code looks like this:

```
    @Override
    public ClubContestDisciplineRegistrationDto toDto(ClubContestDisciplineRegistrationEntity entity) {
        if ( entity == null ) {
            return null;
        }

        Long clubContestRegistrationId = null;
        Long id = null;
        Long version = null;
        Integer part = null;
        DisciplineDto discipline = null;
        Integer sumAthleteMale = null;
        Integer sumAthleteFemale = null;

        clubContestRegistrationId = clubContestRegistrationRepository.countBySquadId( entityClubContestRegistrationId( entity ) );
        id = clubContestRegistrationRepository.countBySquadId( entity.getId() );
        version = clubContestRegistrationRepository.countBySquadId( entity.getVersion() );
        part = entity.getPart();
        discipline = disciplineMapper.toDto( entity.getDiscipline() );
        sumAthleteMale = entity.getSumAthleteMale();
        sumAthleteFemale = entity.getSumAthleteFemale();

        ClubContestDisciplineRegistrationDto clubContestDisciplineRegistrationDto = new ClubContestDisciplineRegistrationDto( id, version, part, clubContestRegistrationId, discipline, sumAthleteMale, sumAthleteFemale );

        return clubContestDisciplineRegistrationDto;
    }
```

When I remove the count method everything works fine

### MapStruct Version

1.5.2

**Comment by Zegveld** [comment] 2024-02-22 14:33
This is not a bug but expected behavior.

You've listed `clubContestRegistrationRepository` as an uses class.
Mapstruct expects that it should use methods listed here whenever possible for mapping actions.
For example a method with the signature `Long methodName(Long argument)` will be used for mapping `Long` to `Long`.
If a method is annotated with `@org.mapstruct.Named` then it is ignored unless specifically mentioned that it should be used.

My suggestion is to either annotate the method mapstruct should not use with `@Named("Do not use for mapping")` or if you need it for a specific mapping as listed in [the qualifier documentation](https://mapstruct.org/documentation/stable/reference/html/#selection-based-on-qualifiers).

Closing as this is not a bug.

**Closed by Zegveld** 2024-02-22 14:33 UTC
Labels: bug
