### ISSUE TITLE
Source / Destination with same Class name but different packages fails

### ISSUE THREAD

**Issue by ahararwala** [mapstruct/mapstruct#1187] opened 2017-04-25 14:27 UTC
In version 1.1.0.Final, the mappings are generated incorrectly in this situation.

Appears to be a regression: previous issue found here https://github.com/mapstruct/mapstruct/issues/394

**Comment by filiphr** [comment] 2017-04-25 16:05
@ahararwala I don't think that it is the same problem. We have this [test](https://github.com/mapstruct/mapstruct/tree/master/processor/src/test/java/org/mapstruct/ap/test/bugs/_394) for it, that is why I think that it might be something else.

Do you have generics perhaps? Can you also try the latest 1.2.0.Beta2? Can you perhaps show us a small reproducible example, so we can pin point the problem?

Thanks :)

**Comment by ahararwala** [comment] 2017-04-25 20:25
I was able to reproduce the error in the mapstruct-examples git repo. Please review my fork at:
https://github.com/ahararwala/mapstruct-examples.git

Note that we are currently using Java 7 with mapstruct version 1.1.0.Final version.

Also I tested the mapstruct-examples with the latest beta version and Java 8 and all the tests were passing. So it looks like the bug could be specific to java 7 and version 1.1.0.Final.

Thanks,

**Comment by filiphr** [comment] 2017-04-25 21:15
@ahararwala Thanks a lot for the reproducer. I'll have a look and get back to you. There are 47 closed issues in Beta1 and 16 in Beta2 most probably it is solved in one of those. In any case I'll let you know with more information in the next days

**Comment by filiphr** [comment] 2017-04-25 21:28
@ahararwala I just checked it out. There are multiple issues with your changes:

* [mapstruct-mapping-with-cycles](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-mapping-with-cycles) must use 1.2.0.Beta2 because it uses the new `@Context`
* [mapstruct-nested-bean-mappings](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-nested-bean-mappings) must also use 1.2.0.Beta2 because it uses the new possibility of MapStruct to automatically generate sub-mapping methods
* The change in [FishTankMapper#L45](https://github.com/ahararwala/mapstruct-examples/blob/master/mapstruct-nested-bean-mappings/src/main/java/org/mapstruct/example/mapper/FishTankMapper.java#L45) is wrong it should be `FishTank map(org.mapstruct.example.model.FishTank source);`

With the changes that I said everything passes without problems. I am using JDK 1.8 though, but I didn't change the java version in the pom.

Can you maybe send us the error messages that are displayed on your side?

**Comment by ahararwala** [comment] 2017-04-27 17:36
We don't get any errors but the generated files contains compile errors.
Appears that the processor is incorrectly mapping the files in the wrong class and therefore does not produce any errors.

**Comment by filiphr** [comment] 2017-04-27 18:40
@ahararwala that is still a problem in our processor, can you please create some reproducer (the changes in the examples repo that you created are invalid, as the minimum requirements mentioned in previous comment must be satisfied). We would like to help you out with the problem, but without a reproducing example we can't do more, sorry.

**Comment by filiphr** [comment] 2017-07-02 11:13
@ahararwala without more feedback we can't act on this one. Therefore, we are going to close it. If you have more info please share and we'll reopen it.

**Closed by filiphr** 2017-07-02 11:13 UTC
