### ISSUE TITLE
MapStruct failed when using target this" annotation "." with several source parameters

### ISSUE THREAD

**Issue by fahmibedoui** [mapstruct/mapstruct#2430] opened 2021-05-05 14:25 UTC
- [ ] Is this an issue (and hence not a question)? 

If this is a question how to use MapStruct there are several resources available.
- Our reference- and API [documentation](http://mapstruct.org/documentation/reference-guide/).
- Our [examples](https://github.com/mapstruct/mapstruct-examples) repository (contributions always welcome)
- Our [FAQ](http://mapstruct.org/faq/)
- [StackOverflow](https://stackoverflow.com), tag MapStruct 
- [Gitter](https://gitter.im/mapstruct/mapstruct-users) (you usually get fast feedback)
- Our [google group](https://groups.google.com/forum/#!forum/mapstruct-users)

**Comment by filiphr** [comment] 2021-05-05 14:30
This is a duplicate of #2402, which has already been fixed.

**Closed by filiphr** 2021-05-05 14:30 UTC

**Comment by fahmibedoui** [comment] 2021-05-05 14:31
Here is an illustration of the example which gives a compilation error:
TestMapper.java:24: error: Method has no source parameter named "otherData". Method source parameters are: "a, b".

    @SuperBuilder
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public abstract class AbstractA {
        	private UUID id;
	        private Integer field1;
	        private AData otherData = new AData();
	
	        @Builder
	        @NoArgsConstructor
	        @AllArgsConstructor
	        @Data
	        public static class AData {
	        	private String paramX1;
	        	private String paramX2;
            }
    }

    @Builder
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public class B {
        private UUID id;
        private String field2;
        @Builder.Default
        private BData otherData = new BData();

        @Builder
        @NoArgsConstructor
        @AllArgsConstructor
        @Data
        public static class BData {
            private String field3;
            private String field4;
        }
    }

    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
    @SuppressWarnings("squid:S1214")
    public interface TestMapper {
        TestMapper INSTANCE = Mappers.getMapper(TestMapper.class);
        BiFunction<AbstractA, B, C> A_AND_B_TO_C = (a, b) -> INSTANCE.aAndBToC(a, b);

        @Mapping(target = ".", source = "a.otherData")
        @Mapping(target = "id", source = "a.id")
        C aAndBToC(AbstractA a, B b);            

    }

**Comment by filiphr** [comment] 2021-05-15 11:29
Did you try the 1.5.0-SNAPSHOT version of MapStruct?
