### ISSUE TITLE
Subclass mapping Question

### ISSUE THREAD

**Issue by CANBAAA** [mapstruct/mapstruct#3156] opened 2023-02-13 09:44 UTC
### Steps to reproduce the problem

```java
@Data
public class Animal {
    private String name;
}
```
Source:
```java
@Data
@EqualsAndHashCode(callSuper = true)
public class Cat extends Animal{
     private String race;
}
```
**Entity**:
```java
@Data
public class TargetAnimal {
     private String name;
     private String race;
}
```
**Mapper**:
```java
@Mapper(componentModel = "spring")
public interface OneConverter {
    @SubclassMapping(target = TargetAnimal.class, source = Cat.class)
    TargetAnimal map(Animal source);
}
```
**Test**:
```java
    @Test
    void fileTest() {
        Cat cat = new Cat();
        cat.setName("cat");
        cat.setRace("race");
        TargetAnimal map = oneConverter.map(cat);
        System.out.println("map = " + map);
    }
```

**expected:  "map = TargetAnimal(name=cat, race=race)"**

**but:   java: No target bean properties found: can't map SubclassMapping for  "Cat cat" to "TargetAnimal targetAnimal". Consider to declare/implement a mapping method: "TargetAnimal map(Cat value)".**

### MapStruct Version

MapSruct 1.5.3Final

**Comment by CANBAAA** [comment] 2023-02-13 10:03
And i changed my Converter to this:
```
@Mapper(componentModel = "spring")
public interface OneConverter {
    @SubclassMapping(source = Cat.class, target = Animal.class)
    TargetAnimal map(Animal source);
}
```
and it told **java: Class 'com.tencent.wecoding.vo.TargetAnimal' is not a subclass of 'com.tencent.wecoding.vo.Animal'.**
how to mapper this inheritance class, sorry for my poor english, thx!

**Comment by Zegveld** [comment] 2023-02-15 19:37
I think the problem might lie with combining mapstruct and lombok. It could be that mapstruct is not detecting the properties for the classes because lombok has not done it's job before mapstruct takes it turn. 
[See the documentation here for more information.](https://mapstruct.org/documentation/stable/reference/html/#lombok)

**Comment by thunderhook** [comment] 2023-02-22 21:18
@Zegveld is right, I tried to reproduce this. With the maven configuration provided in the documentation, the mapping works.
(besides that `race` will not be mapped, because it is not defined how to be mapped)

**Comment by filiphr** [comment] 2023-04-15 15:02
Thanks @Zegveld and @thunderhook. I am going to close this as it cannot be reproduced

**Closed by filiphr** 2023-04-15 15:02 UTC
Labels: bug
