### ISSUE TITLE
Can I config @Builder#disableBuilder globally?

### ISSUE THREAD

**Issue by udoless** [mapstruct/mapstruct#2676] opened 2021-11-26 09:40 UTC
- [x] Is this an issue (and hence not a question)? 
hence

I  am using lombok in my project, but I don't want mapstruct to use builder. So can I config @Builder#disableBuilder globally?

**Comment by filiphr** [comment] 2022-01-30 14:36
Closing this as a duplicate of #1661

**Closed by filiphr** 2022-01-30 14:36 UTC
