### ISSUE TITLE
Improvement: @Generated annotation to mark code that should be ignored by JaCoCo

### ISSUE THREAD

**Issue by empovit** [mapstruct/mapstruct#1528] opened 2018-06-18 15:33 UTC
It would be nice to have an annotation with CLASS retention policy that can be ignored by code coverage tools like [JaCoCo](https://www.jacoco.org/jacoco/). This should work similar to how it's done for [Immutables](https://github.com/jacoco/jacoco/issues/656) and [Lombok](https://github.com/jacoco/jacoco/pull/495).

**Comment by sjaakd** [comment] 2018-06-18 15:38
Is there any annotation that you have in mind?  My setup is such that generated code is in `target\generated-source`.. (not subjected to code-coverage analysis)  How would `JaCoCo` determine coverage on an annotation like `@Generated`? Isn't this a problem of `JaCoCo`

**Comment by empovit** [comment] 2018-06-18 15:53
You need a brand new annotation for that. Ignoring _all_ of the generated code is not good enough because there may be custom mappings that you do want to test. 
It is a problem of both JaCoCo and Mapstruct. If you follow the links I've provided, you can see that it is possible to open an issue for JaCoCo team and ask them to ignore code annotated by Mapstruct. However, you need a suitable annotation in the first place.

**Comment by sjaakd** [comment] 2018-06-23 10:18
Still it feels strange: each code generator should fix a problem that seems to originate somewhere else. For code originating from Lombok I can see a point: it replaces your own class definition (and is doing something that is not intended by JSR-269). In my own code this is solved by some reflective testing of getters and setters in a package (a `TestAllDto`) marker test case will do the trick..


> Ignoring all of the generated code is not good enough because there may be custom mappings that you do want to test.

Custom mappings are in your `src\main\java\` right? A technique would be to inherit from that class yourself (if the mapper is abstract) and cover it with unit test. As for coverage on generated sources: you have a choice. Do - or don't do unit testing on those. Personally I prefer ' do' .

**Comment by akayoshi29** [comment] 2019-07-09 18:41
I would like to have this feature too : ignoring generated code. It can be useful when your project requires a minimum test coverage rate.
> How would JaCoCo determine coverage on an annotation like @Generated?
Jacoco is based on compiled classes. So, we need a mapstruct generated annotation in mapstruct compiled class and then, Jacoco can ignore class with this annotation.

**Comment by bockd** [comment] 2019-07-23 11:05
I agree with @akayoshi29 that it would be nice to be able to ignore the generated code so that it will not affect the code coverage of our project.

**Comment by s4sushilk** [comment] 2019-12-12 08:45
Is this implemented ? Status is still open.
I am trying to find out a way to exclude the mapstruct generated files from jacoco coverage.

**Comment by sjaakd** [comment] 2019-12-12 22:47
> Is this implemented ? Status is still open.

yes.. And going to close this one. It would actually make sense to write some basic unit test.



> I am trying to find out a way to exclude the mapstruct generated files from jacoco coverage.

`target/generated-sources/` I guess is excluded from coverage.

**Comment by OneHalf3544** [comment] 2019-12-26 08:58
> target/generated-sources/ I guess is excluded from coverage.

JaCoCo checks compiled classes. It cannot exclude source directories. For the same reason, JaCoCo cannot exclude classes annotated with  `@Retention(SOURCE) @interface @Generated`.

**Comment by sjaakd** [comment] 2019-12-26 20:08
I'll reopen the issue.  I guess my second argument still stands:

>It would actually make sense to write some basic unit test.

MapStruct is not the same as `autoValue` or `Lombok`.  There are many options that interplay, especially when combined with hand-written-methods and it is possible to create unwanted behaviour. So unit testing still makes sense.

What we could do is add an processor option to use our own `Generated` (retention class) annotation, which I believe will be recognised by Jacoco (reading the documentation).  

@filiphr : WDYT?

**Comment by akayoshi29** [comment] 2019-12-27 14:23
@sjaakd I agree with you. Some basic unit tests are still necessary to check the hand-written mapping is good but not all the generated class (all the null checking for example). 
The Generated annotation will be nice. I believe Jacoco can recognize it automatically too. If not, we could ask them to do it.

**Comment by MarianoLEANCE** [comment] 2020-06-06 02:14
As [said by Godin](https://github.com/jacoco/jacoco/issues/831#issuecomment-455251626) the problem is the retention policy of the `@Generated` annotation.

In order for JaCoCo to correctly ignore mapstruct's generated code an annotation with runtime retention policy is needed.

**Comment by mmalygin** [comment] 2021-08-12 11:50
The javax.annotation.Generated annotation used by mapstruct has retention policy SOURCE which means the annotation will be removed from .class files and Jacoco will not be able to detect it. 
As solutuion, another annotation with retention policy CLASS or RUNTIME is required. the CLASS is preferred because it will be stored in .class files but will not be loaded to memory in runtime. See lombok.Generated for example. As I know Jacoco checks for annotations which contain "Generated" substring in its name. 
Another option is to add an option to mapstruct config that will allow us to add a custom annotations to generated classes. In this case I can configure mapstruct to add lombok.Generated to all generated classes and Jacoco will skip them in coverage report.

**Comment by filiphr** [comment] 2021-08-14 10:41
>Another option is to add an option to mapstruct config that will allow us to add a custom annotations to generated classes. In this case I can configure mapstruct to add lombok.Generated to all generated classes and Jacoco will skip them in coverage report.

There is currently an open request for this. Have a look at #1574.

>What we could do is add an processor option to use our own Generated (retention class) annotation, which I believe will be recognised by Jacoco (reading the documentation).

@sjaakd I missed your question. I believe that doing #1574 is the way forward for this. If people can add whatever they want they can add their own `@Generated` annotation with the correct retention.

>Some basic unit tests are still necessary to check the hand-written mapping is good but not all the generated class (all the null checking for example).

I do not agree that only hand-written mapping should be tested. You can influence the way the mapping is done by different properties on `@Mapper`, `@BeanMapping`, `@Mapping`, using nested source mapping, nested target mapping, etc. All of that should be properly tested if you ask me.

One other approach for ignoring code is if you instruct MapStruct to put the code in a special package and you tell JaCoCo to ignore that.

@sjaakd I am keen on closing this one

**Comment by ChrTall** [comment] 2021-12-12 17:41
@sjaakd 
When you have Dtos that have javax Anntotations such as @NotNull for fields you do not have to write unit tests that cover the Null Checks in the Validator, because you won´t have null fields.
I agree that you should test the mappers, but in such situations it would be better if you could exclude it from jacoco. Are there any updates on when this feature is implemented?

**Comment by Zegveld** [comment] 2022-11-17 17:49
@filiphr, @sjaakd
Do you think that this one is now covered with the upcoming 1.6.0 where `@AnnotateWith` #1574 has been introduced?

**Comment by filiphr** [comment] 2022-11-20 11:37
You are right @Zegveld this one is now covered by the work we did for #1574. If someone wants to use a custom `@Generated` annotation they can do it by using `@AnnotateWith( com.example.Generated.class )`.

Therefore, I am going to close this one

**Closed by filiphr** 2022-11-20 11:37 UTC
Labels: feature, for:team-discussion

**Comment by hamedheidarian** [comment] 2023-02-25 19:07
Hi, It seems there is no @AnnotateWith in the most recent version. How can we solve this problem now?

**Comment by maroodb** [comment] 2026-07-03 12:48
Hi,

Sorry to revive this thread.

Using `@AnnotateWith(com.example.Generated.class)` works, but it introduces unnecessary verbosity. It would be even better if there were a global configuration option that allowed users to specify a custom annotation once, rather than having to add `@AnnotateWith` everywhere.
