### ISSUE TITLE
@InheritInverseConfiguration and @Mapping(target:"bean.childProperty", ignore=true) do not play together

### ISSUE THREAD

**Issue by neowin35** [mapstruct/mapstruct#2278] opened 2020-11-16 15:35 UTC
```java
public interface CarMapper {
    class Details {
        public String brand;
        public String model;
    }
    class DetailsDTO {
        public String brand;
    }
    class Car {
        public Details details;
    }
    class CarDTO {
       public DetailsDTO detailsDTO;
    }

    @Mapping(target = "detailsDTO", source = "details")
    CarDTO map(Car in);

    @InheritInverseConfiguration
    @Mapping(target = "details.model", ignore = true)
    Car map(CarDTO in);
}
```

This example mapper results at 1.3.1.Final to this code to be generatedfor the BrandDTO -> Brand mapping:
```java
protected Details detailsDTOToDetails(DetailsDTO detailsDTO) {
        if ( detailsDTO == null ) {
            return null;
        }
        Details details = new Details();
        details.brand = detailsDTO.brand;

        return details;
    }
```
However after upgrading to 1.4.1.Final this is what gets generated: 
```java
protected Details carDTOToDetails(CarDTO carDTO) {
        if ( carDTO == null ) {
            return null;
        }
        Details details = new Details();

        return details;
    }
```

For some strange reason mapstruct is now trying to map CarDTO to Details. In case I specify the full path to the property to ignore like `in.details.model` than it seems to work. Is that an intentional change or just a regression issue?

**Comment by neowin35** [comment] 2020-12-11 10:41
@filiphr any idea about this?

**Comment by filiphr** [comment] 2020-12-11 20:34
We'll need to investigate a bit more about this. Thanks for reporting it. I'll put it on 1.4.2 so we can have a look at it.

**Comment by filiphr** [comment] 2020-12-14 22:57
@sjaakd the cause of this issue is the fix of https://github.com/mapstruct/mapstruct/issues/2101. Maybe you can have a look at it, I can't seem to understand why exactly it is not working

**Comment by filiphr** [comment] 2021-01-30 08:40
Fixed in https://github.com/mapstruct/mapstruct/pull/2332

**Closed by filiphr** 2021-01-30 08:40 UTC
Labels: bug
