### ISSUE TITLE
Ambiguous Mapping Migration Issues from CR1 to CR2/Final

### ISSUE THREAD

**Issue by zcanann** [mapstruct/mapstruct#1003] opened 2016-12-20 02:37 UTC
MapStruct appears to have lost the ability to automatically resolve the correct setter function when there are multiple of the same name. This is happening for me when mapping to Protobuf generated classes with Builder setter functions. These have the unfortunate habit of violating POJO conventions, and cannot be annotated because they are generated.

In this example, we map a BillingAddress POJO to a generated Protobuf Address.Builder class.

In the Protobuf file (simplified), we have a conflict on setAddress:
```
void setAddress(Address value){
    this.address = value;
}
void setAddress(AddressBuilder builderForValue){
    this.address = builderForValue.build();
}
```

Our code (simplified):
```
@Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, componentModel = "spring",
    nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
    uses = {BuilderFactory.class, MyMappingFunctions.class})
public interface MyMapping {

  @Mappings({

      ... field mappings ...

  })
  @Named("mapAddress")
  Address.Builder mapAddress(BillingAddress billingAddress);

  @Mappings({

      @Mapping(source = "input.billingAddress", target = "address",
          qualifiedByName = "mapAddress"),

  })
  @Named("mapCustomer")
  public PersonalDetails.Builder mapCustomer(
      Input input);
}
```

I was able to workaround this by overriding `isSetterMethod` in the SPI and explicitly returning false for the function that I did not want, and true for the builder function. It is unclear why this cannot be resolved automatically. `mapAddress` operates exclusively on the `Address.Builder` class.

**Comment by filiphr** [comment] 2016-12-20 18:34
@zcanann In CR1 it was working by chance for you. If the order of the `setAddress` methods was different you would have had the same problem.

The "breaking" change is due to #892 and the PR #942. There was already some discussion in the PR.

@agudian, @gunnarmorling the problem is that we do not consider the `setAddress(AddressBuilder builderForValue)` as a candidate write Accessor because the `preferedType` is `Address`. I think we need quite a lot of refactoring to support something like in the case of @zcanann.

**Comment by gunnarmorling** [comment] 2016-12-20 18:46
I'm still missing a piece. Could you post the mapped source types, too? And which error do you get specfically? Maybe you could even provide a small yet complete sample project for reproducing this? Thanks!

**Comment by filiphr** [comment] 2016-12-20 19:13
@gunnarmorling I created a small reproducible gist [here] (https://gist.github.com/filiphr/91e09c3ff668c6d0411108b6c7c40c5a). @zcanann is the gist correct? By the way with 1.2.0-SNAPSHOT it will compile due to the new #60. With 1.1.0.Final it fails with: 

> ERROR MyMapping.java:36 Can't map property "xxx.BillingAddress billingAddress" to "xxx.Address address". Consider to declare/implement a mapping method: "xxx.Address map(xxx.BillingAddress value)

@zcanann in order to avoid the problem as a workaround you can provide something like:

```java
protected Address mapFromBuilder(Address.Builder builder) {
        return builder == null ? null : builder.build();
    }
```

If your builders are generic, you can add a generic method and it should work.

**Comment by zcanann** [comment] 2016-12-20 20:27
Yeah @filiphr, I this accurately captures the essence of the problem.

I tested the work around you provided -- it works like a charm. This solution is much more simple than overriding functionality with the SPI. Thank you.

**Comment by gunnarmorling** [comment] 2016-12-20 21:04
@filiphr How do you envision to solve this? I don't think we can sensibly "guess" which `setAddress()` to call, so I think we'd have to raise an `AmbiguityException` by default and provide a way to specify the target type in this case (`@Mapping#targetType()` or something similar).

**Comment by gunnarmorling** [comment] 2016-12-20 21:10
Btw. on ProtoBuf support in general, there is issue #743. There may be some more things to consider in order to fully support it.

**Comment by filiphr** [comment] 2016-12-20 22:07
@zcanann great that it works 😄. Just one question did you remove the `qualifiedByName = "mapAddress"` or it worked with that one?

@gunnarmorling In this case we could have guessed the correct `setAddress()`. Imagine that we have 2 setter:
```java
setAddress(Address value)
setAddress(Address.Builder builder)
```

There is no mapping method for the first. However, there is one mapping method for the second one. Therefore there is no ambiquity and we use the mapping that we found (also in this case `qualifedByName` was used). 

There are multiple ways to "guess" which write accessor to use:
* We do some ranking based on what was used `resolveViaMethod` > `direct assignment` > `resolveViaConversion` > ... > `resolveViaMethodAndConversion`. If there are 2 possible assignments based with the same "rank" we raise an `AmbiguityException`, otherwise we pick the one with the higher "rank"
* If `qualifiedBy` is used then we use the mapping that corresponds to that one
* If there is more than 1 possible assignment we raise an `AmbiguityException`

In any case with whatever we decide or even if we decide to support this. We would need to do some refactorings, because right now the decision, which write accessor to use is done at the beggining of the mapping. We would need to provide all the possible write accessors (of course incorporate the Collection strategies that we have) and then later one decide which one we can to use.

**Comment by zcanann** [comment] 2016-12-20 22:20
@filiphr I kept the `qualifiedByName = "mapAddress"` and it worked

**Comment by filiphr** [comment] 2017-03-17 23:39
@zcanann we have a pending PR #1136 which I think is the same problem you were experiencing. Can you please try it out with your example and without the workaround? Thanks

**Comment by zcanann** [comment] 2017-04-18 20:23
@filiphr I actually no longer have access to the source code of the project that I had been working on, so I won't be able to test this out in the original scenario. I assume this is at least functioning for the gist you created? If so, then the solution is likely sufficient.

**Comment by thunderhook** [comment] 2023-09-20 21:13
@filiphr I think we can close this one, right?

**Comment by filiphr** [comment] 2023-09-30 09:02
You are right @thunderhook. Closing it now

**Closed by filiphr** 2023-09-30 09:02 UTC
