### ISSUE TITLE
Mapstruct + lombock failed compilation

### ISSUE THREAD

**Issue by alexis-puska** [mapstruct/mapstruct#1361] opened 2017-12-22 15:31 UTC
Hi all, 
Since the 1.2 Final, MapStruct can be used with Lombok out of the box. But i found a bug.

the class : 
@Entity
public class Variable implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    private Long id;
    private String cle;
    private String valeur;

    @ManyToOne
    private FicheDePoste ficheDePoste;

   //Getter Setter
}

the DTO (lombock annotation inside)
@Data
public class VariableDTO implements Serializable {
    private static final long serialVersionUID = 1466956427135915190L;
    private Long id;
    private String cle;
    private String valeur;
    private Long ficheDePosteId;
}

The mapper

@Mapper(componentModel = "spring", uses = {FicheDePosteMapper.class, })
public interface VariableMapper extends EntityMapper <VariableDTO, Variable> {

    @Mapping(source = "ficheDePoste.id", target = "ficheDePosteId")
    VariableDTO toDto(Variable variable); 

    @Mapping(source = "ficheDePosteId", target = "ficheDePoste")
    Variable toEntity(VariableDTO variableDTO); 
    
    default Variable fromId(Long id) {
        if (id == null) {
            return null;
        }
        Variable variable = new Variable();
        variable.setId(id);
        return variable;
    }
}

When in the DTO i create with eclipse generation the setter and getter, i have no problem. When i create getter setter with lombok annotation, in maven Compile state, i get this error : 

[ERROR] service/mapper/VariableMapper.java:[14,5] Unknown property "ficheDePosteId" in result type com.valorecia.gpec.service.dto.VariableDTO. D
id you mean "null"?
[ERROR] service/mapper/VariableMapper.java:[17,5] No property named "ficheDePosteId" exists in source parameter(s). Did you mean "null"?

I think the @Mapping annotation cannot found the lombok setter/getter.

Can someone look inside the code ? 

Thank's

**Comment by filiphr** [comment] 2017-12-22 22:29
Which Lombok version are you using? Does the compilation work with Gradle / Maven, how does your build setup look like? Have you checked the #1159 issue?

**Comment by alexis-puska** [comment] 2017-12-22 22:44
I use with maven, Lombok 1.16.18
The project is generate with Hipster and modified with the client specification.
The maven build failed if i have a @mapping annotation and a DTO with an lombock annotation.
The build work when i not used lombok annotation on this same DTO or if the mapper don't have an @Mapping(source, target) annotation.

**Comment by filiphr** [comment] 2017-12-23 08:08
I have never used Hipster. How does the maven setup look like? Where is the mapstruct-processor dependency defined?

**Comment by alexis-puska** [comment] 2017-12-26 08:45
<mapstruct.version>1.2.0.Final</mapstruct.version>

 <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-jdk8</artifactId>
            <version>${mapstruct.version}</version>
        </dependency>

<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                        
                        <path>
                            <groupId>org.hibernate</groupId>
                            <artifactId>hibernate-jpamodelgen</artifactId>
                            <version>${hibernate.version}</version>
                        </path>

                    </annotationProcessorPaths>
                </configuration>
            </plugin>

**Comment by filiphr** [comment] 2017-12-26 08:59
You are missing the lombok dependency in the `annotationProcessorPaths`. Can you try adding it and let us know?

**Comment by alexis-puska** [comment] 2017-12-26 09:31
It's work ! 
i have add : 
```xml
<path>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>${lombok.version}</version>
</path>
```

to the annotation processor paths and i get no error with @Data / @Mapping annotation. 

Thank's for the solution.

**Comment by filiphr** [comment] 2017-12-26 09:37
No problem, glad that it was just a config problem :). Closing this now

**Closed by filiphr** 2017-12-26 09:37 UTC
Labels: not a bug

**Comment by alexis-puska** [comment] 2017-12-26 09:38
I think that resolution problem can be added in the mapstruct installation documentation in comment like : 
```xml
<configuration>
                <source>1.6</source> <!-- or higher, depending on your project -->
                <target>1.6</target> <!-- or higher, depending on your project -->
                <annotationProcessorPaths>
                    <!-- Lombok dependancies if you use mapstruct and lombok -->
                    <path>
                        <groupId>org.mapstruct</groupId>
                        <artifactId>mapstruct-processor</artifactId>
                        <version>${org.mapstruct.version}</version>
                    </path>
                </annotationProcessorPaths>
            </configuration>
```

because on lombok documentation, no information about the annotation processor. http://mapstruct.org/documentation/installation/

**Comment by filiphr** [comment] 2017-12-26 12:40
That is a good suggestion @alexis-puska I've created https://github.com/mapstruct/mapstruct.org/issues/72

**Comment by de-dan** [comment] 2021-03-24 09:44
Whoever stumbles across this issue now with IntelliJ 2020.3:
In my case I could resolve the issue by reordering the annotation processors, first lombok, then mapstruct:
```
<annotationProcessorPaths>
  <path>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>${version.org.projectlombok}</version>
  </path>
  <path>
    <groupId>org.mapstruct</groupId>
    <artifactId>mapstruct-processor</artifactId>
    <version>${org.mapstruct.version}</version>
  </path>
</annotationProcessorPaths>
```

**Comment by rafaelfborges** [comment] 2021-03-29 22:45
> Whoever stumbles across this issue now with IntelliJ 2020.3:
> In my case I could resolve the issue by reordering the annotation processors, first lombok, then mapstruct:
> 
> ```
> <annotationProcessorPaths>
>   <path>
>     <groupId>org.projectlombok</groupId>
>     <artifactId>lombok</artifactId>
>     <version>${version.org.projectlombok}</version>
>   </path>
>   <path>
>     <groupId>org.mapstruct</groupId>
>     <artifactId>mapstruct-processor</artifactId>
>     <version>${org.mapstruct.version}</version>
>   </path>
> </annotationProcessorPaths>
> ```

Thanks, this solved the problem with Intellij finally.

**Comment by minhnguyenvan95** [comment] 2021-04-01 02:10
Thank you. I've just reorder my annotationProcessor order and it worked

**Comment by minhnguyenvan95** [comment] 2021-04-01 03:30
Check this out https://github.com/mapstruct/mapstruct-examples/blob/master/mapstruct-lombok/build.gradle

**Comment by techjourney010** [comment] 2021-05-27 20:10
With Ideea 2021.1.1 the issue is still present:

After reordering the annotation processor' paths, first lombok, then mapstruct, I could get past clean-install, and I generated the mappers implementations. But there is no way to start the app:
`java: No property named "property_name" exists in source parameter(s). Did you mean "null"?`
```
           <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>16</source>
                    <target>16</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <arg>-Amapstruct.defaultComponentModel=spring</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
```

**Comment by techjourney010** [comment] 2021-05-27 20:24
Finally I fixed it: reload and rebuild the project
