### ISSUE TITLE
Default value not work properly

### ISSUE THREAD

**Issue by JohnGreaves** [mapstruct/mapstruct#2095] opened 2020-05-12 14:04 UTC
While I use mapstruct, I found the bug:

For example: 
```java
@Mapper(componentModel = "spring")
public interface ExceptionMapper {
@Mappings({
            @Mapping(source = "error", target = "internalErrorMessage", qualifiedByName = "formInternalMessage"),
            @Mapping(source = "error", target = "additionalParams", qualifiedByName = "formAdditionalParams"),
            @Mapping(source = "error", target = "internalCode", qualifiedByName = "formInternalCode"),
            @Mapping(source = "httpCode", target = "httpCode", defaultValue = "400"),
    })
    MkwExceptionDto objectErrorToDto(ObjectError error, Integer httpCode);
```

and Mapstruct generates:

```java
if ( httpCode != null ) {
            if ( httpCode != null ) {
                mkwExceptionDto.setHttpCode( httpCode );
            }
            else {
                mkwExceptionDto.setHttpCode( 400 );
            }
        }
```

Depends on double-checking on null, the default value never be set.

<org.mapstruct.version>1.3.1.Final</org.mapstruct.version>

**Comment by chris922** [comment] 2020-05-13 09:56
Thanks for reporting this issue, I did a quick test and indeed.. this looks like a bug

Reproduciable via:

```java
@Mapper
public interface TestMapper {
    @Mapping(target = "httpCode", source = "httpCode", defaultValue = "400")
    MkwExceptionDto objectErrorToDto(Object source, Integer httpCode);

    class MkwExceptionDto {
        Integer httpCode;

        public Integer getHttpCode() {
            return httpCode;
        }

        public void setHttpCode(Integer httpCode) {
            this.httpCode = httpCode;
        }
    }
}
```

Generated code with 1.3.1.Final:

```java
public class TestMapperImpl implements TestMapper {

    @Override
    public MkwExceptionDto objectErrorToDto(Object source, Integer httpCode) {
        if ( source == null && httpCode == null ) {
            return null;
        }

        MkwExceptionDto mkwExceptionDto = new MkwExceptionDto();

        if ( httpCode != null ) {
            if ( httpCode != null ) {
                mkwExceptionDto.setHttpCode( httpCode );
            }
            else {
                mkwExceptionDto.setHttpCode( 400 );
            }
        }

        return mkwExceptionDto;
    }
}
```

**Comment by filiphr** [comment] 2020-05-16 07:48
Closing this as a duplicate of https://github.com/mapstruct/mapstruct/issues/2023. That one uses `defaultExpression`, but the gist of it is the same. Let me know if you don't agree.

You can workaround this by wrapping the `httpCode` in an object. For example:

```
public class HttpCode {

    private final int value;

    private HttpCode(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public static HttpCode create(Integer httpCode, int defaultHttpCode) {
        return httpCode != null ? new HttpCode(httpCode) : new HttpCode(defaultHttpCode);
    }
}
```

And then your mapper will look like: 

```
@Mapper
public interface TestMapper {
    @Mapping(target = "httpCode", source = "httpCode.value", defaultValue = "400")
    MkwExceptionDto objectErrorToDto(Object source, HttpCode httpCode);
}
```

**Closed by filiphr** 2020-05-16 07:48 UTC
Labels: bug
