### ISSUE TITLE
Mappers skips fields that start with 'add' when using Lombok Builder

### ISSUE THREAD

**Issue by ka-wo** [mapstruct/mapstruct#3382] opened 2023-09-13 09:58 UTC
### Expected behavior

A class with fields starting with 'add' should have these fields mapped and not ignored when using Lombok @Builder annotation.

There is an option to create a custom AccessorNamingStrategy and change this behaviour but it's not a correct (or expected) behaviour when using Builder naming.

### Actual behavior

Currently if I have a class like:
```
@Builder
class Foo {
String value;
String addedValue;
}
```
The mapper will omit the second one because it thinks it's 'adder' - https://github.com/mapstruct/mapstruct/blob/ea997f83cefd7d3900f8a6a218af1c20f7a1ef8a/integrationtest/src/test/resources/namingStrategyTest/strategy/src/main/java/org/mapstruct/itest/naming/CustomAccessorNamingStrategy.java#L32

### Steps to reproduce the problem

Create a class with Lombok's @Builder annotation, with few fields that start with 'add' and few that don't.
Generate the mapper - in the generated code it will not all the fields

### MapStruct Version

MapStruct 1.5.5.Final

**Comment by filiphr** [comment] 2023-09-16 09:33
I tried this with

```java
@Data
class FooDto {

    String value;
    String addedValue;

}
```

and mapper

```java
@Mapper
public interface FooMapper {

    Foo map(FooDto source);

}
```

and everything works as expected. Please provide a minimal example that will show the problem. Closing until then.

**Closed by filiphr** 2023-09-16 09:33 UTC
Labels: invalid

**Comment by dokhat-rok** [comment] 2024-04-27 15:51
@filiphr they wrote to you that this happens exactly with the @Builder annotation, and you put the @Data annotation and say that everything works as expected

**Comment by filiphr** [comment] 2024-04-28 08:20
@dokhat-rok, perhaps I wasn't clear enough.

The initial issue had a class named `Foo` that had a `@Builder` on it. I used that class plus the `FooDto` and the `FooMapper`. I couldn't reproduce the problem with that example. Whether `FooDto` has `@Builder` or not is irrelevant, because only the target matters for this problem.

The generated code for this looks like:

```java
public class FooMapperImpl implements FooMapper {

    @Override
    public Foo map(FooDto source) {
        if ( source == null ) {
            return null;
        }

        Foo.FooBuilder foo = Foo.builder();

        foo.value( source.getValue() );
        foo.addedValue( source.getAddedValue() );

        return foo.build();
    }
}
```

and here we can clearly see that `addedValue` is used. If you have some example where something does not work then please share it with us.
