### ISSUE TITLE
Make error message more descriptive if no private collection mapping can (implicitly) be generated

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#558] opened 2015-05-22 11:55 UTC
Currently it states:

> No implementation can be generated for this method. Found no method nor implicit conversion for mapping source element type into target element type.

But it should mention the affected source/target property.

**Comment by sjaakd** [comment] 2015-05-24 19:36
duplicate of #512

**Closed by sjaakd** 2015-05-24 19:36 UTC

**Comment by gunnarmorling** [comment] 2015-05-26 21:54
Ah, cool. Wasn't aware of the original one. Thanks for spotting it and fixing #512 :)
