### ISSUE TITLE
@BeanMapping ignoreByDefault=true for nested classes

### ISSUE THREAD

**Issue by zimi-pl** [mapstruct/mapstruct#2073] opened 2020-04-17 08:06 UTC
Hello,

During my work I found that something is not working as expected.
At least for me. So I decided to create issue for that.
Code below is pretty self describing
I expect that no automatic mapping will be created even for nested beans.
in meantime we will get result:

c
d
null

when expected

c
null
null

ignoreUnmappedSourceProperties explicitly says that it does not work for nested properties
in ignoreByDefault I don't see such warning, so I expect it to work

    @Data
    public static class A {
        @Data
        public static class B {
            private String c;
            private String d;
        }

        private B b;
        private String e;
    }

    @Mapper
    interface AMapper {

        @BeanMapping(ignoreByDefault = true)
        @Mapping(target = "b.c")
        A convert(A a);

    }

    public static void main(String[] args) throws NoSuchMethodException {
        A a = new A();
        A.B b = new A.B();
        b.setC("c");
        b.setD("d");
        a.setB(b);
        a.setE("e");
        A a2 = Mappers.getMapper(AMapper.class).convert(a);
        System.out.println(a2.getB().getC());
        System.out.println(a2.getB().getD());
        System.out.println(a2.getE());
    }

**Comment by Zegveld** [comment] 2024-04-25 10:54
Tried to reproduce this with 1.6.0-SNAPSHOT, but not reproducable anymore.
So this seems to be fixed.
Please respond if this issue still exists otherwise we'll close it soon.

**Comment by filiphr** [comment] 2024-04-27 10:30
Thanks for checking this @Zegveld. Closing it as it has been a really old issue anyways.

**Closed by filiphr** 2024-04-27 10:30 UTC
