### ISSUE TITLE
Cannot use custom mappers with Spring boot 2.0.4/Gradle 4.9

### ISSUE THREAD

**Issue by dpetrecki** [mapstruct/mapstruct#1599] opened 2018-08-29 14:52 UTC
My custom mappers are ignored. I've tried `@Qualifier` and `@Named` and nothing works.
This is my code:

version 1:
```
@Mapper(componentModel = "spring")
public interface UserMapper {
    @Mappings({
            @Mapping(source = "extraData", target = "standardData", qualifiedBy = Reverse.class),
    })
    UserDto map(User user);

    @Qualifier
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    @interface Reverse { }

    @Reverse
    default boolean reverse(boolean input) {
        return !input; //I have little "boolean" (no "Boolean") on both sides
    }
}
```

version 2:
```
@Mapper(componentModel = "spring")
public interface UserMapper {
    @Mappings({
            @Mapping(source = "extraData", target = "standardData", qualifiedByName = "Reverse"),
    })
    UserDto map(User user);

    @Named("Reverse")
    default boolean reverse(boolean input) {
        return !input;
    }
}
```
test:
```
    @Test
    public void testMapper(){
        User user = new User();
        user.setExtraData(true);

        UserDto dto = Mappers.getMapper(UserMapper.class).map(user);

        assertFalse(dto .isStandardData());
    }
```

build.gradle:
```
    compile("org.mapstruct:mapstruct-jdk8:1.2.0.Final")
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.2.0.Final'
    testAnnotationProcessor 'org.mapstruct:mapstruct-processor:1.2.0.Final'
```

I've also tried with 1.3.0Beta1 version and with mapping in a separated file and nothing helps.
I've tested with JUnit 5 and production code.
I've also tested with custom Enum mapper without success.
```
<S extends Enum<S>, T extends Enum<T>> T convert(S source, Class<T> targetClass) {
        try {
            return Enum.valueOf(targetClass, source.name());
        } catch (IllegalArgumentException e) {
            return null;
        }
    }
```
Could anybody help me?

**Comment by sjaakd** [comment] 2018-08-29 18:49
hmm. related to #1597 .. I'll have a look.

**Comment by sjaakd** [comment] 2018-08-29 19:58
ok. I think there are 2 questions reported here. I created a [gist](https://gist.github.com/sjaakd/62355bd8c9be2ad98cb1678413f9d22f). Can't reproduce your problem. The gist works.. 

Wrt to the enum mapping.. Please checkout our [test cases](https://github.com/mapstruct/mapstruct/tree/master/processor/src/test/java/org/mapstruct/ap/test/bugs/_1482)..

**Comment by dpetrecki** [comment] 2018-08-30 05:33
I've created a simple project and found it... My setter took `Boolean` instead of `boolean`. I've tried few combinations and the only issue here is, there is no way to use custom mapper to convert primitives to objects, like:
```
@Reverse
default Boolean reverse(boolean input) {
    return !input;
}
```
With this code, `Boolean` in target class and `boolean` in source class, calling "reverse" is missed in a generated class.

**Comment by sjaakd** [comment] 2018-08-30 06:52
@dpetrecki : Nice to hear 👍 

I want to ask you to use our [gitter room](https://gitter.im/mapstruct/mapstruct-users) to discus problems in using MapStruct or if they are of a more general howto stackoverflow. We have enthiousiastic users quick to answer.

I'll continue to close this issue. Feel free to reopen if I missed something

**Closed by sjaakd** 2018-08-30 06:52 UTC
