### ISSUE TITLE
Map to bean mapping: error when generating code for map key containing a dot symbol

### ISSUE THREAD

**Issue by asihub** [mapstruct/mapstruct#3151] opened 2023-02-06 09:07 UTC
### Expected behavior

It is expected that code for the map key with "." is generated with no errors.

### Actual behavior

When trying to compile code getting the following error:
java: No property named "KEY_NAME.WITH_DOT" exists in source parameter(s). Did you mean "KEY_NAME.empty"?

### Steps to reproduce the problem

1. Create a HashMap<String, String> that contains a few entries. One of the keys should have a dot symbol.
2. Create a respective bean for mapping from the map. 
3. Create MapStruct mapper interface with a method like:
`
@Mapping(target = "keyName", source = "KEY_NAME.WITH_DOT")
MyMappingClass toEntity(Map<String, String> map);
`
4. Try compiling the code with mvn or whatever you use.

### MapStruct Version

1.5.3.Final

**Comment by asihub** [comment] 2023-02-06 09:10
Currently worked around with `expression` but would be nice if it gets worked properly. No issues with other keys without dots.

**Comment by Zegveld** [comment] 2023-02-06 17:11
Duplicate of #3066

**Closed by Zegveld** 2023-02-06 17:11 UTC
Labels: bug
