### ISSUE TITLE
[QUESTION] Why default value in property mapstruct.defaultInjectionStrategy is FIELD?

### ISSUE THREAD

**Issue by romankh3** [mapstruct/mapstruct#2672] opened 2021-11-24 09:05 UTC
Hello.
Thanks for an awesome library.

During using the library I faced, that the default value of property `mapstruct.defaultInjectionStrategy` is `InjectionStrategy.FIELD`

As far as I know, injecting beans via fields is not a good practice in comparison with injecting by the constructor.

Maybe I missed some reasons to make default injecting by field. Or would be better to set the default value for injecting as `InjectionStrategy.CONSTRUCTOR`?

Thanks,
Roman.

**Comment by Zegveld** [comment] 2021-12-27 14:10
duplicate of #1973

**Closed by Zegveld** 2021-12-27 14:10 UTC
