### ISSUE TITLE
Impl class is not generated when the @Mapping target has underscore

### ISSUE THREAD

**Issue by sivaganti** [mapstruct/mapstruct#2018] opened 2019-08-26 10:31 UTC
When i have an underscore in my target string as below the target implementation is not generated. It works fine when the underscores are removed. 

```
@Mappings({	
			@Mapping(target = "Test_Underscore_With_MapStruct", expression="java((String)req.getRequestData().get("MyKey"))")  })
```

Note : i also modify my pojo attribute with /without underscore depending on the target defined. It works with out underscore.

My Maven dependencies
```
	<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct-jdk8</artifactId>
			<version>1.1.0.Final</version>
		</dependency
```

**Comment by filiphr** [comment] 2020-02-23 16:34
@sivaganti I cannot reproduce this. I added a test case as well which is green.

I will close this issue, if you can provide an example project showing this problem we can reopen it.

**Closed by filiphr** 2020-02-23 16:34 UTC
