### ISSUE TITLE
Mapstruct does not work properly with nested fields mapping

### ISSUE THREAD

**Issue by pro100jekon** [mapstruct/mapstruct#2506] opened 2021-07-02 09:13 UTC
Here is a small example of the classes that I had a test with:
```java
@Mapper
public interface TestMapper {

    @Mapping(target = "nested.string", expression = "java( provideString(s) )")
    Target map(Source s);

    default String provideString(Source source) {
        if (source.getS().startsWith("A")) {
            return "hello";
        } else {
            return "bye";
        }
    }
}
```
```java
@Data
public class Nested {

    String string;
}
```
```java
@Data
public class Source {

    String s;
}
```
```java
@Data
public class Target {

    Nested nested;
}
```
There are two issues that I have faced with such mapper structure.
1. If a parameter in an abstract method has different name (meaning ```Source source``` is ```Source s```) then we will have such generated mapper:
```java
public class TestMapperImpl implements TestMapper {

    @Override
    public Target map(Source s) {
        if ( s == null ) {
            return null;
        }

        Target target = new Target();

        target.setNested( sourceToNested( s ) );

        return target;
    }

    protected Nested sourceToNested(Source source) {
        if ( source == null ) {
            return null;
        }

        Nested nested = new Nested();

        nested.setString( provideString(s) );// compilation error

        return nested;
    }
}
```
And we get a compilation error on the line with comment.
2. If we add a brand new parameter to the abstract method
```java
@Mapping(target = "nested.string", expression = "java( provideString(s, string) )")
Target map(Source s, String string);
```
here is a new generated code
```java
public class TestMapperImpl implements TestMapper {

    @Override
    public Target map(Source s, String string) {
        if ( s == null && string == null ) {
            return null;
        }

        Target target = new Target();

        if ( s != null ) {
            if ( target.getNested() == null ) {
                target.setNested( new Nested() );
            }
            sourceToNested( s, target.getNested() );
        }

        return target;
    }

    protected void sourceToNested(Source source, Nested mappingTarget) {
        if ( source == null ) {
            return;
        }

        mappingTarget.setString( provideString(s, string) ); // compilation error
    }
}
```
Not quite sure that this is an intended way of Mapstruct work. Could you please look into this issue?

**Comment by sjaakd** [comment] 2021-07-03 09:16
> Not quite sure that this is an intended way of Mapstruct work. Could you please look into this issue?

No. That's not the intended way MapStruct should work. Expressions are literally used in the code. They are a fall back mechanism for tweaking the output. There's no need to use such mechanism in this case.

This might work however:
```
@Mapper
public interface TestMapper {

    @Mapping(target = "nested.string", source="s")") // indicating that parameter 's' should be taken as start of mapping
    Target map(Source s);

    default String provideString(Source source) {
        if (source.getS().startsWith("A")) {
            return "hello";
        } else {
            return "bye";
        }
    }
}
```
MapStruct will look for a method matching a target `String` with source `s` of type `Source`.

I'll proceed to close this issue. It works as intended.

**Closed by sjaakd** 2021-07-03 09:16 UTC

**Comment by pro100jekon** [comment] 2021-07-04 16:17
Actually, it doesn't look for that method.
Here is the generated code:
```java

import javax.annotation.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2021-07-04T19:13:15+0300",
    comments = "version: 1.4.2.Final, compiler: javac, environment: Java 1.8.0_291 (Oracle Corporation)"
)
public class TestMapperImpl implements TestMapper {

    @Override
    public Target map(Source s) {
        if ( s == null ) {
            return null;
        }

        Target target = new Target();

        target.setNested( sourceToNested( s ) );

        return target;
    }

    protected Nested sourceToNested(Source source) {
        if ( source == null ) {
            return null;
        }

        Nested nested = new Nested();

        nested.setString( source.getS() );

        return nested;
    }
}
```
