### ISSUE TITLE
Bounded wildcard like Collection<? extends OrderItem> is not generated properly

### ISSUE THREAD

**Issue by cornzy** [mapstruct/mapstruct#1170] opened 2017-04-04 20:40 UTC
Easy to reproduce in example project "mapstruct-examples-field-mappings".
Change org.mapstruct.example.dto.Customer.getOrderItems() return type from `Collection<OrderItem>` to `Collection<? extends OrderItem>`.

With the default CollectionMappingStrategy (ACCESSOR_ONLY) this may be hard to generate because you could not add anything to such a list. We are using ADDER_PREFERRED, in this case the generated code would be simple to fix:

  * The adder Method should be found properly
  * The new collection to add the mapped elements needs to be of type `Collection<OrderItem>` (do not copy `? extends`)
  * In some cases the type of the for-loop variable is also `? extends OrderItem` (cannot reproduce with the simple example yet)

**Comment by cornzy** [comment] 2017-04-08 22:16
If you have any hint how to fix it I may have a look in the code for my own :)

**Comment by filiphr** [comment] 2017-04-10 18:55
Can you also make an example that does not work. I think that I know how to reproduce it, but just to be on the same page.

For the adder the generated code looks like:
```java
    for ( ? extends OrderItem order : customer.getOrderItems() ) {
        customerDto.addOrder( orderItemMapper.fromOrder( order ) );
    }
```

The new collection that elements should be added to is of type `Collection<OrderItem>`. Or you mean when the setter is also `? extends OrderItem` then the new collection is with element `? extends OrderItem`?

As for the code, to fix the problem with the adder, you would need to look at the [`AdderWrapper`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/model/assignment/AdderWrapper.java) and it's FreeMarker model [`AdderWrapper.ftl`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/AdderWrapper.ftl). Most probably the fix is in the ftl and you need to take the `typeBound` of the type parameters there.

Whereas for the other one you should look at the [`IterableMappingMethod`](https://github.com/mapstruct/mapstruct/blob/8fab3dd4e5002a2c9f2288efa9635f46386fd04f/processor/src/main/java/org/mapstruct/ap/internal/model/IterableMappingMethod.java) and it's [model](https://github.com/mapstruct/mapstruct/blob/f654da256350b8d72d29c7a30d29cf6e7c266a06/processor/src/main/resources/org/mapstruct/ap/internal/model/IterableMappingMethod.ftl). I think that here is a bit more complex, and we might need to somehow convey the message to the `Type.ftl` or make sure that we create a Type with a Type bound for the assignment.

**Comment by cornzy** [comment] 2017-04-11 19:13
@filiphr thank you for your answer. Yes you found the problem. I will have a look at the mentioned code but I fear I need some more help.

**Comment by filiphr** [comment] 2017-04-11 19:16
@cornzy no problem, glad I could help. If something is not clear just let me know and I can help you out. We are also on gitter at [mapstruct-user](https://gitter.im/mapstruct/mapstruct-users) you can find us there for help as well

**Comment by cornzy** [comment] 2017-04-12 12:29
@filiphr  I think I understood the template files and maybe could fix them. But I cannot find the code where mapstruct decides whether the parameter type of the adder matches or not. At the moment it seems like the adder method is not recognized because of the wrong argument type.
I changed the type of getPets in `org.mapstruct.ap.test.collection.adder._target.Target` to be List<? extends Long> (even this makes no sense) and thought the tests need to be successful anyway. Unfortunately it is not that easy :)

**Comment by filiphr** [comment] 2017-04-13 08:11
The adder is just a wrapper assignment, in the adder you are sure that the `sourceType` is a generic iterable and the element is taken from `sourceType.typeParameters[0]` in the model. You will need to make `sourceType.typeParameters[0].typeBound` in order to get the bound. The place where MapStruct decides to use the adder is [here](https://github.com/mapstruct/mapstruct/blob/fdf37cf45100c3de685aba5ef397a6701e47d349/processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java#L389). You can follow the path to see how MapStruct decides to do an assignment via an adder.

The change you made will not work because there is no Conversion from `? extends Long` to `String` in MapStruct. The conversions in MapStruct work only when the types match and here they don't. You can either add your own mapping from `Long` to `String` and here MapStruct will use your mapping for that, or I would suggest you add a new method that uses one of the `Pet` objects, otherwise it won't work.

**Comment by cornzy** [comment] 2017-05-22 06:56
Finally it seems like I have found the necessary code parts. There are some different kind of matching wildcard collections and I hope I found all necessary combination.

I also resolved a TODO in Type#isAssignableTo() that was responsible for not finding add method when maaping from List<? extend T> to List.

@filiphr in your last comment you said that my change might not work because there is no conversation from ? extends Long to String. But that is exactly one of the major points. If there is a mapping from Long to Stringthis mapping have to be used for ? extends Long as long there is no other more specific type mapping.

Please have a look at my pull request. I will test it in more detail with our code this week.

**Comment by filiphr** [comment] 2017-05-22 07:18
@cornzy awesome for working on this. We'll have a look at it tonight.

Yes I said that in my last comment and I meant that it won't work with the current code that we have, but with the resolving of your TODO it should work.

Testing with your code would be awesome as well, looking to hear how it behaves there as well.

**Comment by filiphr** [comment] 2017-06-28 22:05
It has been integrated with the #1029 PR. Thanks again @cornzy

**Closed by filiphr** 2017-06-28 22:05 UTC
Labels: bug
