### ISSUE TITLE
Support mapping of interface and abstract class (with polymorphism annotation)

### ISSUE THREAD

**Issue by blop** [mapstruct/mapstruct#923] opened 2016-10-06 08:46 UTC
It would be great if mapstruct could provide a way to generate a mapper between interfaces or abstract classes.

Of course requiring that the list of sub-types is provided through an annotation.

Something like  : 
```
@PolymorphismMapping(value = {ImplementationA1.class, ImplementationA2.class, ImplementationA3.class})
InterfaceB mapA(InterfaceA interfaceA);

ImplementationA1 mapA1(ImplementationA1 implementationA1);
ImplementationA2 mapA2(ImplementationA2 implementationA2);
ImplementationA3 mapA3(ImplementationA3 implementationA3);
```

Should generate : 

```
public InterfaceB map(InterfaceA interfaceA) {
	if (interfaceA instanceof ImplementationA1) {
		return mapA1((ImplementationA1) interfaceA);
	} else if (interfaceA instanceof ImplementationA2) {
		return mapA2((ImplementationA2) interfaceA);
	} else if (interfaceA instanceof ImplementationA3) {
		return mapA3((ImplementationA3) interfaceA);
	}
	return null;
}
```

**Comment by agudian** [comment] 2016-10-06 18:05
Duplicate of #131. The `@PolymorphismMapping` suggestion is new, though and we should consider that as a possibility in the design of this feature.

**Closed by agudian** 2016-10-06 18:05 UTC

**Comment by gunnarmorling** [comment] 2016-10-06 18:08
@blop, also if it's a duplicate, thanks for opening this request! I've added a note to the original one so we don't forget about this idea here.

**Comment by agudian** [comment] 2016-10-06 18:09
Same for me, at the same time 😁

**Comment by alxxyz** [comment] 2020-12-04 12:28
Hi, I like this approach and I want to help to implement it.
Can someone help me from which I can start, where should I declare the annotation and where the annotations a processed?

**Comment by filiphr** [comment] 2020-12-05 09:36
Hey @alxxyz, the main issue is #131. 

Regarding the idea that is described here, the best place to start is in the `MapperCreationProcessor#getMappingMethods`. The suggested `@PolymorphismMapping` will need to have its own `MappingMethod` like the `BeanMappingMethod`, `IterableMappingMethod`, `ValueMappingMethod`, etc. Have a look at how the `@IterableMapping` annotation is handled and where it is defined. 

Feel free to reach out if you need more help. You can also reach us in our [Gitter room](https://gitter.im/mapstruct/mapstruct-users)

**Comment by alxxyz** [comment] 2020-12-07 11:37
Hi, I like this approach and I want to help to implement it.
Can someone help me from which I can start, where should I declare the annotation and where the annotations a processed?

**Comment by tamndse62381** [comment] 2021-09-08 04:14
Hi, do we have this feature in the latest release of Mapstruct yet? Up to now, I have to perform multiple instance of check or using the discriminator field for this scenario.

**Comment by MehdiQaos** [comment] 2024-04-09 15:16
@tamndse62381 any updates if this was added?

**Comment by filiphr** [comment] 2024-04-27 08:33
@MehdiQaos yes this was added as part of #131. Have a look at https://mapstruct.org/documentation/stable/reference/html/#sub-class-mappings
