### ISSUE TITLE
NullValueMappingStrategy.RETURN_NULL not returning Null on Update Methods

### ISSUE THREAD

**Issue by frossiar** [mapstruct/mapstruct#3138] opened 2023-01-19 09:56 UTC
### Expected behavior

Using NullValueMappingStrategy.RETURN_NULL on an update method (which is also the default) should make the method return null when the update entity is null.

```
@BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
            nullValueMappingStrategy = NullValueMappingStrategy.RETURN_NULL)
    @Mapping(target = "id", ignore = true)
    public abstract Ship updateShipWithShipDto(ShipDto update, @MappingTarget Ship destination);
```

->

```
@Override
    public Ship updateShipWithShipDto(ShipDto update, Ship destination) {
        if ( update == null ) {
            return null;
        }
        ...
        ...
    }
```

### Actual behavior

It actually makes the method return the original, non-updated target entity:

```
@Override
    public Ship updateShipWithShipDto(ShipDto update, Ship destination) {
        if ( update == null ) {
            return destination;
        }
        ...
        ...
    }
```

This makes it impossible to update this field to null, when updateShipWithShipDto gets called by other Mappers.

Perhaps a third option for NullValueMappingStrategy could be added to apply this current behaviour, but the javadoc on RETURN_NULL states that "If null is passed to a mapping method, null will be returned.". 

### Steps to reproduce the problem

I have created a Short, Self Contained, Correct Example (SSCCE) at this repository: https://github.com/goldflam-gmbh/mapstruct-return-null-from-update 

If you check this out and run a mvn clean compile you will get the result mentioned partially above.

There are also two test cases (which currently fail), to show the behaviour that we expected. 

This behaviour has been implemented because of issue https://github.com/mapstruct/mapstruct/issues/1752 and while we do understand why this is the default option, we also feel like there should be an option to return null. Naming of the NullValueMappingStrategies could be difficult though if a third option was to be added. 

### MapStruct Version

1.5.3.Final

**Comment by filiphr** [comment] 2023-03-17 11:17
Perhaps we need to change the javadoc of the `NullValueMappingStrategy` a bit. Its intended behaviour is for normal mapping methods and not for update mapping methods that return the instance that is being mapped.

>This makes it impossible to update this field to null, when updateShipWithShipDto gets called by other Mappers.

The problem with this is that you are not updating a field, you are updating an existing object. Therefore we changed this behaviour in #1752. Also if you look at the Javadoc of `@MappingTarget` you'll see that there are two update methods possible:

* update method that doesn't return anything
* update method that returns the object being updated

I had a look at your example and the reason why it isn't working is because you have explicitly told MapStruct to ignore null values by using `nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE`.

When I remove the `BeanMapping` from the `TripMapper` and I adapt the `isNotEmpty` method in the `MapperConfig` to

```java
@Condition
    <T> boolean isNotEmpty(JsonNullable<T> field) {
        return field != null && field.isPresent() && field.get() != null;
    }
```

then everything works as expected. 

Therefore, I am going to close this as works as designed

**Closed by filiphr** 2023-03-17 11:17 UTC
Labels: bug
