### ISSUE TITLE
@Mapping could support mutiple targets when ignoring fields

### ISSUE THREAD

**Issue by x80486** [mapstruct/mapstruct#2434] opened 2021-05-06 20:51 UTC
While trying to ignore several fields/members I just found out that I have to specify them (each) on single `@Mapping`:

```java
@Mapping(ignore = true, target = "id")
@Mapping(ignore = true, target = "status")
Result valueFrom(Source source);
```

Would it be possible to make `target` to receive an array instead?

```java
@Mapping(ignore = true, target = ["id", "status"])
Result valueFrom(Source source);
```

**Comment by filiphr** [comment] 2021-05-07 14:10
This is a duplicate of #1958. There is a discussion there my we don't want to support multiple options for `Mapping#target`. In a nutshell, it might make sense for `ignore`, but it doesn't make sense for other things.

**Closed by filiphr** 2021-05-07 14:10 UTC
