### ISSUE TITLE
Multiple constant to nested target mapping error

### ISSUE THREAD

**Issue by eriche39** [mapstruct/mapstruct#1510] opened 2018-06-01 22:28 UTC
with this class:

public class MultipleConstantMapping {
    public static class A{
        public Boolean active;
    }

    public static class C{
        public A a;
    }

    public static class M{
        public C c1;
        public C c2;
    }

    public static class N{
        public M m;
    }

    //ERROR
    @Mapper(uses = {})
    public interface StringToN{
        @Mappings({
            @Mapping(constant="true", target = "m.c1.a.active"),
            @Mapping(constant="true", target = "m.c2.a.active"),
        })
        N map(String source);
    }

    //OK
    @Mapper(uses = {})
    public interface StringToM{
        @Mappings({
            @Mapping(constant="true", target = "c1.a.active"),
            @Mapping(constant="true", target = "c2.a.active"),
        })
        M map(String source);
    }

    //OK
    @Mapper(uses = {})
    public interface AToN{
        @Mappings({
            @Mapping(source = "active", target = "m.c1.a.active"),
            @Mapping(source = "active", target = "m.c2.a.active"),
        })
        N map(A source);
    }

    //Error
    @Mapper(uses = {})
    public interface AToN2{
        @Mappings({
            @Mapping(constant="true", target = "m.c1.a.active"),
            @Mapping(constant="true", target = "m.c2.a.active"),
        })
        N map(A source);
    }
}

MultipleConstantMapping.java:[38,11] Can't map "java.lang.String "true"" to "MultipleConstantMapping.C c2.a.active".

note the AToN interface is working fine.
after remove any one of the Mapping in StringToN, it worked fine.

**Comment by filiphr** [comment] 2018-06-02 05:44
@eriche39 which version of MapStruct are you using?

**Comment by eriche39** [comment] 2018-06-02 08:33
@filiphr 1.2.0.Final

**Comment by filiphr** [comment] 2018-06-02 12:05
@eriche39 I think that what you are experiencing is the same as https://github.com/mapstruct/mapstruct/issues/1320. Which has been fixed in https://github.com/mapstruct/mapstruct/pull/1322. Is it possible for you to give the SNAPSHOT version a try?

**Comment by eriche39** [comment] 2018-06-03 02:46
@filiphr Tested with 1.3.0.SNAPSHOT, it is fixed, thanks!
is there any plan for a beta release?

**Comment by filiphr** [comment] 2018-06-03 05:28
Closing as duplicate of #1320.

@eriche39 yes we want to release 1.3.0.Beta1 as soon as possible. There is one PR from me that we need to finish for the builder so we can do a release.

**Closed by filiphr** 2018-06-03 05:28 UTC
