### ISSUE TITLE
Allow abstract class mapper with constructor and arguments

### ISSUE THREAD

**Issue by Goni-Dev** [mapstruct/mapstruct#2678] opened 2021-12-01 13:52 UTC
In my Spring Boot use case, a resolver-bean is used in the mapper to resolve ids from the source object. The resolved value is then assigned to the target object. This resolver is required in custom mapping code and therefore Springs dependency injection is used to intialize this bean. In the example below there is a resolver for countryIds to countryNames. 

    @Mapper(uses =
    {CountryIdResolver.class}, componentModel = "spring", injectionStrategy = InjectionStrategy.CONSTRUCTOR)
    public abstract class DtoMapper
    {
        protected final CountryIdResolver  countryIdResolver;

        @Autowired
        public DtoMapper(CountryIdResolver countryIdResolver)
        { 
            this.countryIdResolver = countryIdResolver;
        }

        @Mapping(target = "text", source = "test")
        @Mapping(target = "temp", source = "country", qualifiedByName = {"CountryResolver", "Id"})
        public abstract TargetDTO mapStartDTO(SourceDTO startDTO);

        protected String mapCountries(List<Integer> countries) {
            //...
            sb.append(countryIdResolver.resolveCountry(currentCountry));
            //..
            return sb.toString();
        }
    }

    @Named("CountryResolver")
    public class CountryIdResolver
    {
        @Named("Id")
	    public String resolveCountry(int id) {
            //..
            return ""; //resolved id
        }
    }

Issues with the generated impl-class:

- First of all the generated code doesnt compile, due to not calling the super constructor in the generated impl-class.  I circumvented this error with setter-injection, but there might be situations where this isnt possible.

- The generated code is redefining the field countryIdResolver.

**Comment by Zegveld** [comment] 2021-12-27 14:30
As an alternative you could do the following:
```
@Mapper( uses = CountryIdResolver.class, componentModel = "spring", injectionStrategy = InjectionStrategy.CONSTRUCTOR )
public abstract class DtoMapper
{
    @Mapping( target = "text", source = "test" )
    @Mapping( target = "temp", source = "country", qualifiedByName = { "CountryResolver", "Id" } )
    public abstract TargetDTO mapStartDTO(SourceDTO startDTO);

    // This handles the mapping from List<Integer> to List<String>.
    @IterableMapping( qualifiedByName = { "CountryResolver", "Id" } )
    protected abstract List<String> mapCountries( List<Integer> countries );

    // This handles the collection of the result of the first mapping.
    protected String collectCountries( List<String> countries ) {
        //...
        sb.append(currentCountry);
        //..
        return sb.toString();
    }
}

@Named("CountryResolver")
public class CountryIdResolver
{
    @Named("Id")
    public String resolveCountry(int id) {
        //..
        return ""; //resolved id
    }
}
```

In this case you do not need to manually define the injection, because all the actions on the injected class are handled by MapStruct. All you need to define is how to manually collect the result of the conversion.

Hope the above example helps in getting it compiling for you.

See also #2257 and 2211

**Comment by Zegveld** [comment] 2021-12-27 14:32
closing this as it is a duplicate of #2257

**Closed by Zegveld** 2021-12-27 14:32 UTC

**Comment by Goni-Dev** [comment] 2021-12-27 16:36
Thank you for your detailed answer. Your provided solution works for me.I wasn't aware of the qualifiedByName on the IterableMapping-Annotation.
