### ISSUE TITLE
mapping builder that has constructor with some parameters

### ISSUE THREAD

**Issue by Bue-von-hon** [mapstruct/mapstruct#3058] opened 2022-10-19 23:45 UTC
### Use case

hello mapstruct!
i'd like to request some feature like below

Student jack = new student.builder("name", "addr").withAge(25).build();
Person person = new Person("name", "addr");
Student student = mapper.toStudent(person);

i'm using builder with some optional values
nessasy value -> passing to builder constructor
optional value -> with builder

**Comment by filiphr** [comment] 2022-11-03 21:10
@Bue-von-hon I am not sure that I understand what you are looking for. Why is the example you have shared not working with MapStruct? 

Is the mapping builder method a method that takes parameters? If that is the case then this issues is a duplicate of #2081

**Comment by filiphr** [comment] 2022-11-03 21:11
@Bue-von-hon I am not sure that I understand what you are looking for. Why is the example you have shared not working with MapStruct? 

Is the mapping builder method a method that takes parameters? If that is the case then this issues is a duplicate of #2081

**Comment by Bue-von-hon** [comment] 2022-11-03 23:44
> @Bue-von-hon I am not sure that I understand what you are looking for. Why is the example you have shared not working with MapStruct?
> 
> Is the mapping builder method a method that takes parameters? If that is the case then this issues is a duplicate of #2081

@filiphr 
#2081 is what I want
so it has been requesting since 2020...
if so, could I develop that feature for community of mapstruct?

**Comment by filiphr** [comment] 2022-11-05 12:24
>https://github.com/mapstruct/mapstruct/issues/2081 is what I want

Then I am going to close this one.

>so it has been requesting since 2020...
>if so, could I develop that feature for community of mapstruct?

Of course, we are always happy to have the community contribute to MapStruct. Let us know if we can help you somehow.

**Closed by filiphr** 2022-11-05 12:24 UTC
