### ISSUE TITLE
Mappers.getMapper(Class clazz) is throwing a ClassNotFoundException when a mapper is defined with a custom implementation name.

### ISSUE THREAD

**Issue by matleclaire** [mapstruct/mapstruct#1812] opened 2019-05-10 10:05 UTC
Hey guys !

I've discovered what it seems to be an issue with `Mappers.getMapper(Class<T> clazz)` when a Mapper is defined this way

```
// Pay attention to the implementationName which has been defined
@Mapper(componentModel = "spring", implementationName = "<CLASS_NAME>V1Impl")
public interface CarMapper {
  @Mapping(target = "color", ignore = true)
  CarDTO map(Car car);

}
```

And when we try to retrieve its implementation using `Mappers.getMapper(CarMapper.class)`.

Here is the stacktrace 
```
Caused by: java.lang.ClassNotFoundException: Cannot find implementation for com.example.demo.mappers.v1.CarMapper
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:75)
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:58)

```

The issue seems to be located here https://github.com/mapstruct/mapstruct/blob/0e33ad4bbcfd7f8628f63221db4faa7415ac4384/core/src/main/java/org/mapstruct/factory/Mappers.java#L75

The code is trying to load a mapper according to the default class implementation name. The one defined by `implementationName` in annotation `@Mapper` is not considered here. 

I've created a public repo to reproduce this behaviour.
see https://github.com/matleclaire/mapstruct-sample-error

I hope it might help.

**Mapstruct version : 1.3.0-Final**

**Comment by chris922** [comment] 2019-05-24 16:57
Thanks @matleclaire for reporting this!

When you use the component model `spring` it is not expected that you retrieve the mapper with `Mappers.getMapper(...)`. Could you try to remove the component model and do it once again ? Or let Spring inject the mapper.

`Mappers.getMapper(...)` needs some metadata in case the generated class has a different suffix, this will only be generated in case the component model is not set / the default one. In this case the Java ServiceLoader will be used to retrieve the class when I remember correctly...

**Comment by filiphr** [comment] 2019-05-24 20:51
As @chris922 said, the `Mappers` factory is there to provide a convenience way of getting Mappers with the `default` component model. 

It doesn't support mappers with custom name. And it can't read the `@Mapper` annotation, since this annotation is not retained in the byte code (it is a source annotation only).

As @chris922 also said if it can't find a class finishing with `Impl` it will use the Java `ServiceLoader`.

I am closing this since this is works as designed.

Keep in mind that you can still instantiate the class by calling the `Impl` constructor.

**Closed by filiphr** 2019-05-24 20:51 UTC

**Comment by matleclaire** [comment] 2019-06-19 11:48
My comment comes very lately, sorryfor that.

Thanks for all your feedbacks and your explanations. That's pretty clear now.

**Comment by FlyingDream941228** [comment] 2020-09-23 14:33
Is your problem solved?
How to solve it

**Comment by sjaakd** [comment] 2020-09-26 11:11
> Is your problem solved?
> How to solve it

Please don't respond to closed issues. Ask questions on stackoverflow
