### ISSUE TITLE
Dynamic usage of @Autowired causes false positives with bazel unused_deps

### ISSUE THREAD

**Issue by levimeahan** [mapstruct/mapstruct#2272] opened 2020-11-12 22:17 UTC
- [x] Is this an issue (and hence not a question)? 

I have a mapper class generated dynamically like this:

```
@Mapper(componentModel = "spring")
public interface EnumMapper {
   ...
}
```

Using bazel + maven, I have to include `org.springframework:spring-beans` for this to successfully build, however running `bazel //build-utils:unused_deps` tells me it is unused. Failing to include it results in the error: `Couldn't find type org.springframework.beans.factory.annotation.Autowired. Are you missing a dependency on your classpath?`

Maybe this is more of a bazel issue, but detecting a dynamic string -based import like https://github.com/mapstruct/mapstruct/blob/71e9bd3699d1a295bf51abb7d685a093cfc1aa6f/processor/src/main/java/org/mapstruct/ap/internal/processor/SpringComponentProcessor.java#L71 seems rather difficult for any build system. Would it be feasible to make this import in `SpringComponentProcessor.java` static?

**Comment by filiphr** [comment] 2020-11-15 09:14
>Would it be feasible to make this import in `SpringComponentProcessor.java` static?

No we can't do an explicit import here. We do not want to have a hard dependency on `spring-beans`.

MapStruct is an annotation processor that generates java code during compilation time.

If you want to use the `spring` component model then you have to have spring-beans as a dependency.

In my opinion this is a problem of bazel. I don't know much about bazel, but it seems to me that `bazel //build-utils:unused_deps` is not doing a correct job. It should first compile the project and then check for unused dependencies, since the generated code will have static imports of the spring packages.

It seems the Maven alternative for the bazel unused_deps is [maven-dependency-plugin:analyze](https://maven.apache.org/plugins/maven-dependency-plugin/analyze-mojo.html). which will run the `test-compile` phase and then do the analysis. When the `test-compile` phase is run it will also run the `compile` phase and thus it will include the generated sources in the analysis. It seems that bazel doesn't do that.

**Comment by filiphr** [comment] 2020-11-21 07:05
Closing this since I think the problem is not with MapStruct but with Bazel. @levimeahan if you have more information I am more than happy to reopen this.

**Closed by filiphr** 2020-11-21 07:05 UTC

**Comment by levimeahan** [comment] 2020-11-24 00:32
I'll look into it from that angle. Thanks!
