### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by lpedrov** [mapstruct/mapstruct#3262] opened 2023-05-04 13:12 UTC
### Expected behavior

I'm trying to to build this mapper:

```java
public abstract PartnershipMentionCommentDto mapTo(PartnershipMentionComment partnershipMentionComment);

public abstract Collection<PartnershipMentionCommentDto> mapTo(Collection<PartnershipMentionComment> partnershipMentionComments);

@IterableMapping(qualifiedByName = "mapToWithoutChildren")
public abstract Collection<PartnershipMentionCommentDto> mapToWithoutChildren(
        final Collection<PartnershipMentionComment> partnershipMentionComments);

@Named("mapToWithoutChildren")
@Mapping(target = "children", ignore = true)
public abstract PartnershipMentionCommentDto mapToWithoutChildren(PartnershipMentionComment partnershipMentionComment);
``` 

But I'm getting this error:
```java
Ambiguous mapping methods found for mapping property "Collection<PartnershipMentionComment> children" to Collection<PartnershipMentionCommentDto>: Collection<PartnershipMentionCommentDto> mapTo(Collection<PartnershipMentionComment> partnershipMentionComments), Collection<PartnershipMentionCommentDto> mapToWithoutChildren(Collection<PartnershipMentionComment> partnershipMentionComments). See https://mapstruct.org/faq/#ambiguous for more info.
``` 

For what I understand the problem is related with:
```java
public abstract Collection<PartnershipMentionCommentDto> mapTo(Collection<PartnershipMentionComment> partnershipMentionComments);
``` 

I changed to this:
```java
 @Named("mapTo")
 public abstract PartnershipMentionCommentDto mapTo(PartnershipMentionComment partnershipMentionComment);

 @IterableMapping(qualifiedByName = "mapTo")
 public abstract Collection<PartnershipMentionCommentDto> mapTo(Collection<PartnershipMentionComment> partnershipMentionComments);

 @IterableMapping(qualifiedByName = "mapToWithoutChildren")
 public abstract Collection<PartnershipMentionCommentDto> mapToWithoutChildren(
        final Collection<PartnershipMentionComment> partnershipMentionComments);

 @Named("mapToWithoutChildren")
 @Mapping(target = "children", ignore = true)
 public abstract PartnershipMentionCommentDto mapToWithoutChildren(PartnershipMentionComment partnershipMentionComment);
``` 

Still I'm getting the error. I thought this change would be enough.

But the strange thing is if I change to this:
```java
public abstract PartnershipMentionCommentDto mapTo(PartnershipMentionComment partnershipMentionComment);

public abstract Collection<PartnershipMentionCommentDto> mapTo(Collection<PartnershipMentionComment> partnershipMentionComments);

@Named("")
@IterableMapping(qualifiedByName = "mapToWithoutChildren")
public abstract Collection<PartnershipMentionCommentDto> mapToWithoutChildren(
        final Collection<PartnershipMentionComment> partnershipMentionComments);

@Named("mapToWithoutChildren")
@Mapping(target = "children", ignore = true)
public abstract PartnershipMentionCommentDto mapToWithoutChildren(PartnershipMentionComment partnershipMentionComment);
``` 

or this:
```java
public abstract PartnershipMentionCommentDto mapTo(PartnershipMentionComment partnershipMentionComment);

@Named("")
public abstract Collection<PartnershipMentionCommentDto> mapTo(Collection<PartnershipMentionComment> partnershipMentionComments);

@IterableMapping(qualifiedByName = "mapToWithoutChildren")
public abstract Collection<PartnershipMentionCommentDto> mapToWithoutChildren(
        final Collection<PartnershipMentionComment> partnershipMentionComments);

@Named("mapToWithoutChildren")
@Mapping(target = "children", ignore = true)
public abstract PartnershipMentionCommentDto mapToWithoutChildren(PartnershipMentionComment partnershipMentionComment);
``` 

It works. Is this an expected behavior?

### Steps to reproduce the problem

/ #
```java
public abstract PartnershipMentionCommentDto mapTo(PartnershipMentionComment partnershipMentionComment);

public abstract Collection<PartnershipMentionCommentDto> mapTo(Collection<PartnershipMentionComment> partnershipMentionComments);

@IterableMapping(qualifiedByName = "mapToWithoutChildren")
public abstract Collection<PartnershipMentionCommentDto> mapToWithoutChildren(
        final Collection<PartnershipMentionComment> partnershipMentionComments);

@Named("mapToWithoutChildren")
@Mapping(target = "children", ignore = true)
public abstract PartnershipMentionCommentDto mapToWithoutChildren(PartnershipMentionComment partnershipMentionComment);
``` 

### MapStruct Version

Mapstruct 1.5.5.Final

**Comment by Zegveld** [comment] 2023-05-04 17:36
this is caused by the `public abstract PartnershipMentionCommentDto mapTo(PartnershipMentionComment partnershipMentionComment);` method. The field `children` which that method wants to map has 2 viable options.

You need to tell mapstruct which one you want to use:
1. `public abstract Collection<PartnershipMentionCommentDto> mapTo(Collection<PartnershipMentionComment> partnershipMentionComments);`
2. `public abstract Collection<PartnershipMentionCommentDto> mapToWithoutChildren(
        final Collection<PartnershipMentionComment> partnershipMentionComments);`

Closing this as it is not a bug, but expected behavior. However feel free to reply to this for more clarification to get your issue sorted out.

**Closed by Zegveld** 2023-05-04 17:36 UTC
Labels: bug

**Comment by lpedrov** [comment] 2023-05-04 18:40
It is! Odd! Then how do you explain that works with @Named("")?

And in my first example I'm telling mapstruct which to use

```java
@Named("mapTo")
 public abstract PartnershipMentionCommentDto mapTo(PartnershipMentionComment partnershipMentionComment);

 @IterableMapping(qualifiedByName = "mapTo")
 public abstract Collection<PartnershipMentionCommentDto> mapTo(Collection<PartnershipMentionComment> partnershipMentionComments);

 @IterableMapping(qualifiedByName = "mapToWithoutChildren")
 public abstract Collection<PartnershipMentionCommentDto> mapToWithoutChildren(
        final Collection<PartnershipMentionComment> partnershipMentionComments);

 @Named("mapToWithoutChildren")
 @Mapping(target = "children", ignore = true)
 public abstract PartnershipMentionCommentDto mapToWithoutChildren(PartnershipMentionComment partnershipMentionComment);
``` 

As you can see, but if it's made some other way why you didn't puted an example?

**Comment by Zegveld** [comment] 2023-05-04 19:10
> As you can see, but if it's made some other way can you explain how? And "qualifiedByName" and "Named" do not seem work as expect too.

I figured that my explanation might feel a bit shorted, so here is a longer one with some semi-code:

As I said in my reply the issue is caused by the attempt to implement this method: `public abstract PartnershipMentionCommentDto mapTo(PartnershipMentionComment partnershipMentionComment);`.
```
 @Override
 public PartnershipMentionCommentDto mapTo(PartnershipMentionComment partnershipMentionComment){
    // do checks and stuff
    // attempt to map the children field.
    // find 2 options --> Ambiguous error.
    // signature 1: Collection<PartnershipMentionCommentDto> mapTo(Collection<PartnershipMentionComment>)
    // signature 2: Collection<PartnershipMentionCommentDto> mapToWithoutChildren(Collection<PartnershipMentionComment>)
 }
```

Adding the `@Named` to either of these 2 signatures will make mapstruct not use that one. For example:
```
public abstract PartnershipMentionCommentDto mapTo(PartnershipMentionComment partnershipMentionComment);

 @IterableMapping(qualifiedByName = "mapTo")
 public abstract Collection<PartnershipMentionCommentDto> mapTo(Collection<PartnershipMentionComment> partnershipMentionComments);

 @IterableMapping(qualifiedByName = "mapToWithoutChildren")
 @Named("mapToWithoutChildren")
 public abstract Collection<PartnershipMentionCommentDto> mapToWithoutChildren(
        final Collection<PartnershipMentionComment> partnershipMentionComments);

 @Named("mapToWithoutChildren")
 @Mapping(target = "children", ignore = true)
 public abstract PartnershipMentionCommentDto mapToWithoutChildren(PartnershipMentionComment partnershipMentionComment);
```

Will result in:
```
@Override
public PartnershipMentionCommentDto mapTo(PartnershipMentionComment partnershipMentionComment) {
    // because the other has @Named and there is no qualified by name mapping present:
    // map children using the method with signature `Collection<PartnershipMentionCommentDto> mapTo(Collection<PartnershipMentionComment>)`
}

@Override
 public Collection<PartnershipMentionCommentDto> mapTo(Collection<PartnershipMentionComment> partnershipMentionComments){
   // because the other has @Named and there is no qualified by name mapping present:
   // uses the method with signature `PartnershipMentionCommentDto mapTo(PartnershipMentionComment)`
 }

@Override
 public Collection<PartnershipMentionCommentDto> mapToWithoutChildren(
        final Collection<PartnershipMentionComment> partnershipMentionComments){
   // because of the qualified by name mapping:
   // uses the method with signature `PartnershipMentionCommentDto mapToWithoutChildren(PartnershipMentionComment)` 
 }

@Override
 public abstract PartnershipMentionCommentDto mapToWithoutChildren(PartnershipMentionComment partnershipMentionComment){
   // does not map children because of the ignore mapping.
 }
```

So the following will take place with the above example in a stack:
1. `PartnershipMentionCommentDto mapTo(PartnershipMentionComment)` is called
2. for children: `Collection<PartnershipMentionCommentDto> mapTo(Collection<PartnershipMentionComment>)` is called
3. `PartnershipMentionCommentDto mapTo(PartnershipMentionComment)` is called for each child
4. go to 2.

At some point there are no children or you end up in an infinite loop a.k.a. StackOverflowException.

So as shown in the above examples adding the `@Named` to the singular method has no effect. However adding it to one of the Iterable methods does have an effect because that is where it went wrong. MapStruct could not decide which of the two Iterable methods it should use.

Depending on if you want to map the entire tree or just the first level you need decide which of the 2 Iterable methods to annotate with `@Named`.
