### ISSUE TITLE
Better support for builder pattern classes

### ISSUE THREAD

**Issue by mheidt** [mapstruct/mapstruct#2331] opened 2021-01-14 22:23 UTC
If the class contains a static Builder inner class, the generated implementation only contains the line
```
Builder foo = FooClass.builder();
return foo.build();
```

I have to add 
`@Mapping(target="withId")
`
to get mapstruct add a line like
`foo.withId(dto.getId());`

It would be nice, if not only fields with get/set are considered but those that only have with-methods as well.

**Comment by filiphr** [comment] 2021-01-15 15:13
Closing this as a duplicate of #2330

**Closed by filiphr** 2021-01-15 15:13 UTC
