### ISSUE TITLE
unmappedTargetPolicy does not affect missing nested target properties

### ISSUE THREAD

**Issue by petoalbert** [mapstruct/mapstruct#1266] opened 2017-08-09 10:13 UTC
Suppose we have the following classes:

    class A {
        int x;
        int y;
    }

    class B {
        int x;
        int y;
     }

     class C {
         B nested;
     }

In this case, I would expect the following mapping to generate a warning or error (depending on the value of unmappedTargetPolicy), because there is no mapping specified for `nested.y`, but mapstruct _does not generate any warning or error_ during the build:

    @Mappings({
        @Mapping(target = "nested.x", source = "x")
    })
    C mapX(X x);

It would be nice to have this feature in mapstruct.

**Comment by filiphr** [comment] 2017-08-16 20:02
@petoalbert You are explicitly mapping `nested.x` to `x` and for this reason MapStruct is only generating that mapping, we can't know what you mean to map.

If you want to map the `nested` to the source parameter than you can do something like:

```java
@Mappings({
    @Mapping(target = "nested", source = "in")
})
C mapX(A in);
```

And then you will get correctly the warning or error in case something is not mapped.

**Comment by filiphr** [comment] 2017-09-03 17:19
@petoalbert I am going to close this issue as the current nested mappings work as designed. If you have ideas how we can achieve what you need please let us know

**Closed by filiphr** 2017-09-03 17:19 UTC

**Comment by sp4ce** [comment] 2020-11-17 18:30
@filiphr you did not really answer the issue when you said

> You are explicitly mapping nested.x to x and for this reason MapStruct is only generating that mapping, we can't know what you mean to map.

The problem is is that `nested.y` is not mapped and this should generate a warning. I think the idea behing the initial request is that MapStruct should consider the entire object hierarchy, not only the first level.

So on a more "real" example

```java

Class PersonDto {
  PetDto pet;
}

Class PetDto {
  long id;
  String name;
}

@Mapping(target = "pet.name", source = "name")
PersonDto toPersonDto(String name);
```
Here you can easily see that the `PetDto` would be missing its `id`.

**Comment by filiphr** [comment] 2020-11-21 07:37
I understand the point @sp4ce, but using nested target properties is a really tricky one, there is a big complexity in that area, especially when we try to create forged methods. There are cases where we should emit warning and there are times where we shouldn't.

You could be mapping the nested target `pet` from different totally unrelated sources.

I would suggest doing something like the following:

```
@Mapping(target = "pet", source = "person")
PersonDto toPersonDto(Person person);

@Mapping(target = "name", source = "petName")
PetDto toPersonDto(Person person);
```
