### ISSUE TITLE
Intellij support

### ISSUE THREAD

**Issue by mdeinum** [mapstruct/mapstruct#520] opened 2015-03-27 10:52 UTC
Would be nice if there would also be IntelliJ IDEA support. 

JetBrains issue is [IDEA-138364](https://youtrack.jetbrains.com/issue/IDEA-138364) add some votes then it might be picked up.

**Comment by agudian** [comment] 2015-03-27 11:05
Great, thanks for opening up that issue in the JetBrains tracker. I've placed my vote. :+1: 

We already have an Eclipse plugin in the works (with code-completion for source/target, more features to come).

In case JetBrains doesn't create such a plugin, maybe you'd like to bootstrap one yourself here with us?

**Comment by krishna81m** [comment] 2015-09-25 22:03
We see an issue with Tomcat plugin, it packages all generated resources correctly in right package in WAR but when doing a local debug, these generated sources are not available. This is only with IntelliJ. Is anybody aware of this issue? 

The obvious hack is to add the generated sources class to the plugin classpath.

**Comment by thekalinga** [comment] 2017-03-14 08:08
After migrating to the latest versions of lombok & mapstruct, intellij throws duplicate class error.

Here are the steps to reproduce the error.

1. Run `./gradlew clean compileJava` from terminal
2. Debug spring boot application from Intellij

You would get a duplicate class error.

This is because intellij is creating its own version of generated source under `build/classes/main/generated`, but the gradle plugin (from terminal) is generating the same source under `build/generated/` & registering this path as a source in intellij.

This is causing Intellij to find another class with the same name under the same package when it tries to compile, so it bailing out saying there is a duplicate class.

Temp work around for this problem is to do a `./gradlew clean` & dont run gradle compileJava task from terminal.

Now if you try to debug, intellij will continue to generate the source in its default location & since we dint run `compileJava` from terminal, it finds only one source in its source paths.

**Comment by filiphr** [comment] 2017-03-14 18:57
@thekalinga this looks like a problem with your IntelliJ setup (or a bug in IntelliJ). Check your settings under `Build, Execution, Deployment -> Compiler -> AnnotationProcessors`

For me with Maven and the IntelliJ 2017.1 EAP (171.3780.15) it works.

**Comment by thekalinga** [comment] 2017-03-15 11:36
I'm using `IntelliJ IDEA 2016.3.5`, not EAP. Not sure if this the culprit/there is an issue with gradle builds.

**Comment by filiphr** [comment] 2017-08-09 07:56
I have started working on a plugin for IntelliJ. [mapstruct-idea](https://github.com/mapstruct/mapstruct-idea) is the name of the repository that you can watch and create issues for.

The plugin is not yet published as it is WIP. Currently there is only support for autocompletion for `componentModel` and rudimentary auto-completion and go to declaration for `source` and `target`. Feel free to open issues there with suggestion about what you want to see in the plugin.

**Comment by gimoh** [comment] 2017-08-14 14:56
@filiphr what should the settings under `Build, Execution, Deployment -> Compiler -> AnnotationProcessors` be? I've enabled _annotation processing_ in there, but it didn't seem to make a difference

do you also need to have builds delegated to Gradle in `Build, Execution, Deployment -> Gradle -> Runner`? (that seems to work for me although it's a bit slower)

**Comment by gimoh** [comment] 2017-08-16 07:33
@filiphr OK, I get it now, I thought that if you enable annotation processing in IntelliJ (`Build, Execution, Deployment -> Compiler -> AnnotationProcessors`) you don't need to delegate to Gradle

If you are delegating to Gradle, does annotation processing still need to be enabled in IntelliJ?

**Comment by filiphr** [comment] 2017-08-16 07:37
@gimoh if you are delegating to Gradle, the enabling of annotation processing in IntelliJ does nothing as IntelliJ will use Gradle to compile your code.

Enabling annotation processing in IntelliJ can theoretically work if you don't use the `apt` plugin, and you define the dependency in such way that IntelliJ can pick it up and see the processor.

**Comment by filiphr** [comment] 2017-09-19 22:28
I am happy finally close this issue 😄.

We have released our plugin the the Jetbrains repository. [Here](http://mapstruct.org/news/2017-09-19-announcing-mapstruct-idea/) is a link to our announcement and [here](https://plugins.jetbrains.com/plugin/10036-mapstruct-support) is the link to the plugin.

Give it a go and feel free to give us feedback and suggestions into its own repository at [mapstruct-idea](https://github.com/mapstruct/mapstruct-idea)

**Closed by filiphr** 2017-09-19 22:28 UTC

**Comment by lex-em** [comment] 2017-09-25 04:51
it is awesome!
