### ISSUE TITLE
No nullcheck for nested source-properties with simple type-conversion in in 1.1.0CR1 

### ISSUE THREAD

**Issue by svendig** [mapstruct/mapstruct#912] opened 2016-09-28 08:19 UTC
Mapstruct 1.1.0CR1 behaves different to Beta2, when mapping nested source-properties, that need a simple type-conversion. In CR1 no nullcheck is generated, what might potentially lead to Nullpointers.
Is there a new configuration I'm missing or is this a bug?

The objects to map:
```java
public class Source {
   private SubSource sub;
	public SubSource getSub() {
		return sub;
	}
	public void setSub(SubSource sub) {
		this.sub = sub;
	}
}

public class SubSource {
	private Integer prop;
	public Integer getProp() {
		return prop;
	}
	public void setProp(Integer prop) {
		this.prop = prop;
	}
}

public class Target {
	private BigDecimal prop;
	public BigDecimal getProp() {
		return prop;
	}
	public void setProp(BigDecimal prop) {
		this.prop = prop;
	}
}
```

The mapper:
```java
@Mapper
public interface SourceTargetMapper {
  @Mapping(target ="prop", source="sub.prop")
  Target map(Source source);\n
}
```

The CR1 result:
```java
public class SourceTargetMapperImpl implements SourceTargetMapper {

    @Override
    public Target map(Source source) {
        if ( source == null ) {
            return null;
        }

        Target target = new Target();

        target.setProp( BigDecimal.valueOf( sourceSubProp( source ) ) );

        return target;
    }

    private Integer sourceSubProp(Source source) {

        if ( source == null ) {
            return null;
        }
        SubSource sub = source.getSub();
        if ( sub == null ) {
            return null;
        }
        Integer prop = sub.getProp();
        if ( prop == null ) {
            return null;
        }
        return prop;
    }
}
```

In Beta2 there is an additional nullcheck generated:
```java
public class SourceTargetMapperImpl implements SourceTargetMapper {

    @Override
    public Target map(Source source) {
    ...
        if ( sourceSubProp( source ) != null ) {
            target.setProp( BigDecimal.valueOf( sourceSubProp( source ) ) );
        }
    ...
    }

    private Integer sourceSubProp(Source source) {
        ...
    }
}
```

**Comment by sjaakd** [comment] 2016-09-29 16:28
@svendig: are you really sure?  I thought I covered this case in issue #891. See also `org.mapstruct.ap.test.bugs._891`.  I solved this in CR1 but it was failing in Beta2.

**Comment by gunnarmorling** [comment] 2016-09-29 17:30
Seems we should verify/fix this before the final.

**Comment by svendig** [comment] 2016-09-29 18:21
@sjaakd: You are right, this issue is a duplicate to #891, that also relates to 1.1.0.CR1. I guess you fixed it for 1.1.0.Final.

**Comment by gunnarmorling** [comment] 2016-09-29 18:39
@svendig, so can you confirm it works on the current master if you built
MapStruct yourself and use that SNAPSHOT version?

**Comment by svendig** [comment] 2016-09-30 07:26
@sjaakd @gunnarmorling: yes i can confirm that this issue is fixed in the SNAPSHOT version.
### The generated Mapper:
```java
@Override
public Target map(Source source) {
    ...
    Integer integer = sourceSubProp( source );
    if ( integer != null ) {
        target.setProp( BigDecimal.valueOf( integer ) );
    }
    ...
}
```

**Comment by sjaakd** [comment] 2016-09-30 19:54
@svendig .. thanks a lot for verifying I'm going to close this as duplicate of #891

**Closed** 2016-09-30 19:55 UTC
Labels: duplicate
