### ISSUE TITLE
Provide a way to customize templates

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#706] opened 2015-12-08 20:17 UTC

**Comment by sjaakd** [comment] 2015-12-08 20:29
:smile: Perhaps via some kind of SPI mechanism

**Comment by yntelectual** [comment] 2016-03-13 16:21
Hi, any plans on this? Custom templates would be very beneficial in many cases. For example if I want to add some custom logic for every instance of specific class, or customize collection mapping(Due to hibernate lazy loading proxies, etc.)

**Comment by agudian** [comment] 2016-03-13 17:01
Can you give a more specific example of what you try to do? Perhaps the BeforeMapping/AfterMapping methods could already help you?

**Comment by yntelectual** [comment] 2016-03-13 18:09
Thanks for your quick reply. When you have an entity loaded from DB, that has many lazily loaded relationships that are not loaded at the time of mapping, you either have to ignore them manually via `@Mapping` or load them - which goes against the point of lazy loading. Hibernate uses custom Collection types to enable this functionality - e.g. a wrapper on top of `Set` or `ArrayList` which internally checks, whether the contents have been loaded from DB, or throws LazyInitializationException when you try to access it(i.e. Mapper will trigger this exception when it does the implicit Collection mapping). 
My goal would be to somehow check every collection object, before it gets mapped, whether it is an instance of Hibernate `PersistentCollection`, and if it is, whether it has been initialized. If it is not initialiazed, then skip it. With `BeforeMapping` I can only catch specific attributes.
Another use case is HATEOAS meta information in every object. Say, for every eventy a `_link` attribute should be set pointing to REST url where it can be loaded. 

Especially the safe handling of lazy loaded collections would be very handy. I have tried to come up with an elegant solution using the current API, but the closes I got is to write a decorator for every entity, and check its fields via reflection :/

**Comment by agudian** [comment] 2016-03-13 19:19
> With BeforeMapping I can only catch specific attributes.

Not necessarily, as it works on super types as well, e.g. to be invoked for all mapping methods that map from a `List<? extends AbstractEntity>` (if you have such a type or marker interface). But you are right, such a method would not be able to prevent loading the collection. On the other hand, I would find it odd that the mapper would create different results based on whether the entity has been fully initialized or not. That kind of internal state should remain internal, as it changes as a side effect of the instances previous usage - or in case of batch fetching, the previous usage of other instances of the same type. If the consumers of the result type don't need the information in the collection, then the result type shouldn't contain that property. But if a consumer needs the collection, it should always be fully mapped. Otherwise you might get into serious trouble at some point... But it's your application :wink:. If you want to go down that road, the only way currently is to create a decorator wrapping the collection-property mapping methods.

For the second use case, the HATEOAS, that sounds like somethink that should be doable quite nicely with `@AfterMapping` methods, possibly even only one if your data model is generic enough.

Totally made-up example:
```java
@AfterMapping
public void addLink(BaseEntity source, @MappingTarget DocumentWithMetadata target) {
  target.addLinkMetadata( LinkFactory.createLinkForEntity( source ) );
}
```

**Comment by yntelectual** [comment] 2016-03-13 19:52
I appreciate your feedback. The HATEOAS approach with `@AfterMapping` is nice indeed. However, with the association mapping, I still think that the mapping should be able to assist in handling association expansion. I understand, that it could be handled by different DTO models but still. Consider a very RESTfull example, when you one main entity, say `Issue` that has many associations. When you are querying issues as list, via `GET /issues` you probably expect a list of DTO objects(`List<IssueDTO>`), containing only basic attributes of every item. Once you want to load the detail of specific item `GET /issues/123` the same `IssuesDTO` could now have several of its most common associations expanded, say `issue.project` or `issue.reporter`. Many REST API services provide a way of customizing, what associations should be loaded. An example from JIRA API `rest/api/latest/issue/JRA-9?expand=names,renderedFields,comments`. One approach is to create several different mapper methods, based on the ignored/included associations e.g. `IssueMapper.toDTOBasic, IssueMapper.toDTOComplete`, but it seems error prone when the model changes, or refactors as you have to specify attribute names as string.  I would like to hear your opinion on this.  Do you see any feasible way how a similar requirement might be fulfilled with Mapstruct at present form? Would you be interested in such feature if someone implemented it?

**Comment by agudian** [comment] 2016-03-13 20:17
The solution with the different mapping methods would have been my next proposal as well... :+1: 
Regarding the refactorings, you'd be safe from renaming / removed properties as MapStruct throws an error at you at compile time. But you'd still have to think about adding the `ignore` to the more basic mappings when you add a new lazy collection.

Regarding your example, I'd still prefer using `BasicIssueDto` for search results and `IssueDto extends BasicIssueDto` for the full beauty - it just feels like the easiest thing to do. For the request-driven expansion of selected properties, I'm not sure if that's something that MapStruct is right for. 

Anyway, how would you propose such a problem could be solved with MapStruct? What would the user configure for the mapper and how would the generated code look like?

Hanging up the carrot, even it it turns out not to be something suitable for MapStruct itself, there are already some ways to manipulate the generator results by adding adding a custom jar to the processor-classpath. So I'm sure we'll find a solution for you in any case.

**Comment by yntelectual** [comment] 2016-03-13 20:57
Could you elaborate on the generator manipulation via custom jar(or point me to some resources)? 
Request driven expansion should not be handled by Mapstruct - it should just handle mapping into single DTO class from source entity with various level of association loading.
I do see different options how to handle this problem and until I found any better approach I will surely be able to achieve my goals with tools at hand. But maybe some kind of extension mechanism would make for a more elegant solution. I was thinking along the lines of `jackson-datatype-hibernate` for example. An optional module that is registered as dependency and extends the mapper at specifically defined points - in this case it would intercept mapping of complex types and collections and skip mapping any lazily loaded proxy attributes that are not initialized without throwing err on access.. If there was a facility to plug in some logic inside the mapping mechanism, then I could create a general policy for all instances of certain type, or wrap a bunch of common `AfterMapping` features into a single package that gets included into every new project. 
Extension could have access to `delegate` object - so that it could invoke the default mapping operations(e.g. my hibernate collections is loaded, just map it as usual)
And while I am at it, how could Mapstruct handle mapping from `Collection<Entity>` to some wrapper DTO object, say 
```java
class CollectionWrapper<T> {
  private String _link;
  private long size;
  private long offset;
  private long totalCount;
  private List<T> items;
}
```
So that I could map:
```java
class Foo {
  private List<Bar> bars;
}
```
into 
```java
class FooDTO {
  private CollectionWrapper<BarDTO> bars;
}
```
Thanks again for your efforts and let me know if I am getting too specific, so that I do not pollute this issue with unrelated comments.

**Comment by agudian** [comment] 2016-03-14 19:48
The currently possible way of adding customizations is via the ServiceLoader mechanism. Implement `ModelElementProcessor<Mapper, Mapper>` with a priority after that of the implementation `MapperCreationProcessor` (it creates most of the internal model for a mapper) and before `MapperRenderingProcessor` (which writes the mapper to a .java file).
Your implementation needs to be registered in your jars `META-INF/services/org.mapstruct.ap.internal.processor.ModelElementProcessor` file for MapStruct to pick it up (via ServiceLoader).
What you would do is somehow adapt or wrap the `PropertyMapping` instances with your own customization type (most of the model is immutable, so you might have to create matching delegators or something).
Another thing you need to know is that each part of the model is transformed to the Java code using a Freemarker template fragment with the same package-path / file name (at least by default for most of our model classes - check what's in `src/main/resources/**/*.ftl`). That way you can scan for `PropertyMapping` instances that need addititional code wrapping the original code snippet, replace it with a custom decorator for that type, add a template for it with the delegation to the wrapped delegate within the template, e.g.:
```
if ( HibernateHelper.isInitialized( ${delegate.assignment.sourceReference} ) ) {
    <@includeModel object=delegate />
}
```
Something along that way... 
But you are right, we pollute this issue. Would be great if we could move this to the Mailing-List or something.

In any case, if you go forward with the customization, please let us know what you did. Currently we have all the necessary stuff in `*.internal.*` packages to make clear that we won't go any lengths to keep the classes compatible between releases. Getting feedback on what people use and how is important to us to getting an idea of how a more stable API/SPI would need to support.

**Comment by gbogaert** [comment] 2016-10-05 12:37
@agudian I'm very interested in the mechanism of template overriding.
Could you detail the mechanism plz ?

**Comment by rinaldodev** [comment] 2020-02-08 11:39
@agudian so I've been messing with MapStruct's code last night and trying to implement what you suggested.

I did implement a new Processor like you said, but I just don't know how to tinker with the PropertyMappings. 
I tought about implemeting a Wrapper, like you suggested, but I can't just replace the PropertyMapping with my own Wrapper, because it's a different type and the BeanMappingMethod ony accepts PropertyMappings. 
The other way I tought was with inheritance, but PropertyMapping also doesn't seem suitable for that.

Is there anything I'm missing here? Maybe my understanding of what you suggested is oversimplified?

**Comment by martinsefcik** [comment] 2020-02-13 05:10
@rinaldodev Yes, private constructor(s) on objects like PropertyMapping are very limiting. It does not help to me to create dynamic proxies from them and replace them in Mapper via reflection. Still cannot change getTemplateName() behaviour in PropertyMapping as it is not executed outside PropertyMapping but internally.

It's nice to have option to create and register new Processor, but It cannot do to much with existing sourceModel.

Maybe another way would be to replace TemplateLoader in configuration, but I didn't try it yet.

**Comment by mickroll** [comment] 2020-07-21 08:04
This feature would be highly appreciated. Would solve so many customization problems.
Ours is this: we want the Mapper to throw a custom Exception for an unknown enum value, instead of an `IllegalArgumentException`. With a slightly modified `ValueMappingMethod.ftl` this woud be a no-brainer.

**Comment by sjaakd** [comment] 2020-07-25 07:19
@mickroll the problem is that you'll have to define a clean interface inside MapStruct. Although the current FTL template suit MapStruct, it's not said that we are going to rely on this in the future. One of the thoughts is to use Java Poet and make an all-java solution. 

You can imagine that we're stuck forever with it, when we open up templates as a means of interfacing with MapStruct.

**Comment by filiphr** [comment] 2020-07-25 09:58
I agree with @sjaakd on this one. Allowing custom templates is a pandora box, it would make it extremely difficult for us to do improvements if we open up customizing of templates.

I think that it is more beneficial to add certain SPIs that would allow to customize different things.

For example the requirement from @mickroll is to customize the thrown exception in the generated `ValueMapping`. Instead of changing the template we can allow SPI implementors to provide the exception that needs to be thrown.

We've added [EnumNamingStrategy](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/spi/EnumNamingStrategy.java) in 1.4. Perhaps we can rename that to `EnumMapingStrategy` and add a method that would return the `TypeElement` of the exception that it should be thrown. 

@mickroll and everyone else can you please create separate issues for the use cases that you have to change the templates.

**Comment by mickroll** [comment] 2020-07-27 06:43
@filiphr I have added #2169, including your idea of using an enhanced `EnumMappingStrategy`.

**Comment by sjaakd** [comment] 2020-10-12 20:47
@gunnarmorling .. Let's close this one. See mine and @filiphr 's comments above. We will find some way to customise.. But not via templates.. First we need to refactor (and perhaps use java poet) and go to a clean cut programmable interface.

**Closed by sjaakd** 2020-10-12 20:47 UTC
