### ISSUE TITLE
Version 1.5.3 doesn't consider Mapping annotations for nested objects (worked with 1.5.2)

### ISSUE THREAD

**Issue by Grosskopferter** [mapstruct/mapstruct#3057] opened 2022-10-19 10:15 UTC
### Expected behavior

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2022-10-19T12:05:51+0200",
    comments = "version: 1.5.2.Final, compiler: Eclipse JDT (IDE) 1.4.200.v20220802-0458, environment: Java 11.0.16.1 (Eclipse Adoptium)"
)
@Component
public class TestMapperImpl extends TestMapper {

    @Override
    public Model dtoToModel(DTO dto) {
        if ( dto == null ) {
            return null;
        }

        Model model = new Model();

        model.setModelField( dto.getDtoField() );
        model.setNested( dtoToModel( dto.getNested() ) );

        return model;
    }
}
```

### Actual behavior

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2022-10-19T12:08:22+0200",
    comments = "version: 1.5.3.Final, compiler: Eclipse JDT (IDE) 1.4.200.v20220802-0458, environment: Java 11.0.16.1 (Eclipse Adoptium)"
)
@Component
public class TestMapperImpl extends TestMapper {

    @Override
    public Model dtoToModel(DTO dto) {
        if ( dto == null ) {
            return null;
        }

        Model model = new Model();

        model.setModelField( dto.getDtoField() );
        model.setNested( dTOToModel( dto.getNested() ) );

        return model;
    }

    protected Model dTOToModel(DTO dTO) {
        if ( dTO == null ) {
            return null;
        }

        Model model = new Model();

        model.setNested( dtoToModel( dTO.getNested() ) );

        return model;
    }
}
```

### Steps to reproduce the problem

Model class:
```
public class Model {
	private String modelField;
	private Model nested;

	public String getModelField() {
		return modelField;
	}

	public void setModelField(String modelField) {
		this.modelField = modelField;
	}

	public Model getNested() {
		return nested;
	}

	public void setNested(Model nested) {
		this.nested = nested;
	}

}
```

DTO class:
```
public class DTO {

	private String dtoField;

	private DTO nested;

	public String getDtoField() {
		return dtoField;
	}

	public void setDtoField(String dtoField) {
		this.dtoField = dtoField;
	}

	public DTO getNested() {
		return nested;
	}

	public void setNested(DTO nested) {
		this.nested = nested;
	}

}
```

Mapper:
```
@Mapper(componentModel = "spring")
public abstract class TestMapper {

	@Mapping(target = "modelField", source = "dtoField")
	public abstract Model dtoToModel(DTO dto);

}
```

### MapStruct Version

MapStruct 1.5.3

**Comment by Zegveld** [comment] 2022-10-20 17:54
## Analysis
the cause of this change lies with the fix for this issue: #2825
For subclassmappings we do not want to consider the original method as a possible method.
This change also affected all other mappings like the above one.

**Closed** 2022-11-04 13:21 UTC
Labels: bug
