### ISSUE TITLE
Ordering of mapstruct and lombok gradle annotationProcessor seems to matter

### ISSUE THREAD

**Issue by kaweston** [mapstruct/mapstruct#1581] opened 2018-08-09 22:30 UTC
In a work project I have to ensure that the lombok annotationProcessor directive is listed after mapstruct otherwise various errors occur.  Identical behaviour whether running gradle from command line or via the gradle window in Intellij.

```
// Good setup
dependencies {
   compile("org.mapstruct:mapstruct-jdk8")

    annotationProcessor("au.com.agic.api:commons-mapping")
    annotationProcessor("org.mapstruct:mapstruct-processor")
    annotationProcessor("org.projectlombok:lombok") <<=== Lombok after mapstruct

    testAnnotationProcessor("au.com.agic.api:commons-mapping")
    testAnnotationProcessor("org.mapstruct:mapstruct-processor")
    testAnnotationProcessor("org.projectlombok:lombok")

    // Other dependencies

}

// Error setup
 dependencies {
   compile("org.mapstruct:mapstruct-jdk8")

   annotationProcessor("org.projectlombok:lombok") <<=== Lombok before mapstruct
    annotationProcessor("au.com.agic.api:commons-mapping")
    annotationProcessor("org.mapstruct:mapstruct-processor")
   
   testAnnotationProcessor("org.projectlombok:lombok")
    testAnnotationProcessor("au.com.agic.api:commons-mapping")
    testAnnotationProcessor("org.mapstruct:mapstruct-processor")
    

    // Other dependencies

}
```

Sample of errors encountered.  Not sure if this matters but both TravelWhatIfPrice and ContactDetails use lombok Builder annotations although the Builder class are already defined without methods so that I can use the Jackson library's @JsonPOJOBuilder(withPrefix="") annotation to match with lombok's setter naming convention.

......CsApi2TravelWhatIfPricesMapper.java:11: error: au.com.agic.api.travel.domain.TravelWhatIfPrice does not have an accessible parameterless constructor.
    TravelWhatIfPrice toModel(final CsApi2TravelWhatIfPrice csApi2TravelWhatIfPrice);

....... CsApi2ContactDetailsMapper.java:23: error: Property "id" has no write accessor in au.com.agic.api.travel.domain.ContactDetails.
    @Mapping(target = "id", source = "id")

**Comment by filiphr** [comment] 2018-08-18 08:47
The order should not matter. However, I think that the problem with the builders is https://github.com/rzwitserloot/lombok/issues/1538. During compilation we can't see the builder and the builder methods from Lombok. If you split the Lombok and MapSruct mappers into 2 different modules then it is going to work. You can chime in on the linked Lombok issue.

What do you mean with

>Builder class are already defined without methods so that I can use the Jackson library's @JsonPOJOBuilder(withPrefix="") annotation to match with lombok's setter naming convention.

**Comment by filiphr** [comment] 2018-08-20 03:31
Thanks for providing more information. I'll dig into it to see what is happening. It seems that when you declare your builder there is something affecting the issue I linked. In any case I am fairly certain that the actual problem is the fact that MapStruct does not see the accessors of the builder, due to Lombok not exposing them

**Comment by AnkushNakaskar** [comment] 2019-04-16 04:43
Hi @filiphr ,
I am also facing the same issue,Will you be able let me know, is it still in process?

**Comment by filiphr** [comment] 2019-05-04 21:28
@kaweston I checked this and for some reason when mapstruct is before lombok then we see all the builder methods, but when we are after lombok then we don't see the builder methods, but we do see the getters. I can't explain this. This is with the latest (1.18.6) version.

@AnkushNakaskar if you swap the order is it working? Which Lombok version are you using?

**Comment by reitzig** [comment] 2020-08-04 16:48
We seem to have a similar issue. For us, this made the code compile (again):

![image](https://user-images.githubusercontent.com/4246780/89321291-120b1f00-d683-11ea-8eac-6bdf0ebc4c3c.png)

If we find time, we'll provide an MWE in a separate issue.

**Comment by hydra1983** [comment] 2021-11-10 08:44
It does matter.

```Dependency order```

```java
// before
annotationProcessor("org.projectlombok:lombok")
annotationProcessor("org.mapstruct:mapstruct-processor:${Versions.mapstructVersion}")

// after
annotationProcessor("org.mapstruct:mapstruct-processor:${Versions.mapstructVersion}")
annotationProcessor("org.projectlombok:lombok")
```

```Generated code```

```java
// before
Task = new Task();

return task;

// after
TaskBuilder task = Task.builder();

task.id( source.getId() );
task.serialNumber( source.getSerialNumber() );

return task.build();
```

**Comment by filiphr** [comment] 2021-11-13 16:05
@hydra1983 the order should not matter. I would suggest upgrading Lombok and also adding the `lombok-mapstruct-binding` dependency as well. I tried your example in our [mapstruct-lombok](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-lombok) example and everything works fine.

I am going to close this until someone can provide an example project where this is reproducible

**Closed by filiphr** 2021-11-13 16:05 UTC

**Comment by remal** [comment] 2021-11-14 18:33
@filiphr I faced the same issue and fixed it with some Gradle tricks. Unfortunately, I can't provide you with an example because it's not an open-source project and Gradle config is really complex.

**Comment by hydra1983** [comment] 2022-03-13 10:12
@filiphr Got the problem fixed. As it's caused by something like #2260. I ignored all the mappings, and set the value in decorator.

**Comment by hydra1983** [comment] 2022-03-23 18:24
@remal This is my gradle kotlin configuration and it works fine. The order do matters.
```kotlin
// mapstruct + lombok
    compileOnly("org.projectlombok:lombok:${Versions.lombokVersion}")
    compileOnly("org.mapstruct:mapstruct:${Versions.mapstructVersion}")
    annotationProcessor("org.projectlombok:lombok:${Versions.lombokVersion}")
    annotationProcessor("org.mapstruct:mapstruct-processor:${Versions.mapstructVersion}")
    annotationProcessor("org.projectlombok:lombok-mapstruct-binding:${Versions.lombokMapStructBindingVersion}")
```

```bash
java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
Eclipse OpenJ9 VM (build openj9-0.21.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20200728_646 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - c82ff0c20f based on jdk8u265-b01)
```

```bash
./gradlew --version

------------------------------------------------------------
Gradle 7.3.3
------------------------------------------------------------

Build time:   2021-12-22 12:37:54 UTC
Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_265 (Eclipse OpenJ9 openj9-0.21.0)
OS:           Mac OS X 10.15.7 x86_64
```

```kotlin
    const val mapstructVersion = "1.4.2.Final"
    const val lombokVersion = "1.18.22"
    const val lombokMapStructBindingVersion = "0.2.0"
```

**Comment by implermine** [comment] 2022-09-14 05:39
Is there no further discussion? i've experienced same issue with @hydra1983 and solved problem by `https://stackoverflow.com/a/68621947/16901221` , yet annotationProcessor's order has no matter?

**Comment by remal** [comment] 2023-03-31 23:53
@hydra1983 I had to create my own Lombok Gradle plugin to fix it: https://github.com/remal-gradle-plugins/lombok

**Comment by hydra1983** [comment] 2023-04-01 04:14
> @hydra1983 I had to create my own Lombok Gradle plugin to fix it: https://github.com/remal-gradle-plugins/lombok

Cool, I will have a try. Thanks a lot.
