### ISSUE TITLE
NPE - generating mapper that uses another mapper

### ISSUE THREAD

**Issue by thilken** [mapstruct/mapstruct#1374] opened 2018-02-08 09:38 UTC
Trying to generate a mapper during build in IntelliJ I got a NPE. The class to generate a mapper for is abstract, is annotated with Mapper annotation specfying a config and uses. It has several methods annotated with multiple Mapping annotations. Furthermore it has three methods annotated with AfterMapping that have a parameter annotated with MappingTarget. 

The corresponding mapper configuration is annotated with MapperConfig that specifies unmappedTargetPolicy as ReportingPolicy.ERROR, mappingInheritanceStrategy as MappingInheritanceStrategy.AUTO_INHERIT_FROM_CONFIG. It includes one method that is annotated with multiple Mapping annotations. Everyone specifies a target. Some additionally specify ignore as true, some others specify source and some use constant.

The stacktrace I got is:

Error:(54, 17) java: Internal error in the mapping processor: java.lang.NullPointerException
at org.mapstruct.ap.internal.model.source.SourceReference.copyForInheritanceTo(SourceReference.java:302)
at org.mapstruct.ap.internal.model.source.Mapping.copyForInheritanceTo(Mapping.java:366)
at org.mapstruct.ap.internal.model.source.MappingOptions.applyInheritedOptions(MappingOptions.java:142)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.mergeInheritedOptions(MapperCreationProcessor.java:416)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:260)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:143)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:114)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:73)
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:223)
at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:203)
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:169)
at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
at com.sun.tools.javac.main.Main.compile(Main.java:523)
at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:199)
at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:467)
at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:331)
at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:258)
at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:216)
at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1246)
at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:923)
at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:995)
at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:886)
at org.jetbrains.jps.incremental.IncProjectBuilder.access$500(IncProjectBuilder.java:68)
at org.jetbrains.jps.incremental.IncProjectBuilder$BuildParallelizer.lambda$queueTask$0(IncProjectBuilder.java:857)
at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

**Comment by filiphr** [comment] 2018-02-08 22:43
@thilken can you tell us which version of MapStruct you are using? Also if you can provide us some code, that reproduces the NPE, as well, it would be easier for us to help you out.

The line for the error is strange as there is nothing there in 1.2.0. And on top of that that method is 3 years old

**Comment by filiphr** [comment] 2018-02-19 23:13
Closing due to lack of requested feedback. If you provide us with more information we would be more than happy to reopen the issue

**Closed by filiphr** 2018-02-19 23:13 UTC
