### ISSUE TITLE
@AfterMapping method with multi-parameters of same type gets wrong argument list

### ISSUE THREAD

**Issue by shane-chen** [mapstruct/mapstruct#1804] opened 2019-05-03 11:34 UTC
Dear developers, 

I'm upgrading mapStruct to 1.3.0 in our project that uses mapStruct for years (it really does great job) and got problem in method annotated with @AfterMapping. I'm not sure, if it's a new feature or maybe a bug. In the following example, the mapAfter() method has two parameters of the same type: a and b. 
```
@Mapper()
public abstract class TestMapper {
    @Mapping(source = "entity.code", target = "code")
    abstract Dto mapEntity(Entity entity, Integer a, Integer b);
    
    @AfterMapping
    protected void mapAfter(@MappingTarget Dto dto, Integer a, Integer b) {
    }
}

class Entity {
    private String code;
     // getter/setter
}

class Dto {
    private String code;
  // getter/settter
}
```
The class generated will duplicate one parameter and call **mapAfter(dto, a, a)** instead of **mapAfter(dto, a, b)**.
```
@Component
public class TestMapperImpl extends TestMapper {

    @Override
    Dto mapEntity(Entity entity, Integer a, Integer b) {
        if ( entity == null && a == null && b == null ) {
            return null;
        }

        Dto dto = new Dto();

        if ( entity != null ) {
            dto.setCode( entity.getCode() );
        }

        mapAfter( dto, a, a ); // should be mapAfter(dto, a, b);

        return dto;
    }
}
```
If I change signatures and use a different type to mapEntity(Entity entity, Integer a, int b). mapAfter(@MappingTarget Dto dto, Integer a, int b), then the generated class is correct.
Is there a constraint that the type of parameter must be unique? 

Thanks and best,
Shengyao

**Comment by chris922** [comment] 2019-05-16 08:44
Thanks Shengyao for reporting this! That is definitely a bug and it should be fixed within PR #1782.
So it should be available in the next release. 

You can try with the current version from master to verify that the fix is also working for your use-case (basically just check out and call `mvn clean install -DskipDistribution=true`, see https://github.com/mapstruct/mapstruct#building-from-source)

I will close this issue, in case the fix is not working for you we can reopen it.

**Closed by chris922** 2019-05-16 08:44 UTC

**Comment by shane-chen** [comment] 2019-05-17 09:26
Hi Chris, thank you so much for your help. Best, Shengyao

**Comment by filiphr** [comment] 2019-05-21 11:10
Duplicate of #1457 (adding it for a reference only)

**Comment by ViktorZieg** [comment] 2021-11-18 12:03
Hey guys,

```
@Mapper()
public abstract class TestMapper {
    @Mapping(source = "entity.code", target = "code")
    abstract Dto mapEntity(Entity entity, OtherEntity b);
    
    @AfterMapping
    protected void mapAfter(@MappingTarget Dto dto, OtherEntity b) {
    }
}
```
In my case `Entity` has an Attribute with the type of `OtherEntity`. I just want to map the `OtherEntity` object to that field. Instead, it keeps mapping the `id` attribute of `OtherEntity` to `Entity`.
Not sure if I am right here, feel free to tell me where I can get help to this.

**Comment by filiphr** [comment] 2021-11-20 07:39
@ViktorZieg if you have questions then please use one of:

* [StackOverflow](https://stackoverflow.com/questions/tagged/mapstruct)
* [Gitter Room](https://gitter.im/mapstruct/mapstruct-users)
* [GitHub Disccussion](https://github.com/mapstruct/mapstruct/discussions)
