### ISSUE TITLE
MapStruct 1.3.0.Final fails to find a property on a parent class when a static method is present

### ISSUE THREAD

**Issue by fpavageau** [mapstruct/mapstruct#1728] opened 2019-02-19 17:18 UTC
I've pushed [a sample project](https://github.com/fpavageau/mapstruct-unknown-property), but I'll try to summarize here.

`MyEntity` has no properties but extends `AuditableEntity` which has `createdDate` et `lastModifiedDate`. `MyDto` has `createdDate` et `lastModifiedDate` directly. A mapper to convert `MyDto` into `MyEntity` fails to compile when `MyEntity` also has a static `builder()` method whose return type is a nested class (`MyEntity.MyEntityBuilder`). Yes, this looks like Lombok, but I've simplified the example not to use it.

The same code compiles with 1.2.0.Final.

**Comment by sjaakd** [comment] 2019-02-19 19:03
That's right.. We added builders in MapStruct 1.3.0.Final. So MapStruct recognises your builder. Checkout [this](https://github.com/mapstruct/mapstruct/issues/1713#issuecomment-463362918) to circumvent this. Duplicate of #1713

**Closed by sjaakd** 2019-02-19 19:03 UTC
