### ISSUE TITLE
Automap java.util.Optional

### ISSUE THREAD

**Issue by cdalexndr** [mapstruct/mapstruct#2477] opened 2021-06-10 15:47 UTC
- [x] Is this an issue (and hence not a question)? 

I get a bunch of errors `Can't map property "Optional<Value> entity.member" to "Value dto.member"`, so I have to add a bunch of useless mappings for each of my Optional parameter type:
```
String mapOptionalString( Optional<String> value ) {
   return value.orElse( null );
}

SomeClass mapOptionalSomeClass( Optional<SomeClass> value ) {
   return value.orElse( null );
}

etc...
```

**Comment by filiphr** [comment] 2021-06-12 08:46
I think that this is a duplicate of #674. Therefore I am going to close it.

An alternative workaround is to use:

```
public class OptionalUtils {

    public static <T> T fromOptional(Optional<T> optional) {
        return optional.orElse( null );
    }

}
```

Then in your mapper you can use 

```
@Mapper(uses = OptionalUtils.class)
public interface CustomMapper {

}
```

Note: this might not work on 1.4.2, but we have a fix on SNAPSHOT that should make this work.

**Closed by filiphr** 2021-06-12 08:46 UTC
