### ISSUE TITLE
Missing fields when mapping recursive nested objects

### ISSUE THREAD

**Issue by HoaiDang-work** [mapstruct/mapstruct#3062] opened 2022-10-25 17:07 UTC
### Expected behavior

Because my component have recursive children of the same class. I expect all component mapping is done using the same `toGrpc` method. Anyway to ensure the mapping to call the method `toGrpc` recursively.

### Actual behavior

Another method `componentToMediaTemplateComponent` is created to convert the first child level. Which does not set some fields.

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2022-10-25T23:47:03+0700",
    comments = "version: 1.5.3.Final, compiler: IncrementalProcessingEnvironment from gradle-language-java-7.5.1.jar, environment: Java 11.0.9 (Oracle Corporation)"
)
public class MediaTemplateComponentMapperImpl implements MediaTemplateComponentMapper {

    private final MediaTemplateAttributeMapper mediaTemplateAttributeMapper = Mappers.getMapper( MediaTemplateAttributeMapper.class );

    @Override
    public MediaTemplateComponent toGrpc(Component source) {
        if ( source == null ) {
            return null;
        }

        MediaTemplateComponent.Builder mediaTemplateComponent = MediaTemplateComponent.newBuilder();

        if ( source.getComponents() != null ) {
            for ( Component component : source.getComponents() ) {
                mediaTemplateComponent.addComponents( componentToMediaTemplateComponent( component ) );
            }
        }

        mediaTemplateComponent.setId( source.toTriggerComponent().getId() );
        mediaTemplateComponent.setContent( source.toTriggerComponent().getContent() );
        mediaTemplateComponent.setAltText( source.toTriggerComponent().getAltText() );

        return mediaTemplateComponent.build();
    }

    protected MediaTemplateComponent componentToMediaTemplateComponent(Component component) {
        if ( component == null ) {
            return null;
        }

        MediaTemplateComponent.Builder mediaTemplateComponent = MediaTemplateComponent.newBuilder();

        
        if ( component.getComponents() != null ) {
            for ( Component component1 : component.getComponents() ) {
                mediaTemplateComponent.addComponents( toGrpc( component1 ) );
            }
        }

        return mediaTemplateComponent.build();
    }
}
```

### Steps to reproduce the problem

I want to map Component to MediaTemplateComponent 
```
public class Component {

  List<Component> components;

  TriggerComponent toTriggerComponent();
}

public class MediaTemplateComponent {

  String id;
  String context;
  String altText;
  List<MediaTemplateComponent> components;

}

public interface MediaTemplateComponentMapper {

  MediaTemplateComponentMapper INSTANCE = Mappers.getMapper(MediaTemplateComponentMapper.class);

  @Mapping(target = "id", expression = "java(source.toTriggerComponent().getId())")
  @Mapping(target = "content", expression = "java(source.toTriggerComponent().getContent())")
  @Mapping(target = "altText", expression = "java(source.toTriggerComponent().getAltText())")
  MediaTemplateComponent toGrpc(Component source);

}
```

### MapStruct Version

1.5.3.Final

**Comment by Zegveld** [comment] 2022-10-25 18:35
duplicate of #3057 .

**Closed by Zegveld** 2022-10-25 18:35 UTC
Labels: bug
