### ISSUE TITLE
NPE in eclipse annotation processor

### ISSUE THREAD

**Issue by gliviu** [mapstruct/mapstruct#1352] opened 2017-12-06 16:56 UTC
Happens in eclipse oxygen when importing project with gradle eclipse plugin.
* git clone https://github.com/gliviu/mapstruct-error
* cd mapstruct-error
* gradle eclipse
* from eclipse File->Import->Existing projects into workspace->mapstruct-error
* from Project Explorer go to src/main/java/mapstruct/PersonDto.java and uncomment `//@Nullable`
* save file
* observe errors appearing in Converters.java - Internal error in the mapping processor: java.lang.NullPointerException  
![image](https://user-images.githubusercontent.com/8597812/33673574-d1b7e59e-dab5-11e7-8064-25f669720a37.png)

Importing project using **File->Import->Existing gradle project** does not suffer from this. I suppose the apt generation is done with Gradle avoiding completely Eclipse compiler.

**Comment by filiphr** [comment] 2017-12-06 22:37
@gliviu Can you share us the entire stacktrace of the error that occurs in Eclipse? I unfortunately have no Eclipse. 

By looking at the repo you provided, I see that there are no `@Nullable` providers in the project. Which means that there should be a compile error in `PersonDto`, is that correct? All this looks like some bug in the Eclipse compiler or our Eclipse specific workarounds not working correctly 😄 

Regarding importing the gradle project, it all comes down to whether you want to build to be performed by Eclipse or Gradle.

**Comment by gliviu** [comment] 2017-12-07 09:00
The nullable annotation exists - https://github.com/gliviu/mapstruct-error/blob/master/src/main/java/mapstruct/Nullable.java. Project should compile fine.

Strangely I never seen a stack trace for this error. Only what is shown in the screenshot above.
Tried again this morning and out of nothing I've got the stacktrace :smiley: 

```
Internal error in the mapping processor: java.lang.NullPointerException
at org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl.getEnclosedElements(TypeElementImpl.java:148)
at org.mapstruct.ap.internal.util.workarounds.SpecificCompilerWorkarounds.replaceTypeElementIfNecessary(SpecificCompilerWorkarounds.java:112)
at org.mapstruct.ap.internal.util.Executables.getAllEnclosedAccessors(Executables.java:208)
at org.mapstruct.ap.internal.model.common.Type.getAllAccessors(Type.java:534)
at org.mapstruct.ap.internal.model.common.Type.getSetters(Type.java:608)
at org.mapstruct.ap.internal.model.common.Type.getPropertyWriteAccessors(Type.java:461)
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.setupMethodWithMapping(BeanMappingMethod.java:114)
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.forgedMethod(BeanMappingMethod.java:107)
at org.mapstruct.ap.internal.model.AbstractBaseBuilder.createForgedAssignment(AbstractBaseBuilder.java:107)
at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.forgeMapping(PropertyMapping.java:653)
at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.build(PropertyMapping.java:293)
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:560)
at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:145)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:373)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:152)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:123)
at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:80)
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:280)
at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:260)
at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:226)
at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:162)
at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:110)
at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:135)
at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:933)
at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:443)
at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:419)
at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:372)
at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.compile(IncrementalImageBuilder.java:331)
at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:305)
at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.build(IncrementalImageBuilder.java:136)
at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildDeltas(JavaBuilder.java:267)
at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:195)
at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)  
```

**Comment by filiphr** [comment] 2017-12-07 22:25
Sorry I missed that. The stacktrace would help us a lot so we can pinpoint the issue.

Can I use your example repo as a reproducal in our tests?

**Comment by gliviu** [comment] 2017-12-08 15:25
absolutely

**Comment by filiphr** [comment] 2018-04-06 21:13
I didn't write earlier. However, I tried writing a test and this passes with the `0.26.0` version of the eclipse tycho compiler (the one which we are using in our tests). Maybe we need to update to the latest one 1.1.0

**Comment by filiphr** [comment] 2018-08-18 20:30
Closing this as we can't seem to reproduce it. I have tried with tycho 0.26.0, 1.0.0, 1.2.0 and in Eclipse itself. If we can get a reproduciable test with the tycho-compiler-jdt then we would be able to do something

**Closed by filiphr** 2018-08-18 20:30 UTC
