### ISSUE TITLE
lombok and mapstruct confilcts in gradle project

### ISSUE THREAD

**Issue by Zane-XY** [mapstruct/mapstruct#735] opened 2016-02-02 07:33 UTC
I can't get mapstruct working in a project using lombok and build with gradle.  In the gradle build, it yields:
```
warning: Unmapped target properties ...
```
If I try to use gradle annotation processor plugin, the lombok annotaitons failed to work. How to can I get the three working togother?

**Comment by sjaakd** [comment] 2016-02-02 19:59
@Zane-XY Have you checked #510 ? I reckon this is a duplicate..

**Comment by sjaakd** [comment] 2016-02-09 19:01
duplicate of #510

**Closed by sjaakd** 2016-02-09 19:01 UTC

**Comment by gunnarmorling** [comment] 2016-02-09 21:40
For the record, the work-around for the time being is to have your Lombok-enhanced beans and your MapStruct-generated mappers in two separate modules of your build. That way it's ensured that MapStruct can see the accessors generated by Lombok.

Unfortunately, there is not much we can do on our side as Lombok essentially is going beyond of what's defined by the annotation processing environment (JSR 269) and there is no portable way for other (compatible) processors such as MapStruct to deal with that.

**Comment by OlegDokuka** [comment] 2016-03-02 14:11
So, there is no way to do the same thing in Gradle like we did with Maven?

**Comment by gunnarmorling** [comment] 2016-03-02 14:30
@OlegDokuka, you could work with a multi-module set-up in Gradle, too. The key just is that it doesn't work if MapStruct and Lombok are invoked in the course of one compilation. If it's different modules, it'll work, no matter what the build tool is. The reason being that MapStruct then can see the accessors generated by Lombok.

**Comment by OlegDokuka** [comment] 2016-03-03 09:53
Hmmm... sounds good)) thanks)
