### ISSUE TITLE
Can not find symbol

### ISSUE THREAD

**Issue by TodyPlay** [mapstruct/mapstruct#3306] opened 2023-06-14 09:22 UTC
### Expected behavior

![image](https://github.com/mapstruct/mapstruct/assets/54938830/29b17cf0-7f6f-4dc1-ac7e-62683ef8b8b7)
multilevel and use expression

### Actual behavior

![image](https://github.com/mapstruct/mapstruct/assets/54938830/1be24ac0-de67-46b7-b938-b885c22d7230)
just one symbol , so can not find symbol : options

### Steps to reproduce the problem

multilevel and use expression
` @Mapping(target = "questionAnalyse.questionDistributions", expression = "java(this.toDistributionList(questionPo, options))")`

### MapStruct Version

1.5.3.Final

**Comment by Zegveld** [comment] 2023-06-14 16:42
MapStruct is not going to analyse the contents of the expression. It will also not pass according to analysis unneeded parameters. So this behavior is expected for MapStruct. 

However if you annotate the argument `options` with `@Context` mapstruct will pass this on to submethods and then it does become available at the location where it currently is missing.

Hope this helps with getting this working for you.

**Comment by TodyPlay** [comment] 2023-06-15 07:50
![image](https://github.com/mapstruct/mapstruct/assets/54938830/1e8a0356-5c67-41df-8b46-33ae2cd81f8a)
@Zegveld thanks for you help. but new problem....

**Comment by filiphr** [comment] 2023-06-16 10:41
If you use `@Context` then the parameter will be passed in the methods below so it will fix one problem, but then it causes another problem because you are using it as a source in other places. You'll need to either wrap everything in one class and use that or pass the list twice (once as `@Context` and once as a normal mapping method). I would advise wrapping the 3 source parameters into one class.

Going to close this since it works as designed and it isn't an issue

**Closed by filiphr** 2023-06-16 10:41 UTC
Labels: bug
