### ISSUE TITLE
default component model is not longer honored with @Mapper(uses = ....)

### ISSUE THREAD

**Issue by Dichotomia** [mapstruct/mapstruct#1189] opened 2017-04-26 08:38 UTC
When a mapper has a annotation @Mapper(uses = ...), the default component model is no longer honored. I tried with "spring" value.

I need to add @Mapper(uses = ..., componentModel = "spring"). 
I use mapstruct-jdk8 1.2.0.Beta2, with lombok 1.16.16.

**Comment by filiphr** [comment] 2017-04-26 18:03
Do you mean the component model set via compiler property? Can you provide a reproducer?

Are you creating the mappers every time with the same commands, i.e. do you use maven or gradle or you are relying on the IDE to invoke the apt?

**Comment by Dichotomia** [comment] 2017-04-26 21:11
The property mapstruct.defaultComponentModel is set to "spring" by the maven compiler plugin.

**Comment by filiphr** [comment] 2017-04-27 18:50
Can you perhaps provide a reproducer? I tried it out in the examples repo and it works as expected. With `mvn clean install` everything works correctly. However, if the apt is invoked from within an IDE (at least from IntelliJ) it won't work as the maven compiler arguments are not picked up by IntelliJ (I am not sure for Eclipse).

**Comment by Dichotomia** [comment] 2017-05-09 08:14
Sorry i am little busy. I will try to provide a reproducer as soon as possible.

**Comment by filiphr** [comment] 2017-05-09 16:26
@Dichotomia no problem, once we have the reproducer we would be able to find out what exactly is the problem

**Comment by Guchman** [comment] 2017-08-05 17:05
Same in gradle 2.3 configuration with
`compileJava {
    options.compilerArgs = [
            '-Amapstruct.defaultComponentModel=spring'
    ]
}`
Generate uses as new.
But generates correctly with  @Mapper(componentModel = "spring")

**Comment by filiphr** [comment] 2017-08-05 17:17
@Guchman can you provide us a small reproducer? This most likely looks like a configuration problem than problem with MapStruct

**Comment by Guchman** [comment] 2017-08-06 15:05
@filiphr problem fixed, but I don't know how) I've trying to reproduce that but I can't. Works without (componentModel = "spring") now. I'll provide a reproducer If I'll catch that kind of behaviour again. But now I have no idea.

**Comment by filiphr** [comment] 2017-08-06 16:43
@Guchman great that it works now. It could have been some mix of configuration, gradle and the IDE it happens sometimes 😄

**Comment by filiphr** [comment] 2017-08-16 21:30
I am closing this as it was a problem in the configuration and not in MapStruct. Feel free to reopen if you need to.

**Closed by filiphr** 2017-08-16 21:30 UTC
