### ISSUE TITLE
mapstruct reimplements "default" implementations in kotlin interfaces

### ISSUE THREAD

**Issue by jimonthebarn** [mapstruct/mapstruct#1577] opened 2018-08-06 12:58 UTC
While playing around with mapstruct (version 1.2.0.Final) in kotlin (version 1.2.60) and more concretely the of mapping of classes extending from either an abstract class or implementing an interface I noticed that mapstruct reimplements "default" implementations in kotlin interfaces. Im unsure whether this should be considered a bug or more of a feature request since an implementation in a interface in kotlin does not necessarily lead to a jvm default method being generated unless one makes use of the @JvmDefault annotation.

I've set up a little demo project to portray the issue: https://github.com/jimonthebarn/mapstruct-kotlin-interface-mapper-issue

**Comment by jimonthebarn** [comment] 2018-08-06 13:33
Just tested it with @JvmDefault on the non abstract members of the interface. This does not work as well.

**Comment by filiphr** [comment] 2018-08-06 19:06
Just had a look at your example. The problem is that the modifiers of method are `public abstract`. Whereas a Java default method has modifiers `public default`. We call `javax.lang.model.element.Element#getModifier()`. It is a bit weird as the generated bytecode has `public default` as modifiers.

`javax.lang.model.element.ExecutableElement#isDefault()` returns `false` as well.

If you ask me this is a problem in the kotlin annotation processor. It either creates a wrong AST, or it is something else. Can you raise an issue with Kotlin? If you create one I can chime in and talk with them as well.

**Comment by filiphr** [comment] 2018-08-06 19:09
I am going to close this one as I don't see anything that we can do on our side. In case anyone has an idea I will reopen this.

**Closed by filiphr** 2018-08-06 19:09 UTC

**Comment by soberich** [comment] 2018-08-06 20:50
Same problem. Switched to abstract classes instead interfaces. @jimonthebarn did you raised an issue in "youtrack"?

**Comment by jimonthebarn** [comment] 2018-08-07 08:31
@soberich Thank you for the hint with the workaround. This is fine for me as well. I did not raise an issue with jetbrains because there already seems to be an issue for it: https://youtrack.jetbrains.com/issue/KT-4779

**Comment by filiphr** [comment] 2018-08-07 17:41
I've commented on [KT-4779](https://youtrack.jetbrains.com/issue/KT-19415). [Here](https://youtrack.jetbrains.com/issue/KT-19415#focus=streamItem-27-3004241-0-0) is my comment. This is the issue where the Kotlin team added support for `@JvmDefault` (which I suspect the problem is). Feel free to chime in if you have more information

**Comment by filiphr** [comment] 2018-08-08 08:04
I was directed into creating a new issue for Kotlin. Have a look at [KT-25960](https://youtrack.jetbrains.com/issue/KT-25960) for this exact problem
