### ISSUE TITLE
nullptr in beta2

### ISSUE THREAD

**Issue by sjaakd** [mapstruct/mapstruct#1174] opened 2017-04-09 18:47 UTC
nl/bro/dao/ss/bhr/impl/DtoToEntityMapper.java:[82,17] Internal error in the mapping processor: java.lang.NullPointerException  	at org.mapstruct.ap.internal.model.source.SourceReference.copyForInheritanceTo(SourceReference.java:286)  	at org.mapstruct.ap.internal.model.source.Mapping.copyForInheritanceTo(Mapping.java:360)  	at org.mapstruct.ap.internal.model.source.MappingOptions.applyInheritedOptions(MappingOptions.java:179)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.mergeInheritedOptions(MapperCreationProcessor.java:413)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:263)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:146)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:117)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:76)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:270)  	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:250)  	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:216)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:155)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)  	at com.sun.tools.javac.main.Main.compile(Main.java:523)  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)  	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)  	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:171)  	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:886)  	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)  	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  	at java.lang.reflect.Method.invoke(Method.java:498)  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

**Comment by filiphr** [comment] 2017-04-09 19:27
@sjaakd I don't think that this is in Beta2, in Beta2 the line location is a bracket, but it corresponds to a meaningful line in 1.1.0.Final. However, it might be possible that the NPE is both in 1.1.0.Final and Beta2.

**Comment by sjaakd** [comment] 2017-04-09 20:56
Its beta2. 
```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2017-04-07T15:44:45+0200",
    comments = "version: 1.2.0.Beta2, compiler: javac, environment: Java 1.8.0_92 (Oracle Corporation)"
)
```
A bit hard to reproduce. I saw it occuring in relation to lots of other errors. I started fixing the errors and the nullptr disseapeared... Strange.. It seems to be related to a sharedConfig..

**Comment by filiphr** [comment] 2017-04-09 21:52
Then the line number in the stack trace is wrong. [This](https://github.com/mapstruct/mapstruct/blob/1.2.0.Beta2/processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceReference.java#L286) is line 286 in Beta2.

**Comment by sjaakd** [comment] 2017-04-10 21:02
> Then the line number in the stack trace is wrong. This is line 286 in Beta2.

Hmm. I agree. Its strange. Can't explain it though.. Perhaps some kind of build problem on my side. We can keep it open, and see if it occurs again, or we can close it. Can't reproduce it anyway..

**Comment by filiphr** [comment] 2017-04-11 16:09
I think that we can close it (if you can't reproduce it). If it happens again we can reopen it

**Closed by filiphr** 2017-04-11 16:09 UTC
