### ISSUE TITLE
NullValueMappingStrategy for non-existing fields

### ISSUE THREAD

**Issue by bastianleirpo** [mapstruct/mapstruct#1653] opened 2018-11-19 13:02 UTC
Hi,

when updating an Entity by an DTO, missing fields in the source entity are set to null in the target entity. Eg.

```
@Mapper(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public abstract class ContactMapper {
	public abstract void updateContactFromContactDTO(ContactDTO contactDTO, @MappingTarget Contact entity);
}
```
ContactDTO does not contain a uuid attribute, but Contact does. The contact.uuid field is set to null, although `NullValuePropertyMappingStrategy.IGNORE` was set.

Is it a bug or more or less a feature request?

Kind regards
Bastian

**Comment by filiphr** [comment] 2018-11-24 00:58
@bastianleirpo I am not sure that I completely understand what you are saying. If `uuid` is only present in `Contact` than you should get a warning for an unmapped target property. Maybe you are looking for `unmappedTargetPolicy`?

Can you share the code that is generated and where `contact.uuid` is set to `null`?

>Is it a bug or more or less a feature request?

If this really happens (I can't reproduce it) it is a bug. 

I'll close this, let us know in case you have more info and we can reopen it

**Closed by filiphr** 2018-11-24 00:58 UTC
