### ISSUE TITLE
Null value when mapping nested property

### ISSUE THREAD

**Issue by twentylemon** [mapstruct/mapstruct#1404] opened 2018-03-19 19:11 UTC
I ran into an NPE today, I have this custom mapper
```java
class OptionalJavaTimeToStringMapper {
    public String toLocalDateString(Optional<LocalDate> localDate) { /* .. */ }
    public Optional<LocalDate> fromLocalDateString(String localDate) { /* .. */ }
}
```

Which I was going to us to help map these objects:
```java
class Dto {
    String id;
    DtoSpecification specification;
}

class DtoSpecification {
    String date;
}

class Model {
    String id;
    Optional<LocalDate> date;
}

@Mapper(uses = OptionalJavaTimeToStringMapper.class)
interface MyMapper {
    @Mapping(target = "date", source = "specification.date")
    Model fromDto(Dto dto);
}
```

However, `model.date` is always null after mapping, not an empty optional as I expected. 

Digging into why: the code generated produces a helper method to get the date from the specification:
```java
if ( dto == null ) {
    return null;
}
DtoSpecification dtoSpecification = dto.getSpecification();
if ( dtoSpecification == null ) {
    return null;
}
String date = dtoSpecification.getDate();
if ( date == null ) {
    return null;
}
return date;
```

And, in `fromDto` itself:
```java
if ( date != null ) {
    model.setDate( optionalJavaTimeToStringMapper.fromLocalDateString( date ) );
}
// there is no logic for handling date == null, so it just leaves the attribute null
```
The problem is, the generated mapping method doesn't differentiate between `dtoSpecification` and `dtoSpecification.date` being null. The null check in `fromDto` should maybe be `if (dto.getSpecification() != null)`? (nesting further would lead to ugly code? With #1048 it wouldn't be bad)

**Comment by twentylemon** [comment] 2018-03-19 19:14
Just a note, I plan to use `@AfterMapping` to resolve this specific issue in my code, but it sort of defeats the purpose of having the `OptionalJavaTimeToStringMapper` class in the first place.

**Comment by filiphr** [comment] 2018-03-20 20:04
@twentylemon MapStruct is working by design here. There is [Controlling mapping result for `null` arguments](http://mapstruct.org/documentation/stable/reference/html/#mapping-result-for-null-arguments) which should set default values there. Although I am not sure if it would set `Optional.empty()` yet.

It is also debatable if `Optional` should be used as fields and / or function parameters or just as a return type. You can also set the default value of your field to `Optional.empty()`

As for the nesting, yes we are aware about it (like the linked #1048 issue). However, currently we are focused other things for the 1.3.0 release. If someone wants to provide a PR and help out we are more than happy to help out.

I am going to close this issues, as it works as it should. If we need to do something more specific we can reopen it or track it in a different issue.

**Closed by filiphr** 2018-03-20 20:04 UTC

**Comment by twentylemon** [comment] 2018-03-20 21:04
@filiphr True, the default works, makes more sense than `@AfterMapping`, but still not ideal for this, imo. If `specification` is non-null, why wouldn't `specification.date` be mapped, even if it's null? (as a general question -- I am ok with your answer)

Aside, for the optional field, the model in this case is representing a repeating schedule pattern, which may or may not have an end date. Consumers of the end date need to be aware of that -- and it's simpler to do `Optional<LocalDate>` than use a type hierarchy or an enum or something.

**Comment by filiphr** [comment] 2018-03-20 22:09
> specification is non-null, why wouldn't specification.date be mapped, even if it's null? (as a general question -- I am ok with your answer)

Actually for other mappers we shouldn't be doing a null check (I think).

Returning `Optional<LocalDate>` is completely valid I was not referring to that. I was more referring to have have something like:

```
class Model {
    String id;
    LocalDate date;

    Optional<Date> getDate() {
        return Optional.ofNullable(date);
    }

    void setDate(LocalDate date) {
        this.date = date;
    }
}
```

Not sure if it is going to work properly though

**Comment by twentylemon** [comment] 2018-03-20 23:16
But lombok doesn't write that for me :)
Thanks for the quick responses.

**Comment by filiphr** [comment] 2018-03-31 13:38
Didn't know Lombok was involved 😄
