### ISSUE TITLE
Feature request: @ValueMapping support for enum-to-primitive mapping

### ISSUE THREAD

**Issue by johneer532** [mapstruct/mapstruct#2002] opened 2020-01-15 17:06 UTC
I was a little disappointed when I found out that `@ValueMapping` is only for enum-to-enum mapping. I was even more disappointed when I found out that there is not way to do enum-to-string mapping or string-to-enum mapping properly with MapStruct. At least it looks that way.

The best solution I could find so far is based on a suggestion that I found somewhere online: to do it manually. This results in something like this:

```
    default String map(final MyEnum type) {
        switch (type) {

            case A:
                return "val-a";

            case B:
                return "val-b";

            default:
                return null;
        }
    }
```

On the bright side, my mapping logic is still contained in a specific mapper component, although that has more to do with architecture and is not really driven by MapStruct itself.

BUT, from my point of view, that is something that is easy to do for a mapper framework and that is exactly what a mapper framework is supposed to do. When I have to do things like that manually... that makes me just sad.

Could you please consider to enhance the enum-to-primitive and primitive-to-enum mapping capabilities of MapStruct?

**Comment by sjaakd** [comment] 2020-01-15 18:15
Well, have you looked at https://github.com/mapstruct/mapstruct/commit/507ec1b3849be3190cad541dd95fc6b9f3304c5d? Its on our master and introduces enum-string, string-enum.. Have it a go if you want...

**Comment by filiphr** [comment] 2020-01-15 19:18
Closing as duplicate of #1557 and as @sjaakd said this is already implemented on master and would be part of the next release

**Closed** 2020-01-24 20:48 UTC
Labels: duplicate
