### ISSUE TITLE
Map a List into a Map<Key, Value>

### ISSUE THREAD

**Issue by botzzz** [mapstruct/mapstruct#850] opened 2016-08-09 15:00 UTC
Hello,

I'm trying to map a List<Something> into a Map<Key,Value> using a custom mapper.

The compilation fails with this message 

> Can't generate mapping method from iterable type to non-iterable type.

At the top of my mapper I have this code :
```
@Mapper(componentModel = "spring", uses = { CustomMapper.class })
public interface MyMapper {
	public abstract Map<Key, Value> toMap(List<Something> somethings);

```

And my custom mapper is defined like this : 
```
@Component
public class CustomMapper {
	public Map<Key,Value> toMap(List<Something> somethings) {
		Map<Key, Value> map = new HashMap<Key, Value>();
		for(Something som : somethings) {
			// add to map
		}
		return map;
	}
```

Am I missing something ?

Thank you for reading and eventually helping me,

**Comment by gunnarmorling** [comment] 2016-08-11 06:59
You should not declare the `toMap()` method on your `MyMapper` interface. Instead, the method on `CustomMapper` will be used for each property to be mapped from list to map within generated method implementations of `MyMapper`.

I'm going to close this one, as it's not a bug. I suggest you use the [Google Group](https://groups.google.com/forum/#!forum/mapstruct-users) for asking questions, as this issue tracker is more appropriate for filing bugs or feature requests. Thanks!

**Closed by gunnarmorling** 2016-08-11 06:59 UTC
