### ISSUE TITLE
Support custom annotations   

### ISSUE THREAD

**Issue by svpace** [mapstruct/mapstruct#1344] opened 2017-11-23 03:35 UTC
I usually end up with a couple of sets of @Mapping that repeat themselves throughout my mappers.

It would be a nice addition if the annotation processor treats @Mapping annotations as meta-annotations thus allowing me to create custom mapping annotations. Something like:
```Java
@Mapping(/* rule 1*/)
@Mapping(/* rule 2*/)
@Mapping(/* rule 3*/)
interface @MyMapping {}
```

**Comment by filiphr** [comment] 2017-11-23 22:56
I am closing this as a duplicate of #807. Please follow that one.

Have you looked in [Mapper Shared Config](http://mapstruct.org/documentation/stable/reference/html/#shared-configurations). Maybe it can help you out.

**Closed by filiphr** 2017-11-23 22:56 UTC
