### ISSUE TITLE
defaultExpression not being applied when source property not specified explicitly

### ISSUE THREAD

**Issue by marceloverdijk** [mapstruct/mapstruct#1966] opened 2019-11-08 17:49 UTC
When having the following classes:

```
public class AnimalRecord {

    private String[] previousNames;
}

public class Animal {

    private List<String> previousNames;
}
```

and a mapper like:

```
@Mapper
public interface AnimalRecordMapper {

    @Mapping(target = "previousNames", 
            nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS, 
            defaultExpression = "java(Collections.emptyList())")
    Animal toAnimal(AnimalRecord record);
}
```

I would expect that the implementation would convert a `null` array in `AnimalRecord` to an empty `List` (**not** `null`) in the `Animal` instance.

However the generated code looks like:

```
@Override
public Animal toAnimal(AnimalRecord record) {
    if ( record == null ) {
        return null;
    }

    Animal animal = new Animal();

    List<String> list = stringArrayToStringList( record.getPreviousNames() );
    if ( list != null ) {
        animal.setPreviousNames( list );
    }

    return animal;
}
```

When I explicitly add the `source = "previousNames"` to the `@Mapping` like:

```
@Mapper
public interface AnimalRecordMapper {

    @Mapping(source = "previousNames", 
            target = "previousNames", 
            nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS, 
            defaultExpression = "java(Collections.emptyList())")
    Animal toAnimal(AnimalRecord record);
}
```

then the code is generated as expected:

```
@Override
public Animal toAnimal(AnimalRecord record) {
    if ( record == null ) {
        return null;
    }

    Animal animal = new Animal();

    List<String> list = stringArrayToStringList( record.getPreviousNames() );
    if ( list != null ) {
        animal.setPreviousNames( list );
    }
    else {
        animal.setPreviousNames( Collections.emptyList() );
    }

    return animal;
}
```

Note the `else` part generated to set the empty list.

It seems the `defaultExpression` is not being applied when the `source` property is not specified.
Maybe in general or related to the fact that there is also an array to `List` conversion needed.

**Comment by marceloverdijk** [comment] 2019-11-08 17:51
Note: using MapStruct `1.3.1.Final`.

**Comment by filiphr** [comment] 2019-11-08 17:57
Thanks for the issue @marceloverdijk. In my opinion this is a bug, we should always apply the `defaultExpression` irregardless whether `source` is defined or not. Since it applies to the target property

**Comment by sjaakd** [comment] 2019-11-10 11:29
@marceloverdijk .. I tried to replicate the problem, but.. it works on my machine :smile:

```java
@Mapper( imports = Collections.class )
public interface Issue1966Mapper {

    Issue1966Mapper INSTANCE = Mappers.getMapper(Issue1966Mapper.class);

    @Mapping(target = "previousNames",
        nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
        defaultExpression = "java(Collections.emptyList())")
    Animal toAnimal(AnimalRecord record);

    class AnimalRecord {

         private String[] previousNames;

        public String[] getPreviousNames() {
            return previousNames;
        }

        public void setPreviousNames(String[] previousNames) {
            this.previousNames = previousNames;
        }
    }

    class Animal {

        private List<String> previousNames;

        public List<String> getPreviousNames() {
            return previousNames;
        }

        public void setPreviousNames(List<String> previousNames) {
            this.previousNames = previousNames;
        }
    }

}
```

result (as expected):

```java

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2019-11-10T12:25:37+0100",
    comments = "version: , compiler: Eclipse JDT (Batch) 1.2.100.v20160418-1457, environment: Java 1.8.0_181 (Oracle Corporation)"
)
public class Issue1966MapperImpl implements Issue1966Mapper {

    @Override
    public Animal toAnimal(AnimalRecord record) {
        if ( record == null ) {
            return null;
        }

        Animal animal = new Animal();

        List<String> list = stringArrayToStringList( record.getPreviousNames() );
        if ( list != null ) {
            animal.setPreviousNames( list );
        }
        else {
            animal.setPreviousNames( Collections.emptyList() );
        }

        return animal;
    }

    protected List<String> stringArrayToStringList(String[] stringArray) {
        if ( stringArray == null ) {
            return null;
        }

        List<String> list = new ArrayList<String>( stringArray.length );
        for ( String string : stringArray ) {
            list.add( string );
        }

        return list;
    }
}
```

Note: I used the latest master branch in order to create a test case. But I don't think we fixed an issue in this area.

Note ii: I added an import to my mapper.

**Comment by marceloverdijk** [comment] 2019-11-10 17:57
Interesting @sjaakd :-)

I've setup this sample project https://github.com/marceloverdijk/mapstruct-1966
It contains a failing tests, when adding the `source` property explicitly the test succeeds.

Could you check it out and see if you see different behavior?

**Comment by sjaakd** [comment] 2019-11-10 18:36
I just checked.. Compile your example against 1.4.0-SNAPSHOT (our master) and it works as expected.. I guess we must have fixed something for the better :smile:

**Comment by sjaakd** [comment] 2019-11-10 18:42
I added #1967 jus to avoid regression.

**Comment by sjaakd** [comment] 2019-11-10 19:16
@marceloverdijk thanks for reporting. I'll proceed to close the issue, since the problem does not occur on our master.

**Closed by sjaakd** 2019-11-10 19:16 UTC
Labels: bug

**Comment by marceloverdijk** [comment] 2019-11-10 20:30
Yes, I can confirm with `1.4.0-SNAPSHOT` it works as expected 👍

**Comment by shamoh** [comment] 2020-04-02 10:31
When do you expect the `1.4.0` is going to be released?
