### ISSUE TITLE
[Bug] Generated mapping not compiling due to missing import

### ISSUE THREAD

**Issue by julius-d** [mapstruct/mapstruct#3024] opened 2022-09-19 15:46 UTC
Hi!

I wanted to update mapstruct from 1.4.2.Final to 1.5.2.Final.
But that is not possible because the compilation fails due to a missing import in the generated mapper.

I crated a sample repo to reproduce the issue:
https://github.com/julius-d/mapstruct-1-5-2-issue

The compilation fails with
```
[INFO] Compiling 4 source files to /home/runner/work/mapstruct-1-5-2-issue/mapstruct-1-5-2-issue/target/classes
[INFO] -------------------------------------------------------------
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/mapstruct-1-5-2-issue/mapstruct-1-5-2-issue/target/generated-sources/annotations/org/example/mapstruct152issue/AnimalMapperImpl.java:[38,49] package Food does not exist
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

The code is this

```java
package org.example.mapstruct152issue.domain;

import lombok.Builder;
import lombok.Value;
import org.example.mapstruct152issue.domain.Food.FoodType;

@Builder
@Value
public class Animal {

  FoodType foodType;
  String name;
```

```java
package org.example.mapstruct152issue.domain;

public class Food {

  public enum FoodType {
    FOO,
    BAR;
  }

}
```

```java
package org.example.mapstruct152issue;

import lombok.Data;

@Data
public class AnimalDto {

  private String foodType;
  private String name;

}
```

```java
package org.example.mapstruct152issue;

import static org.mapstruct.ReportingPolicy.ERROR;

import org.example.mapstruct152issue.domain.Animal;
import org.mapstruct.Mapper;

@Mapper(unmappedTargetPolicy = ERROR, typeConversionPolicy = ERROR)
public interface AnimalMapper {

  AnimalDto map(Animal animal);
  Animal map(AnimalDto animal);

}
```

The generated code is this
Notice the missing 
`import org.example.mapstruct152issue.domain.Food;`!
```java
package org.example.mapstruct152issue;

import javax.annotation.processing.Generated;
import org.example.mapstruct152issue.domain.Animal;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2022-09-19T17:43:36+0200",
    comments = "version: 1.5.2.Final, compiler: javac, environment: Java 17.0.4.1 (Eclipse Adoptium)"
)
public class AnimalMapperImpl implements AnimalMapper {

    @Override
    public AnimalDto map(Animal animal) {
        if ( animal == null ) {
            return null;
        }

        AnimalDto animalDto = new AnimalDto();

        if ( animal.getFoodType() != null ) {
            animalDto.setFoodType( animal.getFoodType().name() );
        }
        animalDto.setName( animal.getName() );

        return animalDto;
    }

    @Override
    public Animal map(AnimalDto animal) {
        if ( animal == null ) {
            return null;
        }

        Animal.AnimalBuilder animal1 = Animal.builder();

        if ( animal.getFoodType() != null ) {
            animal1.foodType( Enum.valueOf( Food.FoodType.class, animal.getFoodType() ) );
        }
        animal1.name( animal.getName() );

        return animal1.build();
    }
```

**Comment by Zegveld** [comment] 2022-09-19 16:06
duplicate of #2945 which is already marked as fixed for the upcoming release 1.6.0.

**Closed by Zegveld** 2022-09-19 16:06 UTC
