### ISSUE TITLE
Property mapped outside null check

### ISSUE THREAD

**Issue by zoffoliluca** [mapstruct/mapstruct#2654] opened 2021-11-16 08:18 UTC
This is my mapper :

```java
  @Mapping(target = "id", source = "dettaglio.documentoId")
  @Mapping(
      target = "output",
      expression = "java(Paths.get(pathTempDirOutput, dettaglio.getRisultato()).toString())")
  DocumentoOutput fromDettaglioToDocumentoOutput(Dettaglio dettaglio, String pathTempDirOutput);
```

This is the generated code :

```java
    @Override
    public DocumentoOutput fromDettaglioToDocumentoOutput(Dettaglio dettaglio, String pathTempDirOutput) {
        if ( dettaglio == null && pathTempDirOutput == null ) {
            return null;
        }

        DocumentoOutput documentoOutput = new DocumentoOutput();

        if ( dettaglio != null ) {
            documentoOutput.setId( dettaglio.getDocumentoId() );
            documentoOutput.setPageStart( dettaglio.getPageStart() );
            documentoOutput.setPageEnd( dettaglio.getPageEnd() );
        }
        documentoOutput.setOutput( Paths.get(pathTempDirOutput, dettaglio.getRisultato()).toString() );

        return documentoOutput;
    }
```

This code line is outside 'dettaglio' null check :

```java
        documentoOutput.setOutput( Paths.get(pathTempDirOutput, dettaglio.getRisultato()).toString() );
```

Why? Thanks

**Comment by Zegveld** [comment] 2021-11-16 16:45
That is because it is in an expression. 
The expression is not parsed by mapstruct, so it does not know that a reference to the source argument is present there.

To solve it for your situation you can annotate the `String pathTempDirOutput` parameter with `@Context`. 
This should result in the following code:
```
    @Override
    public DocumentoOutput fromDettaglioToDocumentoOutput(Dettaglio dettaglio, String pathTempDirOutput) {
        if ( dettaglio == null ) {
            return null;
        }

        DocumentoOutput documentoOutput = new DocumentoOutput();

        documentoOutput.setId( dettaglio.getDocumentoId() );
        documentoOutput.setPageStart( dettaglio.getPageStart() );
        documentoOutput.setPageEnd( dettaglio.getPageEnd() );

        documentoOutput.setOutput( Paths.get(pathTempDirOutput, dettaglio.getRisultato()).toString() );

        return documentoOutput;
    }
```

hope this helps.

**Comment by filiphr** [comment] 2021-11-20 07:28
An alternative solution to the one proposed by @Zegveld without the use of expression is also possible.

e.g.

```
@Mapping(target = "id", source = "documentoId")
@Mapping(target = "output", source = "risultato", qualifiedByName = "temporaryPath")
DocumentoOutput fromDettaglioToDocumentoOutput(Dettaglio dettaglio, String pathTempDirOutput);

@Named("temporaryPath")
default String createTemporaryPath(String path, @Context String tempDirOutput) {
    return path != null ? Paths.get( tempDirOutput, path).toString() : null;
}
```

This will then generate code similar to what @Zegveld proposed and it will also work in a similar scenario as the original with multiple source parameters.

I am going to close this now since we have provided 2 alternative solutions and this works as designed

**Closed by filiphr** 2021-11-20 07:28 UTC
