### ISSUE TITLE
boolean  conversion 

### ISSUE THREAD

**Issue by plzeng** [mapstruct/mapstruct#1041] opened 2017-01-11 14:01 UTC
When i conversion boolean it  default use Boolean.valueOf, If value is null i still got false . I hope when i use 
Boolean with type of packaging, can return a null value.

**Comment by filiphr** [comment] 2017-01-11 16:53
I don't quite understand what the problem is. Where do we use `Boolean#valueOf()`? Can you show us an example of your mapper?

**Comment by sjaakd** [comment] 2017-02-01 20:32
@plzeng : can you provide an example so that we can reproduce it? I'll proceed to close this issue later this week when we lack a reproducer.

**Comment by plzeng** [comment] 2017-02-06 02:37
Sorry this is my problem, I do not have the correct use.I have resolved .Thanks for your help.

**Closed** 2017-02-06 20:20 UTC
