### ISSUE TITLE
java: Internal error in the mapping processor: java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by wxggithub1996** [mapstruct/mapstruct#2865] opened 2022-06-02 07:11 UTC
1

**Comment by filiphr** [comment] 2022-06-05 06:56
Closing due to missing information

**Closed by filiphr** 2022-06-05 06:56 UTC

**Comment by mnk** [comment] 2023-05-12 00:32
The same exception with mapstruct 1.5.2 running via `mvn -T1C clean install`, Maven 3.9.1, Java 17.0.6:

```
.../PolicyMapper.java:[12,16] error: Internal error in the mapping processor: java.lang.ExceptionInInitializerError
  	at org.mapstruct.ap.shaded.freemarker.ext.beans.ClassIntrospector.isAllowedToExpose(ClassIntrospector.java:534)
  	at org.mapstruct.ap.shaded.freemarker.ext.beans.ClassIntrospector.addPropertyDescriptorToClassIntrospectionData(ClassIntrospector.java:396)
  	at org.mapstruct.ap.shaded.freemarker.ext.beans.ClassIntrospector.addBeanInfoToClassIntrospectionData(ClassIntrospector.java:311)
  	at org.mapstruct.ap.shaded.freemarker.ext.beans.ClassIntrospector.createClassIntrospectionData(ClassIntrospector.java:274)
  	at org.mapstruct.ap.shaded.freemarker.ext.beans.ClassIntrospector.get(ClassIntrospector.java:244)
  	at org.mapstruct.ap.shaded.freemarker.ext.beans.BeanModel.<init>(BeanModel.java:113)
  	at org.mapstruct.ap.shaded.freemarker.ext.beans.BeanModel.<init>(BeanModel.java:103)
  	at org.mapstruct.ap.internal.writer.FreeMarkerModelElementWriter.write(FreeMarkerModelElementWriter.java:37)
  	at org.mapstruct.ap.internal.writer.FreeMarkerWritable.write(FreeMarkerWritable.java:19)
  	at org.mapstruct.ap.internal.writer.ModelWriter.writeModel(ModelWriter.java:69)
  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.createSourceFile(MapperRenderingProcessor.java:62)
  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.writeToSourceFile(MapperRenderingProcessor.java:39)
  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:29)
  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:24)
  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:350)
  	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:330)
  	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:279)
  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:174)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1023)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:939)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1267)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1382)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1234)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:916)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
  	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:82)
  	at jdk.internal.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess0(JavacCompiler.java:700)
  	at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcessWithProperClassloader(JavacCompiler.java:681)
  	at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess(JavacCompiler.java:670)
  	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:187)
  	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1140)
  	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:193)
  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
  	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
  	at org.apache.maven.buildcache.BuildCacheMojosExecutionStrategy.execute(BuildCacheMojosExecutionStrategy.java:132)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
  	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:193)
  	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:180)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833) 
Caused by: java.lang.RuntimeException: Could not load unsafe method null java.io.IOException Stream closed
  	at org.mapstruct.ap.shaded.freemarker.ext.beans.UnsafeMethods.createUnsafeMethodsSet(UnsafeMethods.java:82)
  	at org.mapstruct.ap.shaded.freemarker.ext.beans.UnsafeMethods.<clinit>(UnsafeMethods.java:34)  	... 54 more
```

**Comment by filiphr** [comment] 2023-05-20 08:43
@mnk can you please share an example that we can use to reproduce this problem?

**Comment by mnk** [comment] 2023-05-24 02:42
There is no consistent way to reproduce the error, but it happens ocasionally when building a fairly large Maven multi-module project. Prabably a race condition.

**Comment by filiphr** [comment] 2023-05-24 04:12
In 1.6 we are going to upgrade Freemarker to its latest version. Perhaps that will fix the problem. 1.5 is using a rather old version of Freemarker

**Comment by mnk** [comment] 2024-01-04 16:50
I am fairly confident that this one is caused by a JDK bug. See https://bugs.openjdk.org/browse/JDK-8013722 and https://github.com/mnk/JDK-8013722 for a workaround.

**Comment by filiphr** [comment] 2024-01-28 17:35
Thanks for sharing that @mnk. Seems like https://bugs.openjdk.org/browse/JDK-8205976 is the bug for the github project you shared. Sadly there hasn't been any update on the JDK bug. Have you perhaps opened an issue with the maven-compiler-plugin project?

**Comment by mnk** [comment] 2024-01-28 19:45
From a short email exchange with @jaikiran (assignee on the JDK bug), I get the sense that some attention has already been given to this issue, but also that it is not a "straightforward fix". I also had a look at the code, and tend to agree. Either some clever/fragile reference counting is needed, or the caching could be removed altogether, with possible performance degradation as a result.
As demonstrated here https://github.com/mnk/JDK-8013722/blob/main/pom.xml#L52, the problem can be worked around by calling `new java.net.URL("file:///.").openConnection().setDefaultUseCaches(false);`, so maybe Maven should do that when called with `-T > 1`? We have seen the problem outside annotation processing, so I think the workaround should be implemented directly in Maven and not in maven-compiler-plugin?

**Comment by hohwille** [comment] 2025-04-22 14:38
FYI: I just ran into the same issue so it may not be a total edge-case. In my case it also occurred with maven and `-T1C` so most likely some concurrency race-condition that is hard to isolate or reproduce exactly.
Thanks already for the analysis of the problem. Did someone raise a maven issue for the suggested solution/workaround?

**Comment by mnk** [comment] 2025-04-24 06:39
@hohwille , no I never got around to raise a Maven issue for the problem. It is also potentially problematic to have this as the default configuration, because it may negatively impact build performance. You should probably only pay that price if you are affected by the problem, and are willing to accept the performance hit to get stable builds.
We are, and we have just been running with this simple Maven extension https://github.com/mnk/JDK-8013722/blob/main/disable-jar-cache-extension/src/main/java/org/example/DisableCacheLifecycleParticipant.java - activated by putting `-Dmaven.ext.class.path=${session.rootDirectory}/.mvn/disable-jar-cache-extension.jar` into the `.mvn/maven.config` file.
I would suggest to push for a fix in openjdk instead of working around the problem in Maven.
