### ISSUE TITLE
Improve Lombok integration documentation

### ISSUE THREAD

**Issue by Nikolas-Charalambidis** [mapstruct/mapstruct#3374] opened 2023-09-07 02:52 UTC
### Expected behavior

Assuming the following code and configuration below, I expect the compilation to succeed and the mapper to generate something like this:

```java
public Foo.CarDto toDto(Foo.Car car) {
    if (car == null) {
        return null;
    } else {
        Foo.CarDto carDto = new Foo.CarDto();
        carDto.setEWhatever2(car.getEWhatever1());
        return carDto;
    }
}
```

### Actual behavior

Compilation fails and no implementation is generated.

```
java: No property named "eWhatever1" exists in source parameter(s). Did you mean "EWhatever1"?
```

### Steps to reproduce the problem

- Java 17
- MapStruct 1.5.3.Final
- Lombok 1.18.22
- Lombok Mapstruct Binding 0.2.0

```java
@Mapper
public interface BadMapper {

    @Mapping(target = "eWhatever2", source = "eWhatever1")
    CarDto toDto(Car car);
}
```
```java
@Data
public class Car {

    private String eWhatever1;
}
```
```java
@Data
public class CarDto {

    private String eWhatever2;
}
```

It is important the 1st letter of the variable is lowercase and the 2nd one is uppercase.
- `Ewhatever` interestingly produces a similar error.
- `eWhatever` doesn't work.
- `ewHatever` is ok.
- `ewhatever` is ok.

### MapStruct Version

MapStruct 1.5.3.Final

**Comment by filiphr** [comment] 2023-09-16 07:32
This works as designed. MapStruct is using the Java Bean convention. This means that we are using getters / setters to determine the names of the properties. In this example the getter is `getEWhatever` the name of the property is `EWhatever`. The reason for this is due to the fact the first character after the `get` is lowercased if and only if the letter after that is lowercase.

**Comment by thunderhook** [comment] 2023-09-16 12:08
You can however tell Lombok to generate getters using the Java Bean convention by providing a `lombok.config` file with the property: `lombok.accessors.capitalization=beanspec`

For more info see https://projectlombok.org/features/GetterSetter

**Comment by Nikolas-Charalambidis** [comment] 2023-09-16 16:17
@thunderhook A spot on! `lombok.accessors.capitalization=beanspec resolves` the whole issue. Many thanks!

@filiphr I believe such a gotcha should be documented in the Mapstruct reference guide: https://mapstruct.org/documentation/stable/reference/html/#lombok I have created a PR (https://github.com/mapstruct/mapstruct/pull/3389), kindly, take a look.

**Comment by filiphr** [comment] 2023-09-17 07:45
Thanks a lot for the documentation PR @Nikolas-Charalambidis. I merged it.

**Closed by filiphr** 2023-09-17 07:45 UTC
Labels: documentation
