### ISSUE TITLE
怎么把Bean 转成 Map<String,Object>

### ISSUE THREAD

**Issue by zhaokaiping-github** [mapstruct/mapstruct#2779] opened 2022-03-06 09:30 UTC
- [ ] Is this an issue (and hence not a question)? 

If this is a question how to use MapStruct there are several resources available.
- Our reference- and API [documentation](http://mapstruct.org/documentation/reference-guide/).
- Our [examples](https://github.com/mapstruct/mapstruct-examples) repository (contributions always welcome)
- Our [FAQ](http://mapstruct.org/faq/)
- [StackOverflow](https://stackoverflow.com), tag MapStruct 
- [Gitter](https://gitter.im/mapstruct/mapstruct-users) (you usually get fast feedback)
- Our [google group](https://groups.google.com/forum/#!forum/mapstruct-users)

**Comment by filiphr** [comment] 2022-03-06 21:08
According to google translate the issue name is "How to convert Bean to Map<String,Object>", which means that it is a duplicate of #2504

**Closed by filiphr** 2022-03-06 21:08 UTC
