### ISSUE TITLE
1.2.0.Beta2 doesn't generate sources in Eclipse

### ISSUE THREAD

**Issue by eximius313** [mapstruct/mapstruct#1207] opened 2017-05-22 00:42 UTC
I'm using ```mapstruct-jdk8``` version ```1.2.0.Beta2``` (Beta2 because I use Lombok as well) together with ```Hibernate Static Metamodel Generator```.
My configuration in Eclipse is as following:
![image](https://cloud.githubusercontent.com/assets/5578017/26288712/29daf4a6-3e98-11e7-8606-0ee4be28dd96.png)

Files generated by ```Hibernate Static Metamodel Generator``` are placed inside ```.apt_generated``` folder while Mapstruct generated files are missing

Could you please fix that?

**Comment by filiphr** [comment] 2017-05-22 05:44
Did it work with previous versions? 

Do you use some build tool? If yes how does the setup look like in it, does it build OK with it? 

Does it work if you don't have lombok?

**Comment by eximius313** [comment] 2017-05-22 09:31
1)I don't know - I started project with this version
2)I use gradle, but this issue is present in fresh Eclipse import. I'm providing the test case.
* Import to Eclipse (project will not yet compile)
* invoke ./gradlew eclipse (in order to configure paths)
* Project should compile and Metamodel classes are generated, but not Mapstruct
* Run tests on both "backend" and "frontend" to see results
3)I must use Lombok
[showcase_apt_mapstruct.zip](https://github.com/mapstruct/mapstruct/files/1018309/showcase_apt_mapstruct.zip)

**Comment by agudian** [comment] 2017-05-22 19:03
Well, after importing the projects in Eclipse (I ran `gradlew eclipse` first), the metamodel and the mapper were generated. However, Lobmok didn't run... But I don't have the lombok agent in Eclipse, so that might be expected:
```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2017-05-22T20:50:26+0200",
    comments = "version: 1.2.0.Beta2, compiler: Eclipse JDT (IDE) 1.2.100.v20160418-1457, environment: Java 1.8.0_112 (Oracle Corporation)"
)
@Component
public class UserMapperImpl implements UserMapper {

    @Override
    public UserDTO userToUserDto(User user) {
        if ( user == null ) {
            return null;
        }

        UserDTO userDTO = new UserDTO();

        return userDTO;
    }
}
```

Is `frontend/.apt_generated` empty for you?

**Comment by filiphr** [comment] 2017-05-22 22:04
I also tried the example (without eclipse) and the mappers were also generated but in `frontend/build/generated/source/apt/main`. 

@agudian Lombok must have run, because otherwise we cannot generate the Mappers. Both the `User` and the `UserDTO` need Lombok so we can use the methods.

**Comment by filiphr** [comment] 2017-07-02 10:04
I am going to close this one as the problem is not related to MapStruct and also it works for me without Eclipse and for @agudian in Eclipse.

**Closed by filiphr** 2017-07-02 10:04 UTC

**Comment by evser** [comment] 2017-10-10 12:20
See: https://github.com/mapstruct/mapstruct/issues/1159
Thanks @jmax01, it helps, but I've found several more steps that should be performed:

1. gradlew clean cleanEclipse eclipse
2. Import project to Eclipse
3. Remove lombok.jar javaagent from Eclipse
4. Restart Eclipse
5. Trigger generation of a class annotated with \@Mapper (edit this class or rebuild project)
6. Add lombok.jar javaagent to Eclipse
7. Restart Eclipse

Now all classes will be generated properly.
P. S. Check you configuration files (pom.xml/build.gradle) : https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-lombok

**Comment by sjaakd** [comment] 2017-10-15 09:13
@filiphr : should we document these steps somewhere?

**Comment by eximius313** [comment] 2017-10-15 09:56
@sjaakd, as far as I understood you have to add the ```org.mapstruct.ap.spi.AstModifyingAnnotationProcessor.class``` file to the ```lombok.jar``` first, so I think it's just a workaround. It (perhaps) works, but it's ugly...

**Comment by evser** [comment] 2017-10-15 09:59
@eximius313 yes, you're right. But this step is not enough, it's only the first step, you need 7 additional ones. That's what I was trying to say.

**Comment by filiphr** [comment] 2017-10-15 11:46
@sjaakd I've created https://github.com/mapstruct/mapstruct.org/issues/65 for our website. We can add this under the eclipse setup or maybe as an FAQ, I don't know what is the best.

**Comment by evser** [comment] 2017-10-15 11:54
I would propose to check my solution once again on a clean Eclipse instance, just to make sure that all steps are really valid (I checked them several times, but hope that they work not only for me).

**Comment by agudian** [comment] 2017-10-15 12:25
This really looks like a coincidence and not like something that will continue to work within one project. Eg the removing and adding of the lombok agent and the triggering of the mapper generation in between restarts doesn’t sound like something that has an actual effect on persisted configuration values in Eclipse. Hence I wouldn’t add it to the docs...

I think it’s more something that the lombok guys might need to look into, right?

**Comment by filiphr** [comment] 2017-10-15 12:28
@agudian you might be right. To be honest I didn't read all the steps completely (and I don't know Eclipse a lot). 

One thing I know is that there are issues with the lombok agent (multiple people have been complaining that it does not work with MapStruct and the `AstModifyingAnnotationProcessor`. I think the Lombok guys should do something about it.
