### ISSUE TITLE
Update functionality has problems

### ISSUE THREAD

**Issue by gcanova** [mapstruct/mapstruct#560] opened 2015-05-26 08:00 UTC
Hello, 

I have the following problem: 
Instead of creating new objects and map them I need to update existing objects and map them. This functions well so far, as long as there are no other objects in the object which also need to be updated instead of created newly. Here is a minimal example of what I mean: 

I have a class "Person"
import java.util.ArrayList;
import java.util.List;

public class Person{

	private String firstName;
	private String lastName;
	private List<Pet> pets = new ArrayList<>();
	
    
    public String getFirstName(){
    	return firstName;
    }
    public void setFirstName(String firstName){
    	this.firstName = firstName;
    }
    
    public String getLastName(){
    	return lastName;
    }
    public void setLastName(String lastName){
    	this.lastName = lastName;
    }
    
    public List<Pet> getPets(){
    	return pets;
    }
    public void setUsersForDepartment(List<Pet> pets){
    	this.pets = pets;
    }
}

And I have a class PersonDTO

import java.util.ArrayList;
import java.util.List;

public class PersonDTO{

	private String name;
	private String surname;
	private List<Pet> pets = new ArrayList<>();
	
    
    public String getFirstName(){
    	return name;
    }
    public void setFirstName(String firstName){
    	this.name = firstName;
    }
    
    public String getLastName(){
    	return surname;
    }
    public void setLastName(String lastName){
    	this.surname = lastName;
    }
    
    public List<Pet> getPets(){
    	return pets;
    }
    public void setUsersForDepartment(List<Pet> pets){
    	this.pets = pets;
    }
}

These classes have a List of Pets/PetDTOs:
public class Pet {

	String name; 
	String species;
	
    public String getName(){
    	return name;
    }
    public void setName(String name){
    	this.name = name;
    }
    
    public String getSpecies(){
    	return species;
    }
    
    public void setSpecies(String species){
    	this.species = species;
    }
}

public class PetDTO {

	String nickname; 
	String species;
	
    public String getName(){
    	return nickname;
    }
    public void setName(String name){
    	this.nickname = name;
    }
    
    public String getSpecies(){
    	return species;
    }
    
    public void setSpecies(String species){
    	this.species = species;
    }
}

Now I want to update Person, and also the List<Pet> in Person from the corresponding DTOs. Therefore, I created the following mappers:

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

@Mapper
public abstract class PetDTOtoPetMapper {

//This mapper correctly generates an implementation that updates my pet...
	@Mapping(source = "nickname", target ="name")
	abstract Pet petDTOtoPet(PetDTO source, @MappingTarget Pet destination);
	
}

======================
import java.util.List;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.Mappings;

@Mapper
public abstract class PersonDTOtoPersonMapper {

	// instead of using the implementation of "mapToPetList" below a new list of pets is generated and the elements are added individually..
	@Mappings(value = { @Mapping(target = "firstName", source = "name"),
			@Mapping(target = "lastName", source = "surname") })
	abstract Person personDTOtoPerson(PersonDTO source,
			@MappingTarget Person destination);

	public abstract void mapToPetList(List<Pet> dtos,
			@MappingTarget List<Pet> pets);

}

This class is supposed to update Person AND the corresponding List<Pet> 
Person so far is updated correctly. However, instead of using the generated update method mapToPetList a new mapToList method is generated, which creates a new List of pets..

I hope I could explain my problem... 

Thanks
Gamze

**Comment by sjaakd** [comment] 2015-05-26 11:05
Hi Gamze,

I reckon your issues are already covered in #487, #488 and #489 . The current update functionality only concerns bean update mappings (not maps and iterable types).  Can you check those and see if these addresses your concerns? 

Best regards,
Sjaak

**Comment by gcanova** [comment] 2015-05-26 17:30
Hi Sjaak,

Thanks a lot for the quick response.
As far as I can see collections are not considered by the update functionality yet either, at least not when they are part of another updated object, or did I miss something?

**Comment by sjaakd** [comment] 2015-05-26 19:35
Hi Gamze,

There are few things to consider. 
1. Generating the 'update' implementation for a collection or map is tricky. That's what I try to describe in #487. You have to make an assumption on how to merge the source with the target collection. Hence the proposal in #487.
2. Selecting a handwritten update method is possible (so leaving it up to the user), but unfortunately not supported yet for collections types and maps. It is for beans. Checkout our unit test in `org.mapstruct.ap.test.updatemethods.selection`.
3. I've rewritten your example a little bit. Take in mind that MapStruct follows the bean convention.

```java
package org.mapstruct.ap.test.updatemethods.collection;

import java.util.ArrayList;
import java.util.List;

public class Person {

    private String firstName;
    private String lastName;
    private List<Pet> pets = new ArrayList<Pet>();

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public List<Pet> getPets() {
        return pets;
    }

    public void setPets(List<Pet> pets) {
        this.pets = pets;
    }
   
}
```

```java
package org.mapstruct.ap.test.updatemethods.collection;

import java.util.ArrayList;
import java.util.List;

public class PersonDTO {

    private String name;
    private String surname;
    private List<PetDTO> pets = new ArrayList<PetDTO>();

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public List<PetDTO> getPets() {
        return pets;
    }

    public void setPets(List<PetDTO> pets) {
        this.pets = pets;
    }

}
```

```java
package org.mapstruct.ap.test.updatemethods.collection;

public class Pet {

    String name;
    String species;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSpecies() {
        return species;
    }

    public void setSpecies(String species) {
        this.species = species;
    }
}
```

```java
package org.mapstruct.ap.test.updatemethods.collection;

public class PetDTO {

    String nickname;
    String species;

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getSpecies() {
        return species;
    }

    public void setSpecies(String species) {
        this.species = species;
    }
}
```

```java
package org.mapstruct.ap.test.updatemethods.collection;

import java.util.List;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.Mappings;

@Mapper
public abstract class PersonDTOtoPersonMapper {

// instead of using the implementation of "mapToPetList" below a new list of pets is generated and the elements are added individually..
    @Mappings(value = {
        @Mapping(target = "firstName", source = "name"),
        @Mapping(target = "lastName", source = "surname")
    })
    abstract Person personDTOtoPerson(PersonDTO source, @MappingTarget Person destination);

    public void mapToPetList(List<PetDTO> dtos, @MappingTarget List<Pet> pets) {
    }

//    public List<Pet>  mapToPetList2(List<PetDTO> dtos ) {
//        return null;
//    }
}
```

Note the commented method, with that one it basically works, but unfortunately its not an `update` but `create` method.

```java
package org.mapstruct.ap.test.updatemethods.collection;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

@Mapper
public abstract class PetDTOtoPetMapper {

//This mapper correctly generates an implementation that updates my pet...
    @Mapping(source = "nickname", target = "name")
    abstract Pet petDTOtoPet(PetDTO source, @MappingTarget Pet destination);

}
```

Hope that explains a bit what the current status is on update method.  We might take a step in between allowing selection of update methods with collections / maps.

I'll close this issue, since its already logged.

**Closed by sjaakd** 2015-05-26 19:35 UTC

**Comment by gcanova** [comment] 2015-05-27 05:40
Thank you Sjaakd,

I think at least selecting the update method for collections/maps will I help a lot. Otherwise one would need to manually implement the using mapper either...

Cheers,
Gamze

**Comment by wassila77** [comment] 2021-01-21 17:21
I'm having issue with update collection. any update for the fix ??

**Comment by wassila77** [comment] 2021-01-21 17:35
@sjaakd  The issue is when we update a collection even it's not changed (there's not new entry) , an entry is added to the data base.
We noticed that there's an issue at mapstruct level which creates a new object in the list even it's an update not create.
 
The implementation is not right at the update method that mapstruct creates.
it creates  **ToModel** method, it creates a new object :   IndividualName individualName = new IndividualName(); instead of using the existing object since we are doing un update.


  @Override
    public Set<IndividualName> update(List<IndividualNameResource> individualNameResources, Set<IndividualName> individualNames) {
        if ( individualNameResources == null ) {
            return null;
        }

        individualNames.clear();
        for ( IndividualNameResource individualNameResource : individualNameResources ) {
            individualNames.add( **toModel( individualNameResource )** );
        }

        return individualNames;
    }

@Override
    public IndividualName toModel(IndividualNameResource individualNameResource) {
        if ( individualNameResource == null ) {
            return null;
        }

        **IndividualName individualName = new IndividualName();**
