### ISSUE TITLE
Support of camelCased properties

### ISSUE THREAD

**Issue by lex-em** [mapstruct/mapstruct#1326] opened 2017-11-01 08:02 UTC
may be add support for camelCased properties? e.g.
```
@Data
public class Internal {
    private Long id;
}
```
```
@Data
public class Entity {
    private String data;
    private Internal internal;
}
```
```
@Data
public class EntityDto {
    private String data;
    private Long internalId;
}
```
with mapper:
```
@Mapper
public interface Converter {
    EntityDto to(Entity entity);
}
```
```
public class ConverterImpl implements Converter {

    @Override
    public EntityDto to(Entity entity) {
        if ( entity == null ) {
            return null;
        }

        EntityDto entityDto = new EntityDto();

        Long id = entityInternalId( entity );
        if ( id != null ) {
            entityDto.setInternalId( id );
        }
        entityDto.setData( entity.getData() );

        return entityDto;
    }

    private Long entityInternalId(Entity entity) {
        if ( entity == null ) {
            return null;
        }
        Internal internal = entity.getInternal();
        if ( internal == null ) {
            return null;
        }
        Long id = internal.getId();
        if ( id == null ) {
            return null;
        }
        return id;
    }
}
```

it looks like there is an implicit `@Mapping(target = "internalId", source = "internal.id")` annotation on mapper interface method

**Comment by filiphr** [comment] 2017-11-03 22:04
@lex-em I am not sure I am following what you are looking for. Mapstruct indeed supports camelCase properties.

**Comment by lex-em** [comment] 2017-11-09 03:07
@filiphr can you give me link?

for the sample above mapstruct generate next class:
```
public class ConverterImpl implements Converter {

    @Override
    public EntityDto to(Entity entity) {
        if ( entity == null ) {
            return null;
        }

        EntityDto entityDto = new EntityDto();

        entityDto.setData( entity.getData() );

        return entityDto;
    }
}
```

**Comment by filiphr** [comment] 2017-11-10 22:27
@lex-em just rename your property from `data` into `someData` and MapStruct will generate the correct mappings. I still am not sure what the issue is?

The generated mapping is correct, because that property is the only one that MapStruct can map automatically, if you look at the log you should have some warning saying that `internalId` is not mapped. In order to map that properly you need to define your mapper like:

```java
@Mapper
public interface Converter {

    @Mapping(target = "internalId", source = "internal.id")
    EntityDto to(Entity entity);
}
```

Then the generated code will contain the mapping. 

I am closing this issue, as everything works as expected. Please reopen it if you think it needs reopening

**Closed by filiphr** 2017-11-10 22:27 UTC
