### ISSUE TITLE
Empty object if there is no @Mappings annotation 

### ISSUE THREAD

**Issue by almothafar** [mapstruct/mapstruct#790] opened 2016-03-23 13:16 UTC
I have issue with empty object if I just was have mapper but without any `@Mappings` annotation, as the following example: 

```
@Mapper
public interface UserMapper {
    public static UserMapper INSTANCE = Mappers.getMapper(UserMapper.class);

    User map(UserDTO userDTO);
    UserDTO map(User user);
}
```

Classes: 

User:
```
@Entity
@EntityConcurrencyMode(ConcurrencyMode.NONE)
@Table(name = "USERS")
public class User extends BaseModel {

    @Column(name = "full_name", nullable = false)
    public String fullName;

    @Column(nullable = false)
    public String email;

    public User() {
    }

}
```

UserDTO: 
```
public class UserDTO extends BaseDTO {

    public String fullName;
    public String email;

}
```

So simply the generated UserMapperImpl will be like this : 
```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2016-03-23T15:05:35+0200",
    comments = "version: 1.1.0.Beta1, compiler: javac, environment: Java 1.8.0_66 (Oracle Corporation)"
)
public class UserMapperImpl implements UserMapper {

    @Override
    public User map(UserDTO userDTO) {
        if ( userDTO == null ) {
            return null;
        }

        User user = new User();


        return user;
    }

    @Override
    public UserDTO map(User user) {
        if ( user == null ) {
            return null;
        }

        UserDTO userDTO = new UserDTO();


        return userDTO;
    }
}
```

To get workaround this I just added one target and source: 
```
@Mappings({
            @Mapping(source="fullName", target="fullName"),
    })
```

And Got correct generated implementation.

**Comment by agudian** [comment] 2016-03-23 18:10
As you have already found out in the other issue, the problem is that there are no getters/setters, at least at the time the compiler calls our annotation processor. The order might have been different for you or the altered bean class file might have been available after you added the `@Mapping` annotation, but that's more out of luck then... It wouldn't work every time.

We planning to support accessing public properties directly if there are no getters/setters, though :). Tracked in #557.

I'm closing this as duplicate. Thanks for the report anyway!

**Closed by agudian** 2016-03-23 18:10 UTC
Labels: duplicate

**Comment by lcmartins** [comment] 2020-12-17 02:45
if you are using lombok, place the lombok path inside the plugin/configuration section in the begining, before the mapstruct section, that works for me
