### ISSUE TITLE
SubclassExhaustiveStrategy.RUNTIME_EXCEPTION does not work in combination with @Named and @SubclassMapping

### ISSUE THREAD

**Issue by robeatoz** [mapstruct/mapstruct#3439] opened 2023-11-10 10:40 UTC
### Expected behavior

I expect that the existing mapping configuration remains functional after adding an `@Named` annotation to the mapping method. Specifically, the addition of the `@Named` annotation should not impact the effectiveness or the execution of the already established mappings. The mapping should continue to operate as it did before the annotation being added, seamlessly integrating the `@Named` annotation without causing any disruptions or errors in the mapping process.

### Actual behavior

After adding the `@Named` annotation to the mapping method, I observed an unexpected behavior in the MapStruct framework. Instead of continuing to function as before, the mapping configuration seems to be disrupted. Specifically, the mappings that formerly worked flawlessly are now causing the error `The return type AnimalTarget is an abstract class or interface. Provide a non abstract / non interface result type or a factory method`. This deviation from the expected behavior indicates that the addition of the `@Named` annotation is adversely affecting the established mapping processes.

### Steps to reproduce the problem

Below is a minimalistic example provided to reproduce the observed error. This example demonstrates that the mapping functions correctly without the `@Named` annotation. However, when the `@Named` annotation is added, the error occurs, indicating a direct correlation between the annotation and the issue:

```java
import org.mapstruct.Mapper;
import org.mapstruct.Named;
import org.mapstruct.SubclassExhaustiveStrategy;
import org.mapstruct.SubclassMapping;

import lombok.Data;

@Mapper(
        subclassExhaustiveStrategy = SubclassExhaustiveStrategy.RUNTIME_EXCEPTION
)
public interface TestMapper {

    AnimalContainerTarget mapToAnimalContainer(AnimalContainerSource animalContainerSource);

    @SubclassMapping(source = CatSource.class, target = CatTarget.class)
    @SubclassMapping(source = DogSource.class, target = DogTarget.class)
    @Named("RemoveThisToCompileWithoutErrors")
    AnimalTarget mapToAnimalTarget(AnimalSource animalSource);

}

@Data
class AnimalContainerSource {
    AnimalSource animal;
}

@Data
class AnimalContainerTarget {
    AnimalTarget animal;
}

interface AnimalSource {

}

interface AnimalTarget {

}

@Data
class CatSource implements AnimalSource {
    String name;
}

@Data
class CatTarget implements AnimalTarget {
    String name;

}

@Data
class DogSource implements AnimalSource {
    String name;

}

@Data
class DogTarget implements AnimalTarget {
    String name;
}
```

### MapStruct Version

MapStruct 1.5.5

**Comment by thunderhook** [comment] 2023-11-11 21:51
This has nothing to do with `@SubclassMapping` or the `SubclassExhaustiveStrategy` but instead how MapStruct handles (`@Named`) qualifiers.

Here is another (obviously stupid) example mapper that produces a similar compilation error. MapStruct does not know how to map `SourceObject` to `String` and shows the error: `java: Can't map property "SourceObject object" to "String object". Consider to declare/implement a mapping method: "String map(SourceObject value)".`

When providing that method, everyhing is fine:

```java
@Mapper
public interface TestMapper {

    Target map(Source source);

    default String map(SourceObject value) {
        return value.getSomething();
    }

}

@Data
class Source {
    SourceObject object;
}

@Data
class SourceObject {
    String something;
}

@Data
class Target {
    String object;
}
```

When you declare the qualifier with `@Named` MapStruct will only choose that method when it is explicilty declared with `qualifiedByName = "..."`. _This is not clearly stated in the reference documentation (at least I couldn't find it, maybe we could improve this)._

```java
@Mapper
public interface TestMapper {

    @Mapping( target = "object", source = "object", qualifiedByName = "original")
    Target map(Source source);

    @Named("original")
    default String map(SourceObject value) {
        return value.getSomething();
    }

    @Named("uppercase")
    default String map(SourceObject value) {
        return value.getSomething().toUpperCase();
    }

}
```

So the use-case of an qualifier is when you have several (ambigous or different) mapping methods and you want to control when it is used. To state the docs: "In many occasions, one requires mapping methods with the same method signature (apart from the name) that have different behavior..."

> I expect that the existing mapping configuration remains functional after adding an @Named annotation to the mapping method. Specifically, the addition of the @Named annotation should not impact the effectiveness or the execution of the already established mappings.

This is how the Spring framework handles qualifiers. Maybe that is why you would expect that. Adding a qualifier in Spring does not have an effect when it is the only unambiguous choice.

However this is not the case with MapStruct. Changing this behaviour would not be backward-compatible, only when this could be enabled with an option (in `@Mapper` or `@MapperConfig`).

@filiphr Are there other issues addressing the behaviour of method resolution based on qualifiers? I will change this ticket to an enhancement. If this is by design and should not be changed whatsoever feel free to close this issue.

**Comment by filiphr** [comment] 2023-11-26 19:11
The reason for the error is due to adding the `@Named`. However, if you look a bit closer and see where that error is it would be on the `AnimalContainerTarget mapToAnimalContainer(AnimalContainerSource animalContainerSource);` method and not on the one with `@Named`. The reason for it is due to the fact that MapStruct is going to try to create implicit mapping between `AnimalSource` and `AnimalTarget` for the `mapToAnimalContainer` and that would then lead to the compile error.

There are 2 ways to resolve this error (if you want to keep using `@Named`.

* Get rid of `mapToAnimalContainer`
* Use `@Mapping(target = "animal", qualifiedByName = "RemoveThisToCompileWithoutErrors")` on the `mapToAnimalContainer`.

Going to close the issue as it works as designed.

**Closed by filiphr** 2023-11-26 19:11 UTC
Labels: enhancement
