### ISSUE TITLE
Date tests sometimes (less than 0.1% of the time) fail

### ISSUE THREAD

**Issue by Zegveld** [mapstruct/mapstruct#2806] opened 2022-04-02 16:54 UTC
I've seen tests fail randomly, so this will also make some mappings inconsistent at rare moments. 
Chance of happening seems to be below 0.1% of the time, but would be nice if this was 0%.

1) DateConversionTest.shouldApplyDateFormatForConversionsJdk11
```
[INFO] Running org.mapstruct.ap.test.injectionstrategy.jsr330._default.Jsr330DefaultCompileOptionFieldMapperTest
Error:  Tests run: 22, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 0.906 s <<< FAILURE! - in org.mapstruct.ap.test.conversion.date.DateConversionTest
Error:  org.mapstruct.ap.test.conversion.date.DateConversionTest.shouldApplyDateFormatForConversionsJdk11  Time elapsed: 0.337 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting:
 <"05.07.2013">
to be equal to:
 <"06.07.2013">
but was not.
	at org.mapstruct.ap.test.conversion.date.DateConversionTest.shouldApplyDateFormatForConversionsJdk11(DateConversionTest.java:66)
```

2) NestedMappingMethodInvocationTest
[Another failed test](https://github.com/mapstruct/mapstruct/runs/5611036594?check_suite_focus=true):
```
 [INFO] Running org.mapstruct.ap.test.nestedmethodcall.NestedMappingMethodInvocationTest
Error:  Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.525 s <<< FAILURE! - in org.mapstruct.ap.test.nestedmethodcall.NestedMappingMethodInvocationTest
Error:  org.mapstruct.ap.test.nestedmethodcall.NestedMappingMethodInvocationTest.shouldMapViaMethodAndConversion  Time elapsed: 0.252 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting:
 <2013-07-05T22:00:00.000 (java.util.Date)>
to be equal to:
 <2013-07-06T00:00:00.000 (java.util.Date)>
but was not.
	at org.mapstruct.ap.test.nestedmethodcall.NestedMappingMethodInvocationTest.shouldMapViaMethodAndConversion(NestedMappingMethodInvocationTest.java:74)
```

3) VariableNamingTest
[and another one](https://github.com/mapstruct/mapstruct/runs/5259241075?check_suite_focus=true)
[been a while, but here again (30-05-2022)](https://github.com/mapstruct/mapstruct/runs/6660512111?check_suite_focus=true#step:4:1156):
```
INFO] Running org.mapstruct.ap.test.builtin.BuiltInTest
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.475 s <<< FAILURE! - in org.mapstruct.ap.test.naming.VariableNamingTest
Error:  org.mapstruct.ap.test.naming.VariableNamingTest.shouldGenerateImplementationsOfMethodsWithProblematicVariableNmes  Time elapsed: 0.202 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting map:
 <{"121"="19.07.2013", "42"="31.12.1979"}>
to contain:
 <[MapEntry[key="42", value="01.01.1980"],
    MapEntry[key="121", value="20.07.2013"]]>
but could not find the following map entries:
 <[MapEntry[key="42", value="01.01.1980"],
    MapEntry[key="121", value="20.07.2013"]]>

	at org.mapstruct.ap.test.naming.VariableNamingTest.shouldGenerateImplementationsOfMethodsWithProblematicVariableNmes(VariableNamingTest.java:50)
```

4) DateConversionTest.shouldApplyStringConversionForReverseArrayMethod
[once more](https://github.com/mapstruct/mapstruct/runs/4987671258?check_suite_focus=true),
[Failed test](https://github.com/mapstruct/mapstruct/runs/5798967194?check_suite_focus=true):
```
 [INFO] Running org.mapstruct.ap.test.conversion.date.DateConversionTest
Error:  Tests run: 25, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 0.566 s <<< FAILURE! - in org.mapstruct.ap.test.conversion.date.DateConversionTest
Error:  org.mapstruct.ap.test.conversion.date.DateConversionTest.shouldApplyStringConversionForReverseArrayMethod  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting:
  <[2013-07-05T22:00:00.000 (java.util.Date),
    2013-02-14T00:00:00.000 (java.util.Date),
    2013-04-11T00:00:00.000 (java.util.Date)]>
to contain exactly (and in same order):
  <[2013-07-06T00:00:00.000 (java.util.Date),
    2013-02-14T00:00:00.000 (java.util.Date),
    2013-04-11T00:00:00.000 (java.util.Date)]>
but some elements were not found:
  <[2013-07-06T00:00:00.000 (java.util.Date)]>
and others were not expected:
  <[2013-07-05T22:00:00.000 (java.util.Date)]>

	at org.mapstruct.ap.test.conversion.date.DateConversionTest.shouldApplyStringConversionForReverseArrayMethod(DateConversionTest.java:153)
```

5) MapMappingTest.shouldCreateReverseMapMethodImplementation
[Failed test](https://github.com/mapstruct/mapstruct/actions/runs/3171965701/jobs/5165936390)
```
Error:  Tests run: 21, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.582 s <<< FAILURE! - in org.mapstruct.ap.test.collection.map.MapMappingTest
Error:  org.mapstruct.ap.test.collection.map.MapMappingTest.shouldCreateReverseMapMethodImplementation  Time elapsed: 0.013 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting map:
 <{42L=1979-12-31T23:00:00.000 (java.util.Date), 121L=2013-07-19T22:00:00.000 (java.util.Date)}>
to contain:
 <[MapEntry[key=42L, value=1980-01-01T00:00:00.000 (java.util.Date)],
    MapEntry[key=121L, value=2013-07-20T00:00:00.000 (java.util.Date)]]>
but could not find the following map entries:
 <[MapEntry[key=42L, value=1980-01-01T00:00:00.000 (java.util.Date)],
    MapEntry[key=121L, value=2013-07-20T00:00:00.000 (java.util.Date)]]>

	at org.mapstruct.ap.test.collection.map.MapMappingTest.assertResult(MapMappingTest.java:102)
	at org.mapstruct.ap.test.collection.map.MapMappingTest.shouldCreateReverseMapMethodImplementation(MapMappingTest.java:53)
```

**Comment by filiphr** [comment] 2022-04-03 13:27
I am not sure if the problem is the mapping or if the date itself is already incorrect at the time it is set. Perhaps we need to use `Date.from( Instant.parse(...) )` instead of using the `GregorianCalendar`

**Comment by Zegveld** [comment] 2022-04-03 15:35
It feels like a timezone problem either in the conversion or at the creation of the date object.
Would not surprise me if the problem was in the test setup, could be that your suggestion fixes it since all the failed tests so far use `GregorianCalendar` to create the date objects.
Hopefully future failures will help with pinpointing this issue so we can fix it.

**Comment by arnaldop** [comment] 2022-06-03 15:33
In my current application, I have noticed that certain tests fail after the 28th of the month. This is because date math becomes wonky at that point.

For example, if I have a date of 2020-02-29, is 1 month later 2020-03-29? But then what happens the following year when there is no 2021-02-29? Should it be 2021-03-01?
Or if I have a date of 2022-03-30, is 11 months later 2022-02-28 or 2022-03-02? But if it's 2022-03-02, then my "root" day, the 30th, is no longer correct.

So my tests would fail intermittently, but I figured out they were failing on the 29th through the 31st of the month.

Maybe this helps narrow things down.

**Comment by filiphr** [comment] 2022-06-05 10:04
Thanks a lot for the tips @arnaldop. Your comment inspired me to have a look at this with a different point of view. 

I had a look at the `NestedMappingMethodInvocationTest .shouldMapViaMethodAndConversion`. Which is using a custom date format for formatting.

The way we parse this is:

```
new SimpleDateFormat( "dd.MM.yyyy" ).parse( jaxbElemToValue( source.getDate() ) )
```

The `SimpleDateFormat` will use the default time zone for the tests. Our tests are running in parallel and in some tests we do change it using JUnit Pioneer and `DefaultTimeZone`.  That annotation will correctly reset the time zone, but under parallel test execution it can happen that we use the wrong timezone at certain points.

**Comment by filiphr** [comment] 2022-06-05 10:08
I've created #2869 that might fix some of these things.

**Comment by filiphr** [comment] 2022-06-14 20:04
Closing this since all the tests discovered by @Zegveld should be covered for multi threading. If we find more we can look into them separately.

**Comment by filiphr** [comment] 2022-06-18 12:38
I don't think that my fixes actually helped here. I saw the same problem few days ago when I pushed some things at 23 in the evening.

**Comment by filiphr** [comment] 2023-10-10 18:57
Closing this for now. We'll open a new one if we find some more problems

**Closed by filiphr** 2023-10-10 18:57 UTC
Labels: test
