### ISSUE TITLE
Method resolution within abstract class

### ISSUE THREAD

**Issue by avk2** [mapstruct/mapstruct#1597] opened 2018-08-27 12:11 UTC
I define my mapper as abstract class instead of interface and I need to specify what method should be used on a specific mapping. I've tried this:

  
    @Named("toCountryDtoObject")
    @Mappings({
        ...
    })
    public abstract CountryDto toCountryDto(Country entity);

    
    @Mappings({
        ...
        @Mapping(source = "pk.country", target = "country", qualifiedByName = "toCountryDtoObject"),
        ...
    })
    public abstract ProvinceDto toProvinceDto(Province entity);

But when I go to check the generated implementation, it still doesnt call my method. What I'm doing wrong? `@Named` only works within interfaces?

**Comment by sjaakd** [comment] 2018-08-27 19:34
can you check if `@Named` is MapStruct `@Named` (and not for instance Spring)..?

**Comment by avk2** [comment] 2018-08-28 11:49
Yes, I'm making sure it's taking it from mapstruct package

**Comment by sjaakd** [comment] 2018-08-28 17:58
Ok..Can you provide a reproducer (gist)? Keep it as small as possible. Preferably maven based..

**Comment by avk2** [comment] 2018-08-30 06:48
This is my actual code: 

https://drive.google.com/file/d/1RkYGv-N4pHf_Stz9x5Knbl2kk6C5xWsw/view?usp=sharing

After compiling, I go to the generated code and I get this:

```
@Override
    public AutonomiaDto toAutonomiaDto(Autonomia entity, Idioma idioma) {
        if ( entity == null && idioma == null ) {
            return null;
        }

        AutonomiaDto autonomiaDto = new AutonomiaDto();

        if ( entity != null ) {
            String codigo = entityPkCodigo( entity );
            if ( codigo != null ) {
                autonomiaDto.setCodigo( codigo );
            }
            Pais pais = entityPkPais( entity );
            if ( pais != null ) {
                autonomiaDto.setPais( paisToPaisDto( pais ) );   //should call toPaisDto() instead
            }
        }

        setDtoNombre( entity, idioma, autonomiaDto );

        return autonomiaDto;
    }
```

**Comment by sjaakd** [comment] 2018-08-30 06:53
Ok.. I'll  try to have a look at it asap.

**Comment by sjaakd** [comment] 2018-08-30 17:50
The problem is this: MapStruct cannot select mappings based on 2 source parameters. It can only match up `one target` with `one source`.

Having said that: `Idiom` is not actually a mapping source parameter. Its a `Context` parameter. We have means for that, and those methods are selected automatically. Just annotate the parameter as `@Context` in each method. 

Even nicer: You could create a class to do this (e.g. `IdiomSelector`) and put your logic (even `@AfterMapping` entirely in this class, so you keep your Mapper clean.

.. 
So sumarising and taking your code example
```java
@Mapper(componentModel = "spring")
public interface GeographyMapper {

    @Named("toPaisDto")
    @Mapping(source = "entity.codigo", target = "codigo")
    @Mapping(target = "nombre", ignore = true)
    PaisDto toPaisDto(Pais entity, @Context IdiomaSelector idiomaSelector);

    List<PaisDto> toPaisDtos(List<Pais> entities, @Context IdiomaSelector idiomaSelector);

    @Mapping(source = "entity.pk.codigo", target = "codigo")
    @Mapping(source = "entity.pk.pais", target = "pais", qualifiedByName = "toPaisDto")
    @Mapping(target = "nombre", ignore = true)
    AutonomiaDto toAutonomiaDto(Autonomia entity, @Context IdiomaSelector idiomaSelector);

    List<AutonomiaDto> toAutonomiaDtos(List<Autonomia> entities, @Context IdiomaSelector idiomaSelector);
}
```

```java

@AllArgsConstructor
public class IdiomaSelector {

    private Idioma idioma;

    @AfterMapping
    public void setDtoNombre(Pais entity, Idioma idioma, @MappingTarget PaisDto dto) {
        String nombre = entity.getNombreByLanguage(idioma);
        dto.setNombre(nombre);
    }

    @AfterMapping
    public void setDtoNombre(Autonomia entity, @Context IdiomaSelector idiomaSelector, @MappingTarget AutonomiaDto dto) {
        String nombre = entity.getNombreByLanguage(idioma);
        dto.setNombre(nombre);
    }

}
```

And you can construct the selector with `Idioma`.. WDYT?

**Comment by avk2** [comment] 2018-08-31 06:54
That is much better! But how it's suposed I do the call? 

`geographyMapper.toPaisDto(entity, ?);` and IdiomaSelector method signatures must have IdiomaSelector or Idioma as parameter ?

**Comment by sjaakd** [comment] 2018-08-31 07:03
> geographyMapper.toPaisDto(entity, ?); and IdiomaSelector method signatures must have IdiomaSelector or Idioma as parameter ?

`geographyMapper.toPaisDto(entity, new IdiomSelector( idiom );`

And coming back to your original question: why do you need `@Named("toPaisDto")` and `, qualifiedByName = "toPaisDto"`?? Qualifiers are required if MapStruct has multiple candidate methods it can call. I think there's only one method with a signature that maps `Pais` to `PaisDto`, being `toPaisDto`.  So you can remove them as well.

**Comment by avk2** [comment] 2018-08-31 07:27
Ah nice, so to catch the right methid it's needed to be unique and with one parameter.

Btw, the signature of IdiomaSelector  would be like this: `void setDtoNombre(Pais entity, @MappingTarget PaisDto dto)`

**Comment by sjaakd** [comment] 2018-08-31 09:42
>>Btw, the signature of IdiomaSelector would be like this: void setDtoNombre(Pais entity, @MappingTarget PaisDto dto)

Yep.. I saw I made an error in the `IdeomaSelector`. Can't verify it from my current location, but you meant this (note, also the `@Context IdeomaSelector ideomaSelector` is removed from the other method):

```java
@AllArgsConstructor
public class IdiomaSelector {

    private Idioma idioma;

    @AfterMapping
    public void setDtoNombre(Pais entity,  @MappingTarget PaisDto dto) {
        String nombre = entity.getNombreByLanguage(idioma);
        dto.setNombre(nombre);
    }

    @AfterMapping
    public void setDtoNombre(Autonomia entity, @MappingTarget AutonomiaDto dto) {
        String nombre = entity.getNombreByLanguage(idioma);
        dto.setNombre(nombre);
    }

}
```
That should fix it.. right?

**Comment by sjaakd** [comment] 2018-08-31 10:53
@avk2 : I want to close this issue.. Also: the reported issue is not really a MapStruct issue. We have a [gitter room](https://gitter.im/mapstruct/mapstruct-users) which offers quick response to support questions. Alternatively, you can post questions on StackOverflow and tag them with MapStruct. In that way, many users can profit from the answer. If there's an issue after all, you can open a new one.

**Closed by sjaakd** 2018-08-31 10:53 UTC

**Comment by avk2** [comment] 2018-08-31 11:58
yep! and thanks again
