### ISSUE TITLE
MapStruct is mapping static properties

### ISSUE THREAD

**Issue by davidkron** [mapstruct/mapstruct#926] opened 2016-10-07 08:30 UTC
Hello

I'm using MapStruct 1.1.0.CR1 with Gradle and have discovered, that the generated code also maps static properties, which seems like a bug.

Bean class:

```
 public class Test {

    private String normalProperty;
    private static String staticProperty;

    public String getNormalProperty() {
        return normalProperty;
    }

    public void setNormalProperty(String normalProperty) {
        this.normalProperty = normalProperty;
    }

    public static String getStaticProperty() {
        return staticProperty;
    }

    public static void setStaticProperty(String staticProperty) {
        Test.staticProperty = staticProperty;
    }
 }
```

Mapper interface:

```
 @Mapper
 interface TestMapper {

    Test copy(Test test);
 }
```

Generated code:

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2016-10-07T10:22:47+0200",
    comments = "version: 1.1.0.CR1, compiler: javac, environment: Java 1.8.0_102 (Oracle Corporation)"
)
class TestMapperImpl implements TestMapper {

    @Override
    public Test copy(Test test) {
        if ( test == null ) {
            return null;
        }

        Test test_ = new Test();

        test_.setNormalProperty( test.getNormalProperty() );
        test_.setStaticProperty( test.getStaticProperty() );

        return test_;
    }
}
```

**Comment by sjaakd** [comment] 2016-10-20 19:22
Interesting... Did not know that. In your opinion, would there be serious problems if we keep on supporting that? Note: we are probably not adhering to the Bean Convention in a strict sense, that talks about properties, which I take to be instance variables.

**Comment by filiphr** [comment] 2016-10-21 20:51
There is a way to workaround this. While playing a bit, I noticed that one can provide their own `AccessorNamingStrategy` extending the `DefaultAccessorNamingStrategy` and do a check on the modifiers of the executable, or even earlier in the `getMethodType`

**Comment by gunnarmorling** [comment] 2016-10-21 20:59
Ah yes, that's a good idea. I'm inclined to close this one as "Not a bug". We could add an FAQ entry "How to exclude static properties". But for that we'd need an FAQ on the website first :)

**Comment by filiphr** [comment] 2017-07-02 20:28
Closing this a "Not a bug". I have created https://github.com/mapstruct/mapstruct.org/issues/61 for adding an FAQ

**Closed by filiphr** 2017-07-02 20:28 UTC
Labels: not a bug
