### ISSUE TITLE
Nested mapper interfaces don't work.

### ISSUE THREAD

**Issue by fpeter8** [mapstruct/mapstruct#1160] opened 2017-03-28 12:46 UTC
We tried the following code:

```java
public interface ApiMapper<S, T> {
    
    SalesTransactionMapper SALES_TRANSACTION_MAPPER = Mappers.getMapper(SalesTransactionMapper.class);
    
    T toApiDto(S entity);
    
    S fromApiDto(T apiDto);
    
    @Mapper(uses = {TransactionLineMapper.class, NumericMapper.class, DateTimeMapper.class, EnumMapper.class})
    interface SalesTransactionMapper extends ApiMapper<SalesTransaction, ApiSalesTransaction> {}
    
    @Mapper(uses = {NumericMapper.class, EnumMapper.class})
    interface TransactionLineMapper extends ApiMapper<TransactionLine, ApiTransactionLine> {}
}
```

When I try to access the mapper field, I get the following error:
`java.lang.RuntimeException: java.lang.ClassNotFoundException: Cannot find implementation for dk.dagrofa.merkur.api.dto.mapper.ApiMapper$SalesTransactionMapper`

If I move the actual mapper interfaces into separate files, the loader finds the implementations.

* I checked, MapStruct generates the correct implementations even for a nested interface.
* I checked, the generated code IS inside the jar/war of the project.

**Comment by filiphr** [comment] 2017-03-28 19:26
Just to make sure the implementation that is generated is in its own `SalesTransactionMapperImpl.java` file right?

The factory tries to load `<CLASS_NAME>Impl` and the class name of your mapper is `dk.dagrofa.merkur.api.dto.mapper.ApiMapper$SalesTransactionMapper`

As written in the Javadoc of the factory:

>Mapper implementation types are expected to have the same fully qualified name as their interface type, with the suffix `Impl` appended. When using this factory, mapper types - and any mappers they use - are instantiated by their public no-args constructor.

Your interfaces should be in it's own files. If you want this issue can be considered as a feature request to the `Mappers` factory to consider nested interfaces as well or you can create a new feature request.

**Comment by filiphr** [comment] 2017-04-29 10:43
This a a duplicate of #611. Therefore I will close this one. If you want to follow the status please watch the original.

**Closed by filiphr** 2017-04-29 10:43 UTC
