### ISSUE TITLE
Support constant mapping for enum as a source

### ISSUE THREAD

**Issue by typekpb** [mapstruct/mapstruct#2942] opened 2022-07-27 04:01 UTC
There seems to be no way (despite introduction of `@EnumMapping`) to map constant enum, so I'm still forced to use `@Mapping( expression = "...")` instead.

Current situation:

Source mapping class:
```java

public class A {
    private String prop;

    public String getProp() {
        return prop;
    }

    public void setProp(String prop) {
        this.prop = prop;
    }
}

```
Target mapping class:
```java
public class B {
    private String prop;

    private CType prop2;

    public String getProp() {
        return prop;
    }

    public void setProp(String prop) {
        this.prop = prop;
    }

    public CType getProp2() {
        return prop2;
    }

    public void setProp2(CType prop2) {
        this.prop2 = prop2;
    }
}
```
Enum to map:
```java
public enum CType {
    VAL_1, VAL_2;
}
```
Mapper:
```java
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

@Mapper
public interface BMapper {
    BMapper INSTANCE = Mappers.getMapper(BMapper.class);

    @Mapping(target = "prop2", expression = "java(CType.VAL_2)")
    B map(A source);
}
```

I'd prefer a way, where I'd be able to map `CType.VAL_2` as an annotation field directly.

**Comment by filiphr** [comment] 2022-07-27 15:32
Have you tried using `Mapping#constant`?

In your case:

```java
@Mapper
public interface BMapper {
    BMapper INSTANCE = Mappers.getMapper(BMapper.class);

    @Mapping(target = "prop2", constant = "VAL_2")
    B map(A source);
}
```

Perhaps we need to adapt the javadoc for this

**Comment by nigelsim** [comment] 2023-02-28 03:23
This does not work in 1.4.2.

```
    @Mappings({
            @Mapping(target = "conditionType", constant = "ACTION")
    })
    public abstract RegisterEntryVerificationActivityDto toManuallyActionRegisterEntryVerificationActivityDto(
            AircraftRegisterVerificationActivity authorityConditionActivity);
```

produces

```
    @Override
    public RegisterEntryVerificationActivityDto toManuallyActionRegisterEntryVerificationActivityDto(AircraftRegisterVerificationActivity authorityConditionActivity) {
        if ( authorityConditionActivity == null ) {
            return null;
        }

        RegisterEntryVerificationActivityDto registerEntryVerificationActivityDto = new RegisterEntryVerificationActivityDto();

        registerEntryVerificationActivityDto.setAuthorityConditionId( authorityConditionActivityAuthorityConditionId( authorityConditionActivity ) );
        registerEntryVerificationActivityDto.setRegisterEntryId( authorityConditionActivityRegisteredAircraftId( authorityConditionActivity ) );
        registerEntryVerificationActivityDto.setStatus( authorityConditionActivity.getStatus() );
        registerEntryVerificationActivityDto.setUpdatedAt( authorityConditionActivity.getUpdatedAt() );
        registerEntryVerificationActivityDto.setPerformedBy( personMapper.toSimplePersonDto( authorityConditionActivity.getPerformedBy() ) );

        return registerEntryVerificationActivityDto;
    }
```

If I put an invalid enum in the mapping it correctly throws an error, but it doesn't generate the code.

**Comment by filiphr** [comment] 2023-04-15 16:40
I tried the initial example and it works correctly. Doing `@Mapping(target = "prop2", constant = "VAL_2")` will generate `b.setProp2( CType.VAL_2 )`

I am going to close this. If it is not working as you expect in the latest version then I would propose to create a minimal reproducible repo with the code so that we can try it out.

**Closed by filiphr** 2023-04-15 16:40 UTC

**Comment by testower** [comment] 2023-06-26 19:54
There is in fact one case where this could be improved: When the string value differs from the enum constant. Consider the following example:

```
public enum Version {
  _1_0("1.0"),
  _2_0("2.0");
}
```

The following doesn't work (given some type that uses the Version enum):

```
    @Mapping(target = "version", constant = "1.0")
```

whereas this works:

```
    @Mapping(target = "version", constant = "_1_0")
```

The first would be preferable as long as constant enum values can't be given as literals but only as strings.

**Comment by filiphr** [comment] 2023-07-08 16:08
@testower I don't understand what the problem is in using the enum constant in the `@Mapping`?

If you want to support mapping from an arbitrary string into an enum then I would suggest that you provide a custom mapping method for it.

e.g.

```java
static Version toVersion(String value) {
    // Custom code
}
```

**Comment by testower** [comment] 2023-08-01 18:22
The problem is that the generated string value (e.g. _1_0) feels unnatural and unexpected the actual string value is "1.0", it could easily be misinterpreted as a mistake. I would expect when using the string constant that it would mirror the actual string value, or to be able to supply the literal enum value instead:

```
    @Mapping(target = "version", constant = Version._1_0)
 ```
 
 This communicates clearly the intent, since and any error here would not compile.
 
Note that I assume to have no control over the model over which mapping is performed.

**Comment by bjoneson** [comment] 2023-08-03 19:11
> The problem is that the generated string value (e.g. _1_0) feels unnatural and unexpected when the actual string value is "1.0", it could easily be misinterpreted as a mistake. I would expect when using the string constant that it would mirror the actual string value, or to be able to supply the literal enum value instead:
> 
> ```
>     @Mapping(target = "version", constant = Version._1_0)
> ```
> 
> This communicates clearly the intent, and any error here would not compile.
> 
> Note that I assume to have no control over the model over which mapping is performed.

Ran into this *exact* scenario today. The above mentioned approach would be *so* much more intuitive

**Comment by filiphr** [comment] 2023-08-13 07:26
@testower and @bjoneson I do agree that it would be nice if you can use `@Mapping(target = "version", constant = Version._1_0)` however, the language does not allow things like that. The language here being Java. As I said earlier the only way to do this is to use

```java
    @Mapping(target = "version", constant = "_1_0")
```

MapStruct will properly use `Version._1_0` in the generated code and give a compiler error if `Version._1_0` does not exist.

> I would expect when using the string constant that it would mirror the actual string value, or to be able to supply the literal enum value instead:

An enum is an object that can have arbitrary number of constructor parameters. How should MapStruct know which string property from the enum it should use to map from the string to the enum?

If you do what I said in https://github.com/mapstruct/mapstruct/issues/2942#issuecomment-1627390305 then you can do

```java
```java
    @Mapping(target = "version", constant = "1.0")
```

```

**Comment by testower** [comment] 2023-08-13 07:57
> MapStruct will properly use Version._1_0 in the generated code and give a compiler error if Version._1_0 does not exist.

You're right, it does give a compiler error. So that helps.

> If you do what I said in [#2942 (comment)](https://github.com/mapstruct/mapstruct/issues/2942#issuecomment-1627390305) then you can do
> 
> ```java
> ```java
>     @Mapping(target = "version", constant = "1.0")
> ```

> Note that I assume to have no control over the model over which mapping is performed.

Thanks for the input anyway.
