### ISSUE TITLE
Ambigious mapping detection does not respect Mapping Annotation on method signatures

### ISSUE THREAD

**Issue by Ditscheridou** [mapstruct/mapstruct#2657] opened 2021-11-17 10:14 UTC
I stumbled about this and expected that it would behave different, so please tell me if this is intended or a bug. 

I have a DTO, that has nullable fields. Based on some input values, i need to map the fields or not. So my mapper has these 2 functions: 

`abstract fun toSelectDTO(entity: DomainEntity): SelectDTO`

`@Mapping(target="data",ignore=true) 
abstract fun toSelectDTOWithoutData(entity: DomainEntity): SelectDTO`

Here i would expect, that MapStruct will respect the Mapping annotation and generates me 2 methods that maps to the SelectDTO, one time with the data property and one without, but instead I get the ambiguous mapping error.

**Comment by Zegveld** [comment] 2021-11-17 11:28
You have a mapping that would need to use either of these functions to map from `DomainEntity` to `SelectDTO` and mapstruct will not know which one to use. 
The error should tell you which property it cannot map, this would look something like:
`Ambiguous mapping methods found for mapping "DomainEntity <field>" to "SelectDTO": ....`. where `<field>` would be replaced with the field it could not do the mapping for, e.g. `entity.data`.

For example with something like the following as the source class mapstruct will throw an ambiguous mapping error:
```
class DomainEntity {
    List<DomainEntity> data;
}
```
Because the DomainEntity contains multiple domain entities it will look for a method to map these. In this case it finds both `toSelectDTO` and `toSelectDTOWithoutData` methods and cannot determine which one to use.
Any reference to DomainEntity will do, it could also be one further down the tree in another class.

If this is not present in your case then we would need a reproduction scenario that includes the mapper, source and target classes for the mapping. That way we can analyze what goes wrong and either fix it or better assist you with your mapping issue.

An other option is also the following:
```
@Mapping(target="data", conditionQualifiedByName = "shouldMapData")
abstract fun toSelectDTOWithoutData(entity: DomainEntity): SelectDTO

@Named("shouldMapData")
fun shouldMapData(entity: DomainEntity): boolean {
    // code here that determines whether data should be mapped or not.
}
```

Hope this helps.

**Comment by filiphr** [comment] 2021-11-20 07:30
Closing this since @Zegveld explained why the problem was occurring.

**Closed by filiphr** 2021-11-20 07:30 UTC
