### ISSUE TITLE
auto generated mapping of single element to iterable of same type

### ISSUE THREAD

**Issue by gbrehmer** [mapstruct/mapstruct#663] opened 2015-10-16 14:05 UTC
e.g. result structure (in my use case this is not changeable, structure is based on international standard) contains a list of type A, but my internal structure only have a single instance.

currently i have to write:

```java
@Mapping(source = "item", target = "list")
public abstract Dto entityToDto(Entity e);

public List<DtoB> singleToList(EntityItem item) {
  if (item == null) {
    return Collections.emptyList();
  }
  return Collections.singletonList(singleToSingle(item));
}

public abstract DtoB entityItemToDtoB(EntityItem item);
```

**Comment by gunnarmorling** [comment] 2015-10-29 16:29
Hi @gbrehmer, thanks for the report.

We've discussed that suggestion before in #117 and came to the conclusion that this really is better addressed by a manual mapping method (as you did in your listing).

The problem is that just too many assumptions about the context are needed: Is the immutability of the resulting list (as the case with `singletonList()`) acceptable or not, which element from the collection to take for the inverse case etc.

Thus I am going to close this one as "Won't fix".

**Closed by gunnarmorling** 2015-10-29 16:29 UTC
Labels: wontfix
