### ISSUE TITLE
Mapstruct doesn't generate mappers

### ISSUE THREAD

**Issue by Pryanic** [mapstruct/mapstruct#1544] opened 2018-07-11 14:43 UTC
I use lombok version 1.18, maven 3.5.2, java 1.10 and mapstruct 1.2.0.Final. 
After mvn clean install I start my spring boot application via java -jar  ./target/MyApplication.jar and see in console that Mappers impl doesn't generate also I looked in my jar arhive and saw that this class absent

**Comment by chris922** [comment] 2018-07-11 19:53
Could you please provide your maven configuration? Especially the part how you set up lombok + mapstruct.

**Comment by filiphr** [comment] 2018-07-12 21:59
Closing this as duplicate of #1543 and the fact that I tried the mapstruct-lombok examples with Java 10 and it worked correctly.

**Closed by filiphr** 2018-07-12 21:59 UTC
