### ISSUE TITLE
Default method implementation not taking into consideration

### ISSUE THREAD

**Issue by paulmarcelinbejan** [mapstruct/mapstruct#3458] opened 2023-11-30 00:51 UTC
### Steps to reproduce the problem

Architectural constraint:

```
public interface MapperOutput<DOMAIN, RESPONSE> {

	RESPONSE toResponse(DOMAIN domain);
	
}
```

sometimes I don't need to map DOMAIN to RESPONSE, I only have to return the domain. 

So I have provided a default implementation to return the domain, and this is working fine.

```
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING, injectionStrategy = InjectionStrategy.CONSTRUCTOR)
public interface EmployeeDeleteManyMapper extends  MapperOutput<Void, Void> {
	
	@Override
	default Void toResponse(Void domain) {
		return domain;
	}
	
}
```

Since this is a common behavior, I have decided to introduce a new generic interface called IdentityMapperOutput that return the domain directly as a response

```
public interface IdentityMapperOutput<T> extends MapperOutput<T, T> {

	@Override
	default T toResponse(T domain) {
		return domain;
	}
	
}
```

but now, when I'm extending this interface with the related default method, It gives me an error:

"Void does not have an accessible constructor. Occured at 'RESPONSE toResponse(DOMAIN domain)' in 'MapperOutput'."

```
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING, injectionStrategy = InjectionStrategy.CONSTRUCTOR)
public interface EmployeeDeleteManyMapper extends  IdentityMapperOutput<Void> {
	
}
```

It's not only about Void, it's in general, cause I have tried also with Long:

"Ambiguous constructors found for creating java.lang.Long: Long(long), Long(java.lang.String). Either declare parameterless constructor or annotate the default constructor with an annotation named @Default. Occured at 'RESPONSE toResponse(DOMAIN domain)' in 'MapperOutput'"

### MapStruct Version

1.5.5.Final

**Comment by filiphr** [comment] 2023-12-11 21:38
This looks like some issue in the way we decide which method to use as a mapping method. For some reason MapStruct is picking the method from `MapperOutput` and not the one from `IdentityMapperOutput`. We'll look into this.

However, an architectural question. If you do not need the mapping, why are you even defining an `EmployeeDeleteManyMapper` at all? Do you have more methods in `MapperOutput`?

**Comment by paulmarcelinbejan** [comment] 2023-12-12 08:51
I was trying to create an architecture (https://github.com/paulmarcelinbejan/Coordinator-Architecture) with a Mediator between the common components involved into a rest-api call: a `Validator` for the request, a `Mapper` from request to domain_input, a `Service` to execute the domain logic, a `Mapper` to map the domain_output to response.
But there are cases where not all the components are involved, 
(
Example 1: a get API to retrieve an entity by passing the id, doesn't need to map Long to Long.
Example 2: a delete API, can execute the service logic to delete some entities, and return nothing, which means I don't need to map the output
) 
so I ended up by creating some alternative abstraction for each case.

**Comment by filiphr** [comment] 2023-12-28 16:43
@paulmarcelinbejan I've been looking into reproducing this one. I've tried with javac 1.8.0_302, 11.0.12, 17.0.8 and 21 and it all works as expected. No method gets created.

However, when I try with the Eclipse compiler (ecj) version 3.20 I do have a compile error. 

Can you please share with us which compiler were you using? Are you using Eclipse perhaps? If yes which version?

**Comment by paulmarcelinbejan** [comment] 2023-12-28 16:47
Yes, I'm using Eclipse on Macbook Pro M1 Max
Version: 2022-12 (4.26.0)
Build id: 20221201-1913

**Comment by filiphr** [comment] 2024-01-28 16:28
@paulmarcelinbejan have you tried this with the latest Eclipse (2023-12)?

**Comment by paulmarcelinbejan** [comment] 2024-01-29 05:45
Based on the following example:

```java
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING, injectionStrategy = InjectionStrategy.CONSTRUCTOR)
public interface EmployeeMapper extends IdentityMapperOutput<Employee> {
	
}
```

```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2024-01-29T06:18:42+0100",
    comments = "version: 1.5.5.Final, compiler: Eclipse JDT (IDE) 3.36.0.v20231114-0937, environment: Java 17.0.5 (Eclipse Adoptium)"
)
@Component
public class EmployeeMapperImpl implements EmployeeMapper {

    @Override
    public Employee toResponse(Employee arg0) {
        if ( arg0 == null ) {
            return null;
        }

        Employee employee = new Employee();

        employee.setBankBranchId( arg0.getBankBranchId() );
        employee.setBirthDate( arg0.getBirthDate() );
        employee.setEmail( arg0.getEmail() );
        employee.setId( arg0.getId() );
        employee.setName( arg0.getName() );
        employee.setNationalityId( arg0.getNationalityId() );
        employee.setPhoneNumber( arg0.getPhoneNumber() );
        employee.setResidenceId( arg0.getResidenceId() );
        employee.setSexTypeId( arg0.getSexTypeId() );
        employee.setSurname( arg0.getSurname() );

        return employee;
    }
}
```

the @Override implementation is not necessary here, since the method has a default implementation.
the same thing is happening by using the abstract class instead of interface.

it should be implemented by MapStruct if on the @Mapper interface the method signature is written again annotated with @Override, example:

```java
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING, injectionStrategy = InjectionStrategy.CONSTRUCTOR)
public interface EmployeeMapper extends IdentityMapperOutput<Employee> {
	
	@Override
	Employee toResponse(Employee domain);
	
}
```

Instead, this case is correctly handled when the default method is in the @Mapper interface


```java
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING, injectionStrategy = InjectionStrategy.CONSTRUCTOR)
public interface EmployeeMapper {
	
	default Employee toResponse(Employee domain) {
		return domain;
	}
	
}
```

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2024-01-29T06:36:17+0100",
    comments = "version: 1.5.5.Final, compiler: Eclipse JDT (IDE) 3.36.0.v20231114-0937, environment: Java 17.0.5 (Eclipse Adoptium)"
)
@Component
public class EmployeeMapperImpl implements EmployeeMapper {
}
```

**Comment by filiphr** [comment] 2024-02-11 09:26
Thanks for the information @paulmarcelinbejan. I will try to figure out what the issue with Eclipse is. To me this looks like a bug in the Eclipse Java Compiler, but need to isolate it and try to explain to the Eclipse team exactly where the error is.

**Comment by Zegveld** [comment] 2024-04-28 13:29
@filiphr , I've analyzed this and the problem is as follows for Eclipse Java Compiler (EJC):

```
class GenericMapper<T, S> {
    T map(S source);
}

class IdentityMapper<I> extends GenericMapper<I,I> {
    I map(I source) {
        return source;
    }
}

class PersonMapper extends IdentityMapper<Person> {}
```

when checking if `I map(I source)` is the override method for `T map(S source)` using `PersonMapper` EJC compares `Person map(Person source)` to `T map(S source)` and thinks it is not an override method.

However when we check if `I map(I source)` is the override method for `T map(S source)` using `IdentityMapper` then EJC thinks it is indeed an override method.

I'm creating a PR to have us compare the methods using the class where the method is defined instead of the class where the mapper is defined. This should fix it at our end, but it would still be broken at the eclipse side. Hope this helps with explaining what is wrong to the Eclipse team.

**Comment by filiphr** [comment] 2024-04-28 15:41
>I'm creating a PR to have us compare the methods using the class where the method is defined instead of the class where the mapper is defined. This should fix it at our end, but it would still be broken at the eclipse side. Hope this helps with explaining what is wrong to the Eclipse team.

I don't think that we should try to fix something like that. If you check the [`Elements#overrides`](https://docs.oracle.com/en/java/javase/21/docs/api/java.compiler/javax/lang/model/util/Elements.html#overrides(javax.lang.model.element.ExecutableElement,javax.lang.model.element.ExecutableElement,javax.lang.model.element.TypeElement)).

You'll see that what we are asking is whether `I map(I source)` overrides `T map(S source)` in the `PersonMapper` type. Eclipse says `false` for this. However, according to the spec this is incorrect. If we take the example from the spec it would be similar, but slightly different, to what we have



> A more interesting case can be illustrated by the following example in which a method in class `A` *does not* override a like-named method in interface `B`:
```
class A { public void m() {} }
interface B { void m(); }
...
m1 = ...; // A.m
m2 = ...; // B.m
assert ! elements.overrides(m1, m2, elements.getTypeElement("A"));
```
> When viewed as a member of a third class `C`, however, the method in `A` does override the one in `B`:
```
class C extends A implements B {}
...
assert elements.overrides(m1, m2, elements.getTypeElement("C"));
```

The way I understand this is that method `I map(I source)` as a member of `PersonMapper` does override `T map(S source)`.

I think that we could prepare a test case for the Eclipse Compiler and share it with them so that they can fix the bug, or they can point to use what we are doing incorrectly here.

**Comment by Zegveld** [comment] 2024-04-28 16:17
I've closed the PR as unmerged, because indeed the situation with `C extends A implements B` does not work anymore then. I hope the analysis helps with creating a reproduction for the eclipse team.

**Comment by filiphr** [comment] 2024-05-01 08:44
I've reported this to the Eclipse JDT team https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2403. Therefore, I'm closing this on our side

**Closed by filiphr** 2024-05-01 08:44 UTC
Labels: bug
