### ISSUE TITLE
Support for mapping from bean to Map

### ISSUE THREAD

**Issue by lugavin** [mapstruct/mapstruct#2833] opened 2022-04-28 05:03 UTC
``` java
@Mapper
public interface CarMapper {
 
    CarMapper INSTANCE = Mappers.getMapper( CarMapper.class );
 
    Map<String, Object> carDtoToMap(CarDto dto);
}
```

**Comment by filiphr** [comment] 2022-05-30 18:56
Closing this as a duplicate of https://github.com/mapstruct/mapstruct/issues/2504

**Comment by filiphr** [comment] 2022-05-30 18:57
Please upvote the linked issue @lugavin

**Closed by filiphr** 2022-05-30 18:56 UTC
