### ISSUE TITLE
Support for Sync and Clone

### ISSUE THREAD

**Issue by nagkumar** [mapstruct/mapstruct#68] opened 2013-09-23 06:15 UTC
Hi,

Would it be possible to have sync and clone method support so that, when I am converting DTO to DAO, I can say all the DTO instance data is synced with an existing instance of DAO object..

Regards,
Raja Nagendra Kumar
C.T.O
www.tejasoft.com

**Comment by sjaakd** [comment] 2015-01-31 09:03
@nagkumar , @gunnarmorling : I think this is basically there with the `@MappingTarget` and going to be enhanced with #160. I'll mark it as duplicate (#160 contains more information). WDYT?

**Comment by agudian** [comment] 2015-02-04 18:41
Closing as duplicate of #160... :smile: Let's reopen it in case we missed something that @nagkumar had in mind additionally.

**Closed by agudian** 2015-02-04 18:41 UTC
Labels: duplicate
