### ISSUE TITLE
DeepClone mapping control not generating third tier functions to clone

### ISSUE THREAD

**Issue by mcclellanmj** [mapstruct/mapstruct#3135] opened 2023-01-10 20:27 UTC
### Expected behavior

In 1.5.3.Final DeepClone is not working on an object that has 3 levels of nesting.  However it works okay in 1.5.2.Final with the same @BeanMapping configuration

I have a nested objects as follows

Person -> Address -> ZipCode

In 1.5.2.Final it will clone all the way down to the ZipCode.  In 1.5.3.Final the function to clone the ZipCode is not generated which results in a shallow copy instead of a deep one.

Mapper:
```java
@Mapper(componentModel = "spring")
public abstract class PersonMapper {
    @BeanMapping(mappingControl = DeepClone.class, resultType = Person.class)
    public abstract Person clonePerson(Person person);
}
```

Behavior of this in 1.5.2.Final is below

```java
package com.mcclellan.sdk.test.model;

import javax.annotation.processing.Generated;
import org.springframework.stereotype.Component;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2023-01-10T14:23:36-0600",
    comments = "version: 1.5.2.Final, compiler: javac, environment: Java 19.0.1 (Homebrew)"
)
@Component
public class PersonMapperImpl extends PersonMapper {

    @Override
    public Person clonePerson(Person person) {
        if ( person == null ) {
            return null;
        }

        Person person1 = new Person();

        person1.setFirstName( person.getFirstName() );
        person1.setLastName( person.getLastName() );
        person1.setAddress( addressToAddress( person.getAddress() ) );

        return person1;
    }

    protected ZipCode zipCodeToZipCode(ZipCode zipCode) {
        if ( zipCode == null ) {
            return null;
        }

        ZipCode zipCode1 = new ZipCode();

        zipCode1.setZipCode( zipCode.getZipCode() );
        zipCode1.setExtension( zipCode.getExtension() );

        return zipCode1;
    }

    protected Address addressToAddress(Address address) {
        if ( address == null ) {
            return null;
        }

        Address address1 = new Address();

        address1.setAddressLine1( address.getAddressLine1() );
        address1.setAddressLine2( address.getAddressLine2() );
        address1.setZipCode( zipCodeToZipCode( address.getZipCode() ) );

        return address1;
    }
}
```

### Actual behavior
The file that was generated in 1.5.3 is, note that zip code is a direct copy
```java
package com.mcclellan.sdk.test.model;

import javax.annotation.processing.Generated;
import org.springframework.stereotype.Component;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2023-01-10T14:21:54-0600",
    comments = "version: 1.5.3.Final, compiler: javac, environment: Java 19.0.1 (Homebrew)"
)
@Component
public class PersonMapperImpl extends PersonMapper {

    @Override
    public Person clonePerson(Person person) {
        if ( person == null ) {
            return null;
        }

        Person person1 = new Person();

        person1.setFirstName( person.getFirstName() );
        person1.setLastName( person.getLastName() );
        person1.setAddress( addressToAddress( person.getAddress() ) );

        return person1;
    }

    protected Address addressToAddress(Address address) {
        if ( address == null ) {
            return null;
        }

        Address address1 = new Address();

        address1.setAddressLine1( address.getAddressLine1() );
        address1.setAddressLine2( address.getAddressLine2() );
        address1.setZipCode( address.getZipCode() );

        return address1;
    }
}
```

### Steps to reproduce the problem

Use an @BeanMapping(mappingControl=DeepClone.class) on an object that has 3 levels of nesting to it.
When looking at the generated java file the third level of nesting will be direct copy instead of having a clone method created for it.

```java
@Mapper(componentModel = "spring")
public abstract class PersonMapper {
    @BeanMapping(mappingControl = DeepClone.class, resultType = Person.class)
    public abstract Person clonePerson(Person person);
}
```

### MapStruct Version

1.5.3.Final

**Comment by filiphr** [comment] 2023-03-17 10:25
Indeed the fix for #2743 was the cause of this regression. This will be fixed with #3203

**Closed** 2023-04-13 19:50 UTC
Labels: bug
