### ISSUE TITLE
MapStruct cannot autowire instance of dependent mapper class, it return null

### ISSUE THREAD

**Issue by fac30ff** [mapstruct/mapstruct#1600] opened 2018-09-01 10:03 UTC
So example is:

      @Entity
       Class Foo {
       List<Bar> bars...
     }

    @Entity
    Class Bar {
     List<Foo> foos...
    }

    Class BarDto {
     ....
    }

    Class FooDto {
    ....
    }

    @Mapper(componentModel ="spring", uses ={BarMapper.class}, strategies...)
    interface FooMapper {
    List<Foo> foos(List<FooDto> dtos)
    etc..
    }

(BarMapper class same as FooMapper)So when I lookup in realisation I see that they try to @Autowire instance of each other, and that is fine, but all instances is null , and all list when I try to convert is also automatically is null and all methods return null, and my app crush with NPE.

How to resolve this issue or its impossible and I will write my own impl?

And I would love to suggest you to update generated code for spring 5 remove @autowired and inject as constructor

**Comment by sjaakd** [comment] 2018-09-01 10:57
Have you tried 1.3.0Beta1? I believe it does support constructor injection..

**Comment by fac30ff** [comment] 2018-09-01 11:08
Tried it generate the same code with @autowired, but question how to resolve problem with null instances of @autowired mapper instance

**Comment by sjaakd** [comment] 2018-09-01 11:15
Checkout: https://github.com/mapstruct/mapstruct/blob/master/processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/spring/constructor/CustomerSpringConstructorMapper.java

**Comment by fac30ff** [comment] 2018-09-01 11:44
Tried again and now the dependencies of the beans(Foo.class and Bar.class) in the application context form a cycle, because they had both many to many relationship

**Comment by sjaakd** [comment] 2018-09-01 13:26
Wrt to your suggestion; I think that's covered with InjectionStrategy.CONSTRUCTOR, right? But IIUC the cyclic relation between mappers is the problem. Question: why split into two mappers?

**Comment by filiphr** [comment] 2018-09-01 16:01
The option for constructor injection was added due to such cyclic dependencies. So in this case the field injection should be used.

@fac30ff how are you using the mappers? Can you please create a small project that reproduces this problem so we can have a look at it? As there is nothing special that MapStruct does here.

**Comment by filiphr** [comment] 2018-09-14 18:31
I am going to close this as having the mapper as null sounds strange within a Spring Context. If you provide is with more information, then we can reopen this issue

**Closed by filiphr** 2018-09-14 18:31 UTC

**Comment by elangochordz** [comment] 2020-04-09 04:56
here is my situation ,  I have the code like below ,  
class A {
private B reference; 
}
class B {
 private Map<String, List<Issue>> issues = null;
}
class Issue {
private String issueId; 
}

-------------------------------------------------------
class ADto {
private BDto reference; 
}
class BDto {
 private Map<String, List<IssueDto>> issues = null;
}
class IssueDto {
private String issueId; 
}
------------------------------------------------------
Now i am doing mapping as below  

@@Mapper(componentModel = "spring")
interface Test {
Test MAPPER = Mappers.getMapper(Test .class);
ADto map(A a);
}
when I do this , I am getting the below error ,

Error:(16, 18) java: Can't map property "java.util.Map<java.lang.String,java.util.List<Issue>> issues" to "java.util.Map<java.lang.String,java.util.List<IssueDto>> issues". Consider to declare/implement a mapping method: "java.util.Map<java.lang.String,java.util.List<IssueDto>> map(java.util.Map<java.lang.String,java.util.List<Issue>> value)".

I am using <org.mapstruct.version>1.3.0.Final</org.mapstruct.version> 

Can you please help me ?

**Comment by filiphr** [comment] 2020-04-10 07:30
@elangochordz please do not post on old issues with questions. Please use our [Gitter Room](https://gitter.im/mapstruct/mapstruct-users) or StackOverflow for asking questions

**Comment by andysierra** [comment] 2023-01-23 19:10
> @@Mapper(componentModel = "spring")
> interface Test {
> Test MAPPER = Mappers.getMapper(Test .class);

You're setting the componentModel as spring, but you're using the mapper like a default componentModel mapper (Mappers.getMapper ...) . This could be risky and not giving to you the mapper instance
