### ISSUE TITLE
Java 15 Record source from a dependent library is not supported

### ISSUE THREAD

**Issue by dpetrecki** [mapstruct/mapstruct#2294] opened 2020-12-03 13:45 UTC
There is a serious issue with Record mapping in MapStruct. When I'm trying to map a Record source to a Record target - it works fine. But my case is - my source Record is located in the jar library, imported with maven to my project. In this case, MapStruct doesn't recognise any field inside the source. When trying to add an explicit mapping with
```
@Mapping(target = "services", source = "services")
```
I have an error message:
```
java: No property named "services" exists in source parameter(s). Did you mean "null"?
```
The source looks like that:
```
public record ListModel(List<String> services) {}
```
The target is very similar.

**Comment by filiphr** [comment] 2020-12-03 16:34
Records are a preview feature in Java 15. Are you sure that you have compiled your other jar with enabled preview features?

**Comment by dpetrecki** [comment] 2020-12-05 20:21
Yes, I'm sure. It works fine in the same application, but doesn't work when I've splitted the application to two maven modules.

**Comment by dpetrecki** [comment] 2020-12-07 07:42
I've created a minimal project with the issue. It's not beautiful, I'm sorry :).
![image](https://user-images.githubusercontent.com/30466367/101322202-eda89480-3866-11eb-8a8b-aeb6179ce7ad.png)
pom.xml (1)
```<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>gist</groupId>
    <artifactId>mapstruct</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>target-module</module>
        <module>source-module</module>
    </modules>

    <properties>
        <java.version>15</java.version>
        <mapstruct.version>1.4.1.Final</mapstruct.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${mapstruct.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <release>${java.version}</release>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        --enable-preview
                    </compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```
pom.xml (2):
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>mapstruct</artifactId>
        <groupId>gist</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <groupId>gist.mapstruct</groupId>
    <artifactId>source-module</artifactId>


</project>
```
pom.xml (3):
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>mapstruct</artifactId>
        <groupId>gist</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <groupId>gist.mapstruct</groupId>
    <artifactId>target-module</artifactId>

    <dependencies>
        <dependency>
            <groupId>gist.mapstruct</groupId>
            <artifactId>source-module</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

</project>
```

all records:
```
public record PutRecordNameHere(List<String> data) {
}
```
mapper:
```
package gist;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import source.SourceInAnotherPackage;


@Mapper
public interface RecordMapper {

    TargetRecord mapWorks(SourceInSamePackage source);

    TargetRecord mapDoesntWork(SourceInAnotherPackage source);

    @Mapping(target = "data", source = "data")
    TargetRecord mapDoesntWorkToo(SourceInAnotherPackage source);
}
```
If you compile with ```mapWorks()``` method only - it works. With other methods I have an error message:
```
[INFO] Compiling 3 source files to /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/target-module/target/classes
[INFO] /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/target-module/src/main/java/gist/TargetRecord.java: Some input files use preview language features.
[INFO] /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/target-module/src/main/java/gist/TargetRecord.java: Recompile with -Xlint:preview for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/target-module/src/main/java/gist/RecordMapper.java:[15,40] No property named "data" exists in source parameter(s). Did you mean "null"?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for mapstruct 1.0-SNAPSHOT:
[INFO]
[INFO] mapstruct .......................................... SUCCESS [  0.013 s]
[INFO] source-module ...................................... SUCCESS [ 15.461 s]
[INFO] target-module ...................................... FAILURE [  0.977 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.787 s
[INFO] Finished at: 2020-12-07T08:38:56+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project
 target-module: Compilation failure
[ERROR] /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/target-module/src/main/java/gist/RecordMapper.java:[15,40] No property named "data" exists in source parameter(s). Did you mean "null"?
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :target-module
```

**Comment by filiphr** [comment] 2020-12-07 08:01
I don't see `--enable-preview` in the `source-module`. According to [this](https://docs.oracle.com/en/java/javase/15/language/preview-language-and-vm-features.html) In order to enable preview features you have to:

>To use preview language features in your programs, you must explicitly enable them in the compiler and the runtime system. If not, you'll receive an error message that states that your code is using a preview feature and preview features are disabled by default.

This also means that you have to enable preview features when compiling the `source-module`. If you don't the module is compiled without preview features and this the `target-module` does not see the records from the `source-module`.

**Comment by dpetrecki** [comment] 2020-12-07 08:09
It's in the parent module, so it's inherited. As you can see in my last listing, the source itself is compiled with SUCCESS status.
The compiled & decompiled ```SourceInAnotherPackage``` class looks like this one:
```
public record SourceInAnotherPackage(List<String> data) {
    public SourceInAnotherPackage(List<String> data) {
        this.data = data;
    }

    public List<String> data() {
        return this.data;
    }
}

```

**Comment by dpetrecki** [comment] 2020-12-09 09:45
I have the same issue, when the source is in the same module, but the target is in a different one.

**Comment by dpetrecki** [comment] 2020-12-09 09:50
And also the same with Lombok - if the source/target is in the same module - it works fine. After moving it to another module - MapStruct can't find getters built during compilation.

**Comment by filiphr** [comment] 2020-12-11 18:41
@dpetrecki I just tried a similar example like yours and all worked fine. The record from the `source-module` was in a different package though, not in the default package.

Can you please create a git repository that we can use to run this and see why it doesn't work for you

**Comment by dpetrecki** [comment] 2020-12-14 06:54
@filiphr sure, here's the repo: https://github.com/dpetrecki/mapstruct-2294
I'm sorry for late responses, I need to change some notification settings in my github account.
I've tried it again: here is my complete local log:
```
kaskader@gu177:/mnt/c/Users/dape/IdeaProjects/gist-mapstruct$ mvn clean package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] mapstruct                                                          [pom]
[INFO] source-module                                                      [jar]
[INFO] target-module                                                      [jar]
[INFO]
[INFO] ---------------------------< gist:mapstruct >---------------------------
[INFO] Building mapstruct 1.0-SNAPSHOT                                    [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ mapstruct ---
[INFO]
[INFO] --------------------< gist.mapstruct:source-module >--------------------
[INFO] Building source-module 1.0-SNAPSHOT                                [2/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ source-module ---
[INFO] Deleting /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/source-module/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ source-module ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/source-module/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ source-module ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 1 source file to /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/source-module/target/classes
[INFO] /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/source-module/src/main/java/source/SourceInAnotherPackage.java: /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/source-module/src/main/java/source/SourceInAnotherPackage.java uses preview language features.
[INFO] /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/source-module/src/main/java/source/SourceInAnotherPackage.java: Recompile with -Xlint:preview for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ source-module ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/source-module/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ source-module ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ source-module ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ source-module ---
[INFO] Building jar: /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/source-module/target/source-module-1.0-SNAPSHOT.jar
[INFO]
[INFO] --------------------< gist.mapstruct:target-module >--------------------
[INFO] Building target-module 1.0-SNAPSHOT                                [3/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ target-module ---
[INFO] Deleting /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/target-module/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ target-module ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/target-module/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ target-module ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 3 source files to /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/target-module/target/classes
[INFO] /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/target-module/src/main/java/gist/TargetRecord.java: Some input files use preview language features.
[INFO] /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/target-module/src/main/java/gist/TargetRecord.java: Recompile with -Xlint:preview for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/target-module/src/main/java/gist/RecordMapper.java:[15,40] No property named "data" exists in source parameter(s). Did you mean "null"?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for mapstruct 1.0-SNAPSHOT:
[INFO]
[INFO] mapstruct .......................................... SUCCESS [  0.322 s]
[INFO] source-module ...................................... SUCCESS [  1.907 s]
[INFO] target-module ...................................... FAILURE [  1.025 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.623 s
[INFO] Finished at: 2020-12-14T07:53:27+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project target-module: Compilation failure
[ERROR] /mnt/c/Users/dape/IdeaProjects/gist-mapstruct/target-module/src/main/java/gist/RecordMapper.java:[15,40] No property named "data" exists in source parameter(s). Did you mean "null"?
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :target-module
kaskader@gu177:/mnt/c/Users/dape/IdeaProjects/gist-mapstruct$
```

**Comment by filiphr** [comment] 2020-12-15 20:00
Seems like you hit some kind of bug in the Java compiler.

From my current analysis we have the following problems:

1. Java 15: Invoking `TypeElement#getRecordComponents()` is an empty list -> "No property named "data" exists in source parameter(s)" as there are no properties
2. Java 16.ea.28-open: Invoking `TypeElement#getRecordComponents()` leads to non empty list, ok so far. However, invoking `RecordComponentElement#getAccessor()` leads to an exception in MapStruct. This in my opinion is also a bug in the Java compiler. I will try to create a simpler reproducible test case so the Java team can have a look at it.

**Comment by filiphr** [comment] 2020-12-16 07:08
I submitted a bug report with internal review id 9068188

**Comment by dpetrecki** [comment] 2020-12-16 07:13
OK, thank you. Just one more question. According to your tests - does it work for any java version?

**Comment by filiphr** [comment] 2020-12-16 07:34
I tested with Java 14, 15 and 16.ea.28 it didn't work for any of them

**Comment by filiphr** [comment] 2021-02-06 15:32
Closing this since it is a bug in the JDK (see [JDK-8258535](https://bugs.openjdk.java.net/browse/JDK-8258535). There isn't much that MapStruct can do here, since the API from Java tells us that the record has no components. 

The bug is planned to be fixed in JDK 17, let's see if it is indeed fixed.

**Closed by filiphr** 2021-02-06 15:32 UTC

**Comment by dpetrecki** [comment] 2021-02-08 06:44
OK, thank you for investigating. I hope they'll fix it in some 16 patch.
