### ISSUE TITLE
Mapper generation fails silently with Immutables and non-standard type names of target

### ISSUE THREAD

**Issue by incaseoftrouble** [mapstruct/mapstruct#2208] opened 2020-09-23 15:02 UTC
I use version 1.3.1.Final together with Immutables 2.8.2 and Gradle 6. When giving the target type a non-standard name via `@Value.Style(typeImmutable="*Foo")`, creation of a mapper fails silently, i.e. without *any* error message.

MWE:
Create the following three files in some package (default package does not work because an invalid import is generated), omitting imports for brevity.
```java
@Value.Immutable
public interface From {
  int getProperty();
}

---

@Value.Immutable
@Value.Style(typeImmutable = "*Tuple")
public interface To {
  int getProperty();
}

---

@Mapper
public abstract class Mapper {
  public abstract To map(From from);
}
```
Then, `MapperImpl` is not generated and no error message is emitted, even if you add other mapping methods. When the `@Value.Style` annotation is removed, the implementation is generated without problems.

I guess that some exception in the code resolving the "Builder" class of `To` is caught and silently dropped. I don't mind sticking to the default naming scheme of `ImmutableXY`, however silent failures are a real pain to debug.

For completeness, my gradle file:
```groovy
plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // https://mvnrepository.com/artifact/org.mapstruct/mapstruct
    implementation group: 'org.mapstruct', name: 'mapstruct', version: '1.3.1.Final'
    annotationProcessor group: 'org.mapstruct', name: 'mapstruct-processor', version: '1.3.1.Final'

    // https://immutables.github.io/
    implementation 'org.immutables:value:2.8.2:annotations'
    annotationProcessor group: 'org.immutables', name: 'value', version: '2.8.2'
}
```

EDIT: Sorry if this has been reported already somewhere, I found it quite hard to search for this. The "mapstruct not generating impl"-issues I found were user-side problems.

**Comment by filiphr** [comment] 2020-09-23 16:04
No problem @incaseoftrouble, thanks a lot for the detailed explanation, it is always nice to see such issues.

I think that the work that @massfords has put for #2198 is also addressing this problem. He can correct me if I am wrong.

Currently, we are not doing anything special to handle the different immutables style options.

**Comment by massfords** [comment] 2020-09-23 17:01
I would close this as a dupe of #2198. I'll update that ticket with some new findings.

**Comment by incaseoftrouble** [comment] 2020-09-23 18:22
I can confirm that the symptoms seem to be the same as in #2198. With 1.4.0.CR1 I get
```
error: No implementation was created for MapperTest due to having a problem in the erroneous element test.To. Hint: this often means that some other annotation processor was supposed to process the erroneous element. You can also enable MapStruct verbose mode by setting -Amapstruct.verbose=true as a compilation argument.
public abstract class MapperTest {
                ^
```

**Comment by filiphr** [comment] 2020-10-04 08:20
Thanks for the confirmations @massfords and @incaseoftrouble. I am closing this one in favour of #2198 and PR #2219.

**Closed by filiphr** 2020-10-04 08:20 UTC
