### ISSUE TITLE
Nested bean target "this" with multiple source parameters not works

### ISSUE THREAD

**Issue by reedycreek** [mapstruct/mapstruct#2461] opened 2021-06-01 04:52 UTC
When mapping nested bean to the "this" target, if there are multiple source parameters, it does not work.

Error messages when build with maven:

`Method has no source parameter named "address". Method source parameters are: "tenantId, user".`
 
``` Java
@Mapper
public interface UserConverter {

    @Mapping(target=".", source="user.address")
    UserDto map(TenantId tenantId, UserEntity user);

}
```

**Comment by filiphr** [comment] 2021-06-05 09:05
This is a duplicate of #2402 which has been fixed

**Closed by filiphr** 2021-06-05 09:05 UTC
