### ISSUE TITLE
MapStruct 1.4 regression: issue combining `qualifiedByName`, `uses` and method chaining

### ISSUE THREAD

**Issue by netmikey** [mapstruct/mapstruct#2538] opened 2021-08-08 19:46 UTC
I'm trying to migrate from MapStruct 1.3.x to 1.4. It seems `qualifiedByName` behavior has changed quite a bit, because quite a few things that worked before have stopped working. While I managed to fix a bunch of them, here is a case I cannot seem to fix that easily:

Given the following mapper:

```java
@Mapper(componentModel = "spring", uses = { TeamMapperHelper.class })
public interface TeamMapper {
    @Mapping(target = "iamGroup", source = "in.iamGroupId", qualifiedByName = "lookupGroup")
    public TeamRole map(TeamRoleEntity in);

    public IamGroup map(GroupRepresentation in);
}

@Component
public class TeamMapperHelper {
    @Named("lookupGroup")
    public GroupRepresentation lookupGroup(String groupId) {
        // ... some lookup mechanism ...
    }
}
```

MapStruct 1.3 generated this code:

```java
public TeamRole map(TeamRoleEntity in, Boolean canManageMembers) {
    // ...
    teamRole.setIamGroup( map( teamMapperHelper.lookupGroup( in.getIamGroupId() ) ) );
    // ...
}
```

To recap, it:

- found the method qualified by "lookupGroup" in the `TeamMapperHelper` component, noticed that it gets a `GroupRepresentation` instance back from it
- found that it had a map method for converting that `GroupRepresentation` to the `IamGroup` it needs in the target type

So it ended up chaining those invocations as shown.

MapStruct 1.4 on the other hand throws an error:

> error: Qualifier error. No method found annotated with @Named#value: [ lookupGroup ].

Is that a corner case that has been overlooked in MapStruct 1.4 or was that change of behavior intentional? If so, how can I get the chaining behavior of MapStruct 1.3 back?

**Comment by filiphr** [comment] 2021-08-14 07:36
>I'm trying to migrate from MapStruct 1.3.x to 1.4. It seems `qualifiedByName` behavior has changed quite a bit, because quite a few things that worked before have stopped working. While I managed to fix a bunch of them, here is a case I cannot seem to fix that easily:

Have a look at the [behaviour changes](https://github.com/mapstruct/mapstruct/releases/tag/1.4.0.Beta1) in regard to qualifiers. it is possible that some things worked before without really using the correct qualifiers.

Looking at your example perhaps there is something that we need to relax here and allow to have a combination of qualifier + no qualifier in 2 step mappings. @sjaakd is this something that you could look at?

@netmikey I think that your current fix for this would be

```
@Mapper(componentModel = "spring", uses = { TeamMapperHelper.class })
public interface TeamMapper {
    @Mapping(target = "iamGroup", source = "in.iamGroupId", qualifiedByName = "lookupGroup")
    public TeamRole map(TeamRoleEntity in);

    public IamGroup map(GroupRepresentation in);

    @Named("lookupGroup")
    default public IamGroup mapWithLookupGroup(GroupRepresentation in) {
        return map(in);
    }
}
```

**Comment by netmikey** [comment] 2021-08-15 15:33
Thanks for the hint, @filiphr !
I can confirm that adding the same qualifier to both steps works indeed.

**Comment by jdkleo** [comment] 2021-08-23 11:47
on 1.4.2，Two projects use the same code, one can run and the other can't
`@Component
@Named("TypeConversionWorker")
public class TypeConversionWorker {
@Named("toDeptList")
    public List<Dept> toDeptList(String str) {
        if (StringUtils.isEmpty(str)) {
            return null;
        }
        return JSONUtil.readValue(str, new TypeReference<List<Dept>>() {
        });
    }

    @Named("toPostList")
    public List<Post> toPostList(String str) {
        if (StringUtils.isEmpty(str)) {
            return null;
        }
        return JSONUtil.readValue(str, new TypeReference<List<Post>>() {
        });
    }
}`

`@Mapper(componentModel = "spring", uses = {TypeConversionWorker.class})
public interface UserStruct {
@Mappings({
            @Mapping(source = "dept", target = "dept", qualifiedByName = "toDeptList"),
            @Mapping(source = "post", target = "post", qualifiedByName = "toPostList")
    })
    CommUserDTO convert2DTO(CommUser user);
}`

`Qualifier error. No method found annotated with @Named#value: [ toDeptList ].`

**Comment by jdkleo** [comment] 2021-08-23 12:04
> on 1.4.2，Two projects use the same code, one can run and the other can't
> 
> @component
> @nAmed("TypeConversionWorker")
> public class TypeConversionWorker {
> @nAmed("toDeptList")
> public List toDeptList(String str) {
> if (StringUtils.isEmpty(str)) {
> return null;
> }
> return JSONUtil.readValue(str, new TypeReference<List>() {
> });
> }
> 
> ```
> @Named("toPostList")
> public List<Post> toPostList(String str) {
>     if (StringUtils.isEmpty(str)) {
>         return null;
>     }
>     return JSONUtil.readValue(str, new TypeReference<List<Post>>() {
>     });
> }
> ```
> 
> }
> 
> @Mapper(componentModel = "spring", uses = {TypeConversionWorker.class})
> public interface UserStruct {
> @mappings({
> @mapping(source = "dept", target = "dept", qualifiedByName = "toDeptList"),
> @mapping(source = "post", target = "post", qualifiedByName = "toPostList")
> })
> CommUserDTO convert2DTO(CommUser user);
> }
> 
> Qualifier error. No method found annotated with @nAmed#value: [ toDeptList ].

Sorry, I've fixed it
The problem is the newline character. Typeconversionworker uses CRLF and cannot work. LF can work.

**Comment by incaseoftrouble** [comment] 2021-08-24 21:39
Adding on this issue:

It might be nice to have a `@AlwaysConsider` (stupid name) annotation or `@ConsiderFor({Qualifier1.class, @Qualifier2.class})` which marks mapping methods as being always being available / available also under the given qualifiers. (But I think this isn't the right solution either).

In my case, the following appears quite often: Lets say I have some generic `unpacking` method, e.g.
```java
  @NullableToOptional
  public <T> Optional<T> nullableToOptional(@Nullable T value) {
    return Optional.ofNullable(value);
  }
```
where `@NullableToOptional` is a `@Qualifier`

Now, when I need to map a nullable `Foo foo` to `Optional<Bar> bar`, the `Bar map(Foo foo)` method needs to be `@NullableToOptional`, too.

The most sensible solution would be if instead of `qualifiedBy`, there could be, as @filiphr mentioned, some way of saying that only one step of the conversion should be qualified. Note that it doesn't necessarily have to be the last step (here, we would have `nullableToOptional(map(foo))` but the other way (optional -> nullable) would be `map(optionalToNullable(foo))`.

Maybe the following works: Add `qualifiedPre` and `qualifiedPost` to `@Mapping` which basically means "before you search for a mapping, search for a matching pre-processing method, apply it, and use the result type to search for matching mapping methods according to the usual rules, i.e. including `qualifiedBy`" (analogous for `qualifiedPost`). This could either be made fail-fast (if multiple `qualifiedPre` would match, raise an error) or not (search all potential paths and only raise an error if more than one conversion path is there).

This would also make the slightly awkward "look for a second step conversion if we can't find a direct mapping" a bit more controllable IMO.

**Comment by filiphr** [comment] 2021-08-29 09:48
Thanks for your input @incaseoftrouble, we will take it into consideration when we talk about this issue with the team.

I think that relaxing the constraint, such that at least one qualification is taken into consideration might be an option, but we will let you know once we have discussed this.

I am not a fan of `qualifiedPre` and `qualifiedPost`, it feels a bit too complex. Exposing the two-step conversions a lot in the `@Mapping` is something that I am also not a big fan of 😄

**Comment by incaseoftrouble** [comment] 2021-08-29 14:11
> I think that relaxing the constraint, such that at least one qualification is taken into consideration might be an option, but we will let you know once we have discussed this.

Here at least for me this really feels like "black magic" and lead to unpredictable behaviour. Having at least the possibility to have a "strict" `qualifiedBy` makes sense.

Or, one could have a different sort of annotation `@MappingConversion` that marks a method as a safe, generic way of transforming objects (i.e. they don't fundamentally change the content, only the superficial representation, as for example going from `Optional` to nullable). Then, one could have a "MappingConversionStrategy.STRICT" which only applies two-step conversion using one regular mapping and one such conversion? But I am not sure how I feel about that. Maybe you find better ideas :-)

For me, I don't mind map-struct being a bit "magic", but there should always be a way to be very explicit about which mappings to consider.

**Comment by filiphr** [comment] 2021-09-08 19:02
We have discussed this within the team and have decided to relax the constraint of both 2 step mappings to have to be qualified. We are going to allow only one method to have the qualifier.

**Comment by incaseoftrouble** [comment] 2021-09-08 21:45
Will there be an option to enforce strict mapping? (Maybe on the level of `@Mapping(strictQualified = true)` or similar)

**Comment by filiphr** [comment] 2021-09-09 07:29
Before I forget. I don't think that there is need for `@Mapping#strictQualified`. You could control that through `@NoComplexMapping`. If you use that it will disable 2 step mappings (which might be something that you would be interested in anyways).

And to clarify by strict mapping you would mean that both steps of a 2 step mapping should match the qualifier?

**Comment by incaseoftrouble** [comment] 2021-09-09 07:35
Oh, I wasn't aware of `@NoComplexMapping`. That solves a few issues I think.

> And to clarify by strict mapping you would mean that both steps of a 2 step mapping should match the qualifier?

Yes. I could imagine that there could be weird things. For example if you have two variants of mapping A->B and two variants of B->C. However this is quite constructed I guess - and you could mark the mappings as `@NoComplexMapping` and chain them manually. So there is a way to resolve the ambiguity and this case is rare enough to not care about it for automatic handling I guess.

**Closed** 2022-03-12 22:57 UTC
Labels: enhancement
