### ISSUE TITLE
Presence of both builder and setter on target causes issues for existing @AfterMapping in 1.3beta

### ISSUE THREAD

**Issue by saugatadutta** [mapstruct/mapstruct#1556] opened 2018-07-19 04:29 UTC
First of all let me start by saying a huge thanks for developing a library like this which save a lot of time and effort of a developer and helps keep a very clean code.I am facing an weird issue, any code/logic I write in @AfterMapping is not getting added to the @Generated class. Using version 1.3.0.Beta1

**Mapper class**
```
@Mapper
public abstract class ProductSkuConfigMapper {

    @Mappings({
            @Mapping(target = "itemType", ignore = true)
    })
    public abstract ProdSkuConfig mapProdSkuConfigEntityToProdSkuConfig(ProdSkuConfigEntity
                                                                                prodSkuConfigEntity);


    @AfterMapping
    public void setItemType(ProdSkuConfigEntity prodSkuConfigEntity, @MappingTarget ProdSkuConfig
            prodSkuConfig) {
        prodSkuConfig.setItemType(AppConfigs.ITEM_TYPE.get(prodSkuConfigEntity.getItemType()));
    }
}
```

**Generated Implementation class**

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2018-07-19T09:39:40+0530",
    comments = "version: 1.3.0.Beta1, compiler: javac, environment: Java 1.8.0_151 (Oracle Corporation)"
)
public class ProductSkuConfigMapperImpl extends ProductSkuConfigMapper {

    @Override
    public ProdSkuConfig mapProdSkuConfigEntityToProdSkuConfig(ProdSkuConfigEntity prodSkuConfigEntity) {
        if ( prodSkuConfigEntity == null ) {
            return null;
        }
        ProdSkuConfigBuilder prodSkuConfig = ProdSkuConfig.builder();
        prodSkuConfig.id( prodSkuConfigEntity.getId() );
        prodSkuConfig.displayName( prodSkuConfigEntity.getDisplayName() );
        prodSkuConfig.description( prodSkuConfigEntity.getDescription() );
        prodSkuConfig.itemId( prodSkuConfigEntity.getItemId() );
        prodSkuConfig.quantity( prodSkuConfigEntity.getQuantity() );
        prodSkuConfig.pimApproved( prodSkuConfigEntity.getPimApproved() );
        prodSkuConfig.lastModifiedDate( prodSkuConfigEntity.getLastModifiedDate() );
        CustomFields[] custom = prodSkuConfigEntity.getCustom();
        if ( custom != null ) {
            prodSkuConfig.custom( Arrays.copyOf( custom, custom.length ) );
        }
        return prodSkuConfig.build();
    }
}
```

This is a simple thing that I believe has worked before but this time it's not. Any help/guidance is highly appreciated.

**Comment by sjaakd** [comment] 2018-07-19 08:33
did it work in 1.2?

**Comment by sjaakd** [comment] 2018-07-19 08:38
I noticed that the new `Builder` mechanism is used. You might want to to add the `ProdSkuConfigBuilder` to the after mapping in stead of `ProdSkuBuilder`. I think there's also a way to disable the selection of builders entirely.

**Comment by SaugataDutta** [comment] 2018-07-19 09:30
@sjaakd  yes it worked with 1.2.0.Final

**Comment by sjaakd** [comment] 2018-07-19 10:49
@SaugataDutta : could you provide a reproducer (as simple as possible) as gist? Include the entity + dto + also the builder generator if you using one. With respect to disabling builder selection: have a look at p17 of our [userguide](http://mapstruct.org/documentation/dev/reference/pdf/mapstruct-reference-guide.pdf). You'll have to use the SPI and the `NoOpBuilderProvider`.

**Comment by SaugataDutta** [comment] 2018-07-19 11:09
@sjaakd The code is available in the below Github repo:
https://github.com/SaugataDutta/mapstruct-sample. IT includes the mapper, entity and dto, build.gradle.

**Comment by sjaakd** [comment] 2018-07-19 11:42
@SaugataDutta, try changing into:
```java
    @AfterMapping
    public void setItemType(
            ProdSkuConfigEntity prodSkuConfigEntity,
            @MappingTarget ProdSkuConfig.ProdSkuConfigBuilder builder) {
        builder.itemType(AppConfigs.ITEM_TYPE.get(prodSkuConfigEntity.getItemType()));
    }
```

Your example then works.

Out of curiosity: why are you annotating your DTO classes with both the Lombok `@Builder` and `@Setter`. The first one seems to imply an immutable DTO.

**Comment by SaugataDutta** [comment] 2018-07-19 15:41
@sjaakd Having both is a mistake, we do not need @Setter, @Builder is enough. Seems like  a mistake.Thanks a lot for the solution

**Comment by sjaakd** [comment] 2018-07-19 17:19
@SaugataDutta no problem. I'll keep this issue open, because I think we should at least warn (and an ask the user to make a deliberate choice when both builders  / setters are there. 

@filiphr : there are several options:
1. prefer setters always over builders (downward compatibility in method selection of `@AfterMapping`.
2. error when MapStruct detects both options, use `@BuilderMapper` with a  property (default true) "generateBuilder" or something like that.

**Comment by filiphr** [comment] 2018-09-14 19:05
The problem with Option 1 is that it is difficult for us to know that there are setters. Does having no write accessors imply having no setters? I think that all that would just overcomplicated things.

If we do something I am more for the Option 2

**Comment by jakraska** [comment] 2019-11-19 19:29
+1 to this being a problem.  I added a builder as a convenience method to my model and it broke my mapping.

**Comment by sjaakd** [comment] 2019-11-21 21:31
@jakraska .. did you disable the builder support on the mapper? `@Builder#disableBuilder`? Its a 1.3.1 feature.

**Comment by jakraska** [comment] 2019-11-22 15:29
I'm on a slightly older version but I checked the latest source and it sounds like that would work.  

The docs currently state:

```
In case you want to disable using builders then you can use the NoOpBuilderProvider by creating a org.mapstruct.ap.spi.BuilderProvider file in the META-INF/services directory with org.mapstruct.ap.spi.NoOpBuilderProvider as it’s content.
```

this sounds much easier, but could use a clear example though.  Glad to have the flag available on the @Mapper !

**Comment by sjaakd** [comment] 2019-11-23 07:15
> but could use a clear example though

You mean something like [this](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-spi-accessor-naming)?

It shows how to use the SPI.. Just use that template and replace with `NoOpBuilderProvider`

**Comment by mjustin** [comment] 2022-01-12 22:05
@sjaakd:

> Out of curiosity: why are you annotating your DTO classes with both the Lombok @Builder and @Setter. The first one seems to imply an immutable DTO.

@jakraska:

> +1 to this being a problem. I added a builder as a convenience method to my model and it broke my mapping.

I have the same situation.  I'm working with a code base where the builders are there for a more fluent object construction API of mutable objects.  Note that nothing in the Lombok [`@Builder` documentation](https://projectlombok.org/features/Builder) implies anything about whether the built object is mutable or not.

---

@sjaakd 

> @jakraska .. did you disable the builder support on the mapper? @Builder#disableBuilder? Its a 1.3.1 feature.

I've confirmed that adding this to my bean mapping successfully works around the issue for me:

```java
@BeanMapping(builder = @Builder(disableBuilder = true))
```

That being said, it feels like the presence of the builder is implying immutability for something that might legitimately be mutable.  I think this issue is still valid, and `@AfterMapping` methods that take in the object rather than the builder should be called if they exist.

**Comment by thunderhook** [comment] 2024-12-03 20:15
Hi @Umizhang0910 

thanks for reviving this issue. Support for lifecycle methods like `@AfterMapping` or `@BeforeMapping` have been introduced in release [1.6.0.Beta1](https://github.com/mapstruct/mapstruct/releases/tag/1.6.0.Beta1) with:
* #1454

They work exactly how you described them.

Therefore I will close this issue as completed. If I missed anything we can still reopen it or tackle that specific case in a separate issue.

**Closed by thunderhook** 2024-12-03 20:15 UTC
