### ISSUE TITLE
Mapstruct 1.5.2 & Java 17 not handling null values for iterables

### ISSUE THREAD

**Issue by lkiran** [mapstruct/mapstruct#2961] opened 2022-08-17 09:15 UTC
I just updated my project to Java 17 and mapsturct 1.5.2.Final and generated code no longer handling null value default option strategy. 

```
// MapConfig annotation
@org.mapstruct.MapperConfig(componentModel = "spring",
    collectionMappingStrategy = CollectionMappingStrategy.ADDER_PREFERRED)
public class MapperConfig {
}
```

```
// Mapper annotation
@Mapper(config = MapperConfig.class,
    nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
    nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT,
    nullValueIterableMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT)
public interface SelectionCriteriaMapper {

    SelectionCriteriaDto map(SelectionDto selection);

}
```

```  
// Generated implementation on Java 17 with Mapstruct 1.5.2.Final
...
  if ( selection != null ) {
            List<OptionCodeDto> list = selection.getOptionCodes();
            if ( list != null ) {
                selectionCriteriaDto.optionCodes( new ArrayList<OptionCodeDto>( list ) );
            } 
           ...
```

```
// Generated implementation on Java 8 with Mapstruct 1.2.0.Final
...
if ( selection != null ) {
    List<OptionCodeDto> list = selection.getOptionCodes();
    if ( list != null ) {
        selectionCriteriaDto.setOptionCodes( new ArrayList<OptionCodeDto>( list ) );
    }
    else {  // NOT GENERATING THIS !
        selectionCriteriaDto.setOptionCodes( new ArrayList<OptionCodeDto>() );
    } 
   ....
```

**Comment by filiphr** [comment] 2022-08-17 15:27
The title of this issue is misleading. The problem is not in the fact that you are using Java 17. Try using 1.5.2 with Java 8 and I believe that you will have the same result.

The behaviour was changes in 1.3. More precisely in [1.3.0.Beta2](https://github.com/mapstruct/mapstruct/releases/tag/1.3.0.Beta2). Have a look at the "Handling null or missing source properties" section of the link I shared.

Since this is a documented behaviour change in a previous release, I am going to close this issue.

**Closed by filiphr** 2022-08-17 15:27 UTC

**Comment by lkiran** [comment] 2022-08-17 16:04
Thank you @filiphr  for the answer but despite I specified all of the null value strategies, it's not generating the `else` clause.
```
@Mapper(config = MapperConfig.class,
    nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
    nullValueMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT,
    nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.SET_TO_DEFAULT,
    nullValueIterableMappingStrategy = NullValueMappingStrategy.RETURN_DEFAULT)
public interface SelectionCriteriaMapper {

    SelectionCriteriaDto map(SelectionDto selection);

}
```

**Comment by filiphr** [comment] 2022-08-17 16:10
@lkiran I think that you skipped the first *NB* section

>*NB*: During this we noticed that we handle differently collections / maps for normal mapping methods (i.e. we were setting those to `null` if the source property was `null` or not present). This is now changed and collections / maps won't be set if the source property is null or not present. In such case one needs to use `@ObjectFactory` or set the default in the constructor of the target object

This means that we no longer have the default branch, since we are instantiating the target object ourselves. You should either make sure that creating an empty instance of your object has valid default state or use `@ObjectFactory` and initialize it.
