### ISSUE TITLE
Multiple afterMappers called for mapper and not only the specific after mapper wanted

### ISSUE THREAD

**Issue by nahmias22** [mapstruct/mapstruct#3428] opened 2023-10-29 10:21 UTC
### Expected behavior

In a mapper interface multiple afterMappers are defined for the different mappers defined, and using the same name followed by a prefix or sufix of "after" and lthe relevant inputs and link 1 after mapper to 1 specific after mapper

```java
    @Named("toBookingTrackerDTOConstructor")
    @Mapping(target = "flightBookingList", ignore = true)
    @Mapping(target = "hotelBookingList", ignore = true)
    BookingTrackerDTO toBookingTrackerDTOConstructor(BookingTracker in, List<? extends BookingDTO> bookings);

    @AfterMapping
    default <S extends BookingDTO> void afterToBookingTrackerDTOConstructor(List<S> bookings, @MappingTarget BookingTrackerDTO dto) {
        if (!ListUtils.isEmpty(bookings)) {
            S booking = bookings.get(0);
            if (booking instanceof FlightBookingDTO) {
                dto.setFlightBookingList((List<FlightBookingDTO>) Collections.singletonList(booking));
            } else if (booking instanceof HotelBookingDTO) {
                dto.setHotelBookingList((List<HotelBookingDTO>) Collections.singletonList(booking));
            }
        }
    }

    @Named("toBookingTrackerDTOMinified")
    @Mapping(target = "flightBookingList", ignore = true)
    @Mapping(target = "hotelBookingList", ignore = true)
    BookingTrackerDTO toBookingTrackerDTOMinified(BookingTracker in);

    @AfterMapping
    default void afterToBookingTrackerDTOMinified(BookingTracker in, @MappingTarget BookingTrackerDTO dto) {
        if (!ListUtils.isEmpty(in.getBookingHistory())) {
            var booking = in.getBookingHistory().stream()
                    .max((o1, o2) -> Long.compare(o1.getId(), o2.getId()))
                    .orElseThrow(() -> new ApplicationException(
                            ErrorCode.OPERATION_FAILED,
                            new Object[]{"A main booking belonging to this tracker could not be found"},
                            this.getClass().getSimpleName()
                    ));
            if (booking instanceof FlightBooking) {
                dto.setFlightBookingList(
                        Collections.singletonList(toFlightBookingDTO((FlightBooking) booking))
                );
            } else if (booking instanceof HotelBooking) {
                dto.setHotelBookingList(
                        Collections.singletonList(
                                toHotelBookingDTO((HotelBooking) booking)
                        )
                );
            }
        }
    }
```

### Actual behavior

The generated code is the following:
```java

    @Override
    public BookingTrackerDTO toBookingTrackerDTOConstructor(BookingTracker in, List<? extends BookingDTO> bookings) {
        if ( in == null && bookings == null ) {
            return null;
        }

        BookingTrackerDTO bookingTrackerDTO = new BookingTrackerDTO();

        if ( in != null ) {
            bookingTrackerDTO.setId( in.getId() );
            bookingTrackerDTO.setUuid( in.getUuid() );
            bookingTrackerDTO.setCreatedBy( in.getCreatedBy() );
            bookingTrackerDTO.setCreationDT( in.getCreationDT() );
            bookingTrackerDTO.setUpdateDT( in.getUpdateDT() );
            bookingTrackerDTO.setUpdatedBy( in.getUpdatedBy() );
            bookingTrackerDTO.setStatus( statusToStatus( in.getStatus() ) );
            bookingTrackerDTO.setClient( clientMapper.toClientDtoMinified( in.getClient() ) );
            bookingTrackerDTO.setAgent( agentMapper.toAgentDtoMinified( in.getAgent() ) );
            bookingTrackerDTO.setSupplier( supplierToSupplierDTO( in.getSupplier() ) );
            bookingTrackerDTO.setCommissioned( in.getCommissioned() );
            bookingTrackerDTO.setHighlight( in.getHighlight() );
        }

        afterToBookingTrackerDTOConstructor( bookings, bookingTrackerDTO );
        afterToBookingTrackerDTOMinified( in, bookingTrackerDTO );

        return bookingTrackerDTO;
    }

    @Override
    public BookingTrackerDTO toBookingTrackerDTOMinified(BookingTracker in) {
        if ( in == null ) {
            return null;
        }

        BookingTrackerDTO bookingTrackerDTO = new BookingTrackerDTO();

        bookingTrackerDTO.setId( in.getId() );
        bookingTrackerDTO.setUuid( in.getUuid() );
        bookingTrackerDTO.setCreatedBy( in.getCreatedBy() );
        bookingTrackerDTO.setCreationDT( in.getCreationDT() );
        bookingTrackerDTO.setUpdateDT( in.getUpdateDT() );
        bookingTrackerDTO.setUpdatedBy( in.getUpdatedBy() );
        bookingTrackerDTO.setStatus( statusToStatus( in.getStatus() ) );
        bookingTrackerDTO.setClient( clientMapper.toClientDtoMinified( in.getClient() ) );
        bookingTrackerDTO.setAgent( agentMapper.toAgentDtoMinified( in.getAgent() ) );
        bookingTrackerDTO.setSupplier( supplierToSupplierDTO( in.getSupplier() ) );
        bookingTrackerDTO.setCommissioned( in.getCommissioned() );
        bookingTrackerDTO.setHighlight( in.getHighlight() );

        afterToBookingTrackerDTOMinified( in, bookingTrackerDTO );

        return bookingTrackerDTO;
    }
```
In the case of the second function only the one and correct afterMapping is called, but in the case on the first afterMapping both afterMappers are called where the minified is not wanted.

### Steps to reproduce the problem

no custom configuration is used and project fallbacks on defaults.

### MapStruct Version

1.5.5-Final

**Comment by Zegveld** [comment] 2023-11-02 14:01
You can use `@Named` on the `@AfterMapping` and then `@BeanMapping(qualifiedByName='...')` on the mapping-methods to specify which `@AfterMapping` is for which mapping.

The mapping's signature allows both methods as valid aftermappings, therefor mapstruct calls them both.
This is the expected behavior for mapstruct.

Closing this since it works as expected, and this is not a bug.

**Closed by Zegveld** 2023-11-02 14:01 UTC
Labels: bug
