### ISSUE TITLE
[REGRESSION] Make MapStruct generate compilable mapping code for attributes of type EnumSet

### ISSUE THREAD

**Issue by kwasny2** [mapstruct/mapstruct#1797] opened 2019-04-25 08:04 UTC
See #732, does not work anymore

**Comment by chris922** [comment] 2019-04-25 09:58
Thanks @kwasny2 for raising this issue!

It is a bit strange that it occurs once again, because there was a unit test added when making the changes for #732. 

Would be great if you can provide the code that you are using that causes this error? Would be great if you can include the (invalid) generated code as well.
Maybe it is a similar but slightly different case here.

**Comment by kwasny2** [comment] 2019-04-25 15:50
Simple case:

  public class CustomerDto {

    public enum Type {
        ONE, TWO
    }

    public EnumSet<Type> enumSet;
  }

 public class Customer {

    public enum Type {
        ONE, TWO
    }

    private EnumSet<Type> enumSet;

    public EnumSet<Type> getEnumSet() {
        return enumSet;
    }

    public void setEnumSet(EnumSet<Type> enumSet) {
        this.enumSet = enumSet;
    }
 }

  @ Mapper
  public interface CustomerMapper {

    Customer toCustomer(CustomerDto customerDto);

    CustomerDto fromCustomer(Customer customer);
  }

Result:

     EnumSet<com.example.myapplication.Customer.Type> enumSet1 = new EnumSet<com.example.myapplication.Customer.Type>();

     EnumSet<Type> enumSet1 = new EnumSet<Type>();

Error: EnumSet is abstract; cannot be instantiated

**Comment by filiphr** [comment] 2019-05-03 21:35
This is not a regression, but rather it was never working 😄(I think). This will be fixed as part of PR #1806

@kwasny2 are you sure that your example works on 1.2.0.Final?

**Closed** 2019-05-05 10:42 UTC
Labels: enhancement

**Comment by filiphr** [comment] 2019-05-05 10:43
Thus has now been fixed on master. You can give it a go @kwasny2
