### ISSUE TITLE
Explore usage in (native) Quarkus application

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#1749] opened 2019-03-10 20:33 UTC
[Quarkus](https://quarkus.io/) is a new effort for providing a stack of mature technologies such as Hibernate, RESTEasy, Netty etc. for building cloud-native applications using Java. Its key differentiators are support for native binaries (via GraalVM) and extraction of typical bootstrapping tasks (e.g. annotation retrieval) from runtime into build time. Both results in vastly reduced memory usage and start-up times (in native as well as JVM modes).

We should explore the usage of MapStruct in a Quarkus application. Given MapStruct doesn't do any sort of reflection, I'd expect things to "just work", but it'd be nice to have a demo and blog post, esp. of usage in native binaries.

**Comment by chris922** [comment] 2019-03-11 20:03
I could imagine that MapStruct is the only mapping framework of this kind that is usable with Quarkus and native images because - as you already mentioned - it doesn't use reflection. Sounds for me like a big plus in case someone uses Quarkus and needs a mapping framework.

I would also like to read a blog post with a demo-case.

**Comment by chris922** [comment] 2019-03-15 08:13
Quarkus + MapStruct works like a charm!
A PR containing an example is available in mapstruct/mapstruct-examples#59

Nevertheless we should still explore more stuff like how complex it is to natively support also `Mappers.getMapper(...)` and/or how to write a quarkus extension.

**Comment by donwitti** [comment] 2019-10-09 12:09
I'm new to quarkus as well as to mapstruct, but when I set up my application like in the example, everything works fine until I reference a mapper from another mapper via "uses". 
I think the problem is that the generated implementation contains the mapper that needs to be injected as a private field, so the quarkus injection doesn't work in this case (see https://quarkus.io/guides/cdi-reference "2. Private Members"). If it would be generated as a package-private field, everything should be fine I guess.

**Comment by sjaakd** [comment] 2019-10-09 12:37
Did you try constructor injection as well?

**Comment by donwitti** [comment] 2019-10-09 12:55
Yes, the referenced mapper field stays null in the instance.

**Comment by sjaakd** [comment] 2019-10-13 07:15
To be clear, you created a mapper like this:

```java
@Mapper( injectionStrategy = InjectionStrategy.CONSTRUCTOR) {

...
}

```

MapStruct generates a public constructor in that case. The field is private but injection happens on the constructor

**Comment by donwitti** [comment] 2019-10-13 10:56
Yes, at least I remember I did so. Unfortunately, I had to move on and switched my project back to non-quarkus. 
I just tried to modify the mapstruct-quarkus example to reproduce the error and I wasn't able to do so, so maybe I got something else wrong. 
Sorry for the confusion and thanks for looking into it.

**Comment by sjaakd** [comment] 2019-11-10 11:54
> I just tried to modify the mapstruct-quarkus example to reproduce the error and I wasn't able to do so, so maybe I got something else wrong in the first place.
> Sorry for the confusion and thanks for looking into it.

No problem. I'll proceed to close this. one. We can always reopen.

**Closed by sjaakd** 2019-11-10 11:54 UTC
