### ISSUE TITLE
@Builder is not recognized on 1.3.0

### ISSUE THREAD

**Issue by soberich** [mapstruct/mapstruct#1400] opened 2018-03-19 08:21 UTC
Hi, 
I saw several tests with lombok's builder but can't manage to make it work on my own.
I believe those tests pass, so maybe there is a bug
I have fluent assessors
```
public class FluentAccessors extends DefaultAccessorNamingStrategy {
    private static final Pattern JAVA_JAVAX_PACKAGE = Pattern.compile( "^javax?\\..*" );

    private static final Pattern BOOL = Pattern.compile("is[A-Z][\\w]+");
    private static final Pattern GETTER = Pattern.compile("get[A-Z][\\w]+");
    private static final Pattern SETTER = Pattern.compile("set[A-Z][\\w]+");

    @Override
    public boolean isGetterMethod(final ExecutableElement method) {
        val methodName = method.getSimpleName().toString();
        val isNonBuilder = !(methodName.startsWith("build") || methodName.startsWith("toBuild"));
        val isNonVoidReturnType = method.getReturnType().getKind() != TypeKind.VOID;
        val isBooleanGetterName = methodName.matches( BOOL.pattern() ) && methodName.length() > 2;
        val returnTypeIsBoolean = method.getReturnType().getKind() == TypeKind.BOOLEAN ||
                "java.lang.Boolean".equals( getQualifiedName( method.getReturnType() ) );
        return (isBooleanGetterName && returnTypeIsBoolean)
                || (isNonBuilder && isNonVoidReturnType && method.getParameters().size() == 0)
                || (methodName.matches( GETTER.pattern()) && method.getParameters().size() == 0);
    }

    @Override
    public boolean isSetterMethod(final ExecutableElement method) {
        val methodName = method.getSimpleName().toString();
        return !(methodName.startsWith("build") || methodName.startsWith("toBuild"))
                || (methodName.matches(SETTER.pattern())
                || isBuilderSetter(method));
    }

    protected boolean isBuilderSetter(final ExecutableElement method) {
        return method.getParameters().size() == 1
                && !JAVA_JAVAX_PACKAGE.matcher( method.getEnclosingElement().asType().toString() ).matches()
                && method.getReturnType().toString().equals( method.getEnclosingElement().asType().toString());
    }

    @Override
    public String getPropertyName(final ExecutableElement getterOrSetterMethod) {
        val methodName = getterOrSetterMethod.getSimpleName().toString();
        if ( methodName.matches( BOOL.pattern() ) || methodName.matches( GETTER.pattern() ) || methodName.matches( SETTER.pattern() ) ) {

            return Introspector.decapitalize(methodName.substring(methodName.matches(BOOL.pattern()) ? 2 : 3));
        }
        else if ( isBuilderSetter( getterOrSetterMethod ) ) {
            return methodName;
        }
        return Introspector.decapitalize(methodName.substring(methodName.matches(BOOL.pattern()) ? 2 : 0));
    }
}
```

and POJO

```
// FIXME: Property "name" has no write accessor in com.psg.lap.domain.model.user.UserDTO.
// FIXME: UserDTO toDto(User user);

//DOES NOT WORK!!
//@Value 
//@Builder(toBuilder = true)
//@Accessors(fluent = true)
//@RequiredArgsConstructor

//WORKS
@Getter
@Setter
@Builder(toBuilder = true)
@Accessors(fluent = true)
@NoArgsConstructor
@AllArgsConstructor
public final class UserDTO {
    private String name;
    private String position;
    private String email;
    private String password;

    @JsonPOJOBuilder(withPrefix = "")
    public static final class UserDTOBuilder {
    }
}


```
It fails to read builder and write to pojo via builder methods.

Mapper
```
@Mapper(componentModel = "cdi"/*, unmappedTargetPolicy = ERROR*/)
public interface UserMapper {

    @Mapping( source = "name",     target = "name" )
    @Mapping( source = "position", target = "position" )
    @Mapping( source = "email",    target = "email" )
    @Mapping( source = "password", target = "password" )
    UserDTO toDto(User user);

    @Mapping(target = "id", ignore = true)
    ...
    @InheritInverseConfiguration(name = "toDto")
    User fromDto(UserDTO userDTO);


    @InheritInverseConfiguration(name = "fromDto")
    UserDTO update(User user, @MappingTarget UserDTO userDTO);

    @InheritConfiguration(name = "fromDto")
    User update(UserDTO userDTO, @MappingTarget User user);


    List<UserDTO> streamUsers(Stream<User> users);
}
```

It works without being a @Value (basically, simply saying HAVING setters) but fails when it's a @Value without setters but with just @Builder, though you have a similar example in tests in last commits in `@Builder round 3` issue page in issue tracker..

**Comment by filiphr** [comment] 2018-03-19 09:41
@soberich are you using the PR as a reference? If not, then What you have here it won't work as it is not on master yet.

Also if your lombok classes are in the same round it is not going to work due to https://github.com/rzwitserloot/lombok/issues/1538. For some reason we can't see the Lombok builder. The tests there have different modules for the Lombok and MapStruct classes

**Comment by soberich** [comment] 2018-03-19 10:37
Ok,
I am using dynamic snapshot version
```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2018-03-19T12:21:19+0300",
    comments = "version: 1.3.0-SNAPSHOT, compiler: javac, environment: Java 9.0.4 (Oracle Corporation)"
)
```
If any workaround, would be great.
Thanks.

**Comment by sjaakd** [comment] 2018-03-23 20:08
@soberich .. I guess you have to wait for the builders until the PR is merged..  1.3 is planned. The major feature is builders.

**Closed by sjaakd** 2018-03-23 20:08 UTC

**Comment by soberich** [comment] 2018-04-22 05:31
Builders are not detected
with or without `(builderClassName = "Builder")` (if matters)
as well as 
with or without `@Value`
```
@Value
@Builder(builderClassName = "Builder")
//@Accessors(fluent = true)
public class Test1 {

    String st1;
    Integer num1;
}
@Data
//@Accessors(fluent = true)
public class Test2 {
    String st1;
    Integer num1;
}
...
@Mapper(mappingInheritanceStrategy = AUTO_INHERIT_ALL_FROM_CONFIG)
...

    Test1 test(Test2 test2);
    Test2 test(Test1 test1);
```

```
 error: com.psg.lap.domain.model.auction.Test1 does not have an accessible parameterless constructor.
    Test1 test(Test2 test2);
          ^
```

What are we missing here?
Spent much time with it.

**Comment by filiphr** [comment] 2018-04-22 05:54
@soberich It will be written in the release notes and in the documentation. There is an issue with Lombok and we can't see the builder method nor the builder setter methods when we run in the same compilation. Unfortunately until rzwitserloot/lombok#1538 is solved you would need to have the Lombok classes in a separate module.

I am really sorry for this, but there is not much that we could do about this at the moment. You can try commenting on the Lombok issues, to see if they can pick it up faster.

A side note with PR #1445 you would be able to use update methods for types that do have a builder

**Comment by soberich** [comment] 2018-04-22 09:59
Please, confirm, If I took it right and that what you are saying is actually what I am experiencing, otherwise - a bug. If it'll turn out it is what you are saying, than I'll stop trying for now.

Here is what is happening, 

if I simply add mapstruct dependencies directly to the module where the mappers are, and both source and target classes..
```
//    implementation(project(path=":ap"))
//    annotationProcessor(project(path=":ap"))
    implementation(group="org.mapstruct", name="mapstruct-processor", version="${extra["mapStructVersion"]}")
    annotationProcessor(group="org.mapstruct", name="mapstruct-processor", version="${extra["mapStructVersion"]}")
    implementation(group="org.mapstruct", name="mapstruct-jdk8", version="${extra["mapStructVersion"]}")
```
Then it actually works perfectly and this
```
@Value
@Builder
public class Test1 {
    String st1;
    Integer num1;
}
@Data
public class Test2 {
    String st1;
    Integer num1;
}
...
@Mapper(mappingInheritanceStrategy = AUTO_INHERIT_ALL_FROM_CONFIG)
...
    Test1 test(Test2 test2);
    Test2 test(Test1 test1);
```
generates proper mappings so far
```
@Override
    public Test1 test(Test2 source) {
        if ( source == null ) {
            return null;
        }
        Test1Builder test1 = Test1.builder();
        if ( source.getSt1() != null ) {
            test1.st1( source.getSt1() );
        }
        if ( source.getNum1() != null ) {
            test1.num1( source.getNum1() );
        }
        return test1.build();
    }

    @Override
    public Test2 test(Test1 source) {
        if ( source == null ) {
            return null;
        }
        Test2 test2 = new Test2();
        if ( source.getSt1() != null ) {
            test2.setSt1( source.getSt1() );
        }
        if ( source.getNum1() != null ) {
            test2.setNum1( source.getNum1() );
        }
        return test2;
    }
```
EVEN if I use custom naming strategy IN THIS EXACT SAME MODULE - It works
BUT, 
If I move CustomNamingStrategy definition to the separate module and apply
```
 implementation(project(path=":ap"))
annotationProcessor(project(path=":ap"))
//    implementation(group="org.mapstruct", name="mapstruct-processor", version="${extra["mapStructVersion"]}")
//    annotationProcessor(group="org.mapstruct", name="mapstruct-processor", version="${extra["mapStructVersion"]}")
//    implementation(group="org.mapstruct", name="mapstruct-jdk8", version="${extra["mapStructVersion"]}")
```
that it fails with 
```
... does not have an accessible parameterless constructor.
    Test1 test(Test2 test2);
          ^
```

**Comment by filiphr** [comment] 2018-04-22 10:06
Your `CustomNamingStrategy` should have no impact on this part of the code. Are you referring to a custom `BuilderProvider`?

If the your custom implementation is in the same module I think it won't be picked up, as it can't load those classes as they are not compiled yet. 

This is really strange, can you perhaps make one small reproducal project so we can have a look at it?

**Comment by filiphr** [comment] 2018-04-22 10:39
Great that you resolved the problem.

Just so I understand correctly for you the builders work when Lombok and MapStruct are in the same module? Do you provide a custom `BuilderProvider` as well?

**Comment by zantoichi** [comment] 2019-10-02 20:33
Any update on the issue? Does the Lombok team need to fix this from their end? Or is it till considered a mapstruct bug?

**Comment by sjaakd** [comment] 2019-10-05 07:24
> Any update on the issue? Does the Lombok team need to fix this from their end? Or is it till considered a mapstruct bug?
> I tried the proposed solutions but nothing works with java 11

The issuer got it to work. So the issue is considered closed. On a side note: many of the problems arise because the annotation processing mechanism is not used properly by Lombok by rewriting existing classes. If you are in the same cycle, you can't see them because they might be there or not depending not the moment.

**Comment by filiphr** [comment] 2019-10-05 12:00
@zantoichi we have analysed the problem and it lead to https://github.com/rzwitserloot/lombok/issues/1538. For whatever reason MapStruct does not see the methods for the builder from Lonbok. I debugged this and I could explicitly see that they were not there. I am not sure what we can do more here

**Comment by msievers** [comment] 2020-10-30 07:20
Another workaround for this might be to just use the very latest `mapstruct:1.4.1.final` together with `lombok:1.18.16` which will build with java 11 by generating mappers using the object constructors (instead of the actual builder) to create instances.

So, in fact, the builders are not used, but it compiles and works as expected, without the need for mutable objects (`@Setters`).
