### ISSUE TITLE
Passing parent by @Context to child in @Named method (through qualifiedByName)

### ISSUE THREAD

**Issue by mkczyk** [mapstruct/mapstruct#3087] opened 2022-11-22 12:17 UTC
### Use case

I try to pass parent object to child in custom method (`@Named` + `qualifiedByName`), but it seems that `@Context` doesn't support that. 

Example:

Classes:
```
@Data
@AllArgsConstructor
public class Parent {
    private String name;
    private Child child;
}

@Data
@AllArgsConstructor
public class Child {
    private String value;
}

@Data
@AllArgsConstructor
public class ParentDto {
    private String name;
    private ChildDto child;
}

@Data
@AllArgsConstructor
public class ChildDto {
    private String valueWithName;
}
```
Mapper:
```
@Mapper
public interface MyMapper {

    ParentDto map(Parent parent);

    @Mapping(target = "valueWithName", source = "child", qualifiedByName = "getValueWithName")
    ChildDto map(Child child, @Context Parent parent);

    @Named("getValueWithName")
    default String getValueWithName(Child child, @Context Parent parent) {
        return child.getValue() + parent.getName(); // NOT WORKING
    }
}
```
Example usage:
```
MyMapper mapper = Mappers.getMapper(MyMapper.class);
Parent parent = new Parent("a", new Child("b"));
ParentDto parentDto = mapper.map(parent);

System.out.println(parentDto.getName()); // a
System.out.println(parentDto.getChild().getValueWithName()); // expect: ba, but null
```
Compilation warning:
```
java: Unmapped target property: "valueWithName". Mapping from property "Child child" to "ChildDto child".
```

### Generated Code

After adding `@Context` I see that generated code stops using mine method and generates its own.

Generated code (with my comments):
```
public class MyMapperImpl implements MyMapper {

    @Override
    public ParentDto map(Parent parent) {
        if ( parent == null ) {
            return null;
        }

        String name = null;
        ChildDto child = null;

        name = parent.getName();
        child = childToChildDto( parent.getChild() ); // NOT PASSED PARENT

        ParentDto parentDto = new ParentDto( name, child );

        return parentDto;
    }

    @Override
    public ChildDto map(Child child, Parent parent) { // NOT USED
        if ( child == null ) {
            return null;
        }

        String valueWithName = null;

        valueWithName = getValueWithName( child, parent );

        ChildDto childDto = new ChildDto( valueWithName );

        return childDto;
    }

    protected ChildDto childToChildDto(Child child) { // USELESS GENERATED METHOD
        if ( child == null ) {
            return null;
        }

        String valueWithName = null;

        ChildDto childDto = new ChildDto( valueWithName );

        return childDto;
    }
}
```

### Possible workarounds

Maybe `@BeforeMapping` and `@AfterMapping` helps to [do workaround](https://stackoverflow.com/questions/53878367/mapstruct-propagate-parent-field-value-to-collection-of-nested-objects/53896638#53896638) but [I tried and fail](https://stackoverflow.com/questions/74522692/mapstruct-pass-parent-to-child-in-list-mapping). 

But anyway, passing parent with `@Context` to custom method could be more intuitive.

### MapStruct Version

1.5.3

**Comment by Zegveld** [comment] 2022-11-23 19:29
Not certain if it would be more intuitive, mapstruct will currently only try to use fields that are already marked with `@Context` to fill parameters that are annotated with `@Context`. Changing this might cause unexpected behaviour in some cases.

As a work-around you can currently use an expression.
```
    @Mapping(target = "child", expression= "java(map(parent.getChild(), parent))")
    ParentDto map(Parent parent);
```

**Comment by filiphr** [comment] 2022-11-26 08:08
Closing this since this works as expected.

An alternative workaround to what @Zegveld explained is:

```java
@Mapper
public interface MyMapper {

    default ParentDto map(Parent parent) {
        return map(parent, parent);
    }

    @Named("mapParentWithContext")
    ParentDto map(Parent parent, @Context Parent parentContext);

    @Mapping(target = "valueWithName", source = "child", qualifiedByName = "getValueWithName")
    ChildDto map(Child child, @Context Parent parent);

    @Named("getValueWithName")
    default String getValueWithName(Child child, @Context Parent parent) {
        return child.getValue() + parent.getName(); // NOT WORKING
    }
}
```

**Closed by filiphr** 2022-11-26 08:08 UTC
